import type { TaskDefinition } from "@simbench/core";

const R5 = {
  completion: 5.0,
  partialPerCheck: true,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
};
const R8 = {
  completion: 8.0,
  partialPerCheck: true,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.2,
};
const R10 = {
  completion: 10.0,
  partialPerCheck: true,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.2,
};

export const cycleTasks: TaskDefinition[] = [
  // ---------------------------------------------------------------------------
  // Stage 3 — basic cycle operations
  // ---------------------------------------------------------------------------
  {
    id: "linear-cyc-001",
    site: "linear",
    domain: "cycles",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Create a cycle",
    goal: "Create a new cycle named 'Cycle 15' in team Engineering (team-1) with description 'Performance optimization'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "cycle_has_state",
        id: "cycle-4",
        expected: "upcoming",
        weight: 1.0,
        description: "Cycle 15 exists in upcoming state",
      },
    ],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["create", "cycle"],
  },
  {
    id: "linear-cyc-002",
    site: "linear",
    domain: "cycles",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Move issue to cycle",
    goal: "Move issue ENG-13 (iss-13) into Cycle 13 (cycle-2).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_in_cycle",
        id: "iss-13",
        expected: "cycle-2",
        weight: 1.0,
        description: "ENG-13 is in cycle-2",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["cycle", "move"],
  },

  // ---------------------------------------------------------------------------
  // Stage 5 — cycle lifecycle
  // ---------------------------------------------------------------------------
  {
    id: "linear-cyc-003",
    site: "linear",
    domain: "cycles",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Complete active cycle",
    goal: "Complete Cycle 13 (cycle-2), the currently active cycle.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "cycle_has_state",
        id: "cycle-2",
        expected: "completed",
        weight: 1.0,
        description: "Cycle 13 is completed",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["cycle", "complete"],
  },
  {
    id: "linear-cyc-004",
    site: "linear",
    domain: "cycles",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Move multiple issues to cycle",
    goal: "Move issues ENG-13 (iss-13) and ENG-14 (iss-14) into Cycle 14 (cycle-3).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_in_cycle",
        id: "iss-13",
        expected: "cycle-3",
        weight: 0.5,
        description: "ENG-13 is in cycle-3",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_cycle",
        id: "iss-14",
        expected: "cycle-3",
        weight: 0.5,
        description: "ENG-14 is in cycle-3",
      },
    ],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["cycle", "bulk"],
  },
  {
    id: "linear-cyc-005",
    site: "linear",
    domain: "cycles",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Remove issue from cycle",
    goal: "Remove issue ENG-5 (iss-5) from Cycle 13 (cycle-2) back to no cycle.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_in_cycle",
        id: "iss-5",
        expected: null,
        weight: 1.0,
        description: "ENG-5 has no cycle",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["cycle", "move"],
  },

  // ---------------------------------------------------------------------------
  // Stage 7 — complex cycle workflows
  // ---------------------------------------------------------------------------
  {
    id: "linear-cyc-006",
    site: "linear",
    domain: "cycles",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Start upcoming cycle",
    goal: "First complete Cycle 13 (cycle-2), then start Cycle 14 (cycle-3).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "cycle_has_state",
        id: "cycle-2",
        expected: "completed",
        weight: 0.5,
        description: "Cycle 13 is completed",
      },
      {
        type: "state_predicate",
        predicate: "cycle_has_state",
        id: "cycle-3",
        expected: "active",
        weight: 0.5,
        description: "Cycle 14 is active",
      },
    ],
    maxSteps: 15,
    rewardProfile: R8,
    tags: ["cycle", "lifecycle", "multi-step"],
  },
  {
    id: "linear-cyc-007",
    site: "linear",
    domain: "cycles",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Plan cycle with issues",
    goal: "Create a new cycle 'Cycle 15' in team Engineering with description 'Bug fixes'. Then move issues ENG-15 (iss-15) and ENG-13 (iss-13) into it.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "cycle_has_state",
        id: "cycle-4",
        expected: "upcoming",
        weight: 0.34,
        description: "Cycle 15 exists",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_cycle",
        id: "iss-15",
        expected: "cycle-4",
        weight: 0.33,
        description: "ENG-15 is in cycle-4",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_cycle",
        id: "iss-13",
        expected: "cycle-4",
        weight: 0.33,
        description: "ENG-13 is in cycle-4",
      },
    ],
    maxSteps: 20,
    rewardProfile: R10,
    tags: ["cycle", "create", "multi-step"],
  },
  {
    id: "linear-cyc-008",
    site: "linear",
    domain: "cycles",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Close cycle and move incomplete",
    goal: "Complete Cycle 13 (cycle-2), then move all incomplete issues (not 'done') from cycle-2 to Cycle 14 (cycle-3). Incomplete cycle-2 issues: ENG-2 (iss-2), ENG-3 (iss-3), ENG-4 (iss-4), ENG-5 (iss-5), ENG-9 (iss-9), ENG-11 (iss-11), ENG-12 (iss-12).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "cycle_has_state",
        id: "cycle-2",
        expected: "completed",
        weight: 0.2,
        description: "Cycle 13 is completed",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_cycle",
        id: "iss-2",
        expected: "cycle-3",
        weight: 0.12,
        description: "ENG-2 moved to cycle-3",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_cycle",
        id: "iss-3",
        expected: "cycle-3",
        weight: 0.11,
        description: "ENG-3 moved to cycle-3",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_cycle",
        id: "iss-4",
        expected: "cycle-3",
        weight: 0.11,
        description: "ENG-4 moved to cycle-3",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_cycle",
        id: "iss-5",
        expected: "cycle-3",
        weight: 0.12,
        description: "ENG-5 moved to cycle-3",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_cycle",
        id: "iss-9",
        expected: "cycle-3",
        weight: 0.11,
        description: "ENG-9 moved to cycle-3",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_cycle",
        id: "iss-11",
        expected: "cycle-3",
        weight: 0.12,
        description: "ENG-11 moved to cycle-3",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_cycle",
        id: "iss-12",
        expected: "cycle-3",
        weight: 0.11,
        description: "ENG-12 moved to cycle-3",
      },
    ],
    maxSteps: 30,
    rewardProfile: R10,
    tags: ["cycle", "bulk", "lifecycle"],
  },
  {
    id: "linear-cyc-009",
    site: "linear",
    domain: "cycles",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Cycle scope adjustment",
    goal: "Remove ENG-5 (iss-5, est 8) from Cycle 13 (cycle-2) and replace it with ENG-15 (iss-15, est 1) to reduce cycle scope.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_in_cycle",
        id: "iss-5",
        expected: null,
        weight: 0.5,
        description: "ENG-5 removed from cycle",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_cycle",
        id: "iss-15",
        expected: "cycle-2",
        weight: 0.5,
        description: "ENG-15 added to cycle-2",
      },
    ],
    maxSteps: 15,
    rewardProfile: R8,
    tags: ["cycle", "move", "planning"],
  },
  {
    id: "linear-cyc-010",
    site: "linear",
    domain: "cycles",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Create and populate cycle",
    goal: "Create cycle 'Cycle 15' in team Engineering with description 'Tech debt cleanup'. Add ENG-13 (iss-13), ENG-14 (iss-14), and ENG-18 (iss-18) to it. Set estimates: ENG-13 = 5, ENG-14 = 3, ENG-18 = 8.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "cycle_has_state",
        id: "cycle-4",
        expected: "upcoming",
        weight: 0.15,
        description: "Cycle 15 exists",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-13",
        expected: { cycleId: "cycle-4", estimate: 5 },
        weight: 0.28,
        description: "ENG-13 in cycle with est 5",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-14",
        expected: { cycleId: "cycle-4", estimate: 3 },
        weight: 0.28,
        description: "ENG-14 in cycle with est 3",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-18",
        expected: { cycleId: "cycle-4", estimate: 8 },
        weight: 0.29,
        description: "ENG-18 in cycle with est 8",
      },
    ],
    maxSteps: 25,
    rewardProfile: R10,
    tags: ["cycle", "create", "bulk", "estimation"],
  },
];
