import type { TaskDefinition } from "@simbench/core";

const R = {
  completion: 5.0,
  partialPerCheck: false,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
};

export const impossibleTasks: TaskDefinition[] = [
  {
    id: "linear-imp-001",
    site: "linear",
    domain: "impossible",
    type: "no_action",
    difficulty: "medium",
    curriculumStage: 8,
    title: "Start already-active cycle",
    goal: "Start Sprint 13 (cycle-6), the active Platform cycle.",
    impossibilityReason:
      "Sprint 13 (cycle-6) is already in 'active' state for the Platform team. Starting an already-active cycle is not allowed.",
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["impossible", "error-recognition"],
  },
  {
    id: "linear-imp-002",
    site: "linear",
    domain: "impossible",
    type: "no_action",
    difficulty: "medium",
    curriculumStage: 8,
    title: "Complete already-completed cycle",
    goal: "Complete Sprint 8 (cycle-1), which is already in 'completed' state.",
    impossibilityReason:
      "Sprint 8 (cycle-1) is already completed. Only active cycles can be completed.",
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["impossible", "error-recognition"],
  },
  {
    id: "linear-imp-003",
    site: "linear",
    domain: "impossible",
    type: "no_action",
    difficulty: "medium",
    curriculumStage: 8,
    title: "Assign to nonexistent member",
    goal: "Assign issue PLT-101 to member 'Chris Davis' (usr-99).",
    impossibilityReason:
      "Member 'Chris Davis' (usr-99) does not exist. Valid members are usr-1 (Priya Sharma) through usr-15 (Suresh Pillai).",
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["impossible", "error-recognition"],
  },
  {
    id: "linear-imp-004",
    site: "linear",
    domain: "impossible",
    type: "no_action",
    difficulty: "medium",
    curriculumStage: 8,
    title: "Invalid status transition",
    goal: "Transition issue PLT-104 (iss-4, currently 'todo') directly to 'done'.",
    impossibilityReason:
      "Direct transition from 'todo' to 'done' is not allowed. Valid transitions from 'todo' are: 'in_progress', 'cancelled'. The issue must go through the workflow: todo -> in_progress -> done.",
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["impossible", "error-recognition", "workflow"],
  },
  {
    id: "linear-imp-005",
    site: "linear",
    domain: "impossible",
    type: "no_action",
    difficulty: "medium",
    curriculumStage: 8,
    title: "Only one active cycle per team",
    goal: "Start a second active cycle in the Platform team while Sprint 13 is still active.",
    impossibilityReason:
      "Sprint 13 (cycle-6) is currently active in the Platform team. Only one cycle can be active per team at a time. Sprint 13 must be completed before another can be started.",
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["impossible", "error-recognition", "cycle"],
  },
  {
    id: "linear-imp-006",
    site: "linear",
    domain: "impossible",
    type: "no_action",
    difficulty: "medium",
    curriculumStage: 8,
    title: "Delete nonexistent label",
    goal: "Delete the label 'deprecated' (label-99).",
    impossibilityReason:
      "Label 'deprecated' (label-99) does not exist. The 12 workspace labels are label-1 through label-12.",
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["impossible", "error-recognition"],
  },
];
