import type { TaskDefinition } from "@thetabench/core"

const R2 = {
  completion: 2.0,
  partialPerCheck: false,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
}
const R5 = {
  completion: 5.0,
  partialPerCheck: true,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
}
const R8 = {
  completion: 8.0,
  partialPerCheck: true,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.2,
}
const R10 = {
  completion: 10.0,
  partialPerCheck: true,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.2,
}
const R15 = {
  completion: 15.0,
  partialPerCheck: true,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.2,
}

// Key issue reference (new CESS data):
//   iss-1  PLT-101  Implement OAuth2 PKCE flow        done         proj-1
//   iss-2  PLT-102  Add refresh token rotation        in_progress  proj-1 cycle-6
//   iss-3  PLT-103  Session management API            in_progress  proj-1 cycle-6
//   iss-4  PLT-104  Rate limiting for auth endpoints  todo         proj-1 cycle-6
//   iss-5  PLT-105  MFA — TOTP                         in_progress  proj-1 cycle-5
//   iss-6  PLT-106  MFA — WebAuthn                     todo         proj-1
//   iss-8  PLT-108  SSO — OIDC                         todo         proj-1
//   iss-9  PLT-109  Auth audit logging                 backlog      proj-1
//   iss-13 PLT-113  Auth service load testing          backlog      proj-1
//   iss-14 PLT-114  Permission model redesign          todo urgent  proj-1 cycle-6
//   iss-16 PLT-116  Auth error code standardization    done         proj-1
//   iss-23 PLT-123  Security review — auth service     backlog      proj-1

export const issueTasks: TaskDefinition[] = [
  // ---------------------------------------------------------------------------
  // Stage 2 — single field updates (easy, maxSteps 10)
  // ---------------------------------------------------------------------------
  {
    id: "linear-iss-001",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Update issue title",
    goal: "Change the title of issue PLT-104 (iss-4) to 'Token-bucket rate limiting for authentication'.",
    evalChecks: [
      {
        type: "state_diff",
        entity: "issues",
        id: "iss-4",
        field: "title",
        expected: "Token-bucket rate limiting for authentication",
        weight: 1.0,
        description: "Issue PLT-104 title updated",
      },
    ],
    maxSteps: 10,
    rewardProfile: R2,
    tags: ["form-fill"],
  },
  {
    id: "linear-iss-002",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Transition issue status",
    goal: "Transition issue PLT-104 (iss-4) from 'todo' to 'in_progress'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-4",
        expected: "in_progress",
        weight: 1.0,
        description: "Issue PLT-104 status is in_progress",
      },
    ],
    maxSteps: 10,
    rewardProfile: R2,
    tags: ["form-fill"],
  },
  {
    id: "linear-iss-003",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Change issue priority",
    goal: "Change issue PLT-109 (iss-9) priority to 'high'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_priority",
        id: "iss-9",
        expected: "high",
        weight: 1.0,
        description: "Issue PLT-109 priority is high",
      },
    ],
    maxSteps: 10,
    rewardProfile: R2,
    tags: ["form-fill"],
  },
  {
    id: "linear-iss-004",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Assign issue to member",
    goal: "Assign issue PLT-106 (iss-6) to Ravi Kumar (usr-3).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_assignee",
        id: "iss-6",
        expected: "usr-3",
        weight: 1.0,
        description: "Issue PLT-106 is assigned to usr-3",
      },
    ],
    maxSteps: 10,
    rewardProfile: R2,
    tags: ["form-fill"],
  },
  {
    id: "linear-iss-005",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Set issue estimate",
    goal: "Set the estimate for issue PLT-113 (iss-13) to 5.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_estimate",
        id: "iss-13",
        expected: 5,
        weight: 1.0,
        description: "Issue PLT-113 has estimate 5",
      },
    ],
    maxSteps: 10,
    rewardProfile: R2,
    tags: ["form-fill"],
  },

  // ---------------------------------------------------------------------------
  // Stage 3 — create / delete (medium, maxSteps 15)
  // ---------------------------------------------------------------------------
  {
    id: "linear-iss-006",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Create an issue",
    goal: "Create a new issue in team Platform (team-1) titled 'Implement password strength meter' with priority 'high'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          title: "Implement password strength meter",
          priority: "high",
          teamId: "team-1",
        },
        weight: 1.0,
        description: "Issue exists with correct fields",
      },
    ],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["create"],
  },
  {
    id: "linear-iss-007",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Create urgent issue with assignee",
    goal: "Create a new issue in team Platform titled 'Login form crashes on empty submit' with priority 'urgent' and assign to Arjun Mehta (usr-2).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          title: "Login form crashes on empty submit",
          priority: "urgent",
          assigneeId: "usr-2",
          teamId: "team-1",
        },
        weight: 1.0,
        description: "Urgent issue exists with correct fields",
      },
    ],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["create"],
  },
  {
    id: "linear-iss-008",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Create issue with cycle and project",
    goal: "Create a new issue in team Platform titled 'Write integration tests for OAuth' in Sprint 13 (cycle-6) and project 'Auth Service' (proj-1) with estimate 3.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          title: "Write integration tests for OAuth",
          cycleId: "cycle-6",
          projectId: "proj-1",
          estimate: 3,
          teamId: "team-1",
        },
        weight: 1.0,
        description: "Issue exists with cycle, project, and estimate",
      },
    ],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["create", "multi-field"],
  },
  {
    id: "linear-iss-009",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Delete an issue",
    goal: "Delete issue PLT-345 (iss-95, one of the triage backlog items).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_count_equals",
        expected: 179,
        weight: 1.0,
        description: "Total issue count is 179 (one deleted)",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["delete"],
  },
  {
    id: "linear-iss-010",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Create issue in Frontend team",
    goal: "Create a new issue in the Frontend team (team-2) titled 'Update brand guidelines' with priority 'medium'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          title: "Update brand guidelines",
          priority: "medium",
          teamId: "team-2",
        },
        weight: 1.0,
        description: "Issue exists in Frontend team",
      },
    ],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["create"],
  },

  // ---------------------------------------------------------------------------
  // Stage 5 — multi-field updates (medium, maxSteps 15)
  // ---------------------------------------------------------------------------
  {
    id: "linear-iss-011",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Multi-field update",
    goal: "Update issue PLT-113 (iss-13): set title to 'Auth service k6 load test suite', priority to 'high', and estimate to 5.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-13",
        expected: {
          title: "Auth service k6 load test suite",
          priority: "high",
          estimate: 5,
        },
        weight: 1.0,
        description: "PLT-113 has updated title, priority, and estimate",
      },
    ],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["multi-field"],
  },
  {
    id: "linear-iss-012",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Add issue to project",
    goal: "Add issue PLT-301 (iss-51, currently a triage backlog item) to the 'Auth Service' project (proj-1).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-51",
        expected: {
          projectId: "proj-1",
        },
        weight: 1.0,
        description: "PLT-301 is in proj-1",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["form-fill"],
  },
  {
    id: "linear-iss-013",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Reassign and reprioritize",
    goal: "Reassign issue PLT-109 (iss-9) from unassigned to Priya Sharma (usr-1) and change priority from 'medium' to 'high'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_assignee",
        id: "iss-9",
        expected: "usr-1",
        weight: 0.5,
        description: "PLT-109 is assigned to usr-1",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_priority",
        id: "iss-9",
        expected: "high",
        weight: 0.5,
        description: "PLT-109 priority is high",
      },
    ],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["multi-field"],
  },
  {
    id: "linear-iss-014",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Update description and labels",
    goal: "Update issue PLT-106 (iss-6): change description to 'FIDO2/WebAuthn enrollment with platform and cross-platform authenticators' and set labelIds to ['label-2', 'label-6'].",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-6",
        expected: {
          description:
            "FIDO2/WebAuthn enrollment with platform and cross-platform authenticators",
          labelIds: ["label-2", "label-6"],
        },
        weight: 1.0,
        description: "PLT-106 has updated description and labels",
      },
    ],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["multi-field"],
  },
  {
    id: "linear-iss-015",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Set due date",
    goal: "Set the due date of issue PLT-105 (iss-5) to '2026-04-30'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-5",
        expected: {
          dueDate: "2026-04-30",
        },
        weight: 1.0,
        description: "PLT-105 has due date 2026-04-30",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["form-fill"],
  },

  // ---------------------------------------------------------------------------
  // Stage 7 — bulk/complex operations (hard, maxSteps 25)
  // ---------------------------------------------------------------------------
  {
    id: "linear-iss-016",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Transition Sprint 13 in-progress to done",
    goal: "Transition all in_progress issues in Sprint 13 (cycle-6) to 'done'. In-progress issues in Sprint 13: PLT-102 (iss-2), PLT-103 (iss-3), PLT-107 (iss-7), PLT-112 (iss-12), PLT-118 (iss-18), PLT-202 (iss-40), PLT-204 (iss-42), PLT-205 (iss-43), PLT-211 (iss-49).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-2",
        expected: "done",
        weight: 0.12,
        description: "PLT-102 done",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-3",
        expected: "done",
        weight: 0.12,
        description: "PLT-103 done",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-7",
        expected: "done",
        weight: 0.11,
        description: "PLT-107 done",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-12",
        expected: "done",
        weight: 0.11,
        description: "PLT-112 done",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-18",
        expected: "done",
        weight: 0.11,
        description: "PLT-118 done",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-40",
        expected: "done",
        weight: 0.11,
        description: "PLT-202 done",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-42",
        expected: "done",
        weight: 0.11,
        description: "PLT-204 done",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-43",
        expected: "done",
        weight: 0.11,
        description: "PLT-205 done",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-49",
        expected: "done",
        weight: 0.1,
        description: "PLT-211 done",
      },
    ],
    maxSteps: 30,
    rewardProfile: R10,
    tags: ["bulk", "transition"],
  },
  {
    id: "linear-iss-017",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Bulk priority for Payment API issues",
    goal: "Set priority to 'urgent' for all Payment API v2 (proj-3) issues that are currently 'in_progress'. In-progress Payment API issues: PLT-202 (iss-40), PLT-204 (iss-42), PLT-205 (iss-43), PLT-211 (iss-49).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_priority",
        id: "iss-40",
        expected: "urgent",
        weight: 0.25,
        description: "PLT-202 urgent",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_priority",
        id: "iss-42",
        expected: "urgent",
        weight: 0.25,
        description: "PLT-204 urgent",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_priority",
        id: "iss-43",
        expected: "urgent",
        weight: 0.25,
        description: "PLT-205 urgent",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_priority",
        id: "iss-49",
        expected: "urgent",
        weight: 0.25,
        description: "PLT-211 urgent",
      },
    ],
    maxSteps: 25,
    rewardProfile: R10,
    tags: ["bulk", "priority"],
  },
  {
    id: "linear-iss-018",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Set estimates for triage backlog",
    goal: "Set estimate to 3 for these three unestimated triage backlog issues: PLT-301 (iss-51), PLT-302 (iss-52), PLT-303 (iss-53).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_estimate",
        id: "iss-51",
        expected: 3,
        weight: 0.34,
        description: "PLT-301 est 3",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_estimate",
        id: "iss-52",
        expected: 3,
        weight: 0.33,
        description: "PLT-302 est 3",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_estimate",
        id: "iss-53",
        expected: 3,
        weight: 0.33,
        description: "PLT-303 est 3",
      },
    ],
    maxSteps: 25,
    rewardProfile: R10,
    tags: ["bulk", "estimation"],
  },

  // ---------------------------------------------------------------------------
  // Stage 8 — complex multi-step (hard, maxSteps 30)
  // ---------------------------------------------------------------------------
  {
    id: "linear-iss-019",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "hard",
    curriculumStage: 8,
    title: "Create 3 issues in Sprint 13",
    goal: "Create 3 new issues in Platform team (team-1), all in Sprint 13 (cycle-6): 'Write API contract tests' (est 3), 'Set up monitoring alerts' (est 2), 'Update deployment docs' (est 1).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          title: "Write API contract tests",
          cycleId: "cycle-6",
          estimate: 3,
          teamId: "team-1",
        },
        weight: 0.34,
        description: "'Write API contract tests' in cycle with est 3",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          title: "Set up monitoring alerts",
          cycleId: "cycle-6",
          estimate: 2,
          teamId: "team-1",
        },
        weight: 0.33,
        description: "'Set up monitoring alerts' in cycle with est 2",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          title: "Update deployment docs",
          cycleId: "cycle-6",
          estimate: 1,
          teamId: "team-1",
        },
        weight: 0.33,
        description: "'Update deployment docs' in cycle with est 1",
      },
    ],
    maxSteps: 30,
    rewardProfile: R15,
    tags: ["create", "bulk", "cycle"],
  },
  {
    id: "linear-iss-020",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "hard",
    curriculumStage: 8,
    title: "Triage backlog issues",
    goal: "Triage two backlog issues: assign PLT-301 (iss-51) to Ravi Kumar (usr-3), assign PLT-302 (iss-52) to Sanjay Gupta (usr-13), and set both to priority 'medium' with estimate 5 each.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-51",
        expected: {
          assigneeId: "usr-3",
          priority: "medium",
          estimate: 5,
        },
        weight: 0.5,
        description: "PLT-301 triaged correctly",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-52",
        expected: {
          assigneeId: "usr-13",
          priority: "medium",
          estimate: 5,
        },
        weight: 0.5,
        description: "PLT-302 triaged correctly",
      },
    ],
    maxSteps: 25,
    rewardProfile: R10,
    tags: ["multi-step", "triage"],
  },
  {
    id: "linear-iss-021",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "hard",
    curriculumStage: 8,
    title: "Complex issue workflow",
    goal: "Create a new issue 'API returns 500 on concurrent requests' in Platform team (team-1) with priority 'urgent', assign to Priya Sharma (usr-1), add to Sprint 13 (cycle-6), project Auth Service (proj-1), set estimate 8, and add labelIds ['label-5', 'label-2'].",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          title: "API returns 500 on concurrent requests",
          priority: "urgent",
          assigneeId: "usr-1",
          cycleId: "cycle-6",
          projectId: "proj-1",
          estimate: 8,
          labelIds: ["label-5", "label-2"],
          teamId: "team-1",
        },
        weight: 1.0,
        description: "Complex issue created with all fields",
      },
    ],
    maxSteps: 20,
    rewardProfile: R10,
    tags: ["create", "multi-field", "complex"],
  },
  {
    id: "linear-iss-022",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "hard",
    curriculumStage: 8,
    title: "Transition chain",
    goal: "Move issue PLT-104 (iss-4) through the workflow: todo -> in_progress -> done.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-4",
        expected: "done",
        weight: 1.0,
        description: "PLT-104 is done after transition chain",
      },
    ],
    maxSteps: 20,
    rewardProfile: R8,
    tags: ["transition", "multi-step"],
  },
  {
    id: "linear-iss-023",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "hard",
    curriculumStage: 8,
    title: "Move issues to active cycle",
    goal: "Move issues PLT-113 (iss-13) and PLT-115 (iss-15) into Sprint 13 (cycle-6) and set their estimates to 5 each.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-13",
        expected: {
          cycleId: "cycle-6",
          estimate: 5,
        },
        weight: 0.5,
        description: "PLT-113 in cycle-6 with est 5",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-15",
        expected: {
          cycleId: "cycle-6",
          estimate: 5,
        },
        weight: 0.5,
        description: "PLT-115 in cycle-6 with est 5",
      },
    ],
    maxSteps: 20,
    rewardProfile: R8,
    tags: ["cycle", "multi-step"],
  },
  {
    id: "linear-iss-024",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "hard",
    curriculumStage: 8,
    title: "Create issue with labels",
    goal: "Create an issue titled 'Unit tests for OAuth callback handler' in Platform team (team-1), assign to Ravi Kumar (usr-3), set estimate 2, add to Sprint 13 (cycle-6), and set labelIds to ['label-2', 'label-8'].",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          title: "Unit tests for OAuth callback handler",
          assigneeId: "usr-3",
          estimate: 2,
          cycleId: "cycle-6",
          labelIds: ["label-2", "label-8"],
          teamId: "team-1",
        },
        weight: 1.0,
        description: "Issue created with all correct fields",
      },
    ],
    maxSteps: 20,
    rewardProfile: R10,
    tags: ["create", "multi-field"],
  },
]
