import type { TaskDefinition } from "@simbench/core";

const R2 = {
  completion: 2.0,
  partialPerCheck: false,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
};
const R5 = {
  completion: 5.0,
  partialPerCheck: true,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
};
const R8 = {
  completion: 8.0,
  partialPerCheck: true,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.2,
};
const R10 = {
  completion: 10.0,
  partialPerCheck: true,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.2,
};
const R15 = {
  completion: 15.0,
  partialPerCheck: true,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.2,
};

export const issueTasks: TaskDefinition[] = [
  // ---------------------------------------------------------------------------
  // Stage 2 — single field updates (easy, maxSteps 10)
  // ---------------------------------------------------------------------------
  {
    id: "linear-iss-001",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Update issue title",
    goal: "Change the title of issue ENG-4 (iss-4) to 'Build session management microservice'.",
    evalChecks: [
      {
        type: "state_diff",
        entity: "issues",
        id: "iss-4",
        field: "title",
        expected: "Build session management microservice",
        weight: 1.0,
        description: "Issue ENG-4 title is 'Build session management microservice'",
      },
    ],
    maxSteps: 10,
    rewardProfile: R2,
    tags: ["form-fill"],
  },
  {
    id: "linear-iss-002",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Transition issue status",
    goal: "Transition issue ENG-4 (iss-4) from 'todo' to 'in_progress'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-4",
        expected: "in_progress",
        weight: 1.0,
        description: "Issue ENG-4 status is in_progress",
      },
    ],
    maxSteps: 10,
    rewardProfile: R2,
    tags: ["form-fill"],
  },
  {
    id: "linear-iss-003",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Change issue priority",
    goal: "Change issue ENG-9 (iss-9) priority to 'urgent'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_priority",
        id: "iss-9",
        expected: "urgent",
        weight: 1.0,
        description: "Issue ENG-9 priority is urgent",
      },
    ],
    maxSteps: 10,
    rewardProfile: R2,
    tags: ["form-fill"],
  },
  {
    id: "linear-iss-004",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Assign issue to member",
    goal: "Assign issue ENG-5 (iss-5) to Jordan Lee (usr-3).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_assignee",
        id: "iss-5",
        expected: "usr-3",
        weight: 1.0,
        description: "Issue ENG-5 is assigned to usr-3",
      },
    ],
    maxSteps: 10,
    rewardProfile: R2,
    tags: ["form-fill"],
  },
  {
    id: "linear-iss-005",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Set issue estimate",
    goal: "Set the estimate for issue ENG-13 (iss-13) to 5.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_estimate",
        id: "iss-13",
        expected: 5,
        weight: 1.0,
        description: "Issue ENG-13 has estimate 5",
      },
    ],
    maxSteps: 10,
    rewardProfile: R2,
    tags: ["form-fill"],
  },

  // ---------------------------------------------------------------------------
  // Stage 3 — create / delete (medium, maxSteps 15)
  // ---------------------------------------------------------------------------
  {
    id: "linear-iss-006",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Create an issue",
    goal: "Create a new issue in team Engineering (team-1) titled 'Implement password strength meter' with priority 'high'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          title: "Implement password strength meter",
          priority: "high",
          teamId: "team-1",
        },
        weight: 1.0,
        description: "Issue 'Implement password strength meter' exists with correct fields",
      },
    ],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["create"],
  },
  {
    id: "linear-iss-007",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Create urgent issue with assignee",
    goal: "Create a new issue in team Engineering titled 'Login form crashes on empty submit' with priority 'urgent' and assign to Sam Williams (usr-2).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          title: "Login form crashes on empty submit",
          priority: "urgent",
          assigneeId: "usr-2",
          teamId: "team-1",
        },
        weight: 1.0,
        description: "Urgent issue exists with correct fields",
      },
    ],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["create"],
  },
  {
    id: "linear-iss-008",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Create issue with cycle and project",
    goal: "Create a new issue in team Engineering titled 'Write integration tests for OAuth' in Cycle 13 (cycle-2) and project 'Auth System' (proj-1) with estimate 3.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          title: "Write integration tests for OAuth",
          cycleId: "cycle-2",
          projectId: "proj-1",
          estimate: 3,
          teamId: "team-1",
        },
        weight: 1.0,
        description: "Issue exists with cycle, project, and estimate",
      },
    ],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["create", "multi-field"],
  },
  {
    id: "linear-iss-009",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Delete an issue",
    goal: "Delete issue ENG-16 (iss-16, 'Add loading skeletons').",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_count_equals",
        expected: 24,
        weight: 1.0,
        description: "Total issue count is 24 (one deleted)",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["delete"],
  },
  {
    id: "linear-iss-010",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Create issue in Design team",
    goal: "Create a new issue in the Design team (team-2) titled 'Update brand guidelines' with priority 'medium'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          title: "Update brand guidelines",
          priority: "medium",
          teamId: "team-2",
        },
        weight: 1.0,
        description: "Issue exists in Design team",
      },
    ],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["create"],
  },

  // ---------------------------------------------------------------------------
  // Stage 5 — multi-field updates (medium, maxSteps 15)
  // ---------------------------------------------------------------------------
  {
    id: "linear-iss-011",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Multi-field update",
    goal: "Update issue ENG-13 (iss-13): set title to 'Standardize API error codes', priority to 'high', and estimate to 5.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-13",
        expected: {
          title: "Standardize API error codes",
          priority: "high",
          estimate: 5,
        },
        weight: 1.0,
        description: "ENG-13 has updated title, priority, and estimate",
      },
    ],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["multi-field"],
  },
  {
    id: "linear-iss-012",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Add issue to project",
    goal: "Add issue ENG-14 (iss-14) to the 'Auth System' project (proj-1).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-14",
        expected: {
          projectId: "proj-1",
        },
        weight: 1.0,
        description: "ENG-14 is in proj-1",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["form-fill"],
  },
  {
    id: "linear-iss-013",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Reassign and reprioritize",
    goal: "Reassign issue ENG-9 (iss-9) from Sam Williams to Alex Johnson (usr-1) and change priority from 'medium' to 'high'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_assignee",
        id: "iss-9",
        expected: "usr-1",
        weight: 0.5,
        description: "ENG-9 is assigned to usr-1",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_priority",
        id: "iss-9",
        expected: "high",
        weight: 0.5,
        description: "ENG-9 priority is high",
      },
    ],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["multi-field"],
  },
  {
    id: "linear-iss-014",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Update description and labels",
    goal: "Update issue ENG-6 (iss-6): change description to 'Document all auth endpoints including OAuth, MFA, and session management' and set labelIds to ['label-4', 'label-2'].",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-6",
        expected: {
          description: "Document all auth endpoints including OAuth, MFA, and session management",
          labelIds: ["label-4", "label-2"],
        },
        weight: 1.0,
        description: "ENG-6 has updated description and labels",
      },
    ],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["multi-field"],
  },
  {
    id: "linear-iss-015",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Set due date",
    goal: "Set the due date of issue ENG-5 (iss-5) to '2025-05-15'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-5",
        expected: {
          dueDate: "2025-05-15",
        },
        weight: 1.0,
        description: "ENG-5 has due date 2025-05-15",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["form-fill"],
  },

  // ---------------------------------------------------------------------------
  // Stage 7 — bulk/complex operations (hard, maxSteps 25)
  // ---------------------------------------------------------------------------
  {
    id: "linear-iss-016",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Transition all in-progress to done",
    goal: "Transition all issues currently 'in_progress' to 'done'. In-progress issues: ENG-2 (iss-2), ENG-3 (iss-3), ENG-9 (iss-9), ENG-11 (iss-11), ENG-12 (iss-12), DES-2 (iss-20).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-2",
        expected: "done",
        weight: 0.17,
        description: "ENG-2 status is done",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-3",
        expected: "done",
        weight: 0.17,
        description: "ENG-3 status is done",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-9",
        expected: "done",
        weight: 0.17,
        description: "ENG-9 status is done",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-11",
        expected: "done",
        weight: 0.17,
        description: "ENG-11 status is done",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-12",
        expected: "done",
        weight: 0.16,
        description: "ENG-12 status is done",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-20",
        expected: "done",
        weight: 0.16,
        description: "DES-2 status is done",
      },
    ],
    maxSteps: 30,
    rewardProfile: R10,
    tags: ["bulk", "transition"],
  },
  {
    id: "linear-iss-017",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Bulk priority for bug issues",
    goal: "Set priority to 'urgent' for all issues labeled 'bug' (label-1). Bug issues: ENG-3 (iss-3), ENG-9 (iss-9), ENG-15 (iss-15), DES-5 (iss-23).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_priority",
        id: "iss-3",
        expected: "urgent",
        weight: 0.25,
        description: "ENG-3 priority is urgent",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_priority",
        id: "iss-9",
        expected: "urgent",
        weight: 0.25,
        description: "ENG-9 priority is urgent",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_priority",
        id: "iss-15",
        expected: "urgent",
        weight: 0.25,
        description: "ENG-15 priority is urgent",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_priority",
        id: "iss-23",
        expected: "urgent",
        weight: 0.25,
        description: "DES-5 priority is urgent",
      },
    ],
    maxSteps: 25,
    rewardProfile: R10,
    tags: ["bulk", "priority"],
  },
  {
    id: "linear-iss-018",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Set estimates for unestimated issues",
    goal: "Set estimate to 3 for all issues that currently have no estimate (null). Unestimated: ENG-13 (iss-13), ENG-14 (iss-14), ENG-18 (iss-18).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_estimate",
        id: "iss-13",
        expected: 3,
        weight: 0.34,
        description: "ENG-13 has estimate 3",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_estimate",
        id: "iss-14",
        expected: 3,
        weight: 0.33,
        description: "ENG-14 has estimate 3",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_estimate",
        id: "iss-18",
        expected: 3,
        weight: 0.33,
        description: "ENG-18 has estimate 3",
      },
    ],
    maxSteps: 25,
    rewardProfile: R10,
    tags: ["bulk", "estimation"],
  },

  // ---------------------------------------------------------------------------
  // Stage 8 — complex multi-step (hard, maxSteps 30)
  // ---------------------------------------------------------------------------
  {
    id: "linear-iss-019",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "hard",
    curriculumStage: 8,
    title: "Create 3 issues in cycle",
    goal: "Create 3 new issues in team Engineering (team-1), all in Cycle 13 (cycle-2): 'Write API contract tests' (est 3), 'Set up monitoring alerts' (est 2), 'Update deployment docs' (est 1).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          title: "Write API contract tests",
          cycleId: "cycle-2",
          estimate: 3,
          teamId: "team-1",
        },
        weight: 0.34,
        description: "Issue 'Write API contract tests' exists in cycle with est 3",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          title: "Set up monitoring alerts",
          cycleId: "cycle-2",
          estimate: 2,
          teamId: "team-1",
        },
        weight: 0.33,
        description: "Issue 'Set up monitoring alerts' exists in cycle with est 2",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          title: "Update deployment docs",
          cycleId: "cycle-2",
          estimate: 1,
          teamId: "team-1",
        },
        weight: 0.33,
        description: "Issue 'Update deployment docs' exists in cycle with est 1",
      },
    ],
    maxSteps: 30,
    rewardProfile: R15,
    tags: ["create", "bulk", "cycle"],
  },
  {
    id: "linear-iss-020",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "hard",
    curriculumStage: 8,
    title: "Triage backlog issues",
    goal: "Triage backlog issues: assign ENG-13 (iss-13) to Jordan Lee (usr-3), assign ENG-14 (iss-14) to Taylor Brown (usr-4), and set both to priority 'medium' with estimate 5 each.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-13",
        expected: {
          assigneeId: "usr-3",
          priority: "medium",
          estimate: 5,
        },
        weight: 0.5,
        description: "ENG-13 is triaged correctly",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-14",
        expected: {
          assigneeId: "usr-4",
          priority: "medium",
          estimate: 5,
        },
        weight: 0.5,
        description: "ENG-14 is triaged correctly",
      },
    ],
    maxSteps: 25,
    rewardProfile: R10,
    tags: ["multi-step", "triage"],
  },
  {
    id: "linear-iss-021",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "hard",
    curriculumStage: 8,
    title: "Complex issue workflow",
    goal: "Create a new issue 'API returns 500 on concurrent requests' in Engineering team (team-1) with priority 'urgent', assign to Alex Johnson (usr-1), add to Cycle 13 (cycle-2), project Auth System (proj-1), set estimate 8, and add labelIds ['label-1', 'label-2'].",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          title: "API returns 500 on concurrent requests",
          priority: "urgent",
          assigneeId: "usr-1",
          cycleId: "cycle-2",
          projectId: "proj-1",
          estimate: 8,
          labelIds: ["label-1", "label-2"],
          teamId: "team-1",
        },
        weight: 1.0,
        description: "Complex issue created with all fields",
      },
    ],
    maxSteps: 20,
    rewardProfile: R10,
    tags: ["create", "multi-field", "complex"],
  },
  {
    id: "linear-iss-022",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "hard",
    curriculumStage: 8,
    title: "Transition chain",
    goal: "Move issue ENG-4 (iss-4) through the workflow: todo -> in_progress -> done.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-4",
        expected: "done",
        weight: 1.0,
        description: "ENG-4 is done after transition chain",
      },
    ],
    maxSteps: 20,
    rewardProfile: R8,
    tags: ["transition", "multi-step"],
  },
  {
    id: "linear-iss-023",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "hard",
    curriculumStage: 8,
    title: "Prepare issues for cycle",
    goal: "Move issues ENG-13 (iss-13) and ENG-14 (iss-14) into Cycle 14 (cycle-3) and set their estimates to 5 each.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-13",
        expected: {
          cycleId: "cycle-3",
          estimate: 5,
        },
        weight: 0.5,
        description: "ENG-13 is in cycle-3 with estimate 5",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-14",
        expected: {
          cycleId: "cycle-3",
          estimate: 5,
        },
        weight: 0.5,
        description: "ENG-14 is in cycle-3 with estimate 5",
      },
    ],
    maxSteps: 20,
    rewardProfile: R8,
    tags: ["cycle", "multi-step"],
  },
  {
    id: "linear-iss-024",
    site: "linear",
    domain: "issues",
    type: "action",
    difficulty: "hard",
    curriculumStage: 8,
    title: "Create issue with labels",
    goal: "Create an issue titled 'Unit tests for OAuth callback handler' in Engineering team (team-1), assign to Jordan Lee (usr-3), set estimate 2, add to Cycle 13 (cycle-2), and set labelIds to ['label-2', 'label-3'].",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          title: "Unit tests for OAuth callback handler",
          assigneeId: "usr-3",
          estimate: 2,
          cycleId: "cycle-2",
          labelIds: ["label-2", "label-3"],
          teamId: "team-1",
        },
        weight: 1.0,
        description: "Issue created with all correct fields",
      },
    ],
    maxSteps: 20,
    rewardProfile: R10,
    tags: ["create", "multi-field"],
  },
];
