import type { TaskDefinition } from "@simbench/core";

const R5 = {
  completion: 5.0,
  partialPerCheck: true,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
};
const R8 = {
  completion: 8.0,
  partialPerCheck: true,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.2,
};

export const labelTasks: TaskDefinition[] = [
  {
    id: "linear-lbl-001",
    site: "linear",
    domain: "labels",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Create a label",
    goal: "Create a new label named 'critical' with color '#dc2626' in team Engineering (team-1).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "label_exists",
        expected: { name: "critical", color: "#dc2626", teamId: "team-1" },
        weight: 1.0,
        description: "Label 'critical' exists with correct color",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["create", "label"],
  },
  {
    id: "linear-lbl-002",
    site: "linear",
    domain: "labels",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Update label color",
    goal: "Update the 'bug' label (label-1) color to '#b91c1c'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "label_exists",
        expected: { name: "bug", color: "#b91c1c" },
        weight: 1.0,
        description: "Label 'bug' has updated color",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["update", "label"],
  },
  {
    id: "linear-lbl-003",
    site: "linear",
    domain: "labels",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Assign label to issue",
    goal: "Add the 'performance' label (label-6) to issue ENG-8 (iss-8) by updating its labelIds to include label-6. Current labelIds: ['label-2']. New labelIds: ['label-2', 'label-6'].",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-8",
        expected: {
          labelIds: ["label-2", "label-6"],
        },
        weight: 1.0,
        description: "ENG-8 has both label-2 and label-6",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["label", "issue"],
  },
  {
    id: "linear-lbl-004",
    site: "linear",
    domain: "labels",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Create label in Design team",
    goal: "Create a new label named 'accessibility' with color '#059669' in the Design team (team-2).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "label_exists",
        expected: { name: "accessibility", color: "#059669", teamId: "team-2" },
        weight: 1.0,
        description: "Label 'accessibility' exists in Design team",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["create", "label"],
  },
  {
    id: "linear-lbl-005",
    site: "linear",
    domain: "labels",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Create label and assign to issues",
    goal: "Create a label 'tech-debt' with color '#6b7280' in Engineering team (team-1). Then add the new label (label-7) to issues ENG-13 (iss-13) and ENG-18 (iss-18).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "label_exists",
        expected: { name: "tech-debt", color: "#6b7280", teamId: "team-1" },
        weight: 0.34,
        description: "Label 'tech-debt' exists",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-13",
        expected: { labelIds: ["label-3", "label-7"] },
        weight: 0.33,
        description: "ENG-13 has label-7",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-18",
        expected: { labelIds: ["label-6", "label-7"] },
        weight: 0.33,
        description: "ENG-18 has label-7",
      },
    ],
    maxSteps: 20,
    rewardProfile: R8,
    tags: ["create", "label", "multi-step"],
  },
];
