import type { TaskDefinition } from "@simbench/core";

const R10 = {
  completion: 10.0,
  partialPerCheck: true,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.2,
};
const R15 = {
  completion: 15.0,
  partialPerCheck: true,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.2,
};

export const multiDomainTasks: TaskDefinition[] = [
  {
    id: "linear-multi-001",
    site: "linear",
    domain: "multi-domain",
    type: "action",
    difficulty: "hard",
    curriculumStage: 9,
    title: "Cycle planning workflow",
    goal: "Complete Cycle 13 (cycle-2). Then start Cycle 14 (cycle-3). Move incomplete issues from cycle-2 (ENG-2 iss-2, ENG-4 iss-4) to cycle-3.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "cycle_has_state",
        id: "cycle-2",
        expected: "completed",
        weight: 0.25,
        description: "Cycle 13 is completed",
      },
      {
        type: "state_predicate",
        predicate: "cycle_has_state",
        id: "cycle-3",
        expected: "active",
        weight: 0.25,
        description: "Cycle 14 is active",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_cycle",
        id: "iss-2",
        expected: "cycle-3",
        weight: 0.25,
        description: "ENG-2 moved to cycle-3",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_cycle",
        id: "iss-4",
        expected: "cycle-3",
        weight: 0.25,
        description: "ENG-4 moved to cycle-3",
      },
    ],
    maxSteps: 25,
    rewardProfile: R10,
    tags: ["cycle", "lifecycle", "multi-step"],
  },
  {
    id: "linear-multi-002",
    site: "linear",
    domain: "multi-domain",
    type: "action",
    difficulty: "hard",
    curriculumStage: 9,
    title: "Release management",
    goal: "Prepare for release: transition all 'in_progress' issues in the active cycle to 'done' (ENG-2 iss-2, ENG-3 iss-3, ENG-9 iss-9, ENG-11 iss-11, ENG-12 iss-12), then complete Cycle 13 (cycle-2).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-2",
        expected: "done",
        weight: 0.12,
        description: "ENG-2 is done",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-3",
        expected: "done",
        weight: 0.12,
        description: "ENG-3 is done",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-9",
        expected: "done",
        weight: 0.12,
        description: "ENG-9 is done",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-11",
        expected: "done",
        weight: 0.12,
        description: "ENG-11 is done",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-12",
        expected: "done",
        weight: 0.12,
        description: "ENG-12 is done",
      },
      {
        type: "state_predicate",
        predicate: "cycle_has_state",
        id: "cycle-2",
        expected: "completed",
        weight: 0.4,
        description: "Cycle 13 is completed",
      },
    ],
    maxSteps: 30,
    rewardProfile: R10,
    tags: ["transition", "cycle", "release"],
  },
  {
    id: "linear-multi-003",
    site: "linear",
    domain: "multi-domain",
    type: "action",
    difficulty: "hard",
    curriculumStage: 9,
    title: "Bug triage and cycle",
    goal: "Triage bug DES-5 (iss-23): assign to Sam Williams (usr-2), set priority to 'urgent', set estimate to 2. Then create a new cycle 'Bug Fix Cycle' in Engineering team with description 'Critical bug fixes'. Move ENG-3 (iss-3) and ENG-9 (iss-9) into the new cycle.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-23",
        expected: {
          assigneeId: "usr-2",
          priority: "urgent",
          estimate: 2,
        },
        weight: 0.3,
        description: "DES-5 triaged correctly",
      },
      {
        type: "state_predicate",
        predicate: "cycle_has_state",
        id: "cycle-4",
        expected: "upcoming",
        weight: 0.2,
        description: "Bug Fix Cycle created",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_cycle",
        id: "iss-3",
        expected: "cycle-4",
        weight: 0.25,
        description: "ENG-3 in bug fix cycle",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_cycle",
        id: "iss-9",
        expected: "cycle-4",
        weight: 0.25,
        description: "ENG-9 in bug fix cycle",
      },
    ],
    maxSteps: 30,
    rewardProfile: R15,
    tags: ["triage", "cycle", "create", "multi-step"],
  },
  {
    id: "linear-multi-004",
    site: "linear",
    domain: "multi-domain",
    type: "action",
    difficulty: "hard",
    curriculumStage: 9,
    title: "Full team setup",
    goal: "Create a new team 'Backend' with key 'BE', lead Alex Johnson (usr-1), members [usr-1, usr-3]. Create a project 'API Platform' in the new team (team-3). Create an issue 'Set up API gateway' in team BE (team-3) with priority 'high', estimate 8, assigned to Jordan Lee (usr-3).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "team_has_fields",
        expected: {
          name: "Backend",
          key: "BE",
          leadId: "usr-1",
        },
        weight: 0.3,
        description: "Backend team created",
      },
      {
        type: "state_predicate",
        predicate: "project_has_fields",
        expected: {
          name: "API Platform",
          teamId: "team-3",
        },
        weight: 0.2,
        description: "API Platform project exists in team-3",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          title: "Set up API gateway",
          priority: "high",
          estimate: 8,
          assigneeId: "usr-3",
          teamId: "team-3",
        },
        weight: 0.5,
        description: "Issue created with all fields in BE team",
      },
    ],
    maxSteps: 30,
    rewardProfile: R15,
    tags: ["team", "project", "create", "multi-step"],
  },
  {
    id: "linear-multi-005",
    site: "linear",
    domain: "multi-domain",
    type: "action",
    difficulty: "hard",
    curriculumStage: 10,
    title: "End-to-end cycle workflow",
    goal: "Complete the full cycle workflow: (1) Complete Cycle 13 (cycle-2), (2) Start Cycle 14 (cycle-3), (3) Create 2 new issues in Engineering team in cycle-3: 'Optimize database queries' (est 5) and 'Add caching layer' (est 8), both assigned to Alex Johnson (usr-1).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "cycle_has_state",
        id: "cycle-2",
        expected: "completed",
        weight: 0.15,
        description: "Cycle 13 completed",
      },
      {
        type: "state_predicate",
        predicate: "cycle_has_state",
        id: "cycle-3",
        expected: "active",
        weight: 0.15,
        description: "Cycle 14 active",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          title: "Optimize database queries",
          estimate: 5,
          assigneeId: "usr-1",
          cycleId: "cycle-3",
          teamId: "team-1",
        },
        weight: 0.35,
        description: "Optimize DB issue created in cycle",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          title: "Add caching layer",
          estimate: 8,
          assigneeId: "usr-1",
          cycleId: "cycle-3",
          teamId: "team-1",
        },
        weight: 0.35,
        description: "Add caching issue created in cycle",
      },
    ],
    maxSteps: 30,
    rewardProfile: R15,
    tags: ["cycle", "create", "lifecycle", "end-to-end"],
  },
  {
    id: "linear-multi-006",
    site: "linear",
    domain: "multi-domain",
    type: "action",
    difficulty: "hard",
    curriculumStage: 9,
    title: "Cross-team issue management",
    goal: "Create an issue 'Shared auth library crash' in Engineering team (team-1) with priority 'urgent', estimate 3, assigned to Jordan Lee (usr-3). Then create a related issue 'Update marketing site auth flow' in Design team (team-2) with priority 'high', assigned to Taylor Brown (usr-4).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          title: "Shared auth library crash",
          priority: "urgent",
          estimate: 3,
          assigneeId: "usr-3",
          teamId: "team-1",
        },
        weight: 0.5,
        description: "Issue created in Engineering team",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          title: "Update marketing site auth flow",
          priority: "high",
          assigneeId: "usr-4",
          teamId: "team-2",
        },
        weight: 0.5,
        description: "Issue created in Design team",
      },
    ],
    maxSteps: 25,
    rewardProfile: R10,
    tags: ["create", "cross-team"],
  },
  {
    id: "linear-multi-007",
    site: "linear",
    domain: "multi-domain",
    type: "action",
    difficulty: "hard",
    curriculumStage: 10,
    title: "Backlog grooming session",
    goal: "Groom the Engineering backlog: (1) Set estimates for ENG-13 (iss-13) to 5 and ENG-14 (iss-14) to 3, (2) Assign ENG-13 to Jordan Lee (usr-3) and ENG-14 to Taylor Brown (usr-4), (3) Add ENG-14 to project Auth System (proj-1), (4) Create a new issue 'API versioning strategy' with estimate 5 in Engineering team.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-13",
        expected: { estimate: 5, assigneeId: "usr-3" },
        weight: 0.25,
        description: "ENG-13 groomed",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-14",
        expected: { estimate: 3, assigneeId: "usr-4", projectId: "proj-1" },
        weight: 0.25,
        description: "ENG-14 groomed with project",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          title: "API versioning strategy",
          estimate: 5,
          teamId: "team-1",
        },
        weight: 0.5,
        description: "New issue created",
      },
    ],
    maxSteps: 30,
    rewardProfile: R15,
    tags: ["grooming", "multi-step", "estimation"],
  },
  {
    id: "linear-multi-008",
    site: "linear",
    domain: "multi-domain",
    type: "action",
    difficulty: "hard",
    curriculumStage: 10,
    title: "Emergency hotfix workflow",
    goal: "Handle an emergency: (1) Create an issue 'Production database connection pool exhausted' in Engineering team with priority 'urgent', estimate 1, assigned to Alex Johnson (usr-1), (2) Add it to Cycle 13 (cycle-2), (3) Immediately transition it to 'in_progress' (first to 'todo', then to 'in_progress').",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          title: "Production database connection pool exhausted",
          priority: "urgent",
          estimate: 1,
          assigneeId: "usr-1",
          cycleId: "cycle-2",
          status: "in_progress",
          teamId: "team-1",
        },
        weight: 1.0,
        description: "Emergency issue created, in cycle, and in progress",
      },
    ],
    maxSteps: 25,
    rewardProfile: R10,
    tags: ["create", "transition", "emergency"],
  },
];
