import type { TaskDefinition } from "@thetabench/core"

const R10 = {
  completion: 10.0,
  partialPerCheck: true,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.2,
}
const R15 = {
  completion: 15.0,
  partialPerCheck: true,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.2,
}

export const multiDomainTasks: TaskDefinition[] = [
  {
    id: "linear-multi-001",
    site: "linear",
    domain: "multi-domain",
    type: "action",
    difficulty: "hard",
    curriculumStage: 9,
    title: "Cycle planning workflow",
    goal: "Complete Sprint 13 (cycle-6). Then create a new cycle 'Sprint 14' in Platform team (team-1) and start it. Move incomplete issues from cycle-6 (PLT-104 iss-4, PLT-118 iss-18) to Sprint 14.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "cycle_has_state",
        id: "cycle-6",
        expected: "completed",
        weight: 0.25,
        description: "Sprint 13 is completed",
      },
      {
        type: "state_predicate",
        predicate: "cycle_has_state",
        id: "cycle-15",
        expected: "active",
        weight: 0.25,
        description: "Sprint 14 is active",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_cycle",
        id: "iss-4",
        expected: "cycle-15",
        weight: 0.25,
        description: "PLT-104 moved to Sprint 14",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_cycle",
        id: "iss-18",
        expected: "cycle-15",
        weight: 0.25,
        description: "PLT-118 moved to Sprint 14",
      },
    ],
    maxSteps: 25,
    rewardProfile: R10,
    tags: ["cycle", "lifecycle", "multi-step"],
  },
  {
    id: "linear-multi-002",
    site: "linear",
    domain: "multi-domain",
    type: "action",
    difficulty: "hard",
    curriculumStage: 9,
    title: "Release hardening",
    goal: "Prepare v2.3.0 release: transition Auth Service in_progress issues (PLT-102 iss-2, PLT-103 iss-3, PLT-105 iss-5, PLT-107 iss-7, PLT-112 iss-12, PLT-118 iss-18) to 'done', then complete Sprint 13 (cycle-6).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-2",
        expected: "done",
        weight: 0.1,
        description: "PLT-102 done",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-3",
        expected: "done",
        weight: 0.1,
        description: "PLT-103 done",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-5",
        expected: "done",
        weight: 0.1,
        description: "PLT-105 done",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-7",
        expected: "done",
        weight: 0.1,
        description: "PLT-107 done",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-12",
        expected: "done",
        weight: 0.1,
        description: "PLT-112 done",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-18",
        expected: "done",
        weight: 0.1,
        description: "PLT-118 done",
      },
      {
        type: "state_predicate",
        predicate: "cycle_has_state",
        id: "cycle-6",
        expected: "completed",
        weight: 0.4,
        description: "Sprint 13 completed",
      },
    ],
    maxSteps: 30,
    rewardProfile: R10,
    tags: ["transition", "cycle", "release"],
  },
  {
    id: "linear-multi-003",
    site: "linear",
    domain: "multi-domain",
    type: "action",
    difficulty: "hard",
    curriculumStage: 9,
    title: "Bug triage and cycle",
    goal: "Triage legacy bug LEG-050 (iss-145): assign to Arjun Mehta (usr-2), set priority to 'urgent', set estimate to 2. Then create a new cycle 'Hotfix Cycle' in Platform team with description 'Critical bug fixes'. Move PLT-102 (iss-2) and PLT-103 (iss-3) into the new cycle.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-145",
        expected: {
          assigneeId: "usr-2",
          priority: "urgent",
          estimate: 2,
        },
        weight: 0.3,
        description: "LEG-050 triaged correctly",
      },
      {
        type: "state_predicate",
        predicate: "cycle_has_state",
        id: "cycle-15",
        expected: "upcoming",
        weight: 0.2,
        description: "Hotfix Cycle created",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_cycle",
        id: "iss-2",
        expected: "cycle-15",
        weight: 0.25,
        description: "PLT-102 in hotfix cycle",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_cycle",
        id: "iss-3",
        expected: "cycle-15",
        weight: 0.25,
        description: "PLT-103 in hotfix cycle",
      },
    ],
    maxSteps: 30,
    rewardProfile: R15,
    tags: ["triage", "cycle", "create", "multi-step"],
  },
  {
    id: "linear-multi-004",
    site: "linear",
    domain: "multi-domain",
    type: "action",
    difficulty: "hard",
    curriculumStage: 9,
    title: "Full team setup",
    goal: "Create a new team 'Mobile' with key 'MOB', lead Priya Sharma (usr-1), members [usr-1, usr-4, usr-6]. Create a project 'Mobile Checkout' in the new team (team-5). Create an issue 'Set up CI for iOS builds' in team MOB (team-5) with priority 'high', estimate 8, assigned to Ananya Iyer (usr-6).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "team_has_fields",
        expected: {
          name: "Mobile",
          key: "MOB",
          leadId: "usr-1",
        },
        weight: 0.3,
        description: "Mobile team created",
      },
      {
        type: "state_predicate",
        predicate: "project_has_fields",
        expected: {
          name: "Mobile Checkout",
          teamId: "team-5",
        },
        weight: 0.2,
        description: "Mobile Checkout project exists in team-5",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          title: "Set up CI for iOS builds",
          priority: "high",
          estimate: 8,
          assigneeId: "usr-6",
          teamId: "team-5",
        },
        weight: 0.5,
        description: "Issue created in MOB team",
      },
    ],
    maxSteps: 30,
    rewardProfile: R15,
    tags: ["team", "project", "create", "multi-step"],
  },
  {
    id: "linear-multi-005",
    site: "linear",
    domain: "multi-domain",
    type: "action",
    difficulty: "hard",
    curriculumStage: 10,
    title: "End-to-end cycle workflow",
    goal: "Complete the full cycle workflow: (1) Complete Sprint 13 (cycle-6), (2) Create a new cycle 'Sprint 14' in Platform team and start it, (3) Create 2 new issues in Platform team in the new cycle: 'Optimize database queries' (est 5) and 'Add caching layer' (est 8), both assigned to Priya Sharma (usr-1).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "cycle_has_state",
        id: "cycle-6",
        expected: "completed",
        weight: 0.15,
        description: "Sprint 13 completed",
      },
      {
        type: "state_predicate",
        predicate: "cycle_has_state",
        id: "cycle-15",
        expected: "active",
        weight: 0.15,
        description: "Sprint 14 active",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          title: "Optimize database queries",
          estimate: 5,
          assigneeId: "usr-1",
          cycleId: "cycle-15",
          teamId: "team-1",
        },
        weight: 0.35,
        description: "Optimize DB issue in new cycle",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          title: "Add caching layer",
          estimate: 8,
          assigneeId: "usr-1",
          cycleId: "cycle-15",
          teamId: "team-1",
        },
        weight: 0.35,
        description: "Add caching issue in new cycle",
      },
    ],
    maxSteps: 30,
    rewardProfile: R15,
    tags: ["cycle", "create", "lifecycle", "end-to-end"],
  },
  {
    id: "linear-multi-006",
    site: "linear",
    domain: "multi-domain",
    type: "action",
    difficulty: "hard",
    curriculumStage: 9,
    title: "Cross-team issue management",
    goal: "Create an issue 'Shared auth library crash' in Platform team (team-1) with priority 'urgent', estimate 3, assigned to Ravi Kumar (usr-3). Then create a related issue 'Update checkout auth flow' in Frontend team (team-2) with priority 'high', assigned to Sneha Reddy (usr-4).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          title: "Shared auth library crash",
          priority: "urgent",
          estimate: 3,
          assigneeId: "usr-3",
          teamId: "team-1",
        },
        weight: 0.5,
        description: "Issue created in Platform team",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          title: "Update checkout auth flow",
          priority: "high",
          assigneeId: "usr-4",
          teamId: "team-2",
        },
        weight: 0.5,
        description: "Issue created in Frontend team",
      },
    ],
    maxSteps: 25,
    rewardProfile: R10,
    tags: ["create", "cross-team"],
  },
  {
    id: "linear-multi-007",
    site: "linear",
    domain: "multi-domain",
    type: "action",
    difficulty: "hard",
    curriculumStage: 10,
    title: "Backlog grooming session",
    goal: "Groom the Platform triage backlog: (1) Set estimates for PLT-301 (iss-51) to 5 and PLT-302 (iss-52) to 3, (2) Assign PLT-301 to Ravi Kumar (usr-3) and PLT-302 to Sanjay Gupta (usr-13), (3) Add PLT-302 to project Auth Service (proj-1), (4) Create a new issue 'API versioning strategy' with estimate 5 in Platform team.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-51",
        expected: { estimate: 5, assigneeId: "usr-3" },
        weight: 0.25,
        description: "PLT-301 groomed",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-52",
        expected: { estimate: 3, assigneeId: "usr-13", projectId: "proj-1" },
        weight: 0.25,
        description: "PLT-302 groomed with project",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          title: "API versioning strategy",
          estimate: 5,
          teamId: "team-1",
        },
        weight: 0.5,
        description: "New issue created",
      },
    ],
    maxSteps: 30,
    rewardProfile: R15,
    tags: ["grooming", "multi-step", "estimation"],
  },
  {
    id: "linear-multi-008",
    site: "linear",
    domain: "multi-domain",
    type: "action",
    difficulty: "hard",
    curriculumStage: 10,
    title: "Emergency hotfix workflow",
    goal: "Handle an emergency: (1) Create an issue 'Production database connection pool exhausted' in Platform team with priority 'urgent', estimate 1, assigned to Priya Sharma (usr-1), (2) Add it to Sprint 13 (cycle-6), (3) Immediately transition it to 'in_progress' (first to 'todo', then to 'in_progress').",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          title: "Production database connection pool exhausted",
          priority: "urgent",
          estimate: 1,
          assigneeId: "usr-1",
          cycleId: "cycle-6",
          status: "in_progress",
          teamId: "team-1",
        },
        weight: 1.0,
        description: "Emergency issue created, in cycle, and in progress",
      },
    ],
    maxSteps: 25,
    rewardProfile: R10,
    tags: ["create", "transition", "emergency"],
  },
]
