import type { TaskDefinition } from "@simbench/core";

const R = {
  completion: 2.0,
  partialPerCheck: false,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
};

export const navigationTasks: TaskDefinition[] = [
  {
    id: "linear-nav-001",
    site: "linear",
    domain: "navigation",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 1,
    title: "Navigate to dashboard",
    goal: "Navigate to the Linear dashboard and report what you see.",
    retrievalRubric: {
      question: "What content is on this page?",
      groundTruth: "Linear Dashboard with issue stats, active cycles, and team overview",
      acceptableVariations: ["dashboard", "Dashboard", "linear dashboard"],
      rubric: "Agent must navigate to the main Linear dashboard page.",
    },
    evalChecks: [],
    maxSteps: 5,
    rewardProfile: R,
    tags: ["navigation"],
  },
  {
    id: "linear-nav-002",
    site: "linear",
    domain: "navigation",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 1,
    title: "Navigate to board view",
    goal: "Navigate to the Board view and report the columns you see.",
    retrievalRubric: {
      question: "What columns are on the board?",
      groundTruth: "Backlog, Todo, In Progress, Done, Cancelled",
      acceptableVariations: ["5 columns", "Backlog, Todo, In Progress, Done, Cancelled"],
      rubric: "Agent must navigate to the board view and list its columns.",
    },
    evalChecks: [],
    maxSteps: 5,
    rewardProfile: R,
    tags: ["navigation"],
  },
  {
    id: "linear-nav-003",
    site: "linear",
    domain: "navigation",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 1,
    title: "Navigate to cycles page",
    goal: "Navigate to the Cycles page and report how many active cycles exist across all teams.",
    retrievalRubric: {
      question: "How many cycles are currently active?",
      groundTruth: "3 active cycles: Sprint 13 (Platform), FE Sprint 13 (Frontend), Infra Sprint 13 (Infra)",
      acceptableVariations: ["3", "3 active cycles", "Sprint 13, FE Sprint 13, Infra Sprint 13"],
      rubric: "Agent must navigate to the cycles page and count cycles with state=active.",
    },
    evalChecks: [],
    maxSteps: 5,
    rewardProfile: R,
    tags: ["navigation"],
  },
  {
    id: "linear-nav-004",
    site: "linear",
    domain: "navigation",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 1,
    title: "Navigate to teams page",
    goal: "Navigate to the Teams page and report the team names.",
    retrievalRubric: {
      question: "What teams exist?",
      groundTruth: "Platform (PLT), Frontend (FE), Infra (INF), Legacy (LEG)",
      acceptableVariations: ["4 teams", "Platform, Frontend, Infra, Legacy", "PLT, FE, INF, LEG"],
      rubric: "Agent must navigate to the teams page and list all 4 team names.",
    },
    evalChecks: [],
    maxSteps: 5,
    rewardProfile: R,
    tags: ["navigation"],
  },
  {
    id: "linear-nav-005",
    site: "linear",
    domain: "navigation",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 1,
    title: "Navigate to projects page",
    goal: "Navigate to the Projects page and report the project names and their target dates.",
    retrievalRubric: {
      question: "What projects exist and when are they due?",
      groundTruth: "Auth Service (2026-06-30), New Checkout Flow (2026-05-30), Payment API v2 (2026-06-15)",
      acceptableVariations: ["3 projects", "Auth Service, New Checkout Flow, Payment API v2"],
      rubric: "Agent must navigate to the projects page and list all 3 projects with dates.",
    },
    evalChecks: [],
    maxSteps: 5,
    rewardProfile: R,
    tags: ["navigation"],
  },
];
