import type { TaskDefinition } from "@simbench/core";

const R = {
  completion: 2.0,
  partialPerCheck: false,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
};

export const navigationTasks: TaskDefinition[] = [
  {
    id: "linear-nav-001",
    site: "linear",
    domain: "navigation",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 1,
    title: "Navigate to dashboard",
    goal: "Navigate to the Linear dashboard and report what you see.",
    retrievalRubric: {
      question: "What content is on this page?",
      groundTruth: "Linear Dashboard with issue stats, active cycles, and team overview",
      acceptableVariations: ["dashboard", "Dashboard", "linear dashboard"],
      rubric: "Agent must navigate to the main Linear dashboard page.",
    },
    evalChecks: [],
    maxSteps: 5,
    rewardProfile: R,
    tags: ["navigation"],
  },
  {
    id: "linear-nav-002",
    site: "linear",
    domain: "navigation",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 1,
    title: "Navigate to board view",
    goal: "Navigate to the Board view and report the columns you see.",
    retrievalRubric: {
      question: "What columns are on the board?",
      groundTruth: "Backlog, Todo, In Progress, Done, Cancelled",
      acceptableVariations: ["5 columns", "Backlog, Todo, In Progress, Done, Cancelled"],
      rubric: "Agent must navigate to the board view and list its columns.",
    },
    evalChecks: [],
    maxSteps: 5,
    rewardProfile: R,
    tags: ["navigation"],
  },
  {
    id: "linear-nav-003",
    site: "linear",
    domain: "navigation",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 1,
    title: "Navigate to cycles page",
    goal: "Navigate to the Cycles page and report the number of cycles.",
    retrievalRubric: {
      question: "How many cycles exist?",
      groundTruth: "3 cycles: Cycle 12 (completed), Cycle 13 (active), Cycle 14 (upcoming)",
      acceptableVariations: ["3", "3 cycles"],
      rubric: "Agent must navigate to the cycles page.",
    },
    evalChecks: [],
    maxSteps: 5,
    rewardProfile: R,
    tags: ["navigation"],
  },
  {
    id: "linear-nav-004",
    site: "linear",
    domain: "navigation",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 1,
    title: "Navigate to teams page",
    goal: "Navigate to the Teams page and report the team names.",
    retrievalRubric: {
      question: "What teams exist?",
      groundTruth: "Engineering (ENG), Design (DES)",
      acceptableVariations: ["2 teams", "Engineering and Design"],
      rubric: "Agent must navigate to the teams page.",
    },
    evalChecks: [],
    maxSteps: 5,
    rewardProfile: R,
    tags: ["navigation"],
  },
];
