import type { TaskDefinition } from "@simbench/core";

const R = {
  completion: 2.0,
  partialPerCheck: false,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
};
const R5 = {
  completion: 5.0,
  partialPerCheck: false,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
};

export const retrievalTasks: TaskDefinition[] = [
  {
    id: "linear-ret-001",
    site: "linear",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Issue assignee lookup",
    goal: "Who is assigned to issue PLT-102?",
    retrievalRubric: {
      question: "Who is assigned to PLT-102?",
      groundTruth: "Kiran Patel",
      acceptableVariations: ["Kiran Patel", "kiran patel", "usr-5"],
      rubric: "PLT-102 (iss-2) is assigned to Kiran Patel (usr-5).",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "linear-ret-002",
    site: "linear",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Cycle description lookup",
    goal: "What is the description of Sprint 13 (the active Platform cycle)?",
    retrievalRubric: {
      question: "What is Sprint 13's description?",
      groundTruth: "Pre-release hardening for v2.3.0",
      acceptableVariations: ["Pre-release hardening for v2.3.0", "pre-release hardening"],
      rubric: "Sprint 13 (cycle-6) has description 'Pre-release hardening for v2.3.0'.",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "linear-ret-003",
    site: "linear",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 3,
    title: "Project status lookup",
    goal: "What is the status of the 'New Checkout Flow' project?",
    retrievalRubric: {
      question: "What is the New Checkout Flow project status?",
      groundTruth: "in_progress",
      acceptableVariations: ["in_progress", "In Progress", "in progress"],
      rubric: "The New Checkout Flow project (proj-2) has status 'in_progress'.",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "linear-ret-004",
    site: "linear",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 3,
    title: "Auth Service done estimate total",
    goal: "What is the total estimate for all 'done' issues in the Auth Service project?",
    retrievalRubric: {
      question: "Total estimate of done Auth Service issues?",
      // done in proj-1: PLT-101(8)+PLT-110(3)+PLT-116(2) = 13
      groundTruth: "13",
      acceptableVariations: ["13", "13 points", "thirteen"],
      rubric: "Auth Service done issues: PLT-101(8)+PLT-110(3)+PLT-116(2) = 13.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["retrieval", "calculation"],
  },
  {
    id: "linear-ret-005",
    site: "linear",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 4,
    title: "Sprint dates lookup",
    goal: "What are the start and end dates of the active Platform cycle Sprint 13?",
    retrievalRubric: {
      question: "When does Sprint 13 start and end?",
      groundTruth: "Start: 2026-03-31, End: 2026-04-13",
      acceptableVariations: [
        "March 31 to April 13",
        "2026-03-31 to 2026-04-13",
        "Mar 31 - Apr 13",
      ],
      rubric: "Sprint 13 (cycle-6) runs from 2026-03-31 to 2026-04-13.",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "linear-ret-006",
    site: "linear",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 4,
    title: "Team lead lookup",
    goal: "Who is the lead of the Frontend team?",
    retrievalRubric: {
      question: "Who leads the Frontend team?",
      groundTruth: "Sneha Reddy",
      acceptableVariations: ["Sneha Reddy", "sneha reddy", "usr-4"],
      rubric: "The Frontend team (team-2) lead is Sneha Reddy (usr-4).",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "linear-ret-007",
    site: "linear",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Urgent issue lookup",
    goal: "Which issue has 'urgent' priority? Report its identifier.",
    retrievalRubric: {
      question: "What is the urgent-priority issue?",
      groundTruth: "PLT-114",
      acceptableVariations: ["PLT-114", "Permission model redesign", "iss-14"],
      rubric: "Only PLT-114 (Permission model redesign) has urgent priority.",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "linear-ret-008",
    site: "linear",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Issue labels lookup",
    goal: "What labels does issue PLT-101 have? Report their names.",
    retrievalRubric: {
      question: "What labels are on PLT-101?",
      groundTruth: "backend, feature",
      acceptableVariations: ["backend and feature", "label-2, label-6"],
      rubric: "PLT-101 (iss-1) has labelIds ['label-2', 'label-6'] = backend + feature.",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "linear-ret-009",
    site: "linear",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Unassigned issue count",
    goal: "How many issues are unassigned (assigneeId is null) across the entire workspace?",
    retrievalRubric: {
      question: "How many issues are unassigned?",
      groundTruth: "127",
      acceptableVariations: ["127", "127 issues"],
      rubric: "127 of 180 issues have null assigneeId — mostly triage backlog + legacy.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["retrieval", "counting"],
  },
  {
    id: "linear-ret-010",
    site: "linear",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Legacy team issue count",
    goal: "How many total issues are in the Legacy team (team-4)?",
    retrievalRubric: {
      question: "How many issues are in the Legacy team?",
      groundTruth: "85",
      acceptableVariations: ["85", "85 issues"],
      rubric: "The Legacy team (team-4) has 85 inherited issues: LEG-001 through LEG-085.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["retrieval", "counting"],
  },
  {
    id: "linear-ret-011",
    site: "linear",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Cycle planned vs completed",
    goal: "For Sprint 13 (active Platform cycle), what are the planned and completed story points?",
    retrievalRubric: {
      question: "Sprint 13 planned vs completed?",
      groundTruth: "Planned: 48, Completed: 35",
      acceptableVariations: ["48 planned, 35 completed", "48/35"],
      rubric: "Sprint 13 (cycle-6) plannedPoints=48, completedPoints=35.",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "linear-ret-012",
    site: "linear",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 3,
    title: "Workspace name lookup",
    goal: "What is the name of this Linear workspace?",
    retrievalRubric: {
      question: "What is the workspace name?",
      groundTruth: "Theta Engineering",
      acceptableVariations: ["Theta Engineering", "theta-eng", "theta engineering"],
      rubric: "The workspace is 'Theta Engineering' with URL key 'theta-eng'.",
    },
    evalChecks: [],
    maxSteps: 5,
    rewardProfile: R,
    tags: ["retrieval"],
  },
];
