import type { TaskDefinition } from "@simbench/core";

const R = {
  completion: 2.0,
  partialPerCheck: false,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
};
const R5 = {
  completion: 5.0,
  partialPerCheck: false,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
};

export const retrievalTasks: TaskDefinition[] = [
  {
    id: "linear-ret-001",
    site: "linear",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Issue assignee lookup",
    goal: "Who is assigned to issue ENG-2?",
    retrievalRubric: {
      question: "Who is assigned to ENG-2?",
      groundTruth: "Jordan Lee",
      acceptableVariations: ["Jordan Lee", "jordan lee", "usr-3"],
      rubric: "ENG-2 (iss-2) is assigned to Jordan Lee (usr-3).",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "linear-ret-002",
    site: "linear",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Cycle description lookup",
    goal: "What is the description of Cycle 13?",
    retrievalRubric: {
      question: "What is Cycle 13's description?",
      groundTruth: "Complete auth module",
      acceptableVariations: ["Complete auth module", "complete auth module"],
      rubric: "Cycle 13 (cycle-2) has description 'Complete auth module'.",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "linear-ret-003",
    site: "linear",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 3,
    title: "Project status lookup",
    goal: "What is the status of the 'Design System' project?",
    retrievalRubric: {
      question: "What is the Design System project status?",
      groundTruth: "planned",
      acceptableVariations: ["planned", "Planned"],
      rubric: "The Design System project (proj-2) has status 'planned'.",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "linear-ret-004",
    site: "linear",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 3,
    title: "Estimate total for done issues",
    goal: "What is the total estimate for all 'done' issues?",
    retrievalRubric: {
      question: "Total estimate of done issues?",
      // done: iss-1(5)+iss-7(3)+iss-10(5)+iss-19(3) = 16
      groundTruth: "16",
      acceptableVariations: ["16", "16 points", "sixteen"],
      rubric: "Done issues: ENG-1(5)+ENG-7(3)+ENG-10(5)+DES-1(3) = 16.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["retrieval", "calculation"],
  },
  {
    id: "linear-ret-005",
    site: "linear",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 4,
    title: "Cycle dates lookup",
    goal: "What are the start and end dates of Cycle 13?",
    retrievalRubric: {
      question: "When does Cycle 13 start and end?",
      groundTruth: "Start: 2025-04-15, End: 2025-04-28",
      acceptableVariations: [
        "April 15 to April 28",
        "2025-04-15 to 2025-04-28",
        "Apr 15 - Apr 28",
      ],
      rubric: "Cycle 13 runs from 2025-04-15 to 2025-04-28.",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "linear-ret-006",
    site: "linear",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 4,
    title: "Team lead lookup",
    goal: "Who is the lead of the Design team?",
    retrievalRubric: {
      question: "Who leads the Design team?",
      groundTruth: "Sam Williams",
      acceptableVariations: ["Sam Williams", "sam williams", "usr-2"],
      rubric: "The Design team (team-2) lead is Sam Williams (usr-2).",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "linear-ret-007",
    site: "linear",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Issue priority lookup",
    goal: "What is the priority of issue ENG-3?",
    retrievalRubric: {
      question: "What priority is ENG-3?",
      groundTruth: "urgent",
      acceptableVariations: ["urgent", "Urgent"],
      rubric: "ENG-3 (iss-3) has priority 'urgent'.",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "linear-ret-008",
    site: "linear",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Issue labels lookup",
    goal: "What labels does issue ENG-2 have?",
    retrievalRubric: {
      question: "What labels are on ENG-2?",
      groundTruth: "feature (label-2)",
      acceptableVariations: ["feature", "label-2"],
      rubric: "ENG-2 (iss-2) has labelIds: ['label-2'] which is the 'feature' label.",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "linear-ret-009",
    site: "linear",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Unassigned issue count",
    goal: "How many issues are unassigned (no assignee)?",
    retrievalRubric: {
      question: "How many issues are unassigned?",
      // null assigneeId: iss-5, iss-13, iss-14, iss-18, iss-23 = 5
      groundTruth: "5",
      acceptableVariations: ["five", "5 issues"],
      rubric: "Five issues are unassigned: ENG-5, ENG-13, ENG-14, ENG-18, DES-5.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["retrieval", "counting"],
  },
  {
    id: "linear-ret-010",
    site: "linear",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Design team issue count",
    goal: "How many total issues are in the Design team (team-2)?",
    retrievalRubric: {
      question: "How many issues are in the Design team?",
      groundTruth: "7",
      acceptableVariations: ["seven", "7 issues"],
      rubric: "The Design team (team-2) has 7 issues: DES-1 through DES-7.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["retrieval", "counting"],
  },
];
