import type { TaskDefinition } from "@simbench/core";

const R = {
  completion: 5.0,
  partialPerCheck: false,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
};
const RH = {
  completion: 8.0,
  partialPerCheck: false,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.1,
};

export const searchTasks: TaskDefinition[] = [
  {
    id: "linear-srch-001",
    site: "linear",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Find issues by assignee",
    goal: "How many issues are assigned to Sam Williams (usr-2)?",
    retrievalRubric: {
      question: "How many issues are assigned to Sam Williams?",
      // iss-3(ENG-3), iss-9(ENG-9), iss-19(DES-1), iss-20(DES-2), iss-24(DES-6) = 5
      groundTruth: "5",
      acceptableVariations: ["five", "5 issues"],
      rubric: "Sam Williams (usr-2) is assigned to ENG-3, ENG-9, DES-1, DES-2, DES-6 = 5 issues.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["retrieval", "counting"],
  },
  {
    id: "linear-srch-002",
    site: "linear",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Find issues in active cycle",
    goal: "List all issues in the active cycle (Cycle 13). What are their identifiers?",
    retrievalRubric: {
      question: "What issues are in Cycle 13?",
      // cycle-2 issues: iss-2(ENG-2), iss-3(ENG-3), iss-4(ENG-4), iss-5(ENG-5), iss-9(ENG-9), iss-11(ENG-11), iss-12(ENG-12) = 7
      groundTruth: "ENG-2, ENG-3, ENG-4, ENG-5, ENG-9, ENG-11, ENG-12",
      acceptableVariations: ["7 issues", "7"],
      rubric: "Cycle 13 (cycle-2) contains 7 issues: ENG-2, ENG-3, ENG-4, ENG-5, ENG-9, ENG-11, ENG-12.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["retrieval", "cycle"],
  },
  {
    id: "linear-srch-003",
    site: "linear",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Find issues by project",
    goal: "How many issues are in the 'Auth System' project (proj-1)?",
    retrievalRubric: {
      question: "How many issues are in the Auth System project?",
      // proj-1: iss-1, iss-2, iss-3, iss-4, iss-5, iss-6, iss-11, iss-12, iss-15 = 9
      groundTruth: "9",
      acceptableVariations: ["nine", "9 issues"],
      rubric: "Project proj-1 has 9 issues: ENG-1, ENG-2, ENG-3, ENG-4, ENG-5, ENG-6, ENG-11, ENG-12, ENG-15.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["retrieval", "project"],
  },
  {
    id: "linear-srch-004",
    site: "linear",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Find issues by label",
    goal: "How many issues have the 'feature' label (label-2)?",
    retrievalRubric: {
      question: "How many issues have the feature label?",
      // label-2 in labelIds: iss-1, iss-2, iss-4, iss-5, iss-8, iss-12, iss-17 = 7
      groundTruth: "7",
      acceptableVariations: ["seven", "7 issues"],
      rubric: "Seven issues have label-2 (feature): ENG-1, ENG-2, ENG-4, ENG-5, ENG-8, ENG-12, ENG-17.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["retrieval", "counting"],
  },
  {
    id: "linear-srch-005",
    site: "linear",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Find urgent priority issues",
    goal: "Which issues have 'urgent' priority? List their identifiers.",
    retrievalRubric: {
      question: "Which issues have urgent priority?",
      // urgent: iss-3(ENG-3) = 1
      groundTruth: "ENG-3",
      acceptableVariations: ["1 issue", "ENG-3"],
      rubric: "One issue has urgent priority: ENG-3.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["retrieval", "priority"],
  },
  {
    id: "linear-srch-006",
    site: "linear",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Find unestimated issues",
    goal: "Which issues have no estimate set (null)? List their identifiers.",
    retrievalRubric: {
      question: "Which issues are unestimated?",
      // null estimate: iss-13(ENG-13), iss-14(ENG-14), iss-18(ENG-18) = 3
      groundTruth: "ENG-13, ENG-14, ENG-18",
      acceptableVariations: ["3 issues", "3", "ENG-13, ENG-14, ENG-18"],
      rubric: "Three issues have null estimate: ENG-13, ENG-14, ENG-18.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["retrieval", "estimation"],
  },
  {
    id: "linear-srch-007",
    site: "linear",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Cycle velocity calculation",
    goal: "What is the total estimate for all issues in Cycle 13 (cycle-2)?",
    retrievalRubric: {
      question: "What is the total estimate in Cycle 13?",
      // cycle-2: iss-2(8)+iss-3(3)+iss-4(5)+iss-5(8)+iss-9(2)+iss-11(5)+iss-12(3) = 34
      groundTruth: "34",
      acceptableVariations: ["34 points", "34 estimate points", "thirty-four"],
      rubric: "Cycle 13 total: 8+3+5+8+2+5+3 = 34 estimate points.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: RH,
    tags: ["retrieval", "calculation"],
  },
];
