import type { TaskDefinition } from "@simbench/core";

const R = {
  completion: 5.0,
  partialPerCheck: false,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
};
const RH = {
  completion: 8.0,
  partialPerCheck: false,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.1,
};

export const searchTasks: TaskDefinition[] = [
  {
    id: "linear-srch-001",
    site: "linear",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Find issues by assignee",
    goal: "How many issues are assigned to Ravi Kumar (usr-3)?",
    retrievalRubric: {
      question: "How many issues are assigned to Ravi Kumar?",
      // Ravi: PLT-101, PLT-105, PLT-114, PLT-201, PLT-211 = 5
      groundTruth: "5",
      acceptableVariations: ["five", "5 issues"],
      rubric: "Ravi Kumar (usr-3) is assigned to PLT-101, PLT-105, PLT-114, PLT-201, PLT-211 = 5 issues.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["retrieval", "counting"],
  },
  {
    id: "linear-srch-002",
    site: "linear",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Find issues in active cycle",
    goal: "List all issues in the active Platform cycle (Sprint 13). What are their identifiers?",
    retrievalRubric: {
      question: "What issues are in Sprint 13?",
      groundTruth: "PLT-102, PLT-103, PLT-104, PLT-107, PLT-112, PLT-114, PLT-118, PLT-202, PLT-204, PLT-205, PLT-211",
      acceptableVariations: ["11 issues", "11"],
      rubric: "Sprint 13 (cycle-6) contains 11 issues in Platform team.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["retrieval", "cycle"],
  },
  {
    id: "linear-srch-003",
    site: "linear",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Find issues by project",
    goal: "How many issues are in the 'Auth Service' project (proj-1)?",
    retrievalRubric: {
      question: "How many issues are in the Auth Service project?",
      groundTruth: "23",
      acceptableVariations: ["23", "23 issues", "twenty-three"],
      rubric: "Project proj-1 (Auth Service) has 23 issues: PLT-101 through PLT-123.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["retrieval", "project"],
  },
  {
    id: "linear-srch-004",
    site: "linear",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Find issues by backend label",
    goal: "How many issues have the 'backend' label (label-2)?",
    retrievalRubric: {
      question: "How many issues have the backend label?",
      groundTruth: "39",
      acceptableVariations: ["39", "39 issues"],
      rubric: "39 issues have label-2 (backend) — mostly Platform project and Payment API v2 issues.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["retrieval", "counting"],
  },
  {
    id: "linear-srch-005",
    site: "linear",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Find urgent priority issues",
    goal: "Which issues have 'urgent' priority? List their identifiers.",
    retrievalRubric: {
      question: "Which issues have urgent priority?",
      groundTruth: "PLT-114",
      acceptableVariations: ["1 issue", "PLT-114", "Permission model redesign"],
      rubric: "One issue has urgent priority: PLT-114 (Permission model redesign).",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["retrieval", "priority"],
  },
  {
    id: "linear-srch-006",
    site: "linear",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Find unestimated issues",
    goal: "How many issues have no estimate set (null)?",
    retrievalRubric: {
      question: "How many issues are unestimated?",
      groundTruth: "130",
      acceptableVariations: ["130", "130 issues"],
      rubric: "130 issues have null estimate — mostly the 45 triage backlog (PLT-301..345) and 85 legacy (LEG-001..085).",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["retrieval", "estimation"],
  },
  {
    id: "linear-srch-007",
    site: "linear",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Cycle velocity calculation",
    goal: "What is the total estimate for all issues in Sprint 13 (cycle-6)?",
    retrievalRubric: {
      question: "What is the total estimate in Sprint 13?",
      // cycle-6: PLT-102(5)+PLT-103(5)+PLT-104(3)+PLT-107(8)+PLT-112(5)+PLT-114(13)+PLT-118(5)+PLT-202(8)+PLT-204(5)+PLT-205(5)+PLT-211(3) = 65
      groundTruth: "65",
      acceptableVariations: ["65 points", "65 estimate points", "sixty-five"],
      rubric: "Sprint 13 total: 5+5+3+8+5+13+5+8+5+5+3 = 65 estimate points.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: RH,
    tags: ["retrieval", "calculation"],
  },
  {
    id: "linear-srch-008",
    site: "linear",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Count done issues",
    goal: "How many issues across the entire workspace have status 'done'?",
    retrievalRubric: {
      question: "How many done issues?",
      groundTruth: "13",
      acceptableVariations: ["13", "13 done", "thirteen"],
      rubric: "13 issues are marked done — mostly project issues from completed cycles.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["retrieval", "counting"],
  },
  {
    id: "linear-srch-009",
    site: "linear",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Legacy issue count",
    goal: "How many issues are inherited from the Legacy team (team-4)?",
    retrievalRubric: {
      question: "How many legacy team issues?",
      groundTruth: "85",
      acceptableVariations: ["85", "85 issues", "eighty-five"],
      rubric: "The Legacy team has 85 inherited issues (LEG-001..LEG-085).",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["retrieval", "counting"],
  },
];
