"use client"

import { useState } from "react"
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover"
import { HugeiconsIcon } from "@hugeicons/react"
import {
  Search01Icon,
  // General & UI
  CubeIcon,
  Home01Icon,
  StarIcon,
  FlashIcon,
  Target01Icon,
  Chart01Icon,
  CheckmarkSquare01Icon,
  CheckmarkSquare02Icon,
  BulbIcon,
  IdeaIcon,
  DiamondIcon,
  CrownIcon,
  GiftIcon,
  BadgeIcon,
  AuctionIcon,
  MedalFirstPlaceIcon,
  MedalSecondPlaceIcon,
  MedalThirdPlaceIcon,
  Award01Icon,
  Award02Icon,
  RocketIcon,
  Shield01Icon,
  LockIcon,
  HeartAddIcon,
  FireIcon,
  FlowerIcon,
  SnowIcon,
  ZapIcon,
  PowerIcon,
  // People
  UserIcon,
  UserGroupIcon,
  // Communication
  Message01Icon,
  ChatIcon,
  ChatBotIcon,
  ChatAddIcon,
  ChatEditIcon,
  ChatFeedbackIcon,
  ChatSearchIcon,
  ChatSparkIcon,
  ChatTranslateIcon,
  ChatUserIcon,
  MailOpenIcon,
  MailsIcon,
  MailboxIcon,
  PhoneCheckIcon,
  VoiceIcon,
  // Files
  File01Icon,
  FileEditIcon,
  FileCodeIcon,
  FileSearchIcon,
  FileStarIcon,
  FileSyncIcon,
  FileUploadIcon,
  FileDownloadIcon,
  FileHeartIcon,
  FileImageIcon,
  FileMusicIcon,
  FileVideoIcon,
  FileSecurityIcon,
  FileLinkIcon,
  FileClockIcon,
  // Folders
  Folder01Icon,
  FolderOpenIcon,
  FolderAddIcon,
  FolderCheckIcon,
  FolderCodeIcon,
  FolderCloudIcon,
  FolderGitIcon,
  FolderHeartIcon,
  FolderSearchIcon,
  FolderTreeIcon,
  FolderVideoIcon,
  // Charts & Analytics
  ChartIcon,
  ChartUpIcon,
  ChartDownIcon,
  ChartAreaIcon,
  ChartGanttIcon,
  ChartRadarIcon,
  ChartRingIcon,
  ChartScatterIcon,
  ChartBarBigIcon,
  ChartColumnIcon,
  ChartHistogramIcon,
  ChartIncreaseIcon,
  ChartDecreaseIcon,
  ChartEvaluationIcon,
  AnalyticsUpIcon,
  AnalyticsDownIcon,
  // Code & Tech
  CodeIcon,
  CodeSquareIcon,
  CodeCircleIcon,
  CodeSimpleIcon,
  TerminalIcon,
  DatabaseIcon,
  DatabaseAddIcon,
  DatabaseSyncIcon,
  DatabaseSettingIcon,
  DatabaseLightningIcon,
  RouterIcon,
  LaptopIcon,
  ChipIcon,
  CpuIcon,
  GpuIcon,
  HardDriveIcon,
  UsbIcon,
  BluetoothIcon,
  PrinterIcon,
  DroneIcon,
  MicrochipIcon,
  MicroscopeIcon,
  AtomicPowerIcon,
  // Cloud & Computer
  CloudIcon,
  CloudServerIcon,
  CloudUploadIcon,
  CloudDownloadIcon,
  CloudAlertIcon,
  CloudBigRainIcon,
  CloudSnowIcon,
  ComputerIcon,
  ComputerCheckIcon,
  ComputerCloudIcon,
  ComputerActivityIcon,
  ComputerUserIcon,
  // Books
  BookOpenCheckIcon,
  BookEditIcon,
  BookSearchIcon,
  BookHeartIcon,
  BookUserIcon,
  BookUploadIcon,
  // Nature & Earth
  Tree01Icon,
  EarthIcon,
  SolarEnergyIcon,
  SolarPowerIcon,
  // Maps & Navigation
  MapsIcon,
  CompassIcon,
  MapPinIcon,
  NavigationIcon,
  // Media & Audio
  AlbumIcon,
  RadioIcon,
  PodcastIcon,
  NewsIcon,
  RssIcon,
  // Objects & Tools
  InboxIcon,
  InboxCheckIcon,
  Calendar01Icon,
  Activity03Icon,
  Tag01Icon,
  Link01Icon,
  GlobeIcon,
  MoonIcon,
  Sun01Icon,
  TruckIcon,
  RefreshIcon,
  SecurityIcon,
  NoteIcon,
  TranslateIcon,
  BrainIcon,
  BrushIcon,
  PaintBucketIcon,
  PencilIcon,
  ToolsIcon,
  ToolboxIcon,
  PackageIcon,
  PackageDeliveredIcon,
  ZoomIcon,
  WorkIcon,
  GameIcon,
  PuzzleIcon,
  StackStarIcon,
  WifiCircleIcon,
  SdCardIcon,
  DollarCircleIcon,
  BankIcon,
} from "@hugeicons/core-free-icons"

// ─── Types ─────────────────────────────────────────────────────────────────────
type IconType = typeof CubeIcon

// ─── Icon Registry ─────────────────────────────────────────────────────────────
export const PICKER_ICONS: { icon: IconType; name: string }[] = [
  // General & UI
  { icon: CheckmarkSquare01Icon, name: "checkmark square tick" },
  { icon: CheckmarkSquare02Icon, name: "checkmark square tick done" },
  { icon: CubeIcon, name: "cube" },
  { icon: Home01Icon, name: "home" },
  { icon: StarIcon, name: "star" },
  { icon: FlashIcon, name: "flash" },
  { icon: Target01Icon, name: "target" },
  { icon: RocketIcon, name: "rocket" },
  { icon: FireIcon, name: "fire" },
  { icon: FlowerIcon, name: "flower" },
  { icon: SnowIcon, name: "snow" },
  { icon: ZapIcon, name: "zap" },
  { icon: PowerIcon, name: "power" },
  { icon: HeartAddIcon, name: "heart" },
  { icon: IdeaIcon, name: "idea" },
  { icon: BulbIcon, name: "bulb" },
  { icon: DiamondIcon, name: "diamond" },
  { icon: CrownIcon, name: "crown" },
  { icon: GiftIcon, name: "gift" },
  { icon: BadgeIcon, name: "badge" },
  { icon: Award01Icon, name: "award" },
  { icon: Award02Icon, name: "award2" },
  { icon: MedalFirstPlaceIcon, name: "medal gold" },
  { icon: MedalSecondPlaceIcon, name: "medal silver" },
  { icon: MedalThirdPlaceIcon, name: "medal bronze" },
  { icon: AuctionIcon, name: "auction" },
  { icon: Shield01Icon, name: "shield" },
  { icon: LockIcon, name: "lock" },
  // People
  { icon: UserIcon, name: "user" },
  { icon: UserGroupIcon, name: "users group" },
  // Communication
  { icon: Message01Icon, name: "message" },
  { icon: ChatIcon, name: "chat" },
  { icon: ChatBotIcon, name: "chatbot bot" },
  { icon: ChatAddIcon, name: "chat add" },
  { icon: ChatEditIcon, name: "chat edit" },
  { icon: ChatFeedbackIcon, name: "feedback" },
  { icon: ChatSearchIcon, name: "chat search" },
  { icon: ChatSparkIcon, name: "chat spark" },
  { icon: ChatTranslateIcon, name: "translate" },
  { icon: ChatUserIcon, name: "chat user" },
  { icon: MailOpenIcon, name: "mail" },
  { icon: MailsIcon, name: "mails" },
  { icon: MailboxIcon, name: "mailbox" },
  { icon: PhoneCheckIcon, name: "phone" },
  { icon: VoiceIcon, name: "voice" },
  // Files
  { icon: File01Icon, name: "file" },
  { icon: FileEditIcon, name: "file edit" },
  { icon: FileCodeIcon, name: "file code" },
  { icon: FileSearchIcon, name: "file search" },
  { icon: FileStarIcon, name: "file star" },
  { icon: FileSyncIcon, name: "file sync" },
  { icon: FileUploadIcon, name: "file upload" },
  { icon: FileDownloadIcon, name: "file download" },
  { icon: FileHeartIcon, name: "file heart" },
  { icon: FileImageIcon, name: "file image photo" },
  { icon: FileMusicIcon, name: "file music" },
  { icon: FileVideoIcon, name: "file video" },
  { icon: FileSecurityIcon, name: "file security" },
  { icon: FileLinkIcon, name: "file link" },
  { icon: FileClockIcon, name: "file clock" },
  // Folders
  { icon: Folder01Icon, name: "folder" },
  { icon: FolderOpenIcon, name: "folder open" },
  { icon: FolderAddIcon, name: "folder add" },
  { icon: FolderCheckIcon, name: "folder check" },
  { icon: FolderCodeIcon, name: "folder code" },
  { icon: FolderCloudIcon, name: "folder cloud" },
  { icon: FolderGitIcon, name: "folder git" },
  { icon: FolderHeartIcon, name: "folder heart" },
  { icon: FolderSearchIcon, name: "folder search" },
  { icon: FolderTreeIcon, name: "folder tree" },
  { icon: FolderVideoIcon, name: "folder video" },
  // Charts & Analytics
  { icon: Chart01Icon, name: "chart" },
  { icon: ChartIcon, name: "chart bar" },
  { icon: ChartUpIcon, name: "chart up" },
  { icon: ChartDownIcon, name: "chart down" },
  { icon: ChartAreaIcon, name: "chart area" },
  { icon: ChartGanttIcon, name: "chart gantt" },
  { icon: ChartRadarIcon, name: "chart radar" },
  { icon: ChartRingIcon, name: "chart ring" },
  { icon: ChartScatterIcon, name: "chart scatter" },
  { icon: ChartBarBigIcon, name: "chart bar big" },
  { icon: ChartColumnIcon, name: "chart column" },
  { icon: ChartHistogramIcon, name: "histogram" },
  { icon: ChartIncreaseIcon, name: "increase" },
  { icon: ChartDecreaseIcon, name: "decrease" },
  { icon: ChartEvaluationIcon, name: "evaluation" },
  { icon: AnalyticsUpIcon, name: "analytics" },
  { icon: AnalyticsDownIcon, name: "analytics down" },
  // Code & Tech
  { icon: CodeIcon, name: "code" },
  { icon: CodeSquareIcon, name: "code square" },
  { icon: CodeCircleIcon, name: "code circle" },
  { icon: CodeSimpleIcon, name: "code simple" },
  { icon: TerminalIcon, name: "terminal" },
  { icon: DatabaseIcon, name: "database" },
  { icon: DatabaseAddIcon, name: "database add" },
  { icon: DatabaseSyncIcon, name: "database sync" },
  { icon: DatabaseSettingIcon, name: "database setting" },
  { icon: DatabaseLightningIcon, name: "database lightning" },
  { icon: RouterIcon, name: "router" },
  { icon: LaptopIcon, name: "laptop" },
  { icon: ChipIcon, name: "chip" },
  { icon: CpuIcon, name: "cpu processor" },
  { icon: GpuIcon, name: "gpu" },
  { icon: HardDriveIcon, name: "hard drive" },
  { icon: UsbIcon, name: "usb" },
  { icon: BluetoothIcon, name: "bluetooth" },
  { icon: PrinterIcon, name: "printer" },
  { icon: DroneIcon, name: "drone" },
  { icon: MicrochipIcon, name: "microchip" },
  { icon: MicroscopeIcon, name: "microscope science" },
  { icon: AtomicPowerIcon, name: "atom science" },
  // Cloud & Computer
  { icon: CloudIcon, name: "cloud" },
  { icon: CloudServerIcon, name: "cloud server" },
  { icon: CloudUploadIcon, name: "cloud upload" },
  { icon: CloudDownloadIcon, name: "cloud download" },
  { icon: CloudAlertIcon, name: "cloud alert" },
  { icon: CloudBigRainIcon, name: "rain cloud" },
  { icon: CloudSnowIcon, name: "cloud snow" },
  { icon: ComputerIcon, name: "computer desktop" },
  { icon: ComputerCheckIcon, name: "computer check" },
  { icon: ComputerCloudIcon, name: "computer cloud" },
  { icon: ComputerActivityIcon, name: "computer activity" },
  { icon: ComputerUserIcon, name: "computer user" },
  // Books & Learning
  { icon: BookOpenCheckIcon, name: "book" },
  { icon: BookEditIcon, name: "book edit" },
  { icon: BookSearchIcon, name: "book search" },
  { icon: BookHeartIcon, name: "book heart" },
  { icon: BookUserIcon, name: "book user" },
  { icon: BookUploadIcon, name: "book upload" },
  // Nature & Earth
  { icon: Tree01Icon, name: "tree nature" },
  { icon: EarthIcon, name: "earth world" },
  { icon: SolarEnergyIcon, name: "solar energy" },
  { icon: SolarPowerIcon, name: "solar power" },
  // Maps & Navigation
  { icon: MapsIcon, name: "map" },
  { icon: CompassIcon, name: "compass" },
  { icon: MapPinIcon, name: "pin location" },
  { icon: NavigationIcon, name: "navigation" },
  // Media & Audio
  { icon: AlbumIcon, name: "album music" },
  { icon: RadioIcon, name: "radio" },
  { icon: PodcastIcon, name: "podcast" },
  { icon: NewsIcon, name: "news" },
  { icon: RssIcon, name: "rss feed" },
  // Objects & Tools
  { icon: InboxIcon, name: "inbox" },
  { icon: InboxCheckIcon, name: "inbox check" },
  { icon: Calendar01Icon, name: "calendar" },
  { icon: Activity03Icon, name: "activity" },
  { icon: Tag01Icon, name: "tag label" },
  { icon: Link01Icon, name: "link url" },
  { icon: GlobeIcon, name: "globe web" },
  { icon: MoonIcon, name: "moon night" },
  { icon: Sun01Icon, name: "sun day" },
  { icon: TruckIcon, name: "truck delivery" },
  { icon: RefreshIcon, name: "refresh sync" },
  { icon: SecurityIcon, name: "security safe" },
  { icon: NoteIcon, name: "note" },
  { icon: TranslateIcon, name: "translate language" },
  { icon: BrainIcon, name: "brain ai" },
  { icon: BrushIcon, name: "brush design" },
  { icon: PaintBucketIcon, name: "paint bucket" },
  { icon: PencilIcon, name: "pencil write" },
  { icon: ToolsIcon, name: "tools" },
  { icon: ToolboxIcon, name: "toolbox" },
  { icon: PackageIcon, name: "package box" },
  { icon: PackageDeliveredIcon, name: "package delivered" },
  { icon: ZoomIcon, name: "zoom search" },
  { icon: WorkIcon, name: "work office" },
  { icon: GameIcon, name: "game" },
  { icon: PuzzleIcon, name: "puzzle" },
  { icon: StackStarIcon, name: "stack" },
  { icon: WifiCircleIcon, name: "wifi" },
  { icon: SdCardIcon, name: "sd card" },
  { icon: DollarCircleIcon, name: "dollar money" },
  { icon: BankIcon, name: "bank finance" },
]

// ─── Colors ────────────────────────────────────────────────────────────────────
export const PICKER_COLORS = [
  { id: "dark", bg: "bg-zinc-700", text: "text-zinc-400" },
  { id: "gray", bg: "bg-zinc-500", text: "text-muted-foreground" },
  { id: "blue", bg: "bg-blue-600", text: "text-blue-500" },
  { id: "cyan", bg: "bg-cyan-500", text: "text-cyan-500" },
  { id: "green", bg: "bg-green-500", text: "text-green-500" },
  { id: "yellow", bg: "bg-yellow-400", text: "text-yellow-500" },
  { id: "orange", bg: "bg-orange-500", text: "text-orange-500" },
  { id: "pink", bg: "bg-pink-400", text: "text-pink-400" },
  { id: "red", bg: "bg-red-500", text: "text-red-500" },
]

// ─── Emojis ────────────────────────────────────────────────────────────────────
// A small but representative emoji set grouped into the categories
// Linear's picker shows. The set is intentionally hand-picked rather
// than full Unicode — keeping the popover snappy and the search
// space sane. `name` doubles as the search key (lowercase, no
// punctuation) and the tooltip label (`:partying_face:` style).
type EmojiEntry = { char: string; name: string }
type EmojiGroup = { label: string; emojis: EmojiEntry[] }

const EMOJI_GROUPS: EmojiGroup[] = [
  {
    label: "Frequently used",
    emojis: [
      { char: "👍", name: "thumbs_up" },
      { char: "👌", name: "ok_hand" },
      { char: "🙏", name: "pray" },
      { char: "😂", name: "joy" },
      { char: "❤️", name: "heart" },
      { char: "👀", name: "eyes" },
      { char: "✅", name: "white_check_mark" },
      { char: "🙂", name: "slight_smile" },
      { char: "😀", name: "grinning" },
      { char: "😃", name: "smiley" },
      { char: "😄", name: "smile" },
      { char: "🤔", name: "thinking" },
      { char: "😅", name: "sweat_smile" },
      { char: "⚠️", name: "warning" },
      { char: "😕", name: "confused" },
      { char: "❌", name: "x" },
      { char: "🙌", name: "raised_hands" },
      { char: "🎉", name: "tada" },
      { char: "😏", name: "smirk" },
      { char: "☺️", name: "relaxed" },
      { char: "🤷", name: "shrug" },
      { char: "👋", name: "wave" },
      { char: "❓", name: "question" },
    ],
  },
  {
    label: "Smileys & People",
    emojis: [
      { char: "😀", name: "grinning" },
      { char: "😃", name: "smiley" },
      { char: "😄", name: "smile" },
      { char: "😁", name: "grin" },
      { char: "😆", name: "laughing" },
      { char: "😅", name: "sweat_smile" },
      { char: "🤣", name: "rofl" },
      { char: "😂", name: "joy" },
      { char: "🙂", name: "slight_smile" },
      { char: "🙃", name: "upside_down" },
      { char: "🫠", name: "melting_face" },
      { char: "😉", name: "wink" },
      { char: "😊", name: "blush" },
      { char: "😇", name: "innocent" },
      { char: "🥰", name: "smiling_face_with_hearts" },
      { char: "😍", name: "heart_eyes" },
      { char: "🤩", name: "star_struck" },
      { char: "😘", name: "kissing_heart" },
      { char: "😗", name: "kissing" },
      { char: "☺️", name: "relaxed" },
      { char: "😚", name: "kissing_closed_eyes" },
      { char: "😙", name: "kissing_smiling_eyes" },
      { char: "🥲", name: "smiling_face_with_tear" },
      { char: "😋", name: "yum" },
      { char: "😛", name: "stuck_out_tongue" },
      { char: "😜", name: "stuck_out_tongue_winking" },
      { char: "🤪", name: "zany_face" },
      { char: "😝", name: "stuck_out_tongue_closed_eyes" },
      { char: "🤑", name: "money_mouth" },
      { char: "🤗", name: "hugs" },
      { char: "🤭", name: "hand_over_mouth" },
      { char: "🫢", name: "face_with_open_eyes_and_hand_over_mouth" },
      { char: "🫣", name: "face_with_peeking_eye" },
      { char: "🤫", name: "shushing" },
      { char: "🤔", name: "thinking" },
      { char: "🫡", name: "saluting" },
      { char: "🤐", name: "zipper_mouth" },
      { char: "🤨", name: "raised_eyebrow" },
      { char: "😐", name: "neutral" },
      { char: "😑", name: "expressionless" },
      { char: "😶", name: "no_mouth" },
      { char: "🫥", name: "dotted_line_face" },
      { char: "😏", name: "smirk" },
      { char: "😒", name: "unamused" },
      { char: "🙄", name: "rolling_eyes" },
      { char: "😬", name: "grimacing" },
      { char: "🤥", name: "lying" },
      { char: "🫨", name: "shaking_face" },
      { char: "😌", name: "relieved" },
      { char: "😔", name: "pensive" },
      { char: "😪", name: "sleepy" },
      { char: "🤤", name: "drooling" },
      { char: "😴", name: "sleeping" },
      { char: "😷", name: "mask" },
      { char: "🤒", name: "thermometer_face" },
      { char: "🤕", name: "head_bandage" },
      { char: "🤢", name: "nauseated" },
      { char: "🤮", name: "vomiting" },
      { char: "🤧", name: "sneezing" },
      { char: "🥵", name: "hot" },
      { char: "🥶", name: "cold" },
      { char: "🥴", name: "woozy" },
      { char: "😵", name: "dizzy" },
      { char: "🤯", name: "exploding_head" },
      { char: "🤠", name: "cowboy" },
      { char: "🥳", name: "partying_face" },
      { char: "🥸", name: "disguised" },
      { char: "🤓", name: "nerd" },
      { char: "😎", name: "sunglasses" },
      { char: "🧐", name: "monocle" },
      { char: "😕", name: "confused" },
      { char: "🫤", name: "diagonal_mouth" },
      { char: "😟", name: "worried" },
      { char: "🙁", name: "slight_frown" },
      { char: "☹️", name: "frown" },
      { char: "😮", name: "open_mouth" },
      { char: "😯", name: "hushed" },
      { char: "😲", name: "astonished" },
      { char: "😳", name: "flushed" },
      { char: "🥺", name: "pleading" },
      { char: "🥹", name: "holding_back_tears" },
      { char: "😦", name: "frowning" },
      { char: "😧", name: "anguished" },
      { char: "😨", name: "fearful" },
      { char: "😰", name: "cold_sweat" },
      { char: "😥", name: "disappointed_relieved" },
      { char: "😢", name: "cry" },
      { char: "😭", name: "sob" },
      { char: "😱", name: "scream" },
      { char: "😖", name: "confounded" },
      { char: "😣", name: "persevere" },
      { char: "😞", name: "disappointed" },
      { char: "😓", name: "sweat" },
      { char: "😩", name: "weary" },
      { char: "😫", name: "tired" },
      { char: "🥱", name: "yawning" },
      { char: "😤", name: "triumph" },
      { char: "😡", name: "rage" },
      { char: "😠", name: "angry" },
      { char: "🤬", name: "cursing" },
      { char: "😈", name: "smiling_imp" },
      { char: "👿", name: "imp" },
      { char: "💀", name: "skull" },
      { char: "☠️", name: "skull_crossbones" },
      { char: "💩", name: "poop" },
      { char: "🤡", name: "clown" },
      { char: "👹", name: "ogre" },
      { char: "👺", name: "goblin" },
      { char: "👻", name: "ghost" },
      { char: "👽", name: "alien" },
      { char: "👾", name: "space_invader" },
      { char: "🤖", name: "robot" },
      { char: "👋", name: "wave" },
      { char: "🤚", name: "raised_back_of_hand" },
      { char: "🖐️", name: "splayed_hand" },
      { char: "✋", name: "raised_hand" },
      { char: "🖖", name: "vulcan" },
      { char: "🫱", name: "rightwards_hand" },
      { char: "🫲", name: "leftwards_hand" },
      { char: "🫳", name: "palm_down_hand" },
      { char: "🫴", name: "palm_up_hand" },
      { char: "👌", name: "ok_hand" },
      { char: "🤌", name: "pinched_fingers" },
      { char: "🤏", name: "pinching_hand" },
      { char: "✌️", name: "victory" },
      { char: "🤞", name: "fingers_crossed" },
      { char: "🫰", name: "love_you_gesture" },
      { char: "🤟", name: "love_you" },
      { char: "🤘", name: "metal" },
      { char: "🤙", name: "call_me" },
      { char: "👈", name: "point_left" },
      { char: "👉", name: "point_right" },
      { char: "👆", name: "point_up_2" },
      { char: "🖕", name: "middle_finger" },
      { char: "👇", name: "point_down" },
      { char: "☝️", name: "point_up" },
      { char: "👍", name: "thumbs_up" },
      { char: "👎", name: "thumbs_down" },
      { char: "✊", name: "fist_raised" },
      { char: "👊", name: "facepunch" },
      { char: "🤛", name: "left_facing_fist" },
      { char: "🤜", name: "right_facing_fist" },
      { char: "👏", name: "clap" },
      { char: "🙌", name: "raised_hands" },
      { char: "🫶", name: "heart_hands" },
      { char: "👐", name: "open_hands" },
      { char: "🤲", name: "palms_up_together" },
      { char: "🤝", name: "handshake" },
      { char: "🙏", name: "pray" },
      { char: "💅", name: "nail_polish" },
      { char: "🤳", name: "selfie" },
      { char: "💪", name: "muscle" },
      { char: "🦾", name: "mechanical_arm" },
      { char: "🦿", name: "mechanical_leg" },
      { char: "🦵", name: "leg" },
      { char: "🦶", name: "foot" },
      { char: "👂", name: "ear" },
      { char: "🦻", name: "hearing_aid" },
      { char: "👃", name: "nose" },
      { char: "🧠", name: "brain" },
      { char: "🫀", name: "anatomical_heart" },
      { char: "🫁", name: "lungs" },
      { char: "🦷", name: "tooth" },
      { char: "🦴", name: "bone" },
      { char: "👀", name: "eyes" },
      { char: "👁️", name: "eye" },
      { char: "👅", name: "tongue" },
      { char: "👄", name: "lips" },
      { char: "🫦", name: "biting_lip" },
    ],
  },
  {
    label: "Animals & Nature",
    emojis: [
      { char: "🐶", name: "dog" },
      { char: "🐱", name: "cat" },
      { char: "🐭", name: "mouse" },
      { char: "🐹", name: "hamster" },
      { char: "🐰", name: "rabbit" },
      { char: "🦊", name: "fox" },
      { char: "🐻", name: "bear" },
      { char: "🐼", name: "panda" },
      { char: "🐨", name: "koala" },
      { char: "🐯", name: "tiger" },
      { char: "🦁", name: "lion" },
      { char: "🐮", name: "cow" },
      { char: "🐷", name: "pig" },
      { char: "🐽", name: "pig_nose" },
      { char: "🐸", name: "frog" },
      { char: "🐵", name: "monkey_face" },
      { char: "🙈", name: "see_no_evil" },
      { char: "🙉", name: "hear_no_evil" },
      { char: "🙊", name: "speak_no_evil" },
      { char: "🐒", name: "monkey" },
      { char: "🐔", name: "chicken" },
      { char: "🐧", name: "penguin" },
      { char: "🐦", name: "bird" },
      { char: "🐤", name: "baby_chick" },
      { char: "🐣", name: "hatching_chick" },
      { char: "🐥", name: "hatched_chick" },
      { char: "🦆", name: "duck" },
      { char: "🦅", name: "eagle" },
      { char: "🦉", name: "owl" },
      { char: "🦇", name: "bat" },
      { char: "🐺", name: "wolf" },
      { char: "🐗", name: "boar" },
      { char: "🐴", name: "horse" },
      { char: "🦄", name: "unicorn" },
      { char: "🐝", name: "bee" },
      { char: "🐛", name: "bug" },
      { char: "🦋", name: "butterfly" },
      { char: "🐌", name: "snail" },
      { char: "🐞", name: "ladybug" },
      { char: "🐜", name: "ant" },
      { char: "🦟", name: "mosquito" },
      { char: "🦗", name: "cricket" },
      { char: "🕷️", name: "spider" },
      { char: "🦂", name: "scorpion" },
      { char: "🐢", name: "turtle" },
      { char: "🐍", name: "snake" },
      { char: "🦎", name: "lizard" },
      { char: "🦖", name: "trex" },
      { char: "🦕", name: "sauropod" },
      { char: "🐙", name: "octopus" },
      { char: "🦑", name: "squid" },
      { char: "🦐", name: "shrimp" },
      { char: "🦞", name: "lobster" },
      { char: "🦀", name: "crab" },
      { char: "🐡", name: "blowfish" },
      { char: "🐠", name: "tropical_fish" },
      { char: "🐟", name: "fish" },
      { char: "🐬", name: "dolphin" },
      { char: "🐳", name: "whale" },
      { char: "🐋", name: "whale2" },
      { char: "🦈", name: "shark" },
      { char: "🐊", name: "crocodile" },
      { char: "🐅", name: "tiger2" },
      { char: "🐆", name: "leopard" },
      { char: "🦓", name: "zebra" },
      { char: "🦍", name: "gorilla" },
      { char: "🦧", name: "orangutan" },
      { char: "🐘", name: "elephant" },
      { char: "🦛", name: "hippopotamus" },
      { char: "🦏", name: "rhinoceros" },
      { char: "🐪", name: "dromedary" },
      { char: "🐫", name: "camel" },
      { char: "🦒", name: "giraffe" },
      { char: "🦘", name: "kangaroo" },
      { char: "🐃", name: "water_buffalo" },
      { char: "🐂", name: "ox" },
      { char: "🐄", name: "cow2" },
      { char: "🐎", name: "racehorse" },
      { char: "🐖", name: "pig2" },
      { char: "🐏", name: "ram" },
      { char: "🐑", name: "sheep" },
      { char: "🦙", name: "llama" },
      { char: "🐐", name: "goat" },
      { char: "🦌", name: "deer" },
      { char: "🐕", name: "dog2" },
      { char: "🐩", name: "poodle" },
      { char: "🦮", name: "guide_dog" },
      { char: "🐈", name: "cat2" },
      { char: "🐓", name: "rooster" },
      { char: "🦃", name: "turkey" },
      { char: "🦚", name: "peacock" },
      { char: "🦜", name: "parrot" },
      { char: "🦢", name: "swan" },
      { char: "🦩", name: "flamingo" },
      { char: "🌸", name: "cherry_blossom" },
      { char: "💮", name: "white_flower" },
      { char: "🏵️", name: "rosette" },
      { char: "🌹", name: "rose" },
      { char: "🥀", name: "wilted_flower" },
      { char: "🌺", name: "hibiscus" },
      { char: "🌻", name: "sunflower" },
      { char: "🌼", name: "blossom" },
      { char: "🌷", name: "tulip" },
      { char: "🌱", name: "seedling" },
      { char: "🪴", name: "potted_plant" },
      { char: "🌲", name: "evergreen_tree" },
      { char: "🌳", name: "deciduous_tree" },
      { char: "🌴", name: "palm_tree" },
      { char: "🌵", name: "cactus" },
      { char: "🌾", name: "ear_of_rice" },
      { char: "🌿", name: "herb" },
      { char: "☘️", name: "shamrock" },
      { char: "🍀", name: "four_leaf_clover" },
      { char: "🍁", name: "maple_leaf" },
      { char: "🍂", name: "fallen_leaf" },
      { char: "🍃", name: "leaves" },
      { char: "🪨", name: "rock" },
      { char: "🪵", name: "wood" },
    ],
  },
  {
    label: "Food & Drink",
    emojis: [
      { char: "🍏", name: "green_apple" },
      { char: "🍎", name: "apple" },
      { char: "🍐", name: "pear" },
      { char: "🍊", name: "tangerine" },
      { char: "🍋", name: "lemon" },
      { char: "🍌", name: "banana" },
      { char: "🍉", name: "watermelon" },
      { char: "🍇", name: "grapes" },
      { char: "🍓", name: "strawberry" },
      { char: "🫐", name: "blueberries" },
      { char: "🍈", name: "melon" },
      { char: "🍒", name: "cherries" },
      { char: "🍑", name: "peach" },
      { char: "🥭", name: "mango" },
      { char: "🍍", name: "pineapple" },
      { char: "🥥", name: "coconut" },
      { char: "🥝", name: "kiwi" },
      { char: "🍅", name: "tomato" },
      { char: "🍆", name: "eggplant" },
      { char: "🥑", name: "avocado" },
      { char: "🥦", name: "broccoli" },
      { char: "🥬", name: "leafy_green" },
      { char: "🥒", name: "cucumber" },
      { char: "🌶️", name: "hot_pepper" },
      { char: "🫑", name: "bell_pepper" },
      { char: "🌽", name: "corn" },
      { char: "🥕", name: "carrot" },
      { char: "🫒", name: "olive" },
      { char: "🧄", name: "garlic" },
      { char: "🧅", name: "onion" },
      { char: "🥔", name: "potato" },
      { char: "🍠", name: "sweet_potato" },
      { char: "🥐", name: "croissant" },
      { char: "🥯", name: "bagel" },
      { char: "🍞", name: "bread" },
      { char: "🥖", name: "baguette" },
      { char: "🥨", name: "pretzel" },
      { char: "🧀", name: "cheese" },
      { char: "🥚", name: "egg" },
      { char: "🍳", name: "fried_egg" },
      { char: "🧈", name: "butter" },
      { char: "🥞", name: "pancakes" },
      { char: "🧇", name: "waffle" },
      { char: "🥓", name: "bacon" },
      { char: "🥩", name: "steak" },
      { char: "🍗", name: "poultry_leg" },
      { char: "🍖", name: "meat" },
      { char: "🦴", name: "bone" },
      { char: "🌭", name: "hot_dog" },
      { char: "🍔", name: "hamburger" },
      { char: "🍟", name: "fries" },
      { char: "🍕", name: "pizza" },
      { char: "🥪", name: "sandwich" },
      { char: "🌮", name: "taco" },
      { char: "🌯", name: "burrito" },
      { char: "🫔", name: "tamale" },
      { char: "🥙", name: "stuffed_flatbread" },
      { char: "🧆", name: "falafel" },
      { char: "🥘", name: "shallow_pan_of_food" },
      { char: "🍲", name: "stew" },
      { char: "🫕", name: "fondue" },
      { char: "🥣", name: "bowl_with_spoon" },
      { char: "🥗", name: "salad" },
      { char: "🍿", name: "popcorn" },
      { char: "🧂", name: "salt" },
      { char: "🥫", name: "canned_food" },
      { char: "🍱", name: "bento" },
      { char: "🍘", name: "rice_cracker" },
      { char: "🍙", name: "rice_ball" },
      { char: "🍚", name: "rice" },
      { char: "🍛", name: "curry" },
      { char: "🍜", name: "ramen" },
      { char: "🍝", name: "spaghetti" },
      { char: "🍣", name: "sushi" },
      { char: "🍤", name: "fried_shrimp" },
      { char: "🥟", name: "dumpling" },
      { char: "🍢", name: "oden" },
      { char: "🍡", name: "dango" },
      { char: "🦪", name: "oyster" },
      { char: "🍦", name: "ice_cream" },
      { char: "🍧", name: "shaved_ice" },
      { char: "🍨", name: "icecream" },
      { char: "🍩", name: "doughnut" },
      { char: "🍪", name: "cookie" },
      { char: "🎂", name: "birthday_cake" },
      { char: "🍰", name: "cake" },
      { char: "🧁", name: "cupcake" },
      { char: "🥧", name: "pie" },
      { char: "🍫", name: "chocolate_bar" },
      { char: "🍬", name: "candy" },
      { char: "🍭", name: "lollipop" },
      { char: "🍮", name: "custard" },
      { char: "🍯", name: "honey_pot" },
      { char: "🍼", name: "baby_bottle" },
      { char: "🥛", name: "milk" },
      { char: "☕", name: "coffee" },
      { char: "🫖", name: "teapot" },
      { char: "🍵", name: "tea" },
      { char: "🍶", name: "sake" },
      { char: "🍾", name: "champagne" },
      { char: "🍷", name: "wine_glass" },
      { char: "🍸", name: "cocktail" },
      { char: "🍹", name: "tropical_drink" },
      { char: "🍺", name: "beer" },
      { char: "🍻", name: "beers" },
      { char: "🥂", name: "clinking_glasses" },
      { char: "🥃", name: "tumbler_glass" },
      { char: "🥤", name: "cup_with_straw" },
      { char: "🧋", name: "bubble_tea" },
      { char: "🧃", name: "beverage_box" },
      { char: "🧉", name: "mate" },
      { char: "🧊", name: "ice_cube" },
    ],
  },
  {
    label: "Activities",
    emojis: [
      { char: "⚽", name: "soccer" },
      { char: "🏀", name: "basketball" },
      { char: "🏈", name: "football" },
      { char: "⚾", name: "baseball" },
      { char: "🥎", name: "softball" },
      { char: "🎾", name: "tennis" },
      { char: "🏐", name: "volleyball" },
      { char: "🏉", name: "rugby" },
      { char: "🥏", name: "frisbee" },
      { char: "🎱", name: "8ball" },
      { char: "🪀", name: "yo_yo" },
      { char: "🏓", name: "ping_pong" },
      { char: "🏸", name: "badminton" },
      { char: "🏒", name: "ice_hockey" },
      { char: "🏑", name: "field_hockey" },
      { char: "🥍", name: "lacrosse" },
      { char: "🏏", name: "cricket_game" },
      { char: "🪃", name: "boomerang" },
      { char: "🥅", name: "goal_net" },
      { char: "⛳", name: "golf" },
      { char: "🪁", name: "kite" },
      { char: "🏹", name: "bow_and_arrow" },
      { char: "🎣", name: "fishing_pole" },
      { char: "🤿", name: "diving_mask" },
      { char: "🥊", name: "boxing_glove" },
      { char: "🥋", name: "martial_arts" },
      { char: "🎽", name: "running_shirt" },
      { char: "🛹", name: "skateboard" },
      { char: "🛼", name: "roller_skate" },
      { char: "🛷", name: "sled" },
      { char: "⛸️", name: "ice_skate" },
      { char: "🥌", name: "curling_stone" },
      { char: "🎿", name: "ski" },
      { char: "⛷️", name: "skier" },
      { char: "🏂", name: "snowboarder" },
      { char: "🪂", name: "parachute" },
      { char: "🏋️", name: "weight_lifter" },
      { char: "🤼", name: "wrestlers" },
      { char: "🤸", name: "cartwheel" },
      { char: "⛹️", name: "bouncing_ball" },
      { char: "🤺", name: "fencer" },
      { char: "🤾", name: "handball" },
      { char: "🏌️", name: "golfer" },
      { char: "🏇", name: "horse_racing" },
      { char: "🧘", name: "lotus_position" },
      { char: "🏄", name: "surfer" },
      { char: "🏊", name: "swimmer" },
      { char: "🤽", name: "water_polo" },
      { char: "🚣", name: "rowboat" },
      { char: "🧗", name: "climbing" },
      { char: "🚵", name: "mountain_bicyclist" },
      { char: "🚴", name: "bicyclist" },
      { char: "🏆", name: "trophy" },
      { char: "🥇", name: "first_place" },
      { char: "🥈", name: "second_place" },
      { char: "🥉", name: "third_place" },
      { char: "🏅", name: "medal_sports" },
      { char: "🎖️", name: "medal_military" },
      { char: "🏵️", name: "rosette" },
      { char: "🎗️", name: "reminder_ribbon" },
      { char: "🎫", name: "ticket" },
      { char: "🎟️", name: "tickets" },
      { char: "🎪", name: "circus_tent" },
      { char: "🤹", name: "juggling" },
      { char: "🎭", name: "performing_arts" },
      { char: "🩰", name: "ballet_shoes" },
      { char: "🎨", name: "art" },
      { char: "🎬", name: "clapper" },
      { char: "🎤", name: "microphone" },
      { char: "🎧", name: "headphones" },
      { char: "🎼", name: "musical_score" },
      { char: "🎵", name: "musical_note" },
      { char: "🎶", name: "notes" },
      { char: "🎹", name: "musical_keyboard" },
      { char: "🥁", name: "drum" },
      { char: "🪘", name: "long_drum" },
      { char: "🎷", name: "saxophone" },
      { char: "🎺", name: "trumpet" },
      { char: "🎸", name: "guitar" },
      { char: "🪕", name: "banjo" },
      { char: "🎻", name: "violin" },
      { char: "🎲", name: "game_die" },
      { char: "♟️", name: "chess_pawn" },
      { char: "🎯", name: "dart" },
      { char: "🎳", name: "bowling" },
      { char: "🎮", name: "video_game" },
      { char: "🎰", name: "slot_machine" },
      { char: "🧩", name: "jigsaw" },
    ],
  },
  {
    label: "Travel & Places",
    emojis: [
      { char: "🚗", name: "car" },
      { char: "🚕", name: "taxi" },
      { char: "🚙", name: "blue_car" },
      { char: "🚌", name: "bus" },
      { char: "🚎", name: "trolleybus" },
      { char: "🏎️", name: "racing_car" },
      { char: "🚓", name: "police_car" },
      { char: "🚑", name: "ambulance" },
      { char: "🚒", name: "fire_engine" },
      { char: "🚐", name: "minibus" },
      { char: "🛻", name: "pickup_truck" },
      { char: "🚚", name: "truck" },
      { char: "🚛", name: "articulated_lorry" },
      { char: "🚜", name: "tractor" },
      { char: "🛵", name: "motor_scooter" },
      { char: "🏍️", name: "motorcycle" },
      { char: "🛺", name: "auto_rickshaw" },
      { char: "🚲", name: "bike" },
      { char: "🛴", name: "kick_scooter" },
      { char: "🚨", name: "rotating_light" },
      { char: "🚔", name: "oncoming_police_car" },
      { char: "🚍", name: "oncoming_bus" },
      { char: "🚘", name: "oncoming_automobile" },
      { char: "🚖", name: "oncoming_taxi" },
      { char: "🚡", name: "aerial_tramway" },
      { char: "🚠", name: "mountain_cableway" },
      { char: "🚟", name: "suspension_railway" },
      { char: "🚃", name: "railway_car" },
      { char: "🚋", name: "train" },
      { char: "🚞", name: "mountain_railway" },
      { char: "🚝", name: "monorail" },
      { char: "🚄", name: "bullettrain_side" },
      { char: "🚅", name: "bullettrain_front" },
      { char: "🚈", name: "light_rail" },
      { char: "🚂", name: "steam_locomotive" },
      { char: "🚆", name: "train2" },
      { char: "🚇", name: "metro" },
      { char: "🚊", name: "tram" },
      { char: "🚉", name: "station" },
      { char: "✈️", name: "airplane" },
      { char: "🛫", name: "airplane_departure" },
      { char: "🛬", name: "airplane_arriving" },
      { char: "🛩️", name: "small_airplane" },
      { char: "💺", name: "seat" },
      { char: "🛰️", name: "satellite" },
      { char: "🚀", name: "rocket" },
      { char: "🛸", name: "ufo" },
      { char: "🚁", name: "helicopter" },
      { char: "🛶", name: "canoe" },
      { char: "⛵", name: "boat" },
      { char: "🚤", name: "speedboat" },
      { char: "🛥️", name: "motor_boat" },
      { char: "🛳️", name: "passenger_ship" },
      { char: "⛴️", name: "ferry" },
      { char: "🚢", name: "ship" },
      { char: "⚓", name: "anchor" },
      { char: "🪝", name: "hook" },
      { char: "⛽", name: "fuelpump" },
      { char: "🚧", name: "construction" },
      { char: "🚦", name: "vertical_traffic_light" },
      { char: "🚥", name: "traffic_light" },
      { char: "🗺️", name: "world_map" },
      { char: "🗿", name: "moyai" },
      { char: "🗽", name: "statue_of_liberty" },
      { char: "🗼", name: "tokyo_tower" },
      { char: "🏰", name: "european_castle" },
      { char: "🏯", name: "japanese_castle" },
      { char: "🏟️", name: "stadium" },
      { char: "🎡", name: "ferris_wheel" },
      { char: "🎢", name: "roller_coaster" },
      { char: "🎠", name: "carousel_horse" },
      { char: "⛲", name: "fountain" },
      { char: "⛱️", name: "parasol_on_ground" },
      { char: "🏖️", name: "beach_umbrella" },
      { char: "🏝️", name: "desert_island" },
      { char: "🏜️", name: "desert" },
      { char: "🌋", name: "volcano" },
      { char: "⛰️", name: "mountain" },
      { char: "🏔️", name: "mountain_snow" },
      { char: "🗻", name: "mount_fuji" },
      { char: "🏕️", name: "camping" },
      { char: "⛺", name: "tent" },
      { char: "🛖", name: "hut" },
      { char: "🏠", name: "house" },
      { char: "🏡", name: "house_with_garden" },
      { char: "🏘️", name: "houses" },
      { char: "🏚️", name: "derelict_house" },
      { char: "🏗️", name: "building_construction" },
      { char: "🏭", name: "factory" },
      { char: "🏢", name: "office" },
      { char: "🏬", name: "department_store" },
      { char: "🏣", name: "post_office" },
      { char: "🏤", name: "european_post_office" },
      { char: "🏥", name: "hospital" },
      { char: "🏦", name: "bank" },
      { char: "🏨", name: "hotel" },
      { char: "🏪", name: "convenience_store" },
      { char: "🏫", name: "school" },
      { char: "🏩", name: "love_hotel" },
      { char: "💒", name: "wedding" },
      { char: "🏛️", name: "classical_building" },
      { char: "⛪", name: "church" },
      { char: "🕌", name: "mosque" },
      { char: "🕍", name: "synagogue" },
      { char: "🛕", name: "hindu_temple" },
      { char: "🕋", name: "kaaba" },
      { char: "⛩️", name: "shinto_shrine" },
      { char: "🌅", name: "sunrise" },
      { char: "🌄", name: "sunrise_over_mountains" },
      { char: "🌠", name: "stars" },
      { char: "🎇", name: "sparkler" },
      { char: "🎆", name: "fireworks" },
      { char: "🌇", name: "city_sunrise" },
      { char: "🌆", name: "city_sunset" },
      { char: "🏙️", name: "cityscape" },
      { char: "🌃", name: "night_with_stars" },
      { char: "🌌", name: "milky_way" },
      { char: "🌉", name: "bridge_at_night" },
      { char: "🌁", name: "foggy" },
    ],
  },
  {
    label: "Objects",
    emojis: [
      { char: "⌚", name: "watch" },
      { char: "📱", name: "iphone" },
      { char: "📲", name: "calling" },
      { char: "💻", name: "computer" },
      { char: "⌨️", name: "keyboard" },
      { char: "🖥️", name: "desktop_computer" },
      { char: "🖨️", name: "printer" },
      { char: "🖱️", name: "computer_mouse" },
      { char: "🖲️", name: "trackball" },
      { char: "🕹️", name: "joystick" },
      { char: "🗜️", name: "clamp" },
      { char: "💽", name: "minidisc" },
      { char: "💾", name: "floppy_disk" },
      { char: "💿", name: "cd" },
      { char: "📀", name: "dvd" },
      { char: "📼", name: "vhs" },
      { char: "📷", name: "camera" },
      { char: "📸", name: "camera_flash" },
      { char: "📹", name: "video_camera" },
      { char: "🎥", name: "movie_camera" },
      { char: "📽️", name: "film_projector" },
      { char: "🎞️", name: "film_strip" },
      { char: "📞", name: "telephone_receiver" },
      { char: "☎️", name: "phone" },
      { char: "📟", name: "pager" },
      { char: "📠", name: "fax" },
      { char: "📺", name: "tv" },
      { char: "📻", name: "radio" },
      { char: "🎙️", name: "studio_microphone" },
      { char: "🎚️", name: "level_slider" },
      { char: "🎛️", name: "control_knobs" },
      { char: "🧭", name: "compass" },
      { char: "⏱️", name: "stopwatch" },
      { char: "⏲️", name: "timer_clock" },
      { char: "⏰", name: "alarm_clock" },
      { char: "🕰️", name: "mantelpiece_clock" },
      { char: "⌛", name: "hourglass" },
      { char: "⏳", name: "hourglass_flowing_sand" },
      { char: "📡", name: "satellite_antenna" },
      { char: "🔋", name: "battery" },
      { char: "🪫", name: "low_battery" },
      { char: "🔌", name: "electric_plug" },
      { char: "💡", name: "bulb" },
      { char: "🔦", name: "flashlight" },
      { char: "🕯️", name: "candle" },
      { char: "🪔", name: "diya_lamp" },
      { char: "🧯", name: "fire_extinguisher" },
      { char: "🛢️", name: "oil_drum" },
      { char: "💸", name: "money_with_wings" },
      { char: "💵", name: "dollar" },
      { char: "💴", name: "yen" },
      { char: "💶", name: "euro" },
      { char: "💷", name: "pound" },
      { char: "🪙", name: "coin" },
      { char: "💰", name: "moneybag" },
      { char: "💳", name: "credit_card" },
      { char: "💎", name: "gem" },
      { char: "⚖️", name: "balance_scale" },
      { char: "🪜", name: "ladder" },
      { char: "🧰", name: "toolbox" },
      { char: "🪛", name: "screwdriver" },
      { char: "🔧", name: "wrench" },
      { char: "🔨", name: "hammer" },
      { char: "⚒️", name: "hammer_and_pick" },
      { char: "🛠️", name: "hammer_and_wrench" },
      { char: "⛏️", name: "pick" },
      { char: "🪚", name: "carpentry_saw" },
      { char: "🔩", name: "nut_and_bolt" },
      { char: "⚙️", name: "gear" },
      { char: "🪤", name: "mouse_trap" },
      { char: "🧱", name: "brick" },
      { char: "⛓️", name: "chains" },
      { char: "🧲", name: "magnet" },
      { char: "🔫", name: "gun" },
      { char: "💣", name: "bomb" },
      { char: "🧨", name: "firecracker" },
      { char: "🪓", name: "axe" },
      { char: "🔪", name: "knife" },
      { char: "🗡️", name: "dagger" },
      { char: "⚔️", name: "crossed_swords" },
      { char: "🛡️", name: "shield" },
      { char: "🚬", name: "smoking" },
      { char: "⚰️", name: "coffin" },
      { char: "🪦", name: "headstone" },
      { char: "⚱️", name: "funeral_urn" },
      { char: "🏺", name: "amphora" },
      { char: "🔮", name: "crystal_ball" },
      { char: "📿", name: "prayer_beads" },
      { char: "🧿", name: "nazar_amulet" },
      { char: "💈", name: "barber" },
      { char: "⚗️", name: "alembic" },
      { char: "🔭", name: "telescope" },
      { char: "🔬", name: "microscope" },
      { char: "🕳️", name: "hole" },
      { char: "🩹", name: "adhesive_bandage" },
      { char: "🩺", name: "stethoscope" },
      { char: "💊", name: "pill" },
      { char: "💉", name: "syringe" },
      { char: "🩸", name: "drop_of_blood" },
      { char: "🧬", name: "dna" },
      { char: "🦠", name: "microbe" },
      { char: "🧫", name: "petri_dish" },
      { char: "🧪", name: "test_tube" },
      { char: "🌡️", name: "thermometer" },
      { char: "🧹", name: "broom" },
      { char: "🧺", name: "basket" },
      { char: "🧻", name: "roll_of_paper" },
      { char: "🚽", name: "toilet" },
      { char: "🚰", name: "potable_water" },
      { char: "🚿", name: "shower" },
      { char: "🛁", name: "bathtub" },
      { char: "🪥", name: "toothbrush" },
      { char: "🧼", name: "soap" },
      { char: "🪣", name: "bucket" },
      { char: "🧽", name: "sponge" },
      { char: "🧴", name: "lotion_bottle" },
      { char: "🛎️", name: "bellhop_bell" },
      { char: "🔑", name: "key" },
      { char: "🗝️", name: "old_key" },
      { char: "🚪", name: "door" },
      { char: "🪑", name: "chair" },
      { char: "🛏️", name: "bed" },
      { char: "🛋️", name: "couch_and_lamp" },
      { char: "🪞", name: "mirror" },
      { char: "🪟", name: "window" },
      { char: "🖼️", name: "framed_picture" },
      { char: "🛍️", name: "shopping_bags" },
      { char: "🛒", name: "shopping_cart" },
      { char: "🎁", name: "gift" },
      { char: "🎀", name: "ribbon" },
      { char: "🪄", name: "magic_wand" },
      { char: "🪅", name: "pinata" },
      { char: "🎊", name: "confetti_ball" },
      { char: "🎈", name: "balloon" },
      { char: "✉️", name: "envelope" },
      { char: "📩", name: "envelope_with_arrow" },
      { char: "📨", name: "incoming_envelope" },
      { char: "📧", name: "email" },
      { char: "💌", name: "love_letter" },
      { char: "📥", name: "inbox_tray" },
      { char: "📤", name: "outbox_tray" },
      { char: "📦", name: "package" },
      { char: "🏷️", name: "label" },
      { char: "📪", name: "mailbox_closed" },
      { char: "📫", name: "mailbox" },
      { char: "📬", name: "mailbox_with_mail" },
      { char: "📭", name: "mailbox_with_no_mail" },
      { char: "📮", name: "postbox" },
      { char: "📯", name: "postal_horn" },
      { char: "📜", name: "scroll" },
      { char: "📃", name: "page_with_curl" },
      { char: "📄", name: "page_facing_up" },
      { char: "📑", name: "bookmark_tabs" },
      { char: "🧾", name: "receipt" },
      { char: "📊", name: "bar_chart" },
      { char: "📈", name: "chart_with_upwards_trend" },
      { char: "📉", name: "chart_with_downwards_trend" },
      { char: "🗒️", name: "spiral_notepad" },
      { char: "🗓️", name: "spiral_calendar" },
      { char: "📆", name: "calendar" },
      { char: "📅", name: "date" },
      { char: "🗑️", name: "wastebasket" },
      { char: "📇", name: "card_index" },
      { char: "🗃️", name: "card_file_box" },
      { char: "🗳️", name: "ballot_box" },
      { char: "🗄️", name: "file_cabinet" },
      { char: "📋", name: "clipboard" },
      { char: "📁", name: "file_folder" },
      { char: "📂", name: "open_file_folder" },
      { char: "🗂️", name: "card_index_dividers" },
      { char: "🗞️", name: "rolled_up_newspaper" },
      { char: "📰", name: "newspaper" },
      { char: "📓", name: "notebook" },
      { char: "📔", name: "notebook_with_decorative_cover" },
      { char: "📒", name: "ledger" },
      { char: "📕", name: "closed_book" },
      { char: "📗", name: "green_book" },
      { char: "📘", name: "blue_book" },
      { char: "📙", name: "orange_book" },
      { char: "📚", name: "books" },
      { char: "📖", name: "book" },
      { char: "🔖", name: "bookmark" },
      { char: "🧷", name: "safety_pin" },
      { char: "🔗", name: "link" },
      { char: "📎", name: "paperclip" },
      { char: "🖇️", name: "linked_paperclips" },
      { char: "📐", name: "triangular_ruler" },
      { char: "📏", name: "straight_ruler" },
      { char: "🧮", name: "abacus" },
      { char: "📌", name: "pushpin" },
      { char: "📍", name: "round_pushpin" },
      { char: "✂️", name: "scissors" },
      { char: "🖊️", name: "pen" },
      { char: "🖋️", name: "fountain_pen" },
      { char: "✒️", name: "black_nib" },
      { char: "🖌️", name: "paintbrush" },
      { char: "🖍️", name: "crayon" },
      { char: "📝", name: "memo" },
      { char: "✏️", name: "pencil" },
      { char: "🔍", name: "mag" },
      { char: "🔎", name: "mag_right" },
      { char: "🔏", name: "lock_with_ink_pen" },
      { char: "🔐", name: "closed_lock_with_key" },
      { char: "🔒", name: "lock" },
      { char: "🔓", name: "unlock" },
    ],
  },
  {
    label: "Symbols",
    emojis: [
      { char: "❤️", name: "heart" },
      { char: "🧡", name: "orange_heart" },
      { char: "💛", name: "yellow_heart" },
      { char: "💚", name: "green_heart" },
      { char: "💙", name: "blue_heart" },
      { char: "💜", name: "purple_heart" },
      { char: "🖤", name: "black_heart" },
      { char: "🤍", name: "white_heart" },
      { char: "🤎", name: "brown_heart" },
      { char: "💔", name: "broken_heart" },
      { char: "❣️", name: "heart_exclamation" },
      { char: "💕", name: "two_hearts" },
      { char: "💞", name: "revolving_hearts" },
      { char: "💓", name: "heartbeat" },
      { char: "💗", name: "heartpulse" },
      { char: "💖", name: "sparkling_heart" },
      { char: "💘", name: "cupid" },
      { char: "💝", name: "gift_heart" },
      { char: "💟", name: "heart_decoration" },
      { char: "☮️", name: "peace_symbol" },
      { char: "✝️", name: "latin_cross" },
      { char: "☪️", name: "star_and_crescent" },
      { char: "🕉️", name: "om_symbol" },
      { char: "☸️", name: "wheel_of_dharma" },
      { char: "✡️", name: "star_of_david" },
      { char: "🔯", name: "six_pointed_star" },
      { char: "🕎", name: "menorah" },
      { char: "☯️", name: "yin_yang" },
      { char: "☦️", name: "orthodox_cross" },
      { char: "🛐", name: "place_of_worship" },
      { char: "⛎", name: "ophiuchus" },
      { char: "♈", name: "aries" },
      { char: "♉", name: "taurus" },
      { char: "♊", name: "gemini" },
      { char: "♋", name: "cancer" },
      { char: "♌", name: "leo" },
      { char: "♍", name: "virgo" },
      { char: "♎", name: "libra" },
      { char: "♏", name: "scorpius" },
      { char: "♐", name: "sagittarius" },
      { char: "♑", name: "capricorn" },
      { char: "♒", name: "aquarius" },
      { char: "♓", name: "pisces" },
      { char: "🆔", name: "id" },
      { char: "⚛️", name: "atom_symbol" },
      { char: "🉑", name: "accept" },
      { char: "☢️", name: "radioactive" },
      { char: "☣️", name: "biohazard" },
      { char: "📴", name: "mobile_phone_off" },
      { char: "📳", name: "vibration_mode" },
      { char: "🈶", name: "u6709" },
      { char: "🈚", name: "u7121" },
      { char: "🈸", name: "u7533" },
      { char: "🈺", name: "u55b6" },
      { char: "🈷️", name: "u6708" },
      { char: "✴️", name: "eight_pointed_black_star" },
      { char: "🆚", name: "vs" },
      { char: "💮", name: "white_flower" },
      { char: "🉐", name: "ideograph_advantage" },
      { char: "㊙️", name: "secret" },
      { char: "㊗️", name: "congratulations" },
      { char: "🈴", name: "u5408" },
      { char: "🈵", name: "u6e80" },
      { char: "🈹", name: "u5272" },
      { char: "🈲", name: "u7981" },
      { char: "🅰️", name: "a" },
      { char: "🅱️", name: "b" },
      { char: "🆎", name: "ab" },
      { char: "🆑", name: "cl" },
      { char: "🅾️", name: "o2" },
      { char: "🆘", name: "sos" },
      { char: "❌", name: "x" },
      { char: "⭕", name: "o" },
      { char: "🛑", name: "stop_sign" },
      { char: "⛔", name: "no_entry" },
      { char: "📛", name: "name_badge" },
      { char: "🚫", name: "no_entry_sign" },
      { char: "💯", name: "100" },
      { char: "💢", name: "anger" },
      { char: "♨️", name: "hotsprings" },
      { char: "🚷", name: "no_pedestrians" },
      { char: "🚯", name: "do_not_litter" },
      { char: "🚳", name: "no_bicycles" },
      { char: "🚱", name: "non_potable_water" },
      { char: "🔞", name: "underage" },
      { char: "📵", name: "no_mobile_phones" },
      { char: "🚭", name: "no_smoking" },
      { char: "❗", name: "exclamation" },
      { char: "❕", name: "grey_exclamation" },
      { char: "❓", name: "question" },
      { char: "❔", name: "grey_question" },
      { char: "‼️", name: "bangbang" },
      { char: "⁉️", name: "interrobang" },
      { char: "🔅", name: "low_brightness" },
      { char: "🔆", name: "high_brightness" },
      { char: "〽️", name: "part_alternation_mark" },
      { char: "⚠️", name: "warning" },
      { char: "🚸", name: "children_crossing" },
      { char: "🔱", name: "trident" },
      { char: "⚜️", name: "fleur_de_lis" },
      { char: "🔰", name: "beginner" },
      { char: "♻️", name: "recycle" },
      { char: "✅", name: "white_check_mark" },
      { char: "🈯", name: "u6307" },
      { char: "💹", name: "chart" },
      { char: "❇️", name: "sparkle" },
      { char: "✳️", name: "eight_spoked_asterisk" },
      { char: "❎", name: "negative_squared_cross_mark" },
      { char: "🌐", name: "globe_with_meridians" },
      { char: "💠", name: "diamond_shape_with_a_dot_inside" },
      { char: "Ⓜ️", name: "m" },
      { char: "🌀", name: "cyclone" },
      { char: "💤", name: "zzz" },
      { char: "🏧", name: "atm" },
      { char: "🚾", name: "wc" },
      { char: "♿", name: "wheelchair" },
      { char: "🅿️", name: "parking" },
      { char: "🛗", name: "elevator" },
      { char: "🈳", name: "u7a7a" },
      { char: "🈂️", name: "sa" },
      { char: "🛂", name: "passport_control" },
      { char: "🛃", name: "customs" },
      { char: "🛄", name: "baggage_claim" },
      { char: "🛅", name: "left_luggage" },
      { char: "🚹", name: "mens" },
      { char: "🚺", name: "womens" },
      { char: "🚼", name: "baby_symbol" },
      { char: "🚻", name: "restroom" },
      { char: "🚮", name: "put_litter_in_its_place" },
      { char: "🎦", name: "cinema" },
      { char: "📶", name: "signal_strength" },
      { char: "🈁", name: "koko" },
      { char: "🔣", name: "symbols" },
      { char: "ℹ️", name: "information_source" },
      { char: "🔤", name: "abc" },
      { char: "🔡", name: "abcd_lower" },
      { char: "🔠", name: "capital_abcd" },
      { char: "🆖", name: "ng" },
      { char: "🆗", name: "ok" },
      { char: "🆙", name: "up" },
      { char: "🆒", name: "cool" },
      { char: "🆓", name: "free" },
      { char: "0️⃣", name: "zero" },
      { char: "1️⃣", name: "one" },
      { char: "2️⃣", name: "two" },
      { char: "3️⃣", name: "three" },
      { char: "4️⃣", name: "four" },
      { char: "5️⃣", name: "five" },
      { char: "6️⃣", name: "six" },
      { char: "7️⃣", name: "seven" },
      { char: "8️⃣", name: "eight" },
      { char: "9️⃣", name: "nine" },
      { char: "🔟", name: "keycap_ten" },
      { char: "🔢", name: "1234" },
      { char: "#️⃣", name: "hash" },
      { char: "*️⃣", name: "asterisk" },
      { char: "⏏️", name: "eject_button" },
      { char: "▶️", name: "arrow_forward" },
      { char: "⏸️", name: "pause_button" },
      { char: "⏯️", name: "play_or_pause_button" },
      { char: "⏹️", name: "stop_button" },
      { char: "⏺️", name: "record_button" },
      { char: "⏭️", name: "next_track_button" },
      { char: "⏮️", name: "previous_track_button" },
      { char: "⏩", name: "fast_forward" },
      { char: "⏪", name: "rewind" },
      { char: "⏫", name: "arrow_double_up" },
      { char: "⏬", name: "arrow_double_down" },
      { char: "◀️", name: "arrow_backward" },
      { char: "🔼", name: "arrow_up_small" },
      { char: "🔽", name: "arrow_down_small" },
      { char: "➡️", name: "arrow_right" },
      { char: "⬅️", name: "arrow_left" },
      { char: "⬆️", name: "arrow_up" },
      { char: "⬇️", name: "arrow_down" },
      { char: "↗️", name: "arrow_upper_right" },
      { char: "↘️", name: "arrow_lower_right" },
      { char: "↙️", name: "arrow_lower_left" },
      { char: "↖️", name: "arrow_upper_left" },
      { char: "↕️", name: "arrow_up_down" },
      { char: "↔️", name: "left_right_arrow" },
      { char: "↪️", name: "arrow_right_hook" },
      { char: "↩️", name: "leftwards_arrow_with_hook" },
      { char: "⤴️", name: "arrow_heading_up" },
      { char: "⤵️", name: "arrow_heading_down" },
      { char: "🔀", name: "twisted_rightwards_arrows" },
      { char: "🔁", name: "repeat" },
      { char: "🔂", name: "repeat_one" },
      { char: "🔄", name: "arrows_counterclockwise" },
      { char: "🔃", name: "arrows_clockwise" },
      { char: "🎵", name: "musical_note" },
      { char: "🎶", name: "notes" },
      { char: "➕", name: "heavy_plus_sign" },
      { char: "➖", name: "heavy_minus_sign" },
      { char: "➗", name: "heavy_division_sign" },
      { char: "✖️", name: "heavy_multiplication_x" },
      { char: "🟰", name: "heavy_equals_sign" },
      { char: "♾️", name: "infinity" },
      { char: "💲", name: "heavy_dollar_sign" },
      { char: "💱", name: "currency_exchange" },
      { char: "©️", name: "copyright" },
      { char: "®️", name: "registered" },
      { char: "™️", name: "tm" },
      { char: "🔚", name: "end" },
      { char: "🔙", name: "back" },
      { char: "🔛", name: "on" },
      { char: "🔝", name: "top" },
      { char: "🔜", name: "soon" },
      { char: "✔️", name: "heavy_check_mark" },
      { char: "☑️", name: "ballot_box_with_check" },
      { char: "🔘", name: "radio_button" },
      { char: "⚪", name: "white_circle" },
      { char: "⚫", name: "black_circle" },
      { char: "🔴", name: "red_circle" },
      { char: "🟠", name: "orange_circle" },
      { char: "🟡", name: "yellow_circle" },
      { char: "🟢", name: "green_circle" },
      { char: "🔵", name: "large_blue_circle" },
      { char: "🟣", name: "purple_circle" },
      { char: "🟤", name: "brown_circle" },
      { char: "🔺", name: "small_red_triangle" },
      { char: "🔻", name: "small_red_triangle_down" },
      { char: "🔸", name: "small_orange_diamond" },
      { char: "🔹", name: "small_blue_diamond" },
      { char: "🔶", name: "large_orange_diamond" },
      { char: "🔷", name: "large_blue_diamond" },
      { char: "🔳", name: "white_square_button" },
      { char: "🔲", name: "black_square_button" },
      { char: "▪️", name: "black_small_square" },
      { char: "▫️", name: "white_small_square" },
      { char: "◾", name: "black_medium_small_square" },
      { char: "◽", name: "white_medium_small_square" },
      { char: "◼️", name: "black_medium_square" },
      { char: "◻️", name: "white_medium_square" },
      { char: "🟥", name: "red_square" },
      { char: "🟧", name: "orange_square" },
      { char: "🟨", name: "yellow_square" },
      { char: "🟩", name: "green_square" },
      { char: "🟦", name: "blue_square" },
      { char: "🟪", name: "purple_square" },
      { char: "🟫", name: "brown_square" },
      { char: "⬛", name: "black_large_square" },
      { char: "⬜", name: "white_large_square" },
      { char: "🔈", name: "speaker" },
      { char: "🔇", name: "mute" },
      { char: "🔉", name: "sound" },
      { char: "🔊", name: "loud_sound" },
      { char: "🔔", name: "bell" },
      { char: "🔕", name: "no_bell" },
      { char: "📣", name: "mega" },
      { char: "📢", name: "loudspeaker" },
      { char: "👁️‍🗨️", name: "eye_speech_bubble" },
      { char: "💬", name: "speech_balloon" },
      { char: "💭", name: "thought_balloon" },
      { char: "🗯️", name: "right_anger_bubble" },
      { char: "♠️", name: "spades" },
      { char: "♣️", name: "clubs" },
      { char: "♥️", name: "hearts" },
      { char: "♦️", name: "diamonds" },
      { char: "🃏", name: "joker" },
      { char: "🎴", name: "flower_playing_cards" },
      { char: "🀄", name: "mahjong" },
      { char: "🕐", name: "clock1" },
      { char: "🕑", name: "clock2" },
      { char: "🕒", name: "clock3" },
      { char: "🕓", name: "clock4" },
      { char: "🕔", name: "clock5" },
      { char: "🕕", name: "clock6" },
      { char: "🕖", name: "clock7" },
      { char: "🕗", name: "clock8" },
      { char: "🕘", name: "clock9" },
      { char: "🕙", name: "clock10" },
      { char: "🕚", name: "clock11" },
      { char: "🕛", name: "clock12" },
      { char: "🌑", name: "new_moon" },
      { char: "🌒", name: "waxing_crescent_moon" },
      { char: "🌓", name: "first_quarter_moon" },
      { char: "🌔", name: "moon" },
      { char: "🌕", name: "full_moon" },
      { char: "🌖", name: "waning_gibbous_moon" },
      { char: "🌗", name: "last_quarter_moon" },
      { char: "🌘", name: "waning_crescent_moon" },
      { char: "🌙", name: "crescent_moon" },
      { char: "🌚", name: "new_moon_with_face" },
      { char: "🌛", name: "first_quarter_moon_with_face" },
      { char: "🌜", name: "last_quarter_moon_with_face" },
      { char: "🌡️", name: "thermometer" },
      { char: "☀️", name: "sunny" },
      { char: "🌝", name: "full_moon_with_face" },
      { char: "🌞", name: "sun_with_face" },
      { char: "⭐", name: "star" },
      { char: "🌟", name: "star2" },
      { char: "🌠", name: "stars" },
      { char: "☁️", name: "cloud" },
      { char: "⛅", name: "partly_sunny" },
      { char: "⛈️", name: "thunder_cloud_and_rain" },
      { char: "🌤️", name: "mostly_sunny" },
      { char: "🌥️", name: "barely_sunny" },
      { char: "🌦️", name: "partly_sunny_rain" },
      { char: "🌧️", name: "rain_cloud" },
      { char: "🌨️", name: "snow_cloud" },
      { char: "🌩️", name: "lightning" },
      { char: "🌪️", name: "tornado" },
      { char: "🌫️", name: "fog" },
      { char: "🌬️", name: "wind_blowing_face" },
      { char: "🌈", name: "rainbow" },
      { char: "☂️", name: "closed_umbrella" },
      { char: "☔", name: "umbrella_with_rain_drops" },
      { char: "⚡", name: "zap" },
      { char: "❄️", name: "snowflake" },
      { char: "☃️", name: "snowman" },
      { char: "⛄", name: "snowman_without_snow" },
      { char: "☄️", name: "comet" },
      { char: "🔥", name: "fire" },
      { char: "💧", name: "droplet" },
      { char: "🌊", name: "ocean" },
    ],
  },
  {
    label: "Flags",
    emojis: [
      { char: "🏁", name: "checkered_flag" },
      { char: "🚩", name: "triangular_flag_on_post" },
      { char: "🎌", name: "crossed_flags" },
      { char: "🏴", name: "black_flag" },
      { char: "🏳️", name: "white_flag" },
      { char: "🏳️‍🌈", name: "rainbow_flag" },
      { char: "🏳️‍⚧️", name: "transgender_flag" },
      { char: "🏴‍☠️", name: "pirate_flag" },
      { char: "🇺🇸", name: "us" },
      { char: "🇬🇧", name: "gb" },
      { char: "🇨🇦", name: "ca" },
      { char: "🇫🇷", name: "fr" },
      { char: "🇩🇪", name: "de" },
      { char: "🇪🇸", name: "es" },
      { char: "🇮🇹", name: "it" },
      { char: "🇯🇵", name: "jp" },
      { char: "🇨🇳", name: "cn" },
      { char: "🇰🇷", name: "kr" },
      { char: "🇮🇳", name: "in" },
      { char: "🇧🇷", name: "br" },
      { char: "🇲🇽", name: "mx" },
      { char: "🇦🇺", name: "au" },
      { char: "🇳🇿", name: "nz" },
      { char: "🇷🇺", name: "ru" },
      { char: "🇿🇦", name: "za" },
      { char: "🇳🇬", name: "ng" },
      { char: "🇰🇪", name: "ke" },
      { char: "🇪🇬", name: "eg" },
      { char: "🇸🇦", name: "sa" },
      { char: "🇦🇪", name: "ae" },
      { char: "🇮🇱", name: "il" },
      { char: "🇹🇷", name: "tr" },
      { char: "🇮🇩", name: "id" },
      { char: "🇵🇭", name: "ph" },
      { char: "🇹🇭", name: "th" },
      { char: "🇻🇳", name: "vn" },
      { char: "🇸🇬", name: "sg" },
      { char: "🇲🇾", name: "my" },
      { char: "🇵🇰", name: "pk" },
      { char: "🇧🇩", name: "bd" },
      { char: "🇳🇱", name: "nl" },
      { char: "🇧🇪", name: "be" },
      { char: "🇨🇭", name: "ch" },
      { char: "🇸🇪", name: "se" },
      { char: "🇳🇴", name: "no" },
      { char: "🇩🇰", name: "dk" },
      { char: "🇫🇮", name: "fi" },
      { char: "🇵🇱", name: "pl" },
      { char: "🇺🇦", name: "ua" },
      { char: "🇮🇪", name: "ie" },
      { char: "🇵🇹", name: "pt" },
      { char: "🇬🇷", name: "gr" },
      { char: "🇨🇿", name: "cz" },
      { char: "🇦🇹", name: "at" },
      { char: "🇭🇺", name: "hu" },
      { char: "🇷🇴", name: "ro" },
      { char: "🇦🇷", name: "ar" },
      { char: "🇨🇱", name: "cl" },
      { char: "🇨🇴", name: "co" },
      { char: "🇵🇪", name: "pe" },
      { char: "🇻🇪", name: "ve" },
    ],
  },
]

// ─── Component ─────────────────────────────────────────────────────────────────
interface IconPickerPopoverProps {
  trigger: React.ReactNode
  onSelect?: (icon: IconType, colorId: string) => void
  onSelectEmoji?: (char: string, name: string) => void
  defaultIcon?: IconType | null
  defaultColorId?: string
  defaultTab?: "icons" | "emojis"
  stopPropagation?: boolean
  /**
   * Override the popover trigger button's classes. Defaults to a
   * compact 20px square — pages that show the picker as a more
   * prominent block (e.g. the New view editor) override this with
   * the larger styling they need.
   */
  triggerClassName?: string
}

export function IconPickerPopover({
  trigger,
  onSelect,
  onSelectEmoji,
  defaultIcon = null,
  defaultColorId = "gray",
  defaultTab = "icons",
  stopPropagation = false,
  triggerClassName,
}: IconPickerPopoverProps) {
  const [open, setOpen] = useState(false)
  const [pickerTab, setPickerTab] = useState<"icons" | "emojis">(defaultTab)
  const [colorId, setColorId] = useState(defaultColorId)
  const [search, setSearch] = useState("")
  const [selectedIcon, setSelectedIcon] = useState<IconType | null>(defaultIcon)
  const [selectedEmoji, setSelectedEmoji] = useState<string | null>(null)

  const color = PICKER_COLORS.find((c) => c.id === colorId) ?? PICKER_COLORS[1]

  function handleSelect(icon: IconType) {
    setSelectedIcon(icon)
    setSelectedEmoji(null)
    setOpen(false)
    onSelect?.(icon, colorId)
  }
  function handleSelectEmoji(entry: EmojiEntry) {
    setSelectedEmoji(entry.char)
    setSelectedIcon(null)
    setOpen(false)
    onSelectEmoji?.(entry.char, entry.name)
  }
  function switchTab(tab: "icons" | "emojis") {
    setPickerTab(tab)
    setSearch("")
  }
  // The Emojis panel is rendered as a flat list-of-groups since
  // search has to span groups and grouping is just a visual aid.
  const emojiQuery = search.trim().toLowerCase()
  const filteredEmojiGroups: EmojiGroup[] = emojiQuery
    ? [
        {
          label: "Results",
          emojis: EMOJI_GROUPS.flatMap((g) => g.emojis).filter(
            (e) => e.name.includes(emojiQuery) || e.char.includes(emojiQuery)
          ),
        },
      ]
    : EMOJI_GROUPS

  const picker = (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger
        render={
          <button
            type="button"
            className={
              triggerClassName ??
              "hover:bg-accent flex size-5 shrink-0 items-center justify-center rounded"
            }
          />
        }
      >
        {selectedIcon ? (
          <HugeiconsIcon
            icon={selectedIcon}
            className={`size-4 shrink-0 ${color.text}`}
          />
        ) : (
          trigger
        )}
      </PopoverTrigger>

      <PopoverContent
        side="bottom"
        align="start"
        sideOffset={4}
        className="w-80 gap-0 p-0"
      >
        {/* Tabs */}
        <div className="flex border-b px-3 pt-2">
          {(["icons", "emojis"] as const).map((t) => (
            <button
              key={t}
              type="button"
              onClick={() => switchTab(t)}
              className={`px-2 pt-0.5 pb-2 text-xs font-medium transition-colors ${
                pickerTab === t
                  ? "border-foreground text-foreground border-b-2"
                  : "text-muted-foreground hover:text-foreground"
              }`}
            >
              {t.charAt(0).toUpperCase() + t.slice(1)}
            </button>
          ))}
        </div>

        {pickerTab === "emojis" ? (
          <>
            {/* Search */}
            <div className="flex items-center gap-2 border-b px-3 py-2">
              <HugeiconsIcon
                icon={Search01Icon}
                className="text-muted-foreground size-3.5 shrink-0"
              />
              <input
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                placeholder="Search emoji..."
                className="text-foreground placeholder:text-muted-foreground flex-1 bg-transparent text-xs focus:outline-none"
              />
            </div>
            {/* Grouped emoji grid — fixed height so the panel always
                scrolls vertically regardless of how many groups the
                user expands or how big a search result is. */}
            <div className="flex h-80 flex-col gap-2 overflow-y-auto p-2">
              {filteredEmojiGroups.map((group) => (
                <div key={group.label} className="flex flex-col gap-1">
                  <div className="text-muted-foreground px-1 pt-1 text-[11px]">
                    {group.label}
                  </div>
                  <div className="grid grid-cols-[repeat(13,1fr)] gap-0.5">
                    {group.emojis.map((entry, idx) => (
                      <button
                        key={`${entry.name}-${idx}`}
                        type="button"
                        title={`:${entry.name}:`}
                        onClick={() => handleSelectEmoji(entry)}
                        className={`hover:bg-accent flex size-[22px] items-center justify-center rounded text-base leading-none transition-colors ${
                          selectedEmoji === entry.char ? "bg-accent" : ""
                        }`}
                      >
                        {entry.char}
                      </button>
                    ))}
                    {group.emojis.length === 0 && (
                      <p className="text-muted-foreground col-span-full py-3 text-center text-xs">
                        No emoji found
                      </p>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </>
        ) : (
          <IconsPanel
            colorId={colorId}
            setColorId={setColorId}
            search={search}
            setSearch={setSearch}
            selectedIcon={selectedIcon}
            onSelect={handleSelect}
          />
        )}
      </PopoverContent>
    </Popover>
  )

  return stopPropagation ? (
    <div onClick={(e) => e.stopPropagation()}>{picker}</div>
  ) : (
    picker
  )
}

function IconsPanel({
  colorId,
  setColorId,
  search,
  setSearch,
  selectedIcon,
  onSelect,
}: {
  colorId: string
  setColorId: (id: string) => void
  search: string
  setSearch: (s: string) => void
  selectedIcon: IconType | null
  onSelect: (icon: IconType) => void
}) {
  const filtered = search
    ? PICKER_ICONS.filter((e) => e.name.includes(search.toLowerCase()))
    : PICKER_ICONS
  return (
    <>
      {/* Color palette */}
      <div className="flex items-center gap-1.5 px-3 py-2.5">
        {PICKER_COLORS.map((c) => (
          <button
            key={c.id}
            type="button"
            onClick={() => setColorId(c.id)}
            className={`flex size-6 shrink-0 items-center justify-center rounded-full ${c.bg} transition-all ${
              colorId === c.id
                ? "ring-offset-popover ring-2 ring-white/30 ring-offset-1"
                : "opacity-75 hover:opacity-100"
            }`}
          >
            {colorId === c.id && (
              <svg viewBox="0 0 10 10" className="size-3.5" fill="none">
                <path
                  d="M2 5l2 2.5L8 2.5"
                  stroke="white"
                  strokeWidth="1.5"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                />
              </svg>
            )}
          </button>
        ))}
        {/* Rainbow */}
        <button
          type="button"
          onClick={() => setColorId("rainbow")}
          className={`flex size-6 shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-red-400 via-yellow-300 to-blue-400 transition-all ${
            colorId === "rainbow"
              ? "ring-offset-popover ring-2 ring-white/30 ring-offset-1"
              : "opacity-75 hover:opacity-100"
          }`}
        >
          {colorId === "rainbow" && (
            <svg viewBox="0 0 10 10" className="size-3.5" fill="none">
              <path
                d="M2 5l2 2.5L8 2.5"
                stroke="white"
                strokeWidth="1.5"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
            </svg>
          )}
        </button>
      </div>

      {/* Search */}
      <div className="flex items-center gap-2 border-t border-b px-3 py-2">
        <HugeiconsIcon
          icon={Search01Icon}
          className="text-muted-foreground size-3.5 shrink-0"
        />
        <input
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          placeholder="Search icons..."
          className="text-foreground placeholder:text-muted-foreground flex-1 bg-transparent text-xs focus:outline-none"
        />
      </div>

      {/* Icon grid — auto-fill columns to fill the 320px popup */}
      <div className="grid max-h-60 grid-cols-[repeat(14,1fr)] gap-0.5 overflow-auto p-2">
        {filtered.map((entry) => (
          <button
            key={entry.name}
            type="button"
            title={entry.name}
            onClick={() => onSelect(entry.icon)}
            className={`hover:bg-accent flex size-[22px] items-center justify-center rounded transition-colors ${
              selectedIcon === entry.icon ? "bg-accent" : ""
            }`}
          >
            <HugeiconsIcon
              icon={entry.icon}
              strokeWidth={2}
              className="text-foreground/90 size-3.5"
            />
          </button>
        ))}
        {filtered.length === 0 && (
          <p className="text-muted-foreground col-span-full py-3 text-center text-xs">
            No icons found
          </p>
        )}
      </div>
    </>
  )
}
