import type { TaskDefinition } from "@simbench/core";

const R3 = {
  completion: 5.0,
  partialPerCheck: false,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
};
const R5 = {
  completion: 8.0,
  partialPerCheck: true,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
};

export const customerTasks: TaskDefinition[] = [
  {
    id: "cust-001",
    site: "shopify-admin",
    domain: "customers",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Update customer phone",
    goal: "Update Emma Johnson's phone number to '+1 212-555-9999'.",
    evalChecks: [
      {
        type: "state_diff",
        entity: "customers",
        id: "1",
        field: "phone",
        expected: "+1 212-555-9999",
        weight: 1.0,
        description: "Phone updated",
      },
    ],
    maxSteps: 15,
    rewardProfile: R3,
    tags: ["form-fill"],
  },
  {
    id: "cust-002",
    site: "shopify-admin",
    domain: "customers",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Add customer note",
    goal: "Add note 'Prefers express shipping' to Oliver Brown's profile.",
    evalChecks: [
      {
        type: "state_diff",
        entity: "customers",
        id: "8",
        field: "notes",
        expected: "Prefers express shipping",
        weight: 1.0,
        description: "Note added",
      },
    ],
    maxSteps: 15,
    rewardProfile: R3,
    tags: ["form-fill"],
  },
  {
    id: "cust-003",
    site: "shopify-admin",
    domain: "customers",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Update customer email",
    goal: "Change Sofia Martinez's email to 'sofia.martinez@newmail.com'.",
    evalChecks: [
      {
        type: "state_diff",
        entity: "customers",
        id: "3",
        field: "email",
        expected: "sofia.martinez@newmail.com",
        weight: 1.0,
        description: "Email updated",
      },
    ],
    maxSteps: 15,
    rewardProfile: R3,
    tags: ["form-fill"],
  },
  {
    id: "cust-004",
    site: "shopify-admin",
    domain: "customers",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Update customer name",
    goal: "Change Oliver Brown's first name to 'Ollie'.",
    evalChecks: [
      {
        type: "state_diff",
        entity: "customers",
        id: "8",
        field: "firstName",
        expected: "Ollie",
        weight: 1.0,
        description: "Name updated",
      },
    ],
    maxSteps: 15,
    rewardProfile: R3,
    tags: ["form-fill"],
  },

  // Creation
  {
    id: "cust-005",
    site: "shopify-admin",
    domain: "customers",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Create a new customer",
    goal: "Create customer: First='Jane', Last='Doe', Email='jane.doe@example.com'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "customer_exists_with_email",
        expected: "jane.doe@example.com",
        weight: 1.0,
        description: "Customer created",
      },
    ],
    maxSteps: 25,
    rewardProfile: R5,
    tags: ["creation", "form-fill"],
  },
  {
    id: "cust-006",
    site: "shopify-admin",
    domain: "customers",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Create customer with phone",
    goal: "Create: First='Alex', Last='Kim', Email='alex.k@example.com', Phone='+1 555-123-4567'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "customer_exists_with_email",
        expected: "alex.k@example.com",
        weight: 1.0,
        description: "Customer created",
      },
    ],
    maxSteps: 25,
    rewardProfile: R5,
    tags: ["creation", "form-fill"],
  },
  {
    id: "cust-007",
    site: "shopify-admin",
    domain: "customers",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Create VIP customer",
    goal: "Create: First='Maria', Last='Santos', Email='maria.s@example.com'. Add tag 'vip'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "customer_exists_with_email",
        expected: "maria.s@example.com",
        weight: 0.5,
        description: "Customer exists",
      },
      {
        type: "state_predicate",
        predicate: "customer_has_tag",
        expected: "vip",
        weight: 0.5,
        description: "Has VIP tag",
      },
    ],
    maxSteps: 25,
    rewardProfile: R5,
    tags: ["creation", "form-fill"],
  },

  // Multi-field
  {
    id: "cust-010",
    site: "shopify-admin",
    domain: "customers",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Update multiple customer fields",
    goal: "Update Liam Chen: change email to 'liam.chen@newco.com', phone to '+1 415-555-0000', and add note 'Updated contact info March 2026'.",
    evalChecks: [
      {
        type: "state_diff",
        entity: "customers",
        id: "2",
        field: "email",
        expected: "liam.chen@newco.com",
        weight: 0.33,
        description: "Email updated",
      },
      {
        type: "state_diff",
        entity: "customers",
        id: "2",
        field: "phone",
        expected: "+1 415-555-0000",
        weight: 0.33,
        description: "Phone updated",
      },
      {
        type: "state_diff",
        entity: "customers",
        id: "2",
        field: "notes",
        expected: "Updated contact info March 2026",
        weight: 0.34,
        description: "Note updated",
      },
    ],
    maxSteps: 20,
    rewardProfile: R5,
    tags: ["multi-field", "form-fill"],
  },
  {
    id: "cust-008",
    site: "shopify-admin",
    domain: "customers",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Add wholesale tag",
    goal: "Add the tag 'wholesale' to Noah Williams's profile.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "customer_has_tag",
        entity: "customers",
        id: "4",
        expected: "wholesale",
        weight: 1.0,
        description: "Tag added",
      },
    ],
    maxSteps: 15,
    rewardProfile: R3,
    tags: ["form-fill"],
  },
  {
    id: "cust-009",
    site: "shopify-admin",
    domain: "customers",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Create international customer",
    goal: "Create: First='Yuki', Last='Tanaka', Email='yuki.t@example.jp', Phone='+81 3-5555-0001'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "customer_exists_with_email",
        expected: "yuki.t@example.jp",
        weight: 1.0,
        description: "Customer created",
      },
    ],
    maxSteps: 25,
    rewardProfile: R5,
    tags: ["creation"],
  },
];
