import type { TaskDefinition } from "@thetabench/core";

const R3 = {
  completion: 5.0,
  partialPerCheck: false,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
};
const R5 = {
  completion: 8.0,
  partialPerCheck: true,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
};
const R8 = {
  completion: 15.0,
  partialPerCheck: true,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.2,
};

export const discountTasks: TaskDefinition[] = [
  {
    id: "disc-001",
    site: "shopify-admin",
    domain: "discounts",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Create percentage discount",
    goal: "Create a discount code 'SPRING15' with 15% off.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "discount_exists_with_code",
        expected: "SPRING15",
        weight: 1.0,
        description: "Discount created",
      },
    ],
    maxSteps: 25,
    rewardProfile: R5,
    tags: ["creation", "form-fill"],
  },
  {
    id: "disc-002",
    site: "shopify-admin",
    domain: "discounts",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Create fixed amount discount",
    goal: "Create a discount code 'SAVE20' for $20 off.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "discount_exists_with_code",
        expected: "SAVE20",
        weight: 1.0,
        description: "Discount created",
      },
    ],
    maxSteps: 25,
    rewardProfile: R5,
    tags: ["creation", "form-fill"],
  },
  {
    id: "disc-003",
    site: "shopify-admin",
    domain: "discounts",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Create free shipping discount",
    goal: "Create an automatic free shipping discount titled 'Free Ship Weekend'.",
    evalChecks: [
      {
        type: "state_exists",
        entity: "discounts",
        field: "title",
        expected: "Free Ship Weekend",
        weight: 1.0,
        description: "Discount exists",
      },
    ],
    maxSteps: 25,
    rewardProfile: R5,
    tags: ["creation"],
  },
  {
    id: "disc-004",
    site: "shopify-admin",
    domain: "discounts",
    type: "action",
    difficulty: "easy",
    curriculumStage: 3,
    title: "Delete expired discount",
    goal: "Delete the expired discount 'Holiday $15 Off'.",
    evalChecks: [
      {
        type: "state_absent",
        entity: "discounts",
        id: "4",
        weight: 1.0,
        description: "Discount deleted",
      },
    ],
    maxSteps: 15,
    rewardProfile: R3,
    tags: ["deletion"],
  },
  {
    id: "disc-005",
    site: "shopify-admin",
    domain: "discounts",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Update discount value",
    goal: "Change 'Summer Sale 20%' from 20% to 25% off.",
    evalChecks: [
      {
        type: "state_diff",
        entity: "discounts",
        id: "1",
        field: "value",
        expected: "25",
        weight: 1.0,
        description: "Value updated",
      },
    ],
    maxSteps: 20,
    rewardProfile: R5,
    tags: ["form-fill"],
  },
  {
    id: "disc-006",
    site: "shopify-admin",
    domain: "discounts",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Create limited-use discount",
    goal: "Create code 'FLASH50' for 50% off with usage limit of 100.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "discount_exists_with_code",
        expected: "FLASH50",
        weight: 0.5,
        description: "Discount created",
      },
      {
        type: "state_predicate",
        predicate: "discount_has_fields",
        expected: { code: "FLASH50", usageLimit: 100 },
        weight: 0.5,
        description: "Usage limit set to 100",
      },
    ],
    maxSteps: 25,
    rewardProfile: R5,
    tags: ["creation", "form-fill"],
  },
  {
    id: "disc-007",
    site: "shopify-admin",
    domain: "discounts",
    type: "action",
    difficulty: "easy",
    curriculumStage: 3,
    title: "Delete all expired discounts",
    goal: "Delete all discounts with status 'expired'.",
    evalChecks: [
      {
        type: "state_absent",
        entity: "discounts",
        id: "4",
        weight: 1.0,
        description: "Holiday discount deleted",
      },
    ],
    maxSteps: 20,
    rewardProfile: R3,
    tags: ["deletion", "conditional"],
  },
  {
    id: "disc-008",
    site: "shopify-admin",
    domain: "discounts",
    type: "action",
    difficulty: "hard",
    curriculumStage: 8,
    title: "Create and configure discount",
    goal: "Create code 'NEWYEAR30' for 30% off, usage limit 200, start date '2026-01-01', end date '2026-01-31'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "discount_exists_with_code",
        expected: "NEWYEAR30",
        weight: 0.25,
        description: "Discount created",
      },
      {
        type: "state_predicate",
        predicate: "discount_has_fields",
        expected: { code: "NEWYEAR30", usageLimit: 200 },
        weight: 0.25,
        description: "Usage limit set to 200",
      },
      {
        type: "state_predicate",
        predicate: "discount_has_fields",
        expected: { code: "NEWYEAR30", startsAt: "2026-01-01" },
        weight: 0.25,
        description: "Start date set",
      },
      {
        type: "state_predicate",
        predicate: "discount_has_fields",
        expected: { code: "NEWYEAR30", endsAt: "2026-01-31" },
        weight: 0.25,
        description: "End date set",
      },
    ],
    maxSteps: 30,
    rewardProfile: R8,
    tags: ["creation", "multi-field"],
  },
  {
    id: "disc-009",
    site: "shopify-admin",
    domain: "discounts",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Update discount status",
    goal: "Change 'VIP 25% Discount' status from active to expired.",
    evalChecks: [
      {
        type: "state_diff",
        entity: "discounts",
        id: "5",
        field: "status",
        expected: "expired",
        weight: 1.0,
        description: "Status updated",
      },
    ],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["form-fill"],
  },
  {
    id: "disc-010",
    site: "shopify-admin",
    domain: "discounts",
    type: "action",
    difficulty: "hard",
    curriculumStage: 8,
    title: "Discount management workflow",
    goal: "Delete expired 'Holiday $15 Off', update 'Summer Sale 20%' to 30%, and create new code 'LOYALTY10' for 10% off.",
    evalChecks: [
      {
        type: "state_absent",
        entity: "discounts",
        id: "4",
        weight: 0.33,
        description: "Expired deleted",
      },
      {
        type: "state_diff",
        entity: "discounts",
        id: "1",
        field: "value",
        expected: "30",
        weight: 0.33,
        description: "Summer updated",
      },
      {
        type: "state_predicate",
        predicate: "discount_exists_with_code",
        expected: "LOYALTY10",
        weight: 0.34,
        description: "New created",
      },
    ],
    maxSteps: 35,
    rewardProfile: R8,
    tags: ["multi-step", "workflow"],
  },
];
