import type { TaskDefinition } from "./types";

const R = { completion: 5.0, partialPerCheck: false, stepPenalty: -0.01, invalidActionPenalty: -0.1 };

export const impossibleTasks: TaskDefinition[] = [
  { id: "imp-001", site: "shopify-admin", domain: "orders", type: "no_action", difficulty: "medium", curriculumStage: 8, title: "Refund already-refunded order", goal: "Refund order #1036.", impossibilityReason: "Order #1036 is already refunded (paymentStatus='refunded').", evalChecks: [], maxSteps: 15, rewardProfile: R, tags: ["impossible", "error-recognition"] },
  { id: "imp-002", site: "shopify-admin", domain: "orders", type: "no_action", difficulty: "medium", curriculumStage: 8, title: "Fulfill already-fulfilled order", goal: "Fulfill order #1040.", impossibilityReason: "Order #1040 is already fulfilled.", evalChecks: [], maxSteps: 15, rewardProfile: R, tags: ["impossible", "error-recognition"] },
  { id: "imp-003", site: "shopify-admin", domain: "orders", type: "no_action", difficulty: "medium", curriculumStage: 8, title: "Capture payment on paid order", goal: "Capture payment on order #1042.", impossibilityReason: "Order #1042 payment is already 'paid', not 'pending'.", evalChecks: [], maxSteps: 15, rewardProfile: R, tags: ["impossible", "error-recognition"] },
  { id: "imp-004", site: "shopify-admin", domain: "products", type: "no_action", difficulty: "medium", curriculumStage: 8, title: "Delete non-existent product", goal: "Delete the product 'Ultra Premium Jacket'.", impossibilityReason: "No product with title 'Ultra Premium Jacket' exists.", evalChecks: [], maxSteps: 15, rewardProfile: R, tags: ["impossible", "error-recognition"] },
  { id: "imp-005", site: "shopify-admin", domain: "customers", type: "no_action", difficulty: "medium", curriculumStage: 8, title: "Update non-existent customer", goal: "Update the email for customer 'John Smith'.", impossibilityReason: "No customer named 'John Smith' exists.", evalChecks: [], maxSteps: 15, rewardProfile: R, tags: ["impossible", "error-recognition"] },
  { id: "imp-006", site: "shopify-admin", domain: "orders", type: "no_action", difficulty: "hard", curriculumStage: 8, title: "Fulfill order without capturing payment", goal: "Fulfill order #1039 (note: payment is still pending).", impossibilityReason: "Best practice: payment should be captured before fulfillment. Agent should recognize the pending payment.", evalChecks: [], maxSteps: 15, rewardProfile: R, tags: ["impossible", "error-recognition", "conditional"] },
  { id: "imp-007", site: "shopify-admin", domain: "discounts", type: "no_action", difficulty: "medium", curriculumStage: 8, title: "Activate expired discount", goal: "Activate the 'Holiday $15 Off' discount code.", impossibilityReason: "This discount has status 'expired' and its end date (2025-12-31) has passed.", evalChecks: [], maxSteps: 15, rewardProfile: R, tags: ["impossible", "error-recognition"] },
  { id: "imp-008", site: "shopify-admin", domain: "products", type: "no_action", difficulty: "medium", curriculumStage: 8, title: "Edit non-existent product by ID", goal: "Change the price of product #99 to $19.99.", impossibilityReason: "Product with ID '99' does not exist.", evalChecks: [], maxSteps: 15, rewardProfile: R, tags: ["impossible", "error-recognition"] },
];
