import type { TaskDefinition } from "./types";

const R9 = {
  completion: 15.0,
  partialPerCheck: true,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.2,
};
const R10 = {
  completion: 20.0,
  partialPerCheck: true,
  stepPenalty: -0.03,
  invalidActionPenalty: -0.3,
};

export const multiDomainTasks: TaskDefinition[] = [
  // Stage 9 — cross-domain workflows
  {
    id: "multi-001",
    site: "shopify-admin",
    domain: "multi-domain",
    type: "action",
    difficulty: "hard",
    curriculumStage: 9,
    title: "Order processing workflow",
    goal: "Capture the pending payment on order #1039, then fulfill orders #1042 and #1039, and create a 10% discount code 'THANKYOU10'.",
    requires: ["ord-002", "ord-001", "disc-001"],
    evalChecks: [
      {
        type: "state_diff",
        entity: "orders",
        id: "4",
        field: "paymentStatus",
        expected: "paid",
        weight: 0.25,
        description: "Payment captured",
      },
      {
        type: "state_diff",
        entity: "orders",
        id: "1",
        field: "fulfillmentStatus",
        expected: "fulfilled",
        weight: 0.25,
        description: "#1042 fulfilled",
      },
      {
        type: "state_diff",
        entity: "orders",
        id: "4",
        field: "fulfillmentStatus",
        expected: "fulfilled",
        weight: 0.25,
        description: "#1039 fulfilled",
      },
      {
        type: "state_predicate",
        predicate: "discount_exists_with_code",
        expected: "THANKYOU10",
        weight: 0.25,
        description: "Discount created",
      },
    ],
    maxSteps: 45,
    rewardProfile: R9,
    tags: ["workflow", "multi-domain"],
  },
  {
    id: "multi-002",
    site: "shopify-admin",
    domain: "multi-domain",
    type: "action",
    difficulty: "hard",
    curriculumStage: 9,
    title: "New product launch",
    goal: "Create product 'Summer Hat' ($29.99, active, vendor 'ShadeVault'), create discount code 'HATLAUNCH' for 20% off, and update store name to 'Summer Store'.",
    evalChecks: [
      {
        type: "state_exists",
        entity: "products",
        field: "title",
        expected: "Summer Hat",
        weight: 0.33,
        description: "Product created",
      },
      {
        type: "state_predicate",
        predicate: "discount_exists_with_code",
        expected: "HATLAUNCH",
        weight: 0.33,
        description: "Discount created",
      },
      {
        type: "state_predicate",
        predicate: "settings_field_equals",
        field: "storeName",
        expected: "Summer Store",
        weight: 0.34,
        description: "Store name updated",
      },
    ],
    maxSteps: 45,
    rewardProfile: R9,
    tags: ["workflow", "multi-domain"],
  },
  {
    id: "multi-003",
    site: "shopify-admin",
    domain: "multi-domain",
    type: "action_retrieval",
    difficulty: "hard",
    curriculumStage: 9,
    title: "Customer order check and fulfill",
    goal: "Find Emma Johnson's most recent unfulfilled order, fulfill it, add note 'VIP order expedited', and report the order total.",
    requires: ["ord-001", "ord-004"],
    retrievalRubric: {
      question: "What was the order total?",
      groundTruth: "$149.97",
      acceptableVariations: ["149.97", "$149.97"],
      rubric: "Agent must find and report the total of Emma Johnson's unfulfilled order #1042.",
    },
    evalChecks: [
      {
        type: "state_diff",
        entity: "orders",
        id: "1",
        field: "fulfillmentStatus",
        expected: "fulfilled",
        weight: 0.4,
        description: "Order fulfilled",
      },
      {
        type: "state_predicate",
        predicate: "order_has_note_containing",
        entity: "orders",
        id: "1",
        expected: "VIP order expedited",
        weight: 0.3,
        description: "Note added",
      },
    ],
    maxSteps: 35,
    rewardProfile: R9,
    tags: ["workflow", "retrieval", "multi-domain"],
  },

  // Stage 10 — expert
  {
    id: "multi-010",
    site: "shopify-admin",
    domain: "multi-domain",
    type: "action",
    difficulty: "expert",
    curriculumStage: 10,
    title: "Full store operations",
    goal: "Complete these tasks: (1) Fulfill ALL unfulfilled orders, (2) Capture the pending payment on #1039, (3) Create a new customer 'Sam Wilson' (sam@example.com), (4) Create discount 'WELCOME15' for 15% off, (5) Update store name to 'Premium Threads'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "all_orders_fulfilled",
        weight: 0.2,
        description: "All fulfilled",
      },
      {
        type: "state_predicate",
        predicate: "no_pending_payments",
        weight: 0.2,
        description: "No pending",
      },
      {
        type: "state_predicate",
        predicate: "customer_exists_with_email",
        expected: "sam@example.com",
        weight: 0.2,
        description: "Customer created",
      },
      {
        type: "state_predicate",
        predicate: "discount_exists_with_code",
        expected: "WELCOME15",
        weight: 0.2,
        description: "Discount created",
      },
      {
        type: "state_predicate",
        predicate: "settings_field_equals",
        field: "storeName",
        expected: "Premium Threads",
        weight: 0.2,
        description: "Store renamed",
      },
    ],
    maxSteps: 60,
    rewardProfile: R10,
    tags: ["expert", "workflow", "multi-domain"],
  },
  {
    id: "multi-011",
    site: "shopify-admin",
    domain: "multi-domain",
    type: "action",
    difficulty: "expert",
    curriculumStage: 10,
    title: "Product catalog cleanup",
    goal: "Archive all draft products, delete all archived products, set inventory to 0 for all products priced over $100, and create a report discount 'CLEARANCE50' for 50% off.",
    evalChecks: [
      {
        type: "state_diff",
        entity: "products",
        id: "6",
        field: "status",
        expected: "archived",
        weight: 0.15,
        description: "P6 archived",
      },
      {
        type: "state_diff",
        entity: "products",
        id: "11",
        field: "status",
        expected: "archived",
        weight: 0.15,
        description: "P11 archived",
      },
      {
        type: "state_predicate",
        predicate: "discount_exists_with_code",
        expected: "CLEARANCE50",
        weight: 0.2,
        description: "Discount created",
      },
    ],
    maxSteps: 50,
    rewardProfile: R10,
    tags: ["expert", "conditional", "multi-domain"],
  },
  {
    id: "multi-012",
    site: "shopify-admin",
    domain: "multi-domain",
    type: "action_retrieval",
    difficulty: "expert",
    curriculumStage: 10,
    title: "Store audit",
    goal: "Audit the store: (1) How many active products are there? (2) Fulfill all unfulfilled orders. (3) Add note 'Audit complete' to order #1042.",
    retrievalRubric: {
      question: "How many active products?",
      groundTruth: "9",
      acceptableVariations: ["nine", "9 products", "9 active products"],
      rubric: "Agent must count products with status 'active'.",
    },
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "all_orders_fulfilled",
        weight: 0.4,
        description: "All fulfilled",
      },
      {
        type: "state_predicate",
        predicate: "order_has_note_containing",
        entity: "orders",
        id: "1",
        expected: "Audit complete",
        weight: 0.3,
        description: "Audit note",
      },
    ],
    maxSteps: 50,
    rewardProfile: R10,
    tags: ["expert", "retrieval", "workflow"],
  },
  {
    id: "multi-013",
    site: "shopify-admin",
    domain: "multi-domain",
    type: "action",
    difficulty: "expert",
    curriculumStage: 10,
    title: "Customer onboarding workflow",
    goal: "Create customer 'Pat Taylor' (pat@newstore.com, phone +1 555-0099). Create product 'Welcome Gift Box' ($0.00, active). Create discount 'PATSPECIAL' for $25 off. Add note 'New VIP onboarding' to the most recent order.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "customer_exists_with_email",
        expected: "pat@newstore.com",
        weight: 0.25,
        description: "Customer created",
      },
      {
        type: "state_exists",
        entity: "products",
        field: "title",
        expected: "Welcome Gift Box",
        weight: 0.25,
        description: "Product created",
      },
      {
        type: "state_predicate",
        predicate: "discount_exists_with_code",
        expected: "PATSPECIAL",
        weight: 0.25,
        description: "Discount created",
      },
      {
        type: "state_predicate",
        predicate: "order_has_note_containing",
        entity: "orders",
        id: "1",
        expected: "VIP onboarding",
        weight: 0.25,
        description: "Note added",
      },
    ],
    maxSteps: 55,
    rewardProfile: R10,
    tags: ["expert", "multi-domain", "workflow"],
  },
  {
    id: "multi-014",
    site: "shopify-admin",
    domain: "multi-domain",
    type: "action",
    difficulty: "expert",
    curriculumStage: 10,
    title: "End-of-day store close",
    goal: "Process end-of-day: capture all pending payments, fulfill all unfulfilled orders, update store name to 'My Store [Closed]', create note 'End of day processing' on all unfulfilled orders before fulfilling them.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "no_pending_payments",
        weight: 0.25,
        description: "Payments captured",
      },
      {
        type: "state_predicate",
        predicate: "all_orders_fulfilled",
        weight: 0.25,
        description: "All fulfilled",
      },
      {
        type: "state_predicate",
        predicate: "settings_field_equals",
        field: "storeName",
        expected: "My Store [Closed]",
        weight: 0.25,
        description: "Store closed",
      },
      {
        type: "state_predicate",
        predicate: "order_has_note_containing",
        entity: "orders",
        id: "1",
        expected: "End of day",
        weight: 0.25,
        description: "EOD note",
      },
    ],
    maxSteps: 60,
    rewardProfile: R10,
    tags: ["expert", "multi-domain", "workflow"],
  },
];
