import type { TaskDefinition } from "./types";

const R = {
  completion: 2.0,
  partialPerCheck: false,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
};

export const navigationTasks: TaskDefinition[] = [
  {
    id: "nav-001",
    site: "shopify-admin",
    domain: "navigation",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 1,
    title: "Navigate to products",
    goal: "Navigate to the Products page and report the page title.",
    retrievalRubric: {
      question: "What is the page title?",
      groundTruth: "Products",
      acceptableVariations: ["products", "Products page"],
      rubric: "Agent must navigate to /admin/products.",
    },
    evalChecks: [],
    maxSteps: 5,
    rewardProfile: R,
    tags: ["navigation"],
  },
  {
    id: "nav-002",
    site: "shopify-admin",
    domain: "navigation",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 1,
    title: "Navigate to orders",
    goal: "Navigate to the Orders page.",
    retrievalRubric: {
      question: "What page are you on?",
      groundTruth: "Orders",
      acceptableVariations: ["orders"],
      rubric: "Agent must navigate to /admin/orders.",
    },
    evalChecks: [],
    maxSteps: 5,
    rewardProfile: R,
    tags: ["navigation"],
  },
  {
    id: "nav-003",
    site: "shopify-admin",
    domain: "navigation",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 1,
    title: "Navigate to customers",
    goal: "Navigate to the Customers page.",
    retrievalRubric: {
      question: "What page are you on?",
      groundTruth: "Customers",
      acceptableVariations: ["customers"],
      rubric: "Agent must navigate to /admin/customers.",
    },
    evalChecks: [],
    maxSteps: 5,
    rewardProfile: R,
    tags: ["navigation"],
  },
  {
    id: "nav-004",
    site: "shopify-admin",
    domain: "navigation",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 1,
    title: "Navigate to settings",
    goal: "Navigate to the Settings page.",
    retrievalRubric: {
      question: "What page are you on?",
      groundTruth: "Settings",
      acceptableVariations: ["settings"],
      rubric: "Agent must navigate to /admin/settings.",
    },
    evalChecks: [],
    maxSteps: 5,
    rewardProfile: R,
    tags: ["navigation"],
  },
  {
    id: "nav-005",
    site: "shopify-admin",
    domain: "navigation",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 1,
    title: "Navigate to analytics",
    goal: "Navigate to the Analytics page.",
    retrievalRubric: {
      question: "What page are you on?",
      groundTruth: "Analytics",
      acceptableVariations: ["analytics"],
      rubric: "Agent must navigate to /admin/analytics.",
    },
    evalChecks: [],
    maxSteps: 5,
    rewardProfile: R,
    tags: ["navigation"],
  },
];
