import type { TaskDefinition } from "@simbench/core";

const R4 = {
  completion: 8.0,
  partialPerCheck: false,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
};
const R7 = {
  completion: 10.0,
  partialPerCheck: true,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.2,
};
const R8 = {
  completion: 15.0,
  partialPerCheck: true,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.2,
};

export const orderTasks: TaskDefinition[] = [
  // Stage 4 — order operations
  {
    id: "ord-001",
    site: "shopify-admin",
    domain: "orders",
    type: "action",
    difficulty: "medium",
    curriculumStage: 4,
    title: "Fulfill an order",
    goal: "Fulfill order #1042.",
    evalChecks: [
      {
        type: "state_diff",
        entity: "orders",
        id: "1",
        field: "fulfillmentStatus",
        expected: "fulfilled",
        weight: 1.0,
        description: "Order 1 fulfilled",
      },
    ],
    maxSteps: 15,
    rewardProfile: R4,
    tags: ["order-action"],
  },
  {
    id: "ord-002",
    site: "shopify-admin",
    domain: "orders",
    type: "action",
    difficulty: "medium",
    curriculumStage: 4,
    title: "Capture a pending payment",
    goal: "Capture the pending payment on order #1039.",
    evalChecks: [
      {
        type: "state_diff",
        entity: "orders",
        id: "4",
        field: "paymentStatus",
        expected: "paid",
        weight: 1.0,
        description: "Order 4 payment captured",
      },
    ],
    maxSteps: 15,
    rewardProfile: R4,
    tags: ["order-action"],
  },
  {
    id: "ord-003",
    site: "shopify-admin",
    domain: "orders",
    type: "action",
    difficulty: "medium",
    curriculumStage: 4,
    title: "Refund an order",
    goal: "Issue a refund for order #1034.",
    evalChecks: [
      {
        type: "state_diff",
        entity: "orders",
        id: "9",
        field: "paymentStatus",
        expected: "refunded",
        weight: 1.0,
        description: "Order 9 refunded",
      },
    ],
    maxSteps: 15,
    rewardProfile: R4,
    tags: ["order-action"],
  },
  {
    id: "ord-004",
    site: "shopify-admin",
    domain: "orders",
    type: "action",
    difficulty: "medium",
    curriculumStage: 4,
    title: "Add a note to an order",
    goal: "Add the note 'Customer requested expedited shipping' to order #1041.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "order_has_note_containing",
        entity: "orders",
        id: "2",
        expected: "expedited shipping",
        weight: 1.0,
        description: "Note added to order 2",
      },
    ],
    maxSteps: 15,
    rewardProfile: R4,
    tags: ["order-action", "form-fill"],
  },
  {
    id: "ord-005",
    site: "shopify-admin",
    domain: "orders",
    type: "action",
    difficulty: "medium",
    curriculumStage: 4,
    title: "Fulfill order #1033",
    goal: "Fulfill order #1033 for William Taylor.",
    evalChecks: [
      {
        type: "state_diff",
        entity: "orders",
        id: "10",
        field: "fulfillmentStatus",
        expected: "fulfilled",
        weight: 1.0,
        description: "Order 10 fulfilled",
      },
    ],
    maxSteps: 15,
    rewardProfile: R4,
    tags: ["order-action"],
  },

  // Stage 7 — conditional order operations
  {
    id: "ord-010",
    site: "shopify-admin",
    domain: "orders",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Fulfill all unfulfilled orders",
    goal: "Find and fulfill ALL unfulfilled orders.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "all_orders_fulfilled",
        weight: 0.5,
        description: "All orders fulfilled",
      },
      {
        type: "state_diff",
        entity: "orders",
        id: "1",
        field: "fulfillmentStatus",
        expected: "fulfilled",
        weight: 0.125,
        description: "#1042 fulfilled",
      },
      {
        type: "state_diff",
        entity: "orders",
        id: "2",
        field: "fulfillmentStatus",
        expected: "fulfilled",
        weight: 0.125,
        description: "#1041 fulfilled",
      },
      {
        type: "state_diff",
        entity: "orders",
        id: "4",
        field: "fulfillmentStatus",
        expected: "fulfilled",
        weight: 0.125,
        description: "#1039 fulfilled",
      },
      {
        type: "state_diff",
        entity: "orders",
        id: "10",
        field: "fulfillmentStatus",
        expected: "fulfilled",
        weight: 0.125,
        description: "#1033 fulfilled",
      },
    ],
    maxSteps: 40,
    rewardProfile: R7,
    tags: ["conditional", "multi-entity"],
  },
  {
    id: "ord-011",
    site: "shopify-admin",
    domain: "orders",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Process pending payments then fulfill",
    goal: "Capture the pending payment on order #1039, then fulfill it.",
    evalChecks: [
      {
        type: "state_diff",
        entity: "orders",
        id: "4",
        field: "paymentStatus",
        expected: "paid",
        weight: 0.5,
        description: "Payment captured",
      },
      {
        type: "state_diff",
        entity: "orders",
        id: "4",
        field: "fulfillmentStatus",
        expected: "fulfilled",
        weight: 0.5,
        description: "Order fulfilled",
      },
    ],
    maxSteps: 20,
    rewardProfile: R7,
    tags: ["multi-step", "conditional"],
  },

  // Stage 8 — multi-step
  {
    id: "ord-015",
    site: "shopify-admin",
    domain: "orders",
    type: "action",
    difficulty: "hard",
    curriculumStage: 8,
    title: "Complete all order processing",
    goal: "Process all pending actions: capture pending payment on #1039, fulfill all unfulfilled orders (#1042, #1041, #1039, #1033), and add note 'All orders processed' to order #1042.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "no_pending_payments",
        weight: 0.2,
        description: "No pending payments",
      },
      {
        type: "state_predicate",
        predicate: "all_orders_fulfilled",
        weight: 0.4,
        description: "All fulfilled",
      },
      {
        type: "state_predicate",
        predicate: "order_has_note_containing",
        entity: "orders",
        id: "1",
        expected: "All orders processed",
        weight: 0.4,
        description: "Note on #1042",
      },
    ],
    maxSteps: 50,
    rewardProfile: R8,
    tags: ["multi-step", "multi-entity"],
  },

  // Additional
  {
    id: "ord-006",
    site: "shopify-admin",
    domain: "orders",
    type: "action",
    difficulty: "medium",
    curriculumStage: 4,
    title: "Add shipping note",
    goal: "Add note 'Shipped via USPS Priority Mail' to order #1042.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "order_has_note_containing",
        entity: "orders",
        id: "1",
        expected: "USPS Priority",
        weight: 1.0,
        description: "Shipping note added",
      },
    ],
    maxSteps: 15,
    rewardProfile: R4,
    tags: ["order-action", "form-fill"],
  },
  {
    id: "ord-007",
    site: "shopify-admin",
    domain: "orders",
    type: "action",
    difficulty: "medium",
    curriculumStage: 4,
    title: "Fulfill Liam Chen's order",
    goal: "Fulfill the order for Liam Chen (#1041).",
    evalChecks: [
      {
        type: "state_diff",
        entity: "orders",
        id: "2",
        field: "fulfillmentStatus",
        expected: "fulfilled",
        weight: 1.0,
        description: "Order 2 fulfilled",
      },
    ],
    maxSteps: 15,
    rewardProfile: R4,
    tags: ["order-action"],
  },
  {
    id: "ord-008",
    site: "shopify-admin",
    domain: "orders",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Refund partial order",
    goal: "Issue a refund for order #1037 (James Rodriguez, partial fulfillment).",
    evalChecks: [
      {
        type: "state_diff",
        entity: "orders",
        id: "6",
        field: "paymentStatus",
        expected: "refunded",
        weight: 1.0,
        description: "Order 6 refunded",
      },
    ],
    maxSteps: 15,
    rewardProfile: R7,
    tags: ["order-action"],
  },
  {
    id: "ord-009",
    site: "shopify-admin",
    domain: "orders",
    type: "action",
    difficulty: "medium",
    curriculumStage: 4,
    title: "Add customer contact note",
    goal: "Add note 'Called customer to confirm address' to order #1039.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "order_has_note_containing",
        entity: "orders",
        id: "4",
        expected: "confirm address",
        weight: 1.0,
        description: "Note added",
      },
    ],
    maxSteps: 15,
    rewardProfile: R4,
    tags: ["form-fill"],
  },
  {
    id: "ord-012",
    site: "shopify-admin",
    domain: "orders",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Capture and fulfill pending order",
    goal: "Order #1039 has a pending payment. Capture the payment first, then fulfill the order.",
    evalChecks: [
      {
        type: "state_diff",
        entity: "orders",
        id: "4",
        field: "paymentStatus",
        expected: "paid",
        weight: 0.5,
        description: "Captured",
      },
      {
        type: "state_diff",
        entity: "orders",
        id: "4",
        field: "fulfillmentStatus",
        expected: "fulfilled",
        weight: 0.5,
        description: "Fulfilled",
      },
    ],
    maxSteps: 25,
    rewardProfile: R7,
    tags: ["multi-step"],
  },
  {
    id: "ord-013",
    site: "shopify-admin",
    domain: "orders",
    type: "action",
    difficulty: "hard",
    curriculumStage: 8,
    title: "Fulfill and note multiple orders",
    goal: "Fulfill orders #1042 and #1041, then add note 'Batch shipped' to both.",
    evalChecks: [
      {
        type: "state_diff",
        entity: "orders",
        id: "1",
        field: "fulfillmentStatus",
        expected: "fulfilled",
        weight: 0.25,
        description: "#1042 fulfilled",
      },
      {
        type: "state_diff",
        entity: "orders",
        id: "2",
        field: "fulfillmentStatus",
        expected: "fulfilled",
        weight: 0.25,
        description: "#1041 fulfilled",
      },
      {
        type: "state_predicate",
        predicate: "order_has_note_containing",
        entity: "orders",
        id: "1",
        expected: "Batch shipped",
        weight: 0.25,
        description: "#1042 note",
      },
      {
        type: "state_predicate",
        predicate: "order_has_note_containing",
        entity: "orders",
        id: "2",
        expected: "Batch shipped",
        weight: 0.25,
        description: "#1041 note",
      },
    ],
    maxSteps: 35,
    rewardProfile: R8,
    tags: ["multi-step", "multi-entity"],
  },
];
