import type { TaskDefinition } from "@simbench/core";

const R3 = {
  completion: 5.0,
  partialPerCheck: false,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
};
const R5 = {
  completion: 8.0,
  partialPerCheck: true,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
};
const R7 = {
  completion: 10.0,
  partialPerCheck: true,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.2,
};
const R8 = {
  completion: 15.0,
  partialPerCheck: true,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.2,
};

export const productTasks: TaskDefinition[] = [
  // Stage 2 — single field updates
  {
    id: "prod-001",
    site: "shopify-admin",
    domain: "products",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Update product price",
    goal: "Change the price of 'Classic Cotton T-Shirt' from $29.99 to $34.99.",
    evalChecks: [
      {
        type: "state_diff",
        entity: "products",
        id: "1",
        field: "price",
        expected: "34.99",
        weight: 1.0,
        description: "Product 1 price is 34.99",
      },
    ],
    maxSteps: 15,
    rewardProfile: R3,
    tags: ["form-fill"],
  },
  {
    id: "prod-002",
    site: "shopify-admin",
    domain: "products",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Change product status to draft",
    goal: "Set the status of 'Running Sneakers Pro' to Draft.",
    evalChecks: [
      {
        type: "state_diff",
        entity: "products",
        id: "4",
        field: "status",
        expected: "draft",
        weight: 1.0,
        description: "Product 4 status is draft",
      },
    ],
    maxSteps: 15,
    rewardProfile: R3,
    tags: ["form-fill"],
  },
  {
    id: "prod-003",
    site: "shopify-admin",
    domain: "products",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Update product vendor",
    goal: "Change the vendor of 'Canvas Backpack' to 'UrbanPack'.",
    evalChecks: [
      {
        type: "state_diff",
        entity: "products",
        id: "7",
        field: "vendor",
        expected: "UrbanPack",
        weight: 1.0,
        description: "Product 7 vendor is UrbanPack",
      },
    ],
    maxSteps: 15,
    rewardProfile: R3,
    tags: ["form-fill"],
  },
  {
    id: "prod-004",
    site: "shopify-admin",
    domain: "products",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Update product title",
    goal: "Rename 'Slim Fit Jeans' to 'Premium Slim Fit Jeans'.",
    evalChecks: [
      {
        type: "state_diff",
        entity: "products",
        id: "2",
        field: "title",
        expected: "Premium Slim Fit Jeans",
        weight: 1.0,
        description: "Product 2 title updated",
      },
    ],
    maxSteps: 15,
    rewardProfile: R3,
    tags: ["form-fill"],
  },
  {
    id: "prod-005",
    site: "shopify-admin",
    domain: "products",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Update inventory quantity",
    goal: "Set the inventory of 'Polarized Sunglasses' to 200.",
    evalChecks: [
      {
        type: "state_diff",
        entity: "products",
        id: "12",
        field: "inventory",
        expected: 200,
        weight: 1.0,
        description: "Product 12 inventory is 200",
      },
    ],
    maxSteps: 15,
    rewardProfile: R3,
    tags: ["form-fill"],
  },

  // Stage 3 — entity creation
  {
    id: "prod-010",
    site: "shopify-admin",
    domain: "products",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Create a simple product",
    goal: "Create a new product titled 'Bamboo Water Bottle' priced at $24.99 with status 'active'.",
    evalChecks: [
      {
        type: "state_exists",
        entity: "products",
        field: "title",
        expected: "Bamboo Water Bottle",
        weight: 0.5,
        description: "Product exists",
      },
      {
        type: "state_predicate",
        predicate: "product_has_fields",
        entity: "products",
        expected: { title: "Bamboo Water Bottle", price: "24.99", status: "active" },
        weight: 0.5,
        description: "Correct fields",
      },
    ],
    maxSteps: 25,
    rewardProfile: R5,
    tags: ["form-fill", "creation"],
  },
  {
    id: "prod-011",
    site: "shopify-admin",
    domain: "products",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Create product with vendor and type",
    goal: "Create a product: Title='Organic Cotton Tote', Price=$19.99, Vendor='EcoGoods', Type='Accessories', Status='active'.",
    evalChecks: [
      {
        type: "state_exists",
        entity: "products",
        field: "title",
        expected: "Organic Cotton Tote",
        weight: 0.3,
        description: "Product exists",
      },
      {
        type: "state_predicate",
        predicate: "product_has_fields",
        entity: "products",
        expected: { price: "19.99", vendor: "EcoGoods", type: "Accessories" },
        weight: 0.7,
        description: "All fields correct",
      },
    ],
    maxSteps: 30,
    rewardProfile: R5,
    tags: ["form-fill", "creation", "multi-field"],
  },
  {
    id: "prod-012",
    site: "shopify-admin",
    domain: "products",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Create draft product",
    goal: "Create a draft product: Title='Winter Collection Coat', Price=$189.99, Vendor='TrailGear'.",
    evalChecks: [
      {
        type: "state_exists",
        entity: "products",
        field: "title",
        expected: "Winter Collection Coat",
        weight: 0.5,
        description: "Product exists",
      },
      {
        type: "state_predicate",
        predicate: "product_has_fields",
        entity: "products",
        expected: { status: "draft", price: "189.99" },
        weight: 0.5,
        description: "Draft with correct price",
      },
    ],
    maxSteps: 25,
    rewardProfile: R5,
    tags: ["form-fill", "creation"],
  },

  // Stage 5 — multi-field edits
  {
    id: "prod-015",
    site: "shopify-admin",
    domain: "products",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Update multiple product fields",
    goal: "Update 'Wool Blend Sweater': change price to $89.99, vendor to 'PremiumKnits', and status to 'draft'.",
    evalChecks: [
      {
        type: "state_diff",
        entity: "products",
        id: "3",
        field: "price",
        expected: "89.99",
        weight: 0.33,
        description: "Price updated",
      },
      {
        type: "state_diff",
        entity: "products",
        id: "3",
        field: "vendor",
        expected: "PremiumKnits",
        weight: 0.33,
        description: "Vendor updated",
      },
      {
        type: "state_diff",
        entity: "products",
        id: "3",
        field: "status",
        expected: "draft",
        weight: 0.34,
        description: "Status updated",
      },
    ],
    maxSteps: 20,
    rewardProfile: R5,
    tags: ["form-fill", "multi-field"],
  },
  {
    id: "prod-016",
    site: "shopify-admin",
    domain: "products",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Update product description and type",
    goal: "Update 'Leather Weekend Bag': set description to 'Premium full-grain leather travel bag' and type to 'Bags'.",
    evalChecks: [
      {
        type: "state_diff",
        entity: "products",
        id: "5",
        field: "description",
        expected: "Premium full-grain leather travel bag",
        weight: 0.5,
        description: "Description updated",
      },
      {
        type: "state_diff",
        entity: "products",
        id: "5",
        field: "type",
        expected: "Bags",
        weight: 0.5,
        description: "Type updated",
      },
    ],
    maxSteps: 20,
    rewardProfile: R5,
    tags: ["form-fill", "multi-field"],
  },

  // Stage 7 — conditional logic
  {
    id: "prod-020",
    site: "shopify-admin",
    domain: "products",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Archive all draft products",
    goal: "Find all products with status 'draft' and change their status to 'archived'.",
    evalChecks: [
      {
        type: "state_diff",
        entity: "products",
        id: "6",
        field: "status",
        expected: "archived",
        weight: 0.5,
        description: "Product 6 archived",
      },
      {
        type: "state_diff",
        entity: "products",
        id: "11",
        field: "status",
        expected: "archived",
        weight: 0.5,
        description: "Product 11 archived",
      },
    ],
    maxSteps: 30,
    rewardProfile: R7,
    tags: ["conditional", "multi-entity"],
  },
  {
    id: "prod-021",
    site: "shopify-admin",
    domain: "products",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Increase all active product prices by 10%",
    goal: "Increase the price of every active product by 10%. Round to 2 decimal places.",
    evalChecks: [
      {
        type: "state_diff",
        entity: "products",
        id: "1",
        field: "price",
        expected: "32.99",
        weight: 0.11,
        description: "Product 1 price +10%",
      },
      {
        type: "state_diff",
        entity: "products",
        id: "2",
        field: "price",
        expected: "65.99",
        weight: 0.11,
        description: "Product 2 price +10%",
      },
      {
        type: "state_diff",
        entity: "products",
        id: "3",
        field: "price",
        expected: "87.99",
        weight: 0.11,
        description: "Product 3 price +10%",
      },
      {
        type: "state_diff",
        entity: "products",
        id: "4",
        field: "price",
        expected: "131.99",
        weight: 0.11,
        description: "Product 4 price +10%",
      },
      {
        type: "state_diff",
        entity: "products",
        id: "5",
        field: "price",
        expected: "219.99",
        weight: 0.11,
        description: "Product 5 price +10%",
      },
      {
        type: "state_diff",
        entity: "products",
        id: "7",
        field: "price",
        expected: "76.99",
        weight: 0.11,
        description: "Product 7 price +10%",
      },
      {
        type: "state_diff",
        entity: "products",
        id: "8",
        field: "price",
        expected: "27.49",
        weight: 0.11,
        description: "Product 8 price +10%",
      },
      {
        type: "state_diff",
        entity: "products",
        id: "9",
        field: "price",
        expected: "164.99",
        weight: 0.12,
        description: "Product 9 price +10%",
      },
      {
        type: "state_diff",
        entity: "products",
        id: "12",
        field: "price",
        expected: "38.49",
        weight: 0.11,
        description: "Product 12 price +10%",
      },
    ],
    maxSteps: 40,
    rewardProfile: R7,
    tags: ["conditional", "multi-entity", "calculation"],
  },

  // Stage 8 — multi-step same-domain
  {
    id: "prod-025",
    site: "shopify-admin",
    domain: "products",
    type: "action",
    difficulty: "hard",
    curriculumStage: 8,
    title: "Create product and update existing",
    goal: "Create a new product 'Silk Scarf' at $49.99 (active, vendor 'ThreadCo'), then delete the archived product 'Summer Floral Dress'.",
    evalChecks: [
      {
        type: "state_exists",
        entity: "products",
        field: "title",
        expected: "Silk Scarf",
        weight: 0.4,
        description: "New product created",
      },
      {
        type: "state_absent",
        entity: "products",
        id: "10",
        weight: 0.3,
        description: "Archived product deleted",
      },
      {
        type: "state_predicate",
        predicate: "product_exists_with_title",
        expected: "Silk Scarf",
        weight: 0.3,
        description: "Silk Scarf exists",
      },
    ],
    maxSteps: 35,
    rewardProfile: R8,
    tags: ["creation", "deletion", "multi-step"],
  },

  // Additional variety
  {
    id: "prod-006",
    site: "shopify-admin",
    domain: "products",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Archive a product",
    goal: "Set the status of 'Merino Wool Socks (3-Pack)' to 'archived'.",
    evalChecks: [
      {
        type: "state_diff",
        entity: "products",
        id: "8",
        field: "status",
        expected: "archived",
        weight: 1.0,
        description: "Product 8 archived",
      },
    ],
    maxSteps: 15,
    rewardProfile: R3,
    tags: ["form-fill"],
  },
  {
    id: "prod-007",
    site: "shopify-admin",
    domain: "products",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Activate a draft product",
    goal: "Change 'Organic Linen Shirt' from draft to active.",
    evalChecks: [
      {
        type: "state_diff",
        entity: "products",
        id: "6",
        field: "status",
        expected: "active",
        weight: 1.0,
        description: "Product 6 active",
      },
    ],
    maxSteps: 15,
    rewardProfile: R3,
    tags: ["form-fill"],
  },
  {
    id: "prod-008",
    site: "shopify-admin",
    domain: "products",
    type: "action",
    difficulty: "easy",
    curriculumStage: 3,
    title: "Delete a product",
    goal: "Delete the product 'Summer Floral Dress'.",
    evalChecks: [
      {
        type: "state_absent",
        entity: "products",
        id: "10",
        weight: 1.0,
        description: "Product 10 deleted",
      },
    ],
    maxSteps: 15,
    rewardProfile: R3,
    tags: ["deletion"],
  },
  {
    id: "prod-009",
    site: "shopify-admin",
    domain: "products",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Update product description",
    goal: "Set the description of 'Classic Cotton T-Shirt' to 'Premium organic cotton tee, pre-shrunk.'",
    evalChecks: [
      {
        type: "state_diff",
        entity: "products",
        id: "1",
        field: "description",
        expected: "Premium organic cotton tee, pre-shrunk.",
        weight: 1.0,
        description: "Description updated",
      },
    ],
    maxSteps: 15,
    rewardProfile: R3,
    tags: ["form-fill"],
  },
  {
    id: "prod-013",
    site: "shopify-admin",
    domain: "products",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Restock out-of-stock product",
    goal: "Set the inventory of 'Organic Linen Shirt' to 50 and change its status to 'active'.",
    evalChecks: [
      {
        type: "state_diff",
        entity: "products",
        id: "6",
        field: "inventory",
        expected: 50,
        weight: 0.5,
        description: "Inventory set",
      },
      {
        type: "state_diff",
        entity: "products",
        id: "6",
        field: "status",
        expected: "active",
        weight: 0.5,
        description: "Status active",
      },
    ],
    maxSteps: 20,
    rewardProfile: R5,
    tags: ["form-fill", "multi-field"],
  },
  {
    id: "prod-014",
    site: "shopify-admin",
    domain: "products",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Rebrand product vendor and type",
    goal: "Change vendor of ALL 'KnitHouse' products to 'KnitCo' and set their type to 'Knitwear'.",
    evalChecks: [
      {
        type: "state_diff",
        entity: "products",
        id: "3",
        field: "vendor",
        expected: "KnitCo",
        weight: 0.25,
        description: "Product 3 vendor",
      },
      {
        type: "state_diff",
        entity: "products",
        id: "8",
        field: "vendor",
        expected: "KnitCo",
        weight: 0.25,
        description: "Product 8 vendor",
      },
      {
        type: "state_diff",
        entity: "products",
        id: "3",
        field: "type",
        expected: "Knitwear",
        weight: 0.25,
        description: "Product 3 type",
      },
      {
        type: "state_diff",
        entity: "products",
        id: "8",
        field: "type",
        expected: "Knitwear",
        weight: 0.25,
        description: "Product 8 type",
      },
    ],
    maxSteps: 25,
    rewardProfile: R5,
    tags: ["multi-entity", "multi-field"],
  },
  {
    id: "prod-017",
    site: "shopify-admin",
    domain: "products",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Clearance pricing",
    goal: "Set the price of all archived products to $9.99.",
    evalChecks: [
      {
        type: "state_diff",
        entity: "products",
        id: "10",
        field: "price",
        expected: "9.99",
        weight: 1.0,
        description: "Archived product clearance priced",
      },
    ],
    maxSteps: 20,
    rewardProfile: R7,
    tags: ["conditional"],
  },
  {
    id: "prod-018",
    site: "shopify-admin",
    domain: "products",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Create accessory product",
    goal: "Create: Title='Leather Belt', Price=$39.99, Vendor='BagCraft', Type='Accessories', Status='active'.",
    evalChecks: [
      {
        type: "state_exists",
        entity: "products",
        field: "title",
        expected: "Leather Belt",
        weight: 0.5,
        description: "Product exists",
      },
      {
        type: "state_predicate",
        predicate: "product_has_fields",
        entity: "products",
        expected: { price: "39.99", vendor: "BagCraft", type: "Accessories" },
        weight: 0.5,
        description: "Fields correct",
      },
    ],
    maxSteps: 25,
    rewardProfile: R5,
    tags: ["creation", "multi-field"],
  },
  {
    id: "prod-019",
    site: "shopify-admin",
    domain: "products",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Set compare-at prices",
    goal: "Set the compare-at price of 'Running Sneakers Pro' to $149.99 (original price stays $119.99).",
    evalChecks: [
      {
        type: "state_diff",
        entity: "products",
        id: "4",
        field: "compareAtPrice",
        expected: "149.99",
        weight: 0.5,
        description: "Compare price set",
      },
      {
        type: "state_diff",
        entity: "products",
        id: "4",
        field: "price",
        expected: "119.99",
        weight: 0.5,
        description: "Price unchanged",
      },
    ],
    maxSteps: 20,
    rewardProfile: R5,
    tags: ["form-fill"],
  },
  {
    id: "prod-022",
    site: "shopify-admin",
    domain: "products",
    type: "action",
    difficulty: "hard",
    curriculumStage: 8,
    title: "Reorganize vendors",
    goal: "Move all 'ThreadCo' products to vendor 'ThreadCo Premium' and all 'DenimWorks' products to 'DenimWorks Studio'.",
    evalChecks: [
      {
        type: "state_diff",
        entity: "products",
        id: "1",
        field: "vendor",
        expected: "ThreadCo Premium",
        weight: 0.2,
        description: "P1 vendor",
      },
      {
        type: "state_diff",
        entity: "products",
        id: "6",
        field: "vendor",
        expected: "ThreadCo Premium",
        weight: 0.2,
        description: "P6 vendor",
      },
      {
        type: "state_diff",
        entity: "products",
        id: "10",
        field: "vendor",
        expected: "ThreadCo Premium",
        weight: 0.2,
        description: "P10 vendor",
      },
      {
        type: "state_diff",
        entity: "products",
        id: "2",
        field: "vendor",
        expected: "DenimWorks Studio",
        weight: 0.2,
        description: "P2 vendor",
      },
      {
        type: "state_diff",
        entity: "products",
        id: "11",
        field: "vendor",
        expected: "DenimWorks Studio",
        weight: 0.2,
        description: "P11 vendor",
      },
    ],
    maxSteps: 35,
    rewardProfile: R8,
    tags: ["multi-entity", "multi-step"],
  },
  {
    id: "prod-023",
    site: "shopify-admin",
    domain: "products",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Create high-end product",
    goal: "Create: Title='Cashmere Blanket', Price=$299.99, Vendor='KnitHouse', Type='Home', Status='active'.",
    evalChecks: [
      {
        type: "state_exists",
        entity: "products",
        field: "title",
        expected: "Cashmere Blanket",
        weight: 0.5,
        description: "Product exists",
      },
      {
        type: "state_predicate",
        predicate: "product_has_fields",
        entity: "products",
        expected: { price: "299.99", vendor: "KnitHouse" },
        weight: 0.5,
        description: "Fields correct",
      },
    ],
    maxSteps: 25,
    rewardProfile: R5,
    tags: ["creation"],
  },
  {
    id: "prod-024",
    site: "shopify-admin",
    domain: "products",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Low stock alert action",
    goal: "Find all active products with inventory below 50 and set their status to 'draft'.",
    evalChecks: [
      {
        type: "state_diff",
        entity: "products",
        id: "5",
        field: "status",
        expected: "draft",
        weight: 0.2,
        description: "P5 drafted (43 in stock)",
      },
      {
        type: "state_diff",
        entity: "products",
        id: "1",
        field: "status",
        expected: "active",
        weight: 0.1,
        description: "P1 remains active (245 in stock)",
      },
      {
        type: "state_diff",
        entity: "products",
        id: "2",
        field: "status",
        expected: "active",
        weight: 0.1,
        description: "P2 remains active (128 in stock)",
      },
      {
        type: "state_diff",
        entity: "products",
        id: "3",
        field: "status",
        expected: "active",
        weight: 0.1,
        description: "P3 remains active (67 in stock)",
      },
      {
        type: "state_diff",
        entity: "products",
        id: "4",
        field: "status",
        expected: "active",
        weight: 0.1,
        description: "P4 remains active (312 in stock)",
      },
      {
        type: "state_diff",
        entity: "products",
        id: "7",
        field: "status",
        expected: "active",
        weight: 0.1,
        description: "P7 remains active (89 in stock)",
      },
      {
        type: "state_diff",
        entity: "products",
        id: "8",
        field: "status",
        expected: "active",
        weight: 0.1,
        description: "P8 remains active (534 in stock)",
      },
      {
        type: "state_diff",
        entity: "products",
        id: "9",
        field: "status",
        expected: "active",
        weight: 0.1,
        description: "P9 remains active (76 in stock)",
      },
      {
        type: "state_diff",
        entity: "products",
        id: "12",
        field: "status",
        expected: "active",
        weight: 0.1,
        description: "P12 remains active (156 in stock)",
      },
    ],
    maxSteps: 30,
    rewardProfile: R7,
    tags: ["conditional", "multi-entity"],
  },
];
