import type { TaskDefinition } from "@simbench/core";

const R = {
  completion: 5.0,
  partialPerCheck: false,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
};
const RH = {
  completion: 8.0,
  partialPerCheck: false,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.1,
};

export const retrievalTasks: TaskDefinition[] = [
  {
    id: "ret-001",
    site: "shopify-admin",
    domain: "products",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Find product price",
    goal: "What is the price of 'Waterproof Hiking Jacket'?",
    retrievalRubric: {
      question: "Price of Waterproof Hiking Jacket?",
      groundTruth: "$149.99",
      acceptableVariations: ["149.99", "$149.99", "149.99 dollars"],
      rubric: "Agent must find product and report exact price.",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "ret-002",
    site: "shopify-admin",
    domain: "products",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Find product vendor",
    goal: "Who is the vendor of 'Canvas Backpack'?",
    retrievalRubric: {
      question: "Vendor of Canvas Backpack?",
      groundTruth: "BagCraft",
      acceptableVariations: ["bagcraft", "BagCraft"],
      rubric: "Agent must find the vendor field of Canvas Backpack.",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "ret-003",
    site: "shopify-admin",
    domain: "orders",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Find order customer",
    goal: "Who placed order #1038?",
    retrievalRubric: {
      question: "Customer for order #1038?",
      groundTruth: "Ava Thompson",
      acceptableVariations: ["ava thompson", "Ava", "ava.t@example.com"],
      rubric: "Agent must find order #1038 and report the customer name.",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "ret-004",
    site: "shopify-admin",
    domain: "orders",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Find order total",
    goal: "What is the total for order #1036?",
    retrievalRubric: {
      question: "Total for order #1036?",
      groundTruth: "$324.96",
      acceptableVariations: ["324.96", "$324.96"],
      rubric: "Agent must navigate to order #1036 and report the total.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "ret-005",
    site: "shopify-admin",
    domain: "customers",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Find customer location",
    goal: "Where is Mia Davis located?",
    retrievalRubric: {
      question: "Location of Mia Davis?",
      groundTruth: "Toronto, CA",
      acceptableVariations: ["Toronto", "toronto, ca", "Toronto, Canada"],
      rubric: "Agent must find customer and report location.",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "ret-006",
    site: "shopify-admin",
    domain: "customers",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Find top spender",
    goal: "Which customer has spent the most money?",
    retrievalRubric: {
      question: "Top spending customer?",
      groundTruth: "Ava Thompson",
      acceptableVariations: [
        "ava thompson",
        "Ava Thompson - $1,891.42",
        "Ava Thompson ($1,891.42)",
      ],
      rubric: "Agent must compare totalSpent across all customers.",
    },
    evalChecks: [],
    maxSteps: 20,
    rewardProfile: RH,
    tags: ["retrieval", "comparison"],
  },
  {
    id: "ret-007",
    site: "shopify-admin",
    domain: "products",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Count products by vendor",
    goal: "How many products does 'ThreadCo' sell?",
    retrievalRubric: {
      question: "ThreadCo product count?",
      groundTruth: "3",
      acceptableVariations: ["three", "3 products"],
      rubric:
        "ThreadCo products: Classic Cotton T-Shirt, Organic Linen Shirt, Summer Floral Dress = 3.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["retrieval", "counting"],
  },
  {
    id: "ret-008",
    site: "shopify-admin",
    domain: "orders",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Find refunded order",
    goal: "Which order was refunded and what was the total?",
    retrievalRubric: {
      question: "Which order was refunded?",
      groundTruth: "Order #1036 - $324.96",
      acceptableVariations: ["#1036", "1036", "#1036 for $324.96", "Mia Davis order"],
      rubric: "Only order #1036 (Mia Davis) has paymentStatus=refunded, total=$324.96.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "ret-009",
    site: "shopify-admin",
    domain: "discounts",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Find active discount codes",
    goal: "List all active discount codes.",
    retrievalRubric: {
      question: "Active discount codes?",
      groundTruth: "SUMMER20, WELCOME10, VIP25",
      acceptableVariations: [
        "SUMMER20, WELCOME10, VIP25",
        "summer20, welcome10, vip25",
        "Summer Sale 20%, Welcome 10% Off, VIP 25% Discount",
      ],
      rubric:
        "Active code discounts: SUMMER20, WELCOME10, VIP25. Free Shipping Over $100 is automatic (no code).",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "ret-010",
    site: "shopify-admin",
    domain: "products",
    type: "retrieval",
    difficulty: "hard",
    curriculumStage: 6,
    title: "Calculate total inventory value",
    goal: "What is the total value of all inventory? (sum of price * inventory for all products)",
    retrievalRubric: {
      question: "Total inventory value?",
      groundTruth: "$103,513.38",
      acceptableVariations: ["103513.38", "$103,513.38", "103513", "about $103,500"],
      rubric: "Sum each product's price*inventory. 29.99*245 + 59.99*128 + 79.99*67 + 119.99*312 + 199.99*43 + 45.99*0 + 69.99*89 + 24.99*534 + 149.99*76 + 54.99*12 + 39.99*0 + 34.99*156 = $103,513.38",
    },
    evalChecks: [],
    maxSteps: 25,
    rewardProfile: RH,
    tags: ["retrieval", "calculation"],
  },
  {
    id: "ret-011",
    site: "shopify-admin",
    domain: "settings",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Find store currency",
    goal: "What currency is the store using?",
    retrievalRubric: {
      question: "Store currency?",
      groundTruth: "USD",
      acceptableVariations: ["usd", "US Dollar", "US Dollars", "United States Dollar"],
      rubric: "Agent must navigate to settings and report currency.",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "ret-012",
    site: "shopify-admin",
    domain: "orders",
    type: "retrieval",
    difficulty: "hard",
    curriculumStage: 6,
    title: "Find largest order",
    goal: "Which order has the highest total? Report the order number and amount.",
    retrievalRubric: {
      question: "Largest order?",
      groundTruth: "#1036 - $324.96",
      acceptableVariations: [
        "#1036",
        "1036",
        "$324.96",
        "Order #1036 at $324.96",
        "Mia Davis order #1036",
      ],
      rubric: "Order #1036 has the highest total at $324.96.",
    },
    evalChecks: [],
    maxSteps: 20,
    rewardProfile: RH,
    tags: ["retrieval", "comparison"],
  },
  {
    id: "ret-013",
    site: "shopify-admin",
    domain: "products",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Find product status",
    goal: "What is the status of 'Organic Linen Shirt'?",
    retrievalRubric: {
      question: "Status of Organic Linen Shirt?",
      groundTruth: "draft",
      acceptableVariations: ["Draft", "draft"],
      rubric: "Product #6 status is draft.",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "ret-014",
    site: "shopify-admin",
    domain: "customers",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Find customer order count",
    goal: "How many orders has Ava Thompson placed?",
    retrievalRubric: {
      question: "Ava Thompson order count?",
      groundTruth: "15",
      acceptableVariations: ["fifteen", "15 orders"],
      rubric: "Ava Thompson has 15 orders.",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "ret-015",
    site: "shopify-admin",
    domain: "products",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Find out-of-stock products",
    goal: "Which products have 0 inventory?",
    retrievalRubric: {
      question: "Products with 0 inventory?",
      groundTruth: "Organic Linen Shirt, Stretch Chino Shorts",
      acceptableVariations: [
        "Organic Linen Shirt and Stretch Chino Shorts",
        "Stretch Chino Shorts, Organic Linen Shirt",
      ],
      rubric: "Products #6 (inventory=0) and #11 (inventory=0).",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["retrieval", "search"],
  },
];
