import type { TaskDefinition } from "./types";

const R6 = {
  completion: 10.0,
  partialPerCheck: true,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.1,
};

export const searchTasks: TaskDefinition[] = [
  {
    id: "srch-001",
    site: "shopify-admin",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Find cheapest product",
    goal: "Find the cheapest active product and report its name and price.",
    retrievalRubric: {
      question: "What is the cheapest active product?",
      groundTruth: "Merino Wool Socks (3-Pack) - $24.99",
      acceptableVariations: [
        "Merino Wool Socks",
        "merino wool socks (3-pack)",
        "$24.99",
        "24.99",
        "Merino Wool Socks (3-Pack), $24.99",
      ],
      rubric:
        "Agent must identify the cheapest active product by price and report title and price.",
    },
    evalChecks: [],
    maxSteps: 20,
    rewardProfile: R6,
    tags: ["search", "retrieval"],
  },
  {
    id: "srch-002",
    site: "shopify-admin",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Count unfulfilled orders",
    goal: "How many unfulfilled orders are there? Report the count.",
    retrievalRubric: {
      question: "How many unfulfilled orders?",
      groundTruth: "4",
      acceptableVariations: ["four", "4 orders", "4 unfulfilled orders", "There are 4"],
      rubric: "Agent must navigate to orders, count unfulfilled, and report the number.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R6,
    tags: ["search", "retrieval"],
  },
  {
    id: "srch-003",
    site: "shopify-admin",
    domain: "search",
    type: "retrieval",
    difficulty: "hard",
    curriculumStage: 6,
    title: "Find VIP customers",
    goal: "List all customers with the 'vip' tag.",
    retrievalRubric: {
      question: "Which customers have the VIP tag?",
      groundTruth: "Emma Johnson, Liam Chen, Ava Thompson",
      acceptableVariations: [
        "Emma Johnson, Liam Chen, Ava Thompson",
        "Liam Chen, Emma Johnson, Ava Thompson",
        "Emma, Liam, Ava",
      ],
      rubric: "Agent must find all customers tagged 'vip' and list their names.",
    },
    evalChecks: [],
    maxSteps: 25,
    rewardProfile: R6,
    tags: ["search", "retrieval"],
  },
  {
    id: "srch-004",
    site: "shopify-admin",
    domain: "search",
    type: "retrieval",
    difficulty: "hard",
    curriculumStage: 6,
    title: "Calculate total order revenue",
    goal: "What is the total value of all paid, unfulfilled orders?",
    retrievalRubric: {
      question: "Total value of paid unfulfilled orders?",
      groundTruth: "$559.94",
      acceptableVariations: ["559.94", "$559.94", "559.94 dollars"],
      rubric:
        "Agent must find all orders that are paid but unfulfilled (#1042=$149.97, #1041=$259.98, #1033=$149.99) and sum them.",
    },
    evalChecks: [],
    maxSteps: 25,
    rewardProfile: R6,
    tags: ["search", "retrieval", "calculation"],
  },
];
