import type { TaskDefinition } from "@simbench/core";

const R2 = {
  completion: 3.0,
  partialPerCheck: false,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
};
const R5 = {
  completion: 8.0,
  partialPerCheck: true,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
};

export const settingsTasks: TaskDefinition[] = [
  {
    id: "set-001",
    site: "shopify-admin",
    domain: "settings",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Update store name",
    goal: "Change the store name to 'Urban Threads'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "settings_field_equals",
        field: "storeName",
        expected: "Urban Threads",
        weight: 1.0,
        description: "Store name updated",
      },
    ],
    maxSteps: 15,
    rewardProfile: R2,
    tags: ["form-fill"],
  },
  {
    id: "set-002",
    site: "shopify-admin",
    domain: "settings",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Update store email",
    goal: "Change the store contact email to 'hello@urbanthreads.com'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "settings_field_equals",
        field: "email",
        expected: "hello@urbanthreads.com",
        weight: 1.0,
        description: "Email updated",
      },
    ],
    maxSteps: 15,
    rewardProfile: R2,
    tags: ["form-fill"],
  },
  {
    id: "set-003",
    site: "shopify-admin",
    domain: "settings",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Change currency",
    goal: "Change the store currency from USD to EUR.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "settings_field_equals",
        field: "currency",
        expected: "EUR",
        weight: 1.0,
        description: "Currency changed",
      },
    ],
    maxSteps: 15,
    rewardProfile: R2,
    tags: ["form-fill"],
  },
  {
    id: "set-004",
    site: "shopify-admin",
    domain: "settings",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Change weight unit",
    goal: "Change the weight unit from lb to kg.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "settings_field_equals",
        field: "weightUnit",
        expected: "kg",
        weight: 1.0,
        description: "Weight unit changed",
      },
    ],
    maxSteps: 15,
    rewardProfile: R2,
    tags: ["form-fill"],
  },
  {
    id: "set-005",
    site: "shopify-admin",
    domain: "settings",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Update store details",
    goal: "Update store: name='Urban Threads', email='hello@urbanthreads.com', phone='+1 800-555-1234'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "settings_field_equals",
        field: "storeName",
        expected: "Urban Threads",
        weight: 0.33,
        description: "Name",
      },
      {
        type: "state_predicate",
        predicate: "settings_field_equals",
        field: "email",
        expected: "hello@urbanthreads.com",
        weight: 0.33,
        description: "Email",
      },
      {
        type: "state_predicate",
        predicate: "settings_field_equals",
        field: "phone",
        expected: "+1 800-555-1234",
        weight: 0.34,
        description: "Phone",
      },
    ],
    maxSteps: 20,
    rewardProfile: R5,
    tags: ["multi-field", "form-fill"],
  },
];
