import type { TaskDefinition } from "@thetabench/core";

const R5 = { completion: 5.0, partialPerCheck: true, stepPenalty: -0.01, invalidActionPenalty: -0.1 };
const R8 = { completion: 8.0, partialPerCheck: true, stepPenalty: -0.02, invalidActionPenalty: -0.2 };

export const channelTasks: TaskDefinition[] = [
  {
    id: "slack-ch-001",
    site: "slack",
    domain: "channels",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Create a public channel",
    goal: "Create a new public channel named 'q2-launch' with topic 'Q2 product launch coordination'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "channel_exists",
        expected: { name: "q2-launch", type: "public", topic: "Q2 product launch coordination" },
        weight: 1.0,
        description: "q2-launch public channel exists",
      },
    ],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["create", "channel"],
  },
  {
    id: "slack-ch-002",
    site: "slack",
    domain: "channels",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Create a private channel",
    goal: "Create a private channel 'security-review' for the security team.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "channel_exists",
        expected: { name: "security-review", type: "private" },
        weight: 1.0,
        description: "security-review private channel exists",
      },
    ],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["create", "private"],
  },
  {
    id: "slack-ch-003",
    site: "slack",
    domain: "channels",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Rename a channel",
    goal: "Rename channel #hiring (ch-13) to 'recruiting'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "channel_exists",
        expected: { id: "ch-13", name: "recruiting" },
        weight: 1.0,
        description: "ch-13 renamed to recruiting",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["rename"],
  },
  {
    id: "slack-ch-004",
    site: "slack",
    domain: "channels",
    type: "action",
    difficulty: "medium",
    curriculumStage: 4,
    title: "Update channel purpose",
    goal: "Set the purpose of #help-desk (ch-11) to 'Ask and answer questions about dev tools and infra'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "channel_has_purpose",
        id: "ch-11",
        expected: "Ask and answer questions about dev tools and infra",
        weight: 1.0,
        description: "#help-desk purpose updated",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["update"],
  },
  {
    id: "slack-ch-005",
    site: "slack",
    domain: "channels",
    type: "action",
    difficulty: "medium",
    curriculumStage: 4,
    title: "Invite user to channel",
    goal: "Invite Sanjay Gupta (usr-13) to #engineering (ch-4).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "channel_has_member",
        id: "ch-4",
        expected: { userId: "usr-13" },
        weight: 1.0,
        description: "usr-13 added to #engineering",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["invite"],
  },
  {
    id: "slack-ch-006",
    site: "slack",
    domain: "channels",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Remove user from channel",
    goal: "Remove Thomas Weber (usr-14) from #engineering (ch-4).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "channel_member_count",
        id: "ch-4",
        expected: 10,
        weight: 1.0,
        description: "#engineering has 10 members after removal",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["remove"],
  },
  {
    id: "slack-ch-007",
    site: "slack",
    domain: "channels",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Invite three team members",
    goal: "Invite Vikram Singh (usr-7), Meera Nair (usr-8), and Lakshmi Rao (usr-10) to #design (ch-5).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "channel_has_member",
        id: "ch-5",
        expected: { userId: "usr-7" },
        weight: 0.34,
        description: "usr-7 in #design",
      },
      {
        type: "state_predicate",
        predicate: "channel_has_member",
        id: "ch-5",
        expected: { userId: "usr-8" },
        weight: 0.33,
        description: "usr-8 in #design",
      },
      {
        type: "state_predicate",
        predicate: "channel_has_member",
        id: "ch-5",
        expected: { userId: "usr-10" },
        weight: 0.33,
        description: "usr-10 in #design",
      },
    ],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["invite", "multi"],
  },
  {
    id: "slack-ch-008",
    site: "slack",
    domain: "channels",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Archive a channel",
    goal: "Archive channel #hiring (ch-13).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "channel_is_archived",
        id: "ch-13",
        expected: true,
        weight: 1.0,
        description: "#hiring archived",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["archive"],
  },
  {
    id: "slack-ch-009",
    site: "slack",
    domain: "channels",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Unarchive the archived-launch channel",
    goal: "Unarchive #archived-launch (ch-17) to bring it back to active channels.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "channel_is_archived",
        id: "ch-17",
        expected: false,
        weight: 1.0,
        description: "#archived-launch unarchived",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["unarchive"],
  },
  {
    id: "slack-ch-010",
    site: "slack",
    domain: "channels",
    type: "action",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Add bookmark to engineering",
    goal: "Add a bookmark 'Deploy dashboard' with URL 'https://deploy.theta.internal' to #engineering (ch-4).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "channel_has_bookmark",
        id: "ch-4",
        expected: {
          title: "Deploy dashboard",
          url: "https://deploy.theta.internal",
        },
        weight: 1.0,
        description: "New bookmark added",
      },
    ],
    maxSteps: 12,
    rewardProfile: R5,
    tags: ["bookmark"],
  },
  {
    id: "slack-ch-011",
    site: "slack",
    domain: "channels",
    type: "action",
    difficulty: "hard",
    curriculumStage: 6,
    title: "Join a channel",
    goal: "Join the #social channel (ch-14) as the current user.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "channel_has_member",
        id: "ch-14",
        expected: { userId: "usr-1" },
        weight: 1.0,
        description: "usr-1 in #social",
      },
    ],
    maxSteps: 8,
    rewardProfile: R5,
    tags: ["join"],
  },
  {
    id: "slack-ch-012",
    site: "slack",
    domain: "channels",
    type: "action",
    difficulty: "hard",
    curriculumStage: 6,
    title: "Leave a channel",
    goal: "Leave the #random channel (ch-2).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "channel_member_count",
        id: "ch-2",
        expected: 15,
        weight: 1.0,
        description: "#random has 15 members after leaving",
      },
    ],
    maxSteps: 8,
    rewardProfile: R5,
    tags: ["leave"],
  },
  {
    id: "slack-ch-013",
    site: "slack",
    domain: "channels",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Create channel with members",
    goal: "Create a public channel 'mobile-team' with topic 'Mobile app development' and invite Arjun (usr-2), Kiran (usr-5), and Lakshmi (usr-10).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "channel_exists",
        expected: { name: "mobile-team", type: "public" },
        weight: 0.5,
        description: "mobile-team created",
      },
      {
        type: "state_predicate",
        predicate: "channel_member_count",
        id: "mobile-team",
        expected: 4,
        weight: 0.5,
        description: "4 members (creator + 3 invited)",
      },
    ],
    maxSteps: 20,
    rewardProfile: R8,
    tags: ["create", "invite"],
  },
  {
    id: "slack-ch-014",
    site: "slack",
    domain: "channels",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Update multiple channel fields",
    goal: "Update #product (ch-6): topic 'Q2 roadmap & OKRs' and purpose 'Product team hub for planning and reviews'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "channel_has_topic",
        id: "ch-6",
        expected: "Q2 roadmap & OKRs",
        weight: 0.5,
        description: "Topic updated",
      },
      {
        type: "state_predicate",
        predicate: "channel_has_purpose",
        id: "ch-6",
        expected: "Product team hub for planning and reviews",
        weight: 0.5,
        description: "Purpose updated",
      },
    ],
    maxSteps: 15,
    rewardProfile: R8,
    tags: ["update", "multi-field"],
  },
];
