import type { TaskDefinition } from "@thetabench/core";

const R5 = { completion: 5.0, partialPerCheck: true, stepPenalty: -0.01, invalidActionPenalty: -0.1 };
const R8 = { completion: 8.0, partialPerCheck: true, stepPenalty: -0.02, invalidActionPenalty: -0.2 };

export const dmTasks: TaskDefinition[] = [
  {
    id: "slack-dm-001",
    site: "slack",
    domain: "dms",
    type: "action",
    difficulty: "medium",
    curriculumStage: 4,
    title: "Open a 1:1 DM",
    goal: "Open a direct message conversation with Aisha Khan (usr-11).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "dm_exists_with_participants",
        expected: ["usr-1", "usr-11"],
        weight: 1.0,
        description: "DM with usr-11 exists",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["dm", "create"],
  },
  {
    id: "slack-dm-002",
    site: "slack",
    domain: "dms",
    type: "action",
    difficulty: "medium",
    curriculumStage: 4,
    title: "Open a group DM",
    goal: "Open a group direct message with Nikhil (usr-12), Sanjay (usr-13), and Suresh (usr-15).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "dm_exists_with_participants",
        expected: ["usr-1", "usr-12", "usr-13", "usr-15"],
        weight: 1.0,
        description: "Group DM exists",
      },
    ],
    maxSteps: 12,
    rewardProfile: R5,
    tags: ["dm", "group"],
  },
  {
    id: "slack-dm-003",
    site: "slack",
    domain: "dms",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Send DM to Slackbot",
    goal: "Send the message 'help' to Slackbot via dm-4.",
    evalChecks: [
      {
        type: "state_exists",
        entity: "messages",
        field: "text",
        expected: "help",
        weight: 1.0,
        description: "Message 'help' exists",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["dm", "slackbot"],
  },
  {
    id: "slack-dm-004",
    site: "slack",
    domain: "dms",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Mark DM as read",
    goal: "Mark the DM with Ravi Kumar (dm-2) as read.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "read_state_unread_count",
        id: "dm-2",
        expected: { count: 0, userId: "usr-1" },
        weight: 1.0,
        description: "dm-2 unread=0",
      },
    ],
    maxSteps: 8,
    rewardProfile: R5,
    tags: ["dm", "read"],
  },
  {
    id: "slack-dm-005",
    site: "slack",
    domain: "dms",
    type: "action",
    difficulty: "hard",
    curriculumStage: 6,
    title: "Open DM and send first message",
    goal: "Open a DM with Sanjay Gupta (usr-13) and send 'Quick legal question about the new vendor contract.'",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "dm_exists_with_participants",
        expected: ["usr-1", "usr-13"],
        weight: 0.5,
        description: "DM with usr-13 exists",
      },
      {
        type: "state_exists",
        entity: "messages",
        field: "text",
        expected: "Quick legal question about the new vendor contract.",
        weight: 0.5,
        description: "Message sent",
      },
    ],
    maxSteps: 15,
    rewardProfile: R8,
    tags: ["dm", "multi-step"],
  },
  {
    id: "slack-dm-006",
    site: "slack",
    domain: "dms",
    type: "action",
    difficulty: "hard",
    curriculumStage: 6,
    title: "Group DM with leads",
    goal: "Open a group DM with Arjun (usr-2) and Sneha (usr-4), and send 'Sync on release cadence?'",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "dm_exists_with_participants",
        expected: ["usr-1", "usr-2", "usr-4"],
        weight: 0.5,
        description: "Group DM exists",
      },
      {
        type: "state_exists",
        entity: "messages",
        field: "text",
        expected: "Sync on release cadence?",
        weight: 0.5,
        description: "Message sent",
      },
    ],
    maxSteps: 15,
    rewardProfile: R8,
    tags: ["dm", "group", "multi-step"],
  },
];
