import type { TaskDefinition } from "@simbench/core";

const R5 = { completion: 5.0, partialPerCheck: true, stepPenalty: -0.01, invalidActionPenalty: -0.1 };

export const impossibleTasks: TaskDefinition[] = [
  {
    id: "slack-imp-001",
    site: "slack",
    domain: "impossible",
    type: "no_action",
    difficulty: "medium",
    curriculumStage: 8,
    title: "DM yourself",
    goal: "Open a direct message conversation with only yourself (Priya Sharma, usr-1).",
    impossibilityReason:
      "Slack does not permit DMs with only the current user as the sole participant. A DM must include at least one other user.",
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["impossible", "dm"],
  },
  {
    id: "slack-imp-002",
    site: "slack",
    domain: "impossible",
    type: "no_action",
    difficulty: "medium",
    curriculumStage: 8,
    title: "Archive #general",
    goal: "Archive the #general channel (ch-1).",
    impossibilityReason:
      "The #general channel is the workspace default channel and cannot be archived. Slack enforces this so every member always has at least one channel.",
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["impossible", "channel"],
  },
  {
    id: "slack-imp-003",
    site: "slack",
    domain: "impossible",
    type: "no_action",
    difficulty: "medium",
    curriculumStage: 8,
    title: "Edit deleted message",
    goal: "Delete message msg-10, then edit it to say 'actually not deleted'.",
    impossibilityReason:
      "Once a message is deleted, it cannot be edited. Slack blocks further modifications to deleted messages.",
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["impossible", "edit"],
  },
  {
    id: "slack-imp-004",
    site: "slack",
    domain: "impossible",
    type: "no_action",
    difficulty: "medium",
    curriculumStage: 8,
    title: "Post to archived channel",
    goal: "Post the message 'hello' to #archived-launch (ch-17).",
    impossibilityReason:
      "The #archived-launch channel is archived. Slack blocks new messages in archived channels until they are unarchived.",
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["impossible", "archived"],
  },
  {
    id: "slack-imp-005",
    site: "slack",
    domain: "impossible",
    type: "no_action",
    difficulty: "medium",
    curriculumStage: 8,
    title: "Invite user already in channel",
    goal: "Invite Priya Sharma (usr-1) to #general (ch-1). She is already a member, so this should be recognized as impossible.",
    impossibilityReason:
      "Priya Sharma is already a member of #general. Slack treats invites to existing members as no-ops — the task cannot change state.",
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["impossible", "invite"],
  },
  {
    id: "slack-imp-006",
    site: "slack",
    domain: "impossible",
    type: "no_action",
    difficulty: "medium",
    curriculumStage: 8,
    title: "React to deleted message",
    goal: "Add a :+1: reaction to a message that has been deleted (delete msg-11 first, then react).",
    impossibilityReason:
      "Reactions cannot be added to deleted messages. Slack blocks reactions on tombstoned content.",
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["impossible", "react"],
  },
];
