import type { TaskDefinition } from "@thetabench/core"

const R10 = {
  completion: 10.0,
  partialPerCheck: true,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.2,
}
const R15 = {
  completion: 15.0,
  partialPerCheck: true,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.2,
}

export const multiDomainTasks: TaskDefinition[] = [
  {
    id: "slack-multi-001",
    site: "slack",
    domain: "multi-domain",
    type: "action",
    difficulty: "hard",
    curriculumStage: 8,
    title: "Launch project channel",
    goal: "Create a public channel 'project-aurora' with topic 'Aurora redesign'. Invite Sneha (usr-4), Ananya (usr-6), and Meera (usr-8). Then post the first message: 'Welcome — kickoff Wednesday at 10am!'",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "channel_exists",
        expected: {
          name: "project-aurora",
          type: "public",
          topic: "Aurora redesign",
        },
        weight: 0.25,
        description: "project-aurora created",
      },
      {
        type: "state_predicate",
        predicate: "channel_member_count",
        id: "project-aurora",
        expected: 4,
        weight: 0.25,
        description: "4 members (creator + 3 invited)",
      },
      {
        type: "state_predicate",
        predicate: "message_in_channel",
        expected: {
          channelName: "project-aurora",
          text: "Welcome — kickoff Wednesday at 10am!",
          authorId: "usr-1",
        },
        weight: 0.5,
        description: "kickoff message posted",
      },
    ],
    maxSteps: 25,
    rewardProfile: R10,
    tags: ["channel", "invite", "message", "multi-step"],
  },
  {
    id: "slack-multi-002",
    site: "slack",
    domain: "multi-domain",
    type: "action",
    difficulty: "hard",
    curriculumStage: 8,
    title: "Incident response flow",
    goal: "In #incidents (ch-12), post 'INC-043 — payment gateway latency spike', add :fire: reaction to your message, and reply in thread with 'Investigating now'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "message_in_channel",
        expected: {
          channelId: "ch-12",
          text: "INC-043 — payment gateway latency spike",
          authorId: "usr-1",
        },
        weight: 0.5,
        description: "INC-043 posted",
      },
      {
        type: "state_exists",
        entity: "messages",
        field: "text",
        expected: "Investigating now",
        weight: 0.5,
        description: "Thread reply posted",
      },
    ],
    maxSteps: 25,
    rewardProfile: R10,
    tags: ["multi-step", "incidents"],
  },
  {
    id: "slack-multi-003",
    site: "slack",
    domain: "multi-domain",
    type: "action",
    difficulty: "hard",
    curriculumStage: 9,
    title: "Set status and DM",
    goal: "Update your own status to emoji ':spiral_calendar:' with text 'In meetings until 3pm'. Then open a DM with Meera Nair (usr-8) and send 'Will review after meetings.'",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "user_has_status",
        id: "usr-1",
        expected: { emoji: ":spiral_calendar:", text: "In meetings until 3pm" },
        weight: 0.5,
        description: "Status updated",
      },
      {
        type: "state_predicate",
        predicate: "dm_exists_with_participants",
        expected: ["usr-1", "usr-8"],
        weight: 0.2,
        description: "DM with Meera exists",
      },
      {
        type: "state_exists",
        entity: "messages",
        field: "text",
        expected: "Will review after meetings.",
        weight: 0.3,
        description: "Message sent",
      },
    ],
    maxSteps: 25,
    rewardProfile: R10,
    tags: ["status", "dm", "multi-step"],
  },
  {
    id: "slack-multi-004",
    site: "slack",
    domain: "multi-domain",
    type: "action",
    difficulty: "hard",
    curriculumStage: 9,
    title: "Pin and invite workflow",
    goal: "Post the message 'Team norms document — please read' to #general, pin it, and invite Sanjay (usr-13) to #engineering.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "message_in_channel",
        expected: {
          channelId: "ch-1",
          text: "Team norms document — please read",
          authorId: "usr-1",
        },
        weight: 0.4,
        description: "Message posted",
      },
      {
        type: "state_predicate",
        predicate: "channel_has_pin_count",
        id: "ch-1",
        expected: 3,
        weight: 0.3,
        description: "#general has 3 pinned messages",
      },
      {
        type: "state_predicate",
        predicate: "channel_has_member",
        id: "ch-4",
        expected: { userId: "usr-13" },
        weight: 0.3,
        description: "usr-13 in #engineering",
      },
    ],
    maxSteps: 25,
    rewardProfile: R10,
    tags: ["message", "pin", "invite"],
  },
  {
    id: "slack-multi-005",
    site: "slack",
    domain: "multi-domain",
    type: "action",
    difficulty: "expert",
    curriculumStage: 10,
    title: "Cross-domain ship announcement",
    goal: "Create a user group 'ship-crew' with members usr-1, usr-2, usr-3, usr-5. Create a new canvas 'Ship Checklist' in #engineering with content '# Ship Checklist\\n- Review PR\\n- Tag release\\n- Announce'. Post 'Ship day is Thursday! @ship-crew' to #announcements.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "user_group_exists",
        expected: {
          handle: "ship-crew",
          memberIds: ["usr-1", "usr-2", "usr-3", "usr-5"],
        },
        weight: 0.34,
        description: "ship-crew user group created",
      },
      {
        type: "state_predicate",
        predicate: "canvas_exists",
        expected: { title: "Ship Checklist", channelId: "ch-4" },
        weight: 0.33,
        description: "Ship Checklist canvas created",
      },
      {
        type: "state_predicate",
        predicate: "message_in_channel",
        expected: {
          channelId: "ch-3",
          text: "Ship day is Thursday! @ship-crew",
          authorId: "usr-1",
        },
        weight: 0.33,
        description: "Announcement posted",
      },
    ],
    maxSteps: 35,
    rewardProfile: R15,
    tags: ["multi-step", "cross-domain", "expert"],
  },
  {
    id: "slack-multi-006",
    site: "slack",
    domain: "multi-domain",
    type: "action",
    difficulty: "expert",
    curriculumStage: 10,
    title: "Huddle + pin + thread",
    goal: "Start a huddle in #engineering (ch-4) with topic 'Rate limit debug'. Pin message msg-42 to the channel. Reply to the v2.3.0 thread (msg-44) with 'Starting a huddle to debug edge cases.'",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "huddle_is_active",
        expected: { channelId: "ch-4" },
        weight: 0.34,
        description: "Active huddle in #engineering",
      },
      {
        type: "state_predicate",
        predicate: "channel_has_pin_count",
        id: "ch-4",
        expected: 2,
        weight: 0.33,
        description: "#engineering has 2 pins",
      },
      {
        type: "state_predicate",
        predicate: "thread_reply_count",
        id: "msg-44",
        expected: { count: 5 },
        weight: 0.33,
        description: "msg-44 has 5 replies",
      },
    ],
    maxSteps: 35,
    rewardProfile: R15,
    tags: ["multi-step", "huddle", "pin", "thread"],
  },
]
