import type { TaskDefinition } from "@thetabench/core";

const R2 = { completion: 2.0, partialPerCheck: false, stepPenalty: -0.01, invalidActionPenalty: -0.1 };

export const navigationTasks: TaskDefinition[] = [
  {
    id: "slack-nav-001",
    site: "slack",
    domain: "navigation",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 1,
    title: "Navigate to #general",
    goal: "Navigate to the #general channel and describe what you see.",
    retrievalRubric: {
      question: "What is the topic of #general?",
      groundTruth: "Company-wide announcements and work-based matters",
      acceptableVariations: [
        "company-wide announcements",
        "announcements",
        "team-wide communication",
      ],
      rubric: "#general channel topic",
    },
    evalChecks: [],
    maxSteps: 8,
    rewardProfile: R2,
    tags: ["navigation"],
  },
  {
    id: "slack-nav-002",
    site: "slack",
    domain: "navigation",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 1,
    title: "Navigate to threads page",
    goal: "Navigate to the Threads page and report the count of active threads you have replied to or been mentioned in.",
    retrievalRubric: {
      question: "How many threads?",
      groundTruth: "1",
      acceptableVariations: ["1", "one", "a single thread"],
      rubric: "Count of threads in the viewer's thread inbox",
    },
    evalChecks: [],
    maxSteps: 8,
    rewardProfile: R2,
    tags: ["navigation", "threads"],
  },
  {
    id: "slack-nav-003",
    site: "slack",
    domain: "navigation",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 1,
    title: "Navigate to mentions",
    goal: "Navigate to the Mentions page and report how many unread mentions you have.",
    retrievalRubric: {
      question: "How many unread mentions?",
      groundTruth: "3",
      acceptableVariations: ["3", "three"],
      rubric: "Unread mention count for usr-1",
    },
    evalChecks: [],
    maxSteps: 8,
    rewardProfile: R2,
    tags: ["navigation", "mentions"],
  },
  {
    id: "slack-nav-004",
    site: "slack",
    domain: "navigation",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 1,
    title: "Navigate to DMs",
    goal: "Navigate to the Direct messages page and report how many DM conversations you have.",
    retrievalRubric: {
      question: "DM count?",
      groundTruth: "8",
      acceptableVariations: ["8", "eight"],
      rubric: "Total DMs in the workspace",
    },
    evalChecks: [],
    maxSteps: 8,
    rewardProfile: R2,
    tags: ["navigation", "dms"],
  },
  {
    id: "slack-nav-005",
    site: "slack",
    domain: "navigation",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 1,
    title: "Navigate to people directory",
    goal: "Navigate to the People directory and report how many members the workspace has.",
    retrievalRubric: {
      question: "How many members in Theta HQ?",
      groundTruth: "16",
      acceptableVariations: ["16", "sixteen", "15 humans and slackbot"],
      rubric: "Member count including slackbot",
    },
    evalChecks: [],
    maxSteps: 8,
    rewardProfile: R2,
    tags: ["navigation", "people"],
  },
  {
    id: "slack-nav-006",
    site: "slack",
    domain: "navigation",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 1,
    title: "Navigate to Later",
    goal: "Navigate to the Later page and report how many items you have saved.",
    retrievalRubric: {
      question: "Saved items count?",
      groundTruth: "4",
      acceptableVariations: ["4", "four"],
      rubric: "Saved items for usr-1",
    },
    evalChecks: [],
    maxSteps: 8,
    rewardProfile: R2,
    tags: ["navigation", "saved"],
  },
];
