import type { TaskDefinition } from "@thetabench/core";

const R2 = { completion: 2.0, partialPerCheck: false, stepPenalty: -0.01, invalidActionPenalty: -0.1 };
const R5 = { completion: 5.0, partialPerCheck: true, stepPenalty: -0.01, invalidActionPenalty: -0.1 };

export const reactionTasks: TaskDefinition[] = [
  {
    id: "slack-rxn-001",
    site: "slack",
    domain: "reactions",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "React with thumbs up",
    goal: "Add a :+1: reaction to message msg-32 (PLT-102 refresh token rotation PR).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "message_has_reaction",
        id: "msg-32",
        expected: { emoji: ":+1:", userId: "usr-1" },
        weight: 1.0,
        description: "usr-1 reacted with :+1:",
      },
    ],
    maxSteps: 8,
    rewardProfile: R2,
    tags: ["react"],
  },
  {
    id: "slack-rxn-002",
    site: "slack",
    domain: "reactions",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "React with rocket",
    goal: "Add a :rocket: reaction to msg-38 (cluster upgrade complete).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "message_has_reaction",
        id: "msg-38",
        expected: { emoji: ":rocket:", userId: "usr-1" },
        weight: 1.0,
        description: "usr-1 reacted with :rocket:",
      },
    ],
    maxSteps: 8,
    rewardProfile: R2,
    tags: ["react"],
  },
  {
    id: "slack-rxn-003",
    site: "slack",
    domain: "reactions",
    type: "action",
    difficulty: "easy",
    curriculumStage: 3,
    title: "Remove a reaction",
    goal: "Remove the :eyes: reaction from message msg-1 (your own reaction if present, or add it first then remove it).",
    evalChecks: [
      {
        type: "state_exists",
        entity: "messages",
        field: "id",
        expected: "msg-1",
        weight: 0.1,
        description: "msg-1 exists",
      },
    ],
    maxSteps: 10,
    rewardProfile: R2,
    tags: ["react", "remove"],
  },
  {
    id: "slack-rxn-004",
    site: "slack",
    domain: "reactions",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "React with multiple emojis",
    goal: "Add :tada: and :fire: reactions to msg-44 (v2.3.0 announcement).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "message_has_reaction",
        id: "msg-44",
        expected: { emoji: ":tada:", userId: "usr-1" },
        weight: 0.5,
        description: ":tada: reaction",
      },
      {
        type: "state_predicate",
        predicate: "message_has_reaction",
        id: "msg-44",
        expected: { emoji: ":fire:", userId: "usr-1" },
        weight: 0.5,
        description: ":fire: reaction",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["react", "multi"],
  },
  {
    id: "slack-rxn-005",
    site: "slack",
    domain: "reactions",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "React to a DM",
    goal: "Add :heart: reaction to message msg-152 (Priya's approval in dm-1).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "message_has_reaction",
        id: "msg-152",
        expected: { emoji: ":heart:", userId: "usr-1" },
        weight: 1.0,
        description: ":heart: on msg-152",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["react", "dm"],
  },
  {
    id: "slack-rxn-006",
    site: "slack",
    domain: "reactions",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Verify reaction count",
    goal: "Add :+1: reaction to msg-44 so the total :+1: count becomes 6.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "message_reaction_count",
        id: "msg-44",
        expected: { emoji: ":+1:", count: 6 },
        weight: 1.0,
        description: "msg-44 has 6 :+1: reactions",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["react", "count"],
  },
];
