import type { TaskDefinition } from "@simbench/core";

const R2 = { completion: 2.0, partialPerCheck: false, stepPenalty: -0.01, invalidActionPenalty: -0.1 };
const R5 = { completion: 5.0, partialPerCheck: true, stepPenalty: -0.01, invalidActionPenalty: -0.1 };

export const retrievalTasks: TaskDefinition[] = [
  {
    id: "slack-ret-001",
    site: "slack",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Topic of #engineering",
    goal: "What is the topic of the #engineering channel?",
    retrievalRubric: {
      question: "#engineering topic",
      groundTruth: "Engineering org discussions, PR reviews, and incident response",
      acceptableVariations: [
        "engineering discussions",
        "PR reviews",
        "incident response",
      ],
      rubric: "ch-4 topic string",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R2,
    tags: ["retrieval"],
  },
  {
    id: "slack-ret-002",
    site: "slack",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Number of DMs with Priya",
    goal: "How many direct message conversations (including group DMs) does Priya Sharma participate in?",
    retrievalRubric: {
      question: "DMs containing usr-1",
      groundTruth: "7",
      acceptableVariations: ["7", "seven"],
      rubric: "DMs with usr-1 as participant (all except dm-5)",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R2,
    tags: ["retrieval"],
  },
  {
    id: "slack-ret-003",
    site: "slack",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 3,
    title: "CESS ID of Priya Sharma",
    goal: "What is the CESS ID of Priya Sharma?",
    retrievalRubric: {
      question: "Priya's CESS ID",
      groundTruth: "SU001",
      acceptableVariations: ["SU001", "su001"],
      rubric: "usr-1 cessId",
    },
    evalChecks: [],
    maxSteps: 8,
    rewardProfile: R2,
    tags: ["retrieval", "user"],
  },
  {
    id: "slack-ret-004",
    site: "slack",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 3,
    title: "Number of channels in workspace",
    goal: "How many channels exist in the Theta HQ workspace (including archived ones)?",
    retrievalRubric: {
      question: "Total channels count",
      groundTruth: "18",
      acceptableVariations: ["18", "eighteen"],
      rubric: "channels array length",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R2,
    tags: ["retrieval"],
  },
  {
    id: "slack-ret-005",
    site: "slack",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 3,
    title: "User title lookup",
    goal: "What is Sneha Reddy's job title?",
    retrievalRubric: {
      question: "Sneha's title",
      groundTruth: "Design Lead",
      acceptableVariations: ["Design Lead", "Head of Design", "design lead"],
      rubric: "usr-4 title",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["retrieval", "user"],
  },
  {
    id: "slack-ret-006",
    site: "slack",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 4,
    title: "Pinned runbook in engineering",
    goal: "What is pinned in #engineering?",
    retrievalRubric: {
      question: "Pinned in #engineering",
      groundTruth: "runbook link https://runbooks.theta.internal/oncall",
      acceptableVariations: ["runbook", "oncall runbook", "msg-41"],
      rubric: "msg-41 pinned content",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["retrieval", "pinned"],
  },
  {
    id: "slack-ret-007",
    site: "slack",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 4,
    title: "Design channel member count",
    goal: "How many members are in the #design channel?",
    retrievalRubric: {
      question: "Members in #design",
      groundTruth: "6",
      acceptableVariations: ["6", "six"],
      rubric: "ch-5 memberIds length",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["retrieval", "count"],
  },
  {
    id: "slack-ret-008",
    site: "slack",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Slack Connect channel",
    goal: "Which channel is shared with an external workspace via Slack Connect?",
    retrievalRubric: {
      question: "Slack Connect channel",
      groundTruth: "#theta-external-connect",
      acceptableVariations: [
        "theta-external-connect",
        "#theta-external-connect",
        "ch-18",
      ],
      rubric: "ch-18 isShared true",
    },
    evalChecks: [],
    maxSteps: 12,
    rewardProfile: R5,
    tags: ["retrieval", "connect"],
  },
  {
    id: "slack-ret-009",
    site: "slack",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Engineering runbook canvas",
    goal: "Which canvas is attached to #engineering?",
    retrievalRubric: {
      question: "Canvas attached to #engineering",
      groundTruth: "Engineering Runbook",
      acceptableVariations: ["Engineering Runbook", "runbook", "canvas-2"],
      rubric: "ch-4 canvasId → canvas-2 title",
    },
    evalChecks: [],
    maxSteps: 12,
    rewardProfile: R5,
    tags: ["retrieval", "canvas"],
  },
  {
    id: "slack-ret-010",
    site: "slack",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Bug tracker list",
    goal: "In which channel is the 'Bug Tracker' list attached?",
    retrievalRubric: {
      question: "Bug Tracker list channel",
      groundTruth: "#engineering",
      acceptableVariations: ["#engineering", "engineering", "ch-4"],
      rubric: "list-1 channelId",
    },
    evalChecks: [],
    maxSteps: 12,
    rewardProfile: R5,
    tags: ["retrieval", "list"],
  },
];
