import type { TaskDefinition } from "@simbench/core";

const R5 = { completion: 5.0, partialPerCheck: true, stepPenalty: -0.01, invalidActionPenalty: -0.1 };
const R8 = { completion: 8.0, partialPerCheck: true, stepPenalty: -0.02, invalidActionPenalty: -0.2 };

export const searchTasks: TaskDefinition[] = [
  {
    id: "slack-srch-001",
    site: "slack",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Find v2.3.0 announcement author",
    goal: "Who posted the message about the v2.3.0 release? Reply with their full name.",
    retrievalRubric: {
      question: "Author of v2.3.0 release announcement",
      groundTruth: "Priya Sharma",
      acceptableVariations: ["Priya Sharma", "priya", "usr-1", "Priya"],
      rubric: "msg-44 authored by usr-1 Priya Sharma",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["search", "retrieval"],
  },
  {
    id: "slack-srch-002",
    site: "slack",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Count messages by Arjun",
    goal: "How many top-level messages has Arjun Patel (usr-2) posted in #engineering (ch-4)?",
    retrievalRubric: {
      question: "Arjun's top-level messages in #engineering",
      groundTruth: "4",
      acceptableVariations: ["4", "four"],
      rubric: "Count of messages where authorId=usr-2 and channelId=ch-4 and threadRootId is null",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["search", "count"],
  },
  {
    id: "slack-srch-003",
    site: "slack",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Find incident channel",
    goal: "What channel is used for incident response coordination?",
    retrievalRubric: {
      question: "Channel for incidents",
      groundTruth: "#incidents",
      acceptableVariations: ["#incidents", "incidents", "ch-12"],
      rubric: "ch-12 named 'incidents'",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["search", "channel"],
  },
  {
    id: "slack-srch-004",
    site: "slack",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Find pinned messages in #general",
    goal: "How many messages are pinned in #general?",
    retrievalRubric: {
      question: "Pinned messages in #general",
      groundTruth: "2",
      acceptableVariations: ["2", "two"],
      rubric: "ch-1 pinnedMessageIds length",
    },
    evalChecks: [],
    maxSteps: 12,
    rewardProfile: R5,
    tags: ["search", "pinned"],
  },
  {
    id: "slack-srch-005",
    site: "slack",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Find channel with most members",
    goal: "Which public channel has the most members? Reply with the channel name.",
    retrievalRubric: {
      question: "Channel with most members",
      groundTruth: "general",
      acceptableVariations: ["general", "#general", "ch-1"],
      rubric: "general channel includes all 16 members",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["search", "channel"],
  },
  {
    id: "slack-srch-006",
    site: "slack",
    domain: "search",
    type: "retrieval",
    difficulty: "hard",
    curriculumStage: 6,
    title: "Find OAuth PR message",
    goal: "Find the message mentioning 'PLT-101 (OAuth2 PKCE flow) merged'. Who posted it and in which channel?",
    retrievalRubric: {
      question: "Author and channel of OAuth PR message",
      groundTruth: "Arjun Patel in #engineering",
      acceptableVariations: [
        "Arjun in #engineering",
        "usr-2 #engineering",
        "Arjun Patel #engineering",
      ],
      rubric: "msg-31 by usr-2 in ch-4",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R8,
    tags: ["search", "message"],
  },
  {
    id: "slack-srch-007",
    site: "slack",
    domain: "search",
    type: "retrieval",
    difficulty: "hard",
    curriculumStage: 6,
    title: "Count members of engineering team channel",
    goal: "How many members are in #platform-team (ch-7)?",
    retrievalRubric: {
      question: "Members in #platform-team",
      groundTruth: "9",
      acceptableVariations: ["9", "nine"],
      rubric: "ch-7 memberIds length",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R8,
    tags: ["search", "count"],
  },
  {
    id: "slack-srch-008",
    site: "slack",
    domain: "search",
    type: "retrieval",
    difficulty: "hard",
    curriculumStage: 6,
    title: "Find user on vacation",
    goal: "Which user has a 'palm_tree' status indicating vacation?",
    retrievalRubric: {
      question: "User with palm_tree status",
      groundTruth: "Ananya Gupta",
      acceptableVariations: ["Ananya", "Ananya Gupta", "usr-6"],
      rubric: "usr-6 has :palm_tree: 'On vacation until Monday' status",
    },
    evalChecks: [],
    maxSteps: 12,
    rewardProfile: R8,
    tags: ["search", "status"],
  },
];
