import type { TaskDefinition } from "@thetabench/core"

const R2 = {
  completion: 2.0,
  partialPerCheck: false,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
}
const R5 = {
  completion: 5.0,
  partialPerCheck: true,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
}

export const customerTasks: TaskDefinition[] = [
  {
    id: "plain-cus-001",
    site: "plain",
    domain: "customers",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Update customer role",
    goal: "Update customer cus-7 (Mei Tanaka) — change their role to 'Founding Engineer'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "customer_has_fields",
        id: "cus-7",
        expected: { role: "Founding Engineer" },
        weight: 1.0,
        description: "cus-7 has updated role",
      },
    ],
    maxSteps: 8,
    rewardProfile: R2,
    tags: ["form-fill", "customers"],
  },
  {
    id: "plain-cus-002",
    site: "plain",
    domain: "customers",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Move lifecycle stage to active",
    goal: "Customer cus-13 (Omar El-Sayed) just renewed — move their lifecycle stage from 'at_risk' to 'active'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "customer_has_fields",
        id: "cus-13",
        expected: { lifecycleStage: "active" },
        weight: 1.0,
        description: "cus-13 lifecycle = active",
      },
    ],
    maxSteps: 8,
    rewardProfile: R2,
    tags: ["form-fill", "customers"],
  },
  {
    id: "plain-cus-003",
    site: "plain",
    domain: "customers",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 3,
    title: "Find customer by email",
    goal: "Look up the customer whose email is 'naomi@northwind.studio' and report their full name.",
    retrievalRubric: {
      question: "Who is naomi@northwind.studio?",
      groundTruth: "Naomi Chen",
      acceptableVariations: ["Naomi Chen", "naomi chen", "cus-3"],
      rubric: "naomi@northwind.studio is Naomi Chen (cus-3, founder).",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R2,
    tags: ["retrieval", "customers"],
  },
  {
    id: "plain-cus-004",
    site: "plain",
    domain: "customers",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 4,
    title: "Count customer threads",
    goal: "How many threads has customer cus-15 (Marcus Webb) opened?",
    retrievalRubric: {
      question: "How many threads from cus-15?",
      groundTruth: "2",
      acceptableVariations: ["2", "2 threads", "two"],
      rubric:
        "Marcus Webb (cus-15) is the customer on thr-11 and thr-25 — 2 threads.",
    },
    evalChecks: [],
    maxSteps: 12,
    rewardProfile: R5,
    tags: ["retrieval", "customers"],
  },
  {
    id: "plain-cus-005",
    site: "plain",
    domain: "customers",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 3,
    title: "Customer plan lookup",
    goal: "What plan tier is customer cus-9 (Amara Okeke) on?",
    retrievalRubric: {
      question: "Plan of cus-9?",
      groundTruth: "enterprise",
      acceptableVariations: ["enterprise", "Enterprise"],
      rubric: "Amara Okeke (cus-9) is on the enterprise plan.",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R2,
    tags: ["retrieval", "customers"],
  },
  {
    id: "plain-cus-006",
    site: "plain",
    domain: "customers",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Add custom attribute",
    goal: "Add the custom attribute 'churnRisk' = 'low' to customer cus-13 (Omar El-Sayed).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "customer_has_attribute",
        id: "cus-13",
        field: "churnRisk",
        expected: "low",
        weight: 1.0,
        description: "cus-13 customAttributes.churnRisk = low",
      },
    ],
    maxSteps: 12,
    rewardProfile: R5,
    tags: ["customers", "custom-fields"],
  },
  {
    id: "plain-cus-007",
    site: "plain",
    domain: "customers",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Merge duplicate customers",
    goal: "Merge customer cus-20 (River Henson) into cus-11 (Yuki Sato) — they're co-founders sharing the same workspace and got duplicated.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "customer_does_not_exist",
        id: "cus-20",
        weight: 1.0,
        description: "cus-20 was merged away",
      },
    ],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["customers", "merge"],
  },
  {
    id: "plain-cus-008",
    site: "plain",
    domain: "customers",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 4,
    title: "List threads for a customer",
    goal: "List the IDs of all threads opened by customer cus-2 (Rahul Iyer of MegaCorp).",
    retrievalRubric: {
      question: "Thread IDs for cus-2?",
      groundTruth: "thr-1, thr-16",
      acceptableVariations: ["thr-1, thr-16", "thr-1 and thr-16", "2 threads"],
      rubric: "Rahul Iyer (cus-2) opened thr-1 and thr-16.",
    },
    evalChecks: [],
    maxSteps: 12,
    rewardProfile: R5,
    tags: ["retrieval", "customers"],
  },
]
