import type { TaskDefinition } from "@thetabench/core"

const R2 = {
  completion: 2.0,
  partialPerCheck: false,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
}
const R5 = {
  completion: 5.0,
  partialPerCheck: false,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
}

export const labelTasks: TaskDefinition[] = [
  {
    id: "plain-lbl-001",
    site: "plain",
    domain: "labels",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Add label to a thread",
    goal: "Add the 'billing' label (lbl-2) to thread thr-20 ('Billing: switching from monthly to annual').",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "thread_has_label",
        id: "thr-20",
        expected: "lbl-2",
        weight: 1.0,
        description: "thr-20 has billing label",
      },
    ],
    maxSteps: 8,
    rewardProfile: R2,
    tags: ["form-fill", "labels"],
  },
  {
    id: "plain-lbl-002",
    site: "plain",
    domain: "labels",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Remove a misapplied label",
    goal: "Remove the 'urgent' label (lbl-5) from thread thr-1 ('Webhook failing on org_megacorp'). The customer downgraded the severity.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "thread_lacks_label",
        id: "thr-1",
        expected: "lbl-5",
        weight: 1.0,
        description: "thr-1 no longer has urgent label",
      },
    ],
    maxSteps: 8,
    rewardProfile: R2,
    tags: ["form-fill", "labels"],
  },
  {
    id: "plain-lbl-003",
    site: "plain",
    domain: "labels",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Tag a feature request",
    goal: "Add the 'feature-request' label (lbl-3) to thread thr-22 ('Snooze: \\'until next monday\\' off by one day').",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "thread_has_label",
        id: "thr-22",
        expected: "lbl-3",
        weight: 1.0,
        description: "thr-22 has feature-request label",
      },
    ],
    maxSteps: 8,
    rewardProfile: R5,
    tags: ["labels"],
  },
  {
    id: "plain-lbl-004",
    site: "plain",
    domain: "labels",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 4,
    title: "Find all webhook-tagged threads",
    goal: "How many threads have the 'webhook' label (lbl-10)?",
    retrievalRubric: {
      question: "Number of threads with the webhook label?",
      groundTruth: "5",
      acceptableVariations: ["5", "5 threads", "five"],
      rubric:
        "Threads thr-1, thr-11, thr-16, thr-19, thr-25 carry the webhook label.",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["retrieval", "labels"],
  },
  {
    id: "plain-lbl-005",
    site: "plain",
    domain: "labels",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Replace label set",
    goal: "Update thread thr-15: replace its labels so it has only 'bug' (lbl-1) and 'integration' (lbl-9).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "thread_label_set_equals",
        id: "thr-15",
        expected: ["lbl-1", "lbl-9"],
        weight: 1.0,
        description: "thr-15 labels are exactly bug + integration",
      },
    ],
    maxSteps: 12,
    rewardProfile: R5,
    tags: ["labels", "multi-field"],
  },
]
