import type { TaskDefinition } from "@thetabench/core"

const R = {
  completion: 2.0,
  partialPerCheck: false,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
}

export const navigationTasks: TaskDefinition[] = [
  {
    id: "plain-nav-001",
    site: "plain",
    domain: "navigation",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 1,
    title: "Open the Inbox",
    goal: "Navigate to the workspace Inbox and report how many open threads are visible.",
    retrievalRubric: {
      question: "How many threads are open in the inbox?",
      groundTruth: "18",
      acceptableVariations: ["18", "18 threads", "eighteen"],
      rubric: "There are 18 threads in 'open' status across the workspace.",
    },
    evalChecks: [],
    maxSteps: 5,
    rewardProfile: R,
    tags: ["navigation"],
  },
  {
    id: "plain-nav-002",
    site: "plain",
    domain: "navigation",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 1,
    title: "Navigate to Snoozed",
    goal: "Switch the workspace view to Snoozed and report the count.",
    retrievalRubric: {
      question: "How many snoozed threads exist?",
      groundTruth: "3",
      acceptableVariations: ["3", "3 threads", "three"],
      rubric: "There are 3 snoozed threads (thr-7, thr-12, thr-23).",
    },
    evalChecks: [],
    maxSteps: 5,
    rewardProfile: R,
    tags: ["navigation"],
  },
  {
    id: "plain-nav-003",
    site: "plain",
    domain: "navigation",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 1,
    title: "Navigate to Done",
    goal: "Switch the workspace view to Done and report the count of done threads.",
    retrievalRubric: {
      question: "How many threads have status 'done'?",
      groundTruth: "4",
      acceptableVariations: ["4", "4 threads", "four"],
      rubric: "There are 4 done threads (thr-5, thr-9, thr-17, thr-24).",
    },
    evalChecks: [],
    maxSteps: 5,
    rewardProfile: R,
    tags: ["navigation"],
  },
  {
    id: "plain-nav-004",
    site: "plain",
    domain: "navigation",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 1,
    title: "Open a specific thread",
    goal: "Open thread thr-1 ('Webhook failing on org_megacorp') and report the customer's company.",
    retrievalRubric: {
      question: "Which company does the thr-1 customer belong to?",
      groundTruth: "MegaCorp",
      acceptableVariations: ["MegaCorp", "megacorp", "tnt-1"],
      rubric: "thr-1 is opened by Rahul Iyer from MegaCorp (tnt-1).",
    },
    evalChecks: [],
    maxSteps: 5,
    rewardProfile: R,
    tags: ["navigation"],
  },
  {
    id: "plain-nav-005",
    site: "plain",
    domain: "navigation",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 1,
    title: "Open the Customers list",
    goal: "Open the Customers view and report the total number of customers in the workspace.",
    retrievalRubric: {
      question: "How many customers are in the workspace?",
      groundTruth: "20",
      acceptableVariations: ["20", "20 customers", "twenty"],
      rubric: "There are 20 customers seeded across 8 tenants.",
    },
    evalChecks: [],
    maxSteps: 5,
    rewardProfile: R,
    tags: ["navigation"],
  },
]
