import type { TaskDefinition } from "@thetabench/core"

const R = {
  completion: 5.0,
  partialPerCheck: false,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
}

export const retrievalTasks: TaskDefinition[] = [
  {
    id: "plain-ret-001",
    site: "plain",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Thread title lookup",
    goal: "What is the title of thread thr-7?",
    retrievalRubric: {
      question: "Title of thr-7?",
      groundTruth: "Onboarding: SSO with Okta not working",
      acceptableVariations: [
        "Onboarding: SSO with Okta not working",
        "SSO with Okta",
        "Okta",
      ],
      rubric: "thr-7 is titled 'Onboarding: SSO with Okta not working'.",
    },
    evalChecks: [],
    maxSteps: 8,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "plain-ret-002",
    site: "plain",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 3,
    title: "Thread assignee lookup",
    goal: "Who is assigned to thread thr-4 ('Billing: invoice INV-12 wrong amount')?",
    retrievalRubric: {
      question: "Assignee of thr-4?",
      groundTruth: "Marie Lefevre",
      acceptableVariations: ["Marie Lefevre", "marie", "agt-1"],
      rubric: "thr-4 is assigned to Marie Lefevre (agt-1).",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "plain-ret-003",
    site: "plain",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 4,
    title: "Customer plan from a thread",
    goal: "Open thread thr-11 and report what plan the customer is on.",
    retrievalRubric: {
      question: "Plan of the customer on thr-11?",
      groundTruth: "enterprise",
      acceptableVariations: ["enterprise", "Enterprise"],
      rubric:
        "thr-11 is from cus-15 (Marcus Webb, Voltage Pay) — enterprise plan.",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "plain-ret-004",
    site: "plain",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 4,
    title: "Count agents",
    goal: "How many workspace agents are configured?",
    retrievalRubric: {
      question: "Agent count?",
      groundTruth: "5",
      acceptableVariations: ["5", "five", "5 agents"],
      rubric: "There are 5 agents: agt-1..agt-5.",
    },
    evalChecks: [],
    maxSteps: 8,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "plain-ret-005",
    site: "plain",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Active SLA breach status",
    goal: "Which thread is currently the longest-running open + urgent + assigned to Jonas Kim? Report its thread ID.",
    retrievalRubric: {
      question: "Oldest open urgent thread assigned to agt-4?",
      groundTruth: "thr-11",
      acceptableVariations: [
        "thr-11",
        "Stripe webhook events deduped wrong",
        "Stripe",
      ],
      rubric:
        "thr-11 (Stripe webhook dedupe) is open, urgent, assigned to agt-4, and was created on 2026-04-22 — earlier than thr-25 (created 2026-04-23).",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["retrieval"],
  },
]
