import type { TaskDefinition } from "@thetabench/core"

const R = {
  completion: 5.0,
  partialPerCheck: false,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
}

export const searchTasks: TaskDefinition[] = [
  {
    id: "plain-srch-001",
    site: "plain",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Find threads by keyword",
    goal: "How many threads in the workspace contain the word 'webhook' anywhere in their title?",
    retrievalRubric: {
      question: "Threads with 'webhook' in the title?",
      groundTruth: "5",
      acceptableVariations: ["5", "5 threads", "five"],
      rubric:
        "thr-1, thr-11, thr-16, thr-19, thr-25 mention 'webhook' in the title.",
    },
    evalChecks: [],
    maxSteps: 12,
    rewardProfile: R,
    tags: ["retrieval", "search"],
  },
  {
    id: "plain-srch-002",
    site: "plain",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Find urgent threads",
    goal: "How many threads currently have priority 'urgent'?",
    retrievalRubric: {
      question: "Number of urgent-priority threads?",
      groundTruth: "3",
      acceptableVariations: ["3", "three", "3 threads"],
      rubric: "thr-1, thr-11, thr-25 are urgent — 3 threads.",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R,
    tags: ["retrieval", "search"],
  },
  {
    id: "plain-srch-003",
    site: "plain",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Threads assigned to engineer",
    goal: "How many threads are currently assigned to Jonas Kim (agt-4)?",
    retrievalRubric: {
      question: "Thread count for agt-4?",
      groundTruth: "7",
      acceptableVariations: ["7", "7 threads", "seven"],
      rubric:
        "Jonas Kim (agt-4) is assigned to thr-1, thr-7, thr-10, thr-11, thr-16, thr-17, thr-25 — 7 threads.",
    },
    evalChecks: [],
    maxSteps: 12,
    rewardProfile: R,
    tags: ["retrieval", "search"],
  },
  {
    id: "plain-srch-004",
    site: "plain",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Unassigned threads",
    goal: "How many threads currently have no assignee?",
    retrievalRubric: {
      question: "Unassigned thread count?",
      groundTruth: "3",
      acceptableVariations: ["3", "three", "3 threads"],
      rubric: "thr-3, thr-15, thr-18 have null assignee — 3 threads.",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R,
    tags: ["retrieval", "search"],
  },
  {
    id: "plain-srch-005",
    site: "plain",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Find by message keyword",
    goal: "Which thread's most recent message mentions 'Rolling back the v2 signature'? Report its thread ID. (Hint: this happens after the recovery action — search the existing seed messages.)",
    retrievalRubric: {
      question: "Thread with the v2 signature rollback message?",
      groundTruth: "thr-25",
      acceptableVariations: ["thr-25", "Production webhook signature mismatch"],
      rubric:
        "msg-61 on thread thr-25 contains 'Found it — our gateway flipped to v2 signature format'.",
    },
    evalChecks: [],
    maxSteps: 12,
    rewardProfile: R,
    tags: ["retrieval", "search"],
  },
]
