import type { TaskDefinition } from "@thetabench/core"

const R2 = {
  completion: 2.0,
  partialPerCheck: false,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
}
const R5 = {
  completion: 5.0,
  partialPerCheck: false,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
}

export const tenantTasks: TaskDefinition[] = [
  {
    id: "plain-tnt-001",
    site: "plain",
    domain: "teams",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 3,
    title: "Find threads for a tenant",
    goal: "How many threads are open for MegaCorp (tnt-1)?",
    retrievalRubric: {
      question: "How many threads belong to tnt-1?",
      groundTruth: "5",
      acceptableVariations: ["5", "5 threads", "five"],
      rubric:
        "MegaCorp (tnt-1) appears on thr-1, thr-4, thr-16, thr-21 (open) and is the company on cus-2/cus-1/cus-17. Five threads total reference tnt-1.",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R2,
    tags: ["retrieval", "tenants"],
  },
  {
    id: "plain-tnt-002",
    site: "plain",
    domain: "teams",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 3,
    title: "Tenant plan lookup",
    goal: "What plan tier is tenant Voltage Pay (tnt-8) on?",
    retrievalRubric: {
      question: "Plan of tnt-8?",
      groundTruth: "enterprise",
      acceptableVariations: ["enterprise", "Enterprise"],
      rubric: "Voltage Pay (tnt-8) is on the enterprise plan, $31,000 MRR.",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R2,
    tags: ["retrieval", "tenants"],
  },
  {
    id: "plain-tnt-003",
    site: "plain",
    domain: "teams",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Highest-MRR tenant",
    goal: "Which tenant has the highest MRR? Report the tenant name.",
    retrievalRubric: {
      question: "Highest-MRR tenant?",
      groundTruth: "Voltage Pay",
      acceptableVariations: ["Voltage Pay", "voltage pay", "tnt-8"],
      rubric: "Voltage Pay (tnt-8, $31,000) is the highest-MRR tenant.",
    },
    evalChecks: [],
    maxSteps: 12,
    rewardProfile: R5,
    tags: ["retrieval", "tenants"],
  },
  {
    id: "plain-tnt-004",
    site: "plain",
    domain: "teams",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Count tenants by plan",
    goal: "How many tenants are on the 'enterprise' plan?",
    retrievalRubric: {
      question: "Number of enterprise-plan tenants?",
      groundTruth: "3",
      acceptableVariations: ["3", "3 tenants", "three"],
      rubric:
        "MegaCorp (tnt-1), Polymath AI (tnt-5), and Voltage Pay (tnt-8) are on enterprise — 3 tenants.",
    },
    evalChecks: [],
    maxSteps: 12,
    rewardProfile: R5,
    tags: ["retrieval", "tenants"],
  },
  {
    id: "plain-tnt-005",
    site: "plain",
    domain: "teams",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Customers per tenant",
    goal: "How many customers belong to tenant Acme Robotics (tnt-3)?",
    retrievalRubric: {
      question: "Customer count for tnt-3?",
      groundTruth: "3",
      acceptableVariations: ["3", "three", "3 customers"],
      rubric:
        "Acme Robotics (tnt-3) has cus-5 (Sofia), cus-6 (Hassan), cus-19 (Noor) — 3 customers.",
    },
    evalChecks: [],
    maxSteps: 12,
    rewardProfile: R5,
    tags: ["retrieval", "tenants"],
  },
]
