import type { TaskDefinition } from "@thetabench/core"

const R5 = {
  completion: 5.0,
  partialPerCheck: true,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
}
const R8 = {
  completion: 8.0,
  partialPerCheck: true,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.2,
}

// Note: PLAT uses workflow Open → In Development → Code Review → QA → Staging → Done
// FAPP uses workflow Backlog → Ready → In Progress → In Review → QA → Done
// LCRM uses workflow To Do → Doing → Review → Testing → Done → Rejected

export const boardTasks: TaskDefinition[] = [
  // ---------------------------------------------------------------------------
  // Stage 5 — board column movement via status transition
  // ---------------------------------------------------------------------------
  {
    id: "jira-brd-001",
    site: "jira",
    domain: "boards",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Move PLAT issue to In Development",
    goal: "On the PLAT Board, move issue PLAT-15 (iss-6) from 'Open' to 'In Development'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-6",
        expected: "In Development",
        weight: 1.0,
        description: "PLAT-15 is In Development",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["board", "transition"],
  },
  {
    id: "jira-brd-002",
    site: "jira",
    domain: "boards",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Move PLAT issue to Done",
    goal: "On the PLAT Board, move issue PLAT-12 (iss-3, currently 'Code Review') to 'Done'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-3",
        expected: "Done",
        weight: 1.0,
        description: "PLAT-12 is Done",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["board", "transition"],
  },
  {
    id: "jira-brd-003",
    site: "jira",
    domain: "boards",
    type: "action",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Move FAPP issue backward on board",
    goal: "On the FAPP Board, move issue FAPP-11 (iss-57) from 'In Progress' back to 'Ready'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-57",
        expected: "Ready",
        weight: 1.0,
        description: "FAPP-11 is back in Ready",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["board", "transition"],
  },
  {
    id: "jira-brd-004",
    site: "jira",
    domain: "boards",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Progress PLAT In Development issues to Code Review",
    goal: "On the PLAT Board, transition all 'In Development' issues in Sprint 13 to 'Code Review'. In Development in Sprint 13: PLAT-11 (iss-2), PLAT-16 (iss-7), PLAT-19 (iss-10), PLAT-30 (iss-21), PLAT-35 (iss-26), PLAT-51 (iss-32), PLAT-57 (iss-38), PLAT-71 (iss-47), PLAT-76 (iss-52).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-2",
        expected: "Code Review",
        weight: 0.12,
        description: "PLAT-11 in Code Review",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-7",
        expected: "Code Review",
        weight: 0.11,
        description: "PLAT-16 in Code Review",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-10",
        expected: "Code Review",
        weight: 0.11,
        description: "PLAT-19 in Code Review",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-21",
        expected: "Code Review",
        weight: 0.11,
        description: "PLAT-30 in Code Review",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-26",
        expected: "Code Review",
        weight: 0.11,
        description: "PLAT-35 in Code Review",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-32",
        expected: "Code Review",
        weight: 0.11,
        description: "PLAT-51 in Code Review",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-38",
        expected: "Code Review",
        weight: 0.11,
        description: "PLAT-57 in Code Review",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-47",
        expected: "Code Review",
        weight: 0.11,
        description: "PLAT-71 in Code Review",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-52",
        expected: "Code Review",
        weight: 0.11,
        description: "PLAT-76 in Code Review",
      },
    ],
    maxSteps: 25,
    rewardProfile: R8,
    tags: ["board", "transition", "bulk"],
  },
  {
    id: "jira-brd-005",
    site: "jira",
    domain: "boards",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Move QA issues to Staging",
    goal: "On the PLAT Board, transition all 'QA' issues to 'Staging'. Current QA issues: PLAT-13 (iss-4), PLAT-52 (iss-33).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-4",
        expected: "Staging",
        weight: 0.5,
        description: "PLAT-13 is in Staging",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-33",
        expected: "Staging",
        weight: 0.5,
        description: "PLAT-52 is in Staging",
      },
    ],
    maxSteps: 15,
    rewardProfile: R8,
    tags: ["board", "transition", "bulk"],
  },
]
