import type { TaskDefinition } from "@thetabench/core"

const R = {
  completion: 5.0,
  partialPerCheck: false,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
}

export const impossibleTasks: TaskDefinition[] = [
  {
    id: "jira-imp-001",
    site: "jira",
    domain: "impossible",
    type: "no_action",
    difficulty: "medium",
    curriculumStage: 8,
    title: "Start already-active sprint",
    goal: "Start PLAT Sprint 13 (sprint-4).",
    impossibilityReason:
      "PLAT Sprint 13 (sprint-4) is already in 'active' state. Starting an already-active sprint is not allowed.",
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["impossible", "error-recognition"],
  },
  {
    id: "jira-imp-002",
    site: "jira",
    domain: "impossible",
    type: "no_action",
    difficulty: "medium",
    curriculumStage: 8,
    title: "Complete future sprint",
    goal: "Complete PLAT Sprint 14 (sprint-5).",
    impossibilityReason:
      "PLAT Sprint 14 (sprint-5) is in 'future' state. Only active sprints can be completed — a sprint must be started first.",
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["impossible", "error-recognition"],
  },
  {
    id: "jira-imp-003",
    site: "jira",
    domain: "impossible",
    type: "no_action",
    difficulty: "medium",
    curriculumStage: 8,
    title: "Assign to nonexistent user",
    goal: "Assign issue PLAT-10 to user 'Chris Davis' (usr-99).",
    impossibilityReason:
      "User 'Chris Davis' (usr-99) does not exist. Valid users are usr-1 (Priya Sharma) through usr-20 (Omar Farooq).",
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["impossible", "error-recognition"],
  },
  {
    id: "jira-imp-004",
    site: "jira",
    domain: "impossible",
    type: "no_action",
    difficulty: "medium",
    curriculumStage: 8,
    title: "Invalid status for project workflow",
    goal: "Transition issue PLAT-11 (iss-2) to 'Backlog'. PLAT uses the Platform workflow (Open, In Development, Code Review, QA, Staging, Done, Won't Fix).",
    impossibilityReason:
      "'Backlog' is not a valid status in the PLAT workflow. PLAT's workflow states are: Open, In Development, Code Review, QA, Staging, Done, Won't Fix. Each project has its own workflow.",
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["impossible", "error-recognition", "workflow"],
  },
  {
    id: "jira-imp-005",
    site: "jira",
    domain: "impossible",
    type: "no_action",
    difficulty: "medium",
    curriculumStage: 8,
    title: "Only one active sprint per project",
    goal: "Start PLAT Sprint 14 (sprint-5) without completing PLAT Sprint 13 first.",
    impossibilityReason:
      "PLAT Sprint 13 (sprint-4) is currently active in the PLAT project. Only one sprint can be active per project at a time. Sprint 13 must be completed before Sprint 14 can be started.",
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["impossible", "error-recognition", "sprint"],
  },
  {
    id: "jira-imp-006",
    site: "jira",
    domain: "impossible",
    type: "no_action",
    difficulty: "medium",
    curriculumStage: 8,
    title: "Released version cannot be unreleased",
    goal: "Change fix version v2.2.0 (ver-2) status from 'released' to 'unreleased'.",
    impossibilityReason:
      "Version v2.2.0 was released on 2026-03-01. Once a version is released, it cannot be reverted to unreleased — releases are immutable. Create a new version instead.",
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["impossible", "error-recognition", "versions"],
  },
]
