import type { TaskDefinition } from "@thetabench/core"

const R2 = {
  completion: 2.0,
  partialPerCheck: false,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
}
const R5 = {
  completion: 5.0,
  partialPerCheck: true,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
}
const R8 = {
  completion: 8.0,
  partialPerCheck: true,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.2,
}
const R10 = {
  completion: 10.0,
  partialPerCheck: true,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.2,
}
const R15 = {
  completion: 15.0,
  partialPerCheck: true,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.2,
}

// Key issue reference (new CESS data — PLAT project, proj-4):
//   iss-1  PLAT-10  Implement PKCE auth flow      Done            sprint-2
//   iss-2  PLAT-11  Refresh token rotation        In Development  sprint-4
//   iss-3  PLAT-12  Session management API        Code Review     sprint-4
//   iss-4  PLAT-13  Rate limiting — auth          QA              sprint-4
//   iss-5  PLAT-14  MFA — TOTP                    Done            sprint-3
//   iss-6  PLAT-15  MFA — WebAuthn                Open            (no sprint)
//   iss-7  PLAT-16  SSO — SAML                    In Development  sprint-4
//   iss-8  PLAT-17  SSO — OIDC                    Open            (no sprint)
//   iss-10 PLAT-19  Stripe v2 integration         In Development  sprint-4
//   iss-13 PLAT-22  Idempotency keys              Done            sprint-3
//   iss-26 PLAT-35  PCI compliance docs           In Development  sprint-4
//   iss-32 PLAT-51  Payment webhook timeout bug   In Development  sprint-4  highest
//   iss-39 PLAT-58  Payment amount overflow       Open            null      highest  (links to ZD-1001)

export const issueTasks: TaskDefinition[] = [
  // ---------------------------------------------------------------------------
  // Stage 2 — single field updates (easy, maxSteps 10)
  // ---------------------------------------------------------------------------
  {
    id: "jira-iss-001",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Update issue summary",
    goal: "Change the summary of issue PLAT-13 (iss-4) to 'Token-bucket rate limiting for authentication'.",
    evalChecks: [
      {
        type: "state_diff",
        entity: "issues",
        id: "iss-4",
        field: "summary",
        expected: "Token-bucket rate limiting for authentication",
        weight: 1.0,
        description: "PLAT-13 summary updated",
      },
    ],
    maxSteps: 10,
    rewardProfile: R2,
    tags: ["form-fill"],
  },
  {
    id: "jira-iss-002",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Transition issue status",
    goal: "Transition issue PLAT-15 (iss-6) from 'Open' to 'In Development'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-6",
        expected: "In Development",
        weight: 1.0,
        description: "PLAT-15 is In Development",
      },
    ],
    maxSteps: 10,
    rewardProfile: R2,
    tags: ["form-fill"],
  },
  {
    id: "jira-iss-003",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Change issue priority",
    goal: "Change issue PLAT-17 (iss-8) priority to 'Highest'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_priority",
        id: "iss-8",
        expected: "highest",
        weight: 1.0,
        description: "PLAT-17 priority is highest",
      },
    ],
    maxSteps: 10,
    rewardProfile: R2,
    tags: ["form-fill"],
  },
  {
    id: "jira-iss-004",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Assign issue to user",
    goal: "Assign issue PLAT-58 (iss-39, the unassigned payment overflow bug from MegaCorp) to Ravi Kumar (usr-3).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_assignee",
        id: "iss-39",
        expected: "usr-3",
        weight: 1.0,
        description: "PLAT-58 is assigned to usr-3",
      },
    ],
    maxSteps: 10,
    rewardProfile: R2,
    tags: ["form-fill"],
  },
  {
    id: "jira-iss-005",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Set story points",
    goal: "Set story points for issue PLAT-17 (iss-8) to 5.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_story_points",
        id: "iss-8",
        expected: 5,
        weight: 1.0,
        description: "PLAT-17 has 5 story points",
      },
    ],
    maxSteps: 10,
    rewardProfile: R2,
    tags: ["form-fill"],
  },

  // ---------------------------------------------------------------------------
  // Stage 3 — create / delete (medium, maxSteps 15)
  // ---------------------------------------------------------------------------
  {
    id: "jira-iss-006",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Create a story",
    goal: "Create a new story in project PLAT (proj-4) titled 'Implement password strength meter' with priority 'High'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          summary: "Implement password strength meter",
          type: "story",
          priority: "high",
          projectId: "proj-4",
        },
        weight: 1.0,
        description: "Story exists with correct fields",
      },
    ],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["create"],
  },
  {
    id: "jira-iss-007",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Create a bug",
    goal: "Create a new bug in project PLAT titled 'Login form crashes on empty submit' with priority 'Highest' and assign to Arjun Mehta (usr-2).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          summary: "Login form crashes on empty submit",
          type: "bug",
          priority: "highest",
          assigneeId: "usr-2",
          projectId: "proj-4",
        },
        weight: 1.0,
        description: "Bug exists with correct fields",
      },
    ],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["create"],
  },
  {
    id: "jira-iss-008",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Create task with sprint and epic",
    goal: "Create a new task in project PLAT titled 'Write integration tests for OAuth' in PLAT Sprint 13 (sprint-4) and epic 'Auth Service Overhaul' (epic-1) with 3 story points.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          summary: "Write integration tests for OAuth",
          type: "task",
          sprintId: "sprint-4",
          epicId: "epic-1",
          storyPoints: 3,
          projectId: "proj-4",
        },
        weight: 1.0,
        description: "Task exists with sprint, epic, and story points",
      },
    ],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["create", "multi-field"],
  },
  {
    id: "jira-iss-009",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Delete an issue",
    goal: "Delete issue PLAT-79 (iss-55, 'Release notes draft for v2.3.0').",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_count_equals",
        expected: 378,
        weight: 1.0,
        description: "Total issue count is 378 (one deleted)",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["delete"],
  },
  {
    id: "jira-iss-010",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Create issue in FAPP project",
    goal: "Create a new task in the Frontend App project (proj-5) titled 'Update brand guidelines' with priority 'Medium'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          summary: "Update brand guidelines",
          type: "task",
          priority: "medium",
          projectId: "proj-5",
        },
        weight: 1.0,
        description: "Task exists in FAPP project",
      },
    ],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["create"],
  },

  // ---------------------------------------------------------------------------
  // Stage 5 — multi-field updates (medium, maxSteps 15)
  // ---------------------------------------------------------------------------
  {
    id: "jira-iss-011",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Multi-field update",
    goal: "Update issue PLAT-17 (iss-8): set summary to 'Standardize OIDC discovery and token exchange', priority to 'High', and story points to 5.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-8",
        expected: {
          summary: "Standardize OIDC discovery and token exchange",
          priority: "high",
          storyPoints: 5,
        },
        weight: 1.0,
        description: "PLAT-17 has updated summary, priority, and story points",
      },
    ],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["multi-field"],
  },
  {
    id: "jira-iss-012",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Change issue type",
    goal: "Change issue PLAT-17 (iss-8) from 'story' to 'task'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_type",
        id: "iss-8",
        expected: "task",
        weight: 1.0,
        description: "PLAT-17 type is task",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["form-fill"],
  },
  {
    id: "jira-iss-013",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Link issue to epic",
    goal: "Add issue PLAT-58 (iss-39, the unassigned payment overflow bug) to the 'Payment API v2' epic (epic-2).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_in_epic",
        id: "iss-39",
        expected: "epic-2",
        weight: 1.0,
        description: "PLAT-58 is in epic-2",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["form-fill"],
  },
  {
    id: "jira-iss-014",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Reassign and reprioritize",
    goal: "Reassign issue PLAT-50 (iss-31, auth token mobile bug) from Kiran Patel to Priya Sharma (usr-1) and change priority to 'Highest'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_assignee",
        id: "iss-31",
        expected: "usr-1",
        weight: 0.5,
        description: "PLAT-50 is assigned to usr-1",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_priority",
        id: "iss-31",
        expected: "highest",
        weight: 0.5,
        description: "PLAT-50 priority is highest",
      },
    ],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["multi-field"],
  },
  {
    id: "jira-iss-015",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Update description and components",
    goal: "Update issue PLAT-15 (iss-6): change description to 'FIDO2/WebAuthn enrollment with platform and cross-platform authenticators' and add component 'Auth Service' (cmp-2) if not already there.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-6",
        expected: {
          description:
            "FIDO2/WebAuthn enrollment with platform and cross-platform authenticators",
          componentIds: ["cmp-2"],
        },
        weight: 1.0,
        description: "PLAT-15 has updated description and components",
      },
    ],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["multi-field"],
  },

  // ---------------------------------------------------------------------------
  // Stage 7 — bulk/complex operations (hard, maxSteps 25)
  // ---------------------------------------------------------------------------
  {
    id: "jira-iss-016",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Close all Code Review issues",
    goal: "Transition all issues currently 'Code Review' in Sprint 13 to 'QA'. Code Review in Sprint 13: PLAT-12 (iss-3), PLAT-21 (iss-12).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-3",
        expected: "QA",
        weight: 0.5,
        description: "PLAT-12 status is QA",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-12",
        expected: "QA",
        weight: 0.5,
        description: "PLAT-21 status is QA",
      },
    ],
    maxSteps: 25,
    rewardProfile: R10,
    tags: ["bulk", "transition"],
  },
  {
    id: "jira-iss-017",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Bulk priority for critical bugs",
    goal: "Set priority to 'Highest' for PLAT's first 4 open bugs: PLAT-50 (iss-31), PLAT-52 (iss-33), PLAT-53 (iss-34), PLAT-57 (iss-38).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_priority",
        id: "iss-31",
        expected: "highest",
        weight: 0.25,
        description: "PLAT-50 highest",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_priority",
        id: "iss-33",
        expected: "highest",
        weight: 0.25,
        description: "PLAT-52 highest",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_priority",
        id: "iss-34",
        expected: "highest",
        weight: 0.25,
        description: "PLAT-53 highest",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_priority",
        id: "iss-38",
        expected: "highest",
        weight: 0.25,
        description: "PLAT-57 highest",
      },
    ],
    maxSteps: 25,
    rewardProfile: R10,
    tags: ["bulk", "priority"],
  },
  {
    id: "jira-iss-018",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Set points for unestimated PLAT tasks",
    goal: "Set story points to 3 for three unestimated PLAT tasks: PLAT-70 (iss-46), PLAT-73 (iss-49), PLAT-75 (iss-51).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_story_points",
        id: "iss-46",
        expected: 3,
        weight: 0.34,
        description: "PLAT-70 has 3 pts",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_story_points",
        id: "iss-49",
        expected: 3,
        weight: 0.33,
        description: "PLAT-73 has 3 pts",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_story_points",
        id: "iss-51",
        expected: 3,
        weight: 0.33,
        description: "PLAT-75 has 3 pts",
      },
    ],
    maxSteps: 25,
    rewardProfile: R10,
    tags: ["bulk", "estimation"],
  },

  // ---------------------------------------------------------------------------
  // Stage 8 — complex multi-step (hard, maxSteps 30)
  // ---------------------------------------------------------------------------
  {
    id: "jira-iss-019",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "hard",
    curriculumStage: 8,
    title: "Create 3 issues in sprint",
    goal: "Create 3 new tasks in project PLAT, all in PLAT Sprint 13 (sprint-4): 'Write API contract tests' (3 pts), 'Set up monitoring alerts' (2 pts), 'Update deployment docs' (1 pt).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          summary: "Write API contract tests",
          sprintId: "sprint-4",
          storyPoints: 3,
          projectId: "proj-4",
        },
        weight: 0.34,
        description: "'Write API contract tests' in sprint",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          summary: "Set up monitoring alerts",
          sprintId: "sprint-4",
          storyPoints: 2,
          projectId: "proj-4",
        },
        weight: 0.33,
        description: "'Set up monitoring alerts' in sprint",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          summary: "Update deployment docs",
          sprintId: "sprint-4",
          storyPoints: 1,
          projectId: "proj-4",
        },
        weight: 0.33,
        description: "'Update deployment docs' in sprint",
      },
    ],
    maxSteps: 30,
    rewardProfile: R15,
    tags: ["create", "bulk", "sprint"],
  },
  {
    id: "jira-iss-020",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "hard",
    curriculumStage: 8,
    title: "Triage backlog issues",
    goal: "Triage backlog issues: assign PLAT-15 (iss-6) to Ravi Kumar (usr-3), assign PLAT-17 (iss-8) to Sanjay Gupta (usr-14), and set both to priority 'Medium' with 5 story points each.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-6",
        expected: {
          assigneeId: "usr-3",
          priority: "medium",
          storyPoints: 5,
        },
        weight: 0.5,
        description: "PLAT-15 is triaged correctly",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-8",
        expected: {
          assigneeId: "usr-14",
          priority: "medium",
          storyPoints: 5,
        },
        weight: 0.5,
        description: "PLAT-17 is triaged correctly",
      },
    ],
    maxSteps: 25,
    rewardProfile: R10,
    tags: ["multi-step", "triage"],
  },
  {
    id: "jira-iss-021",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "hard",
    curriculumStage: 8,
    title: "Complex issue workflow",
    goal: "Create a new bug 'API returns 500 on concurrent requests' in PLAT with priority 'Highest', assign to Priya Sharma (usr-1), add to PLAT Sprint 13 (sprint-4), link to epic 'Auth Service Overhaul' (epic-1), set 8 story points, component 'Auth Service' (cmp-2), and fix version 'v2.3.0' (ver-4).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          summary: "API returns 500 on concurrent requests",
          type: "bug",
          priority: "highest",
          assigneeId: "usr-1",
          sprintId: "sprint-4",
          epicId: "epic-1",
          storyPoints: 8,
          componentIds: ["cmp-2"],
          fixVersionIds: ["ver-4"],
          projectId: "proj-4",
        },
        weight: 1.0,
        description: "Complex bug issue created with all fields",
      },
    ],
    maxSteps: 20,
    rewardProfile: R10,
    tags: ["create", "multi-field", "complex"],
  },
  {
    id: "jira-iss-022",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "hard",
    curriculumStage: 8,
    title: "Transition chain through PLAT workflow",
    goal: "Move issue PLAT-15 (iss-6) through the full PLAT workflow: Open -> In Development -> Code Review -> QA -> Staging -> Done.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-6",
        expected: "Done",
        weight: 1.0,
        description: "PLAT-15 is Done after full transition chain",
      },
    ],
    maxSteps: 20,
    rewardProfile: R8,
    tags: ["transition", "multi-step"],
  },
  {
    id: "jira-iss-023",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "hard",
    curriculumStage: 8,
    title: "Prepare issues for sprint",
    goal: "Move issues PLAT-15 (iss-6) and PLAT-17 (iss-8) into PLAT Sprint 14 (sprint-5) and set their story points to 5 each.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-6",
        expected: {
          sprintId: "sprint-5",
          storyPoints: 5,
        },
        weight: 0.5,
        description: "PLAT-15 is in sprint-5 with 5 points",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-8",
        expected: {
          sprintId: "sprint-5",
          storyPoints: 5,
        },
        weight: 0.5,
        description: "PLAT-17 is in sprint-5 with 5 points",
      },
    ],
    maxSteps: 20,
    rewardProfile: R8,
    tags: ["sprint", "multi-step"],
  },
  {
    id: "jira-iss-024",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "hard",
    curriculumStage: 8,
    title: "Reorganize epic issues",
    goal: "Move all 'Open' issues currently in epic 'Auth Service Overhaul' (epic-1) to epic 'Payment API v2' (epic-2). Open in epic-1: PLAT-15 (iss-6), PLAT-17 (iss-8).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_in_epic",
        id: "iss-6",
        expected: "epic-2",
        weight: 0.5,
        description: "PLAT-15 is in epic-2",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_epic",
        id: "iss-8",
        expected: "epic-2",
        weight: 0.5,
        description: "PLAT-17 is in epic-2",
      },
    ],
    maxSteps: 25,
    rewardProfile: R10,
    tags: ["bulk", "epic"],
  },
  {
    id: "jira-iss-025",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "hard",
    curriculumStage: 8,
    title: "Create subtask under story",
    goal: "Create a subtask titled 'Unit tests for OAuth callback handler' under the PLAT project, link it to epic 'Auth Service Overhaul' (epic-1), assign to Ravi Kumar (usr-3), set 2 story points, and add to PLAT Sprint 13 (sprint-4).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          summary: "Unit tests for OAuth callback handler",
          type: "subtask",
          epicId: "epic-1",
          assigneeId: "usr-3",
          storyPoints: 2,
          sprintId: "sprint-4",
          projectId: "proj-4",
        },
        weight: 1.0,
        description: "Subtask created with all correct fields",
      },
    ],
    maxSteps: 20,
    rewardProfile: R10,
    tags: ["create", "multi-field"],
  },
]
