import type { TaskDefinition } from "@simbench/core";

const R2 = {
  completion: 2.0,
  partialPerCheck: false,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
};
const R5 = {
  completion: 5.0,
  partialPerCheck: true,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
};
const R8 = {
  completion: 8.0,
  partialPerCheck: true,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.2,
};
const R10 = {
  completion: 10.0,
  partialPerCheck: true,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.2,
};
const R15 = {
  completion: 15.0,
  partialPerCheck: true,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.2,
};

export const issueTasks: TaskDefinition[] = [
  // ---------------------------------------------------------------------------
  // Stage 2 — single field updates (easy, maxSteps 10)
  // ---------------------------------------------------------------------------
  {
    id: "jira-iss-001",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Update issue summary",
    goal: "Change the summary of issue PROJ-4 to 'Build session management microservice'.",
    evalChecks: [
      {
        type: "state_diff",
        entity: "issues",
        id: "iss-4",
        field: "summary",
        expected: "Build session management microservice",
        weight: 1.0,
        description: "Issue PROJ-4 summary is 'Build session management microservice'",
      },
    ],
    maxSteps: 10,
    rewardProfile: R2,
    tags: ["form-fill"],
  },
  {
    id: "jira-iss-002",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Transition issue status",
    goal: "Transition issue PROJ-4 from 'To Do' to 'In Progress'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-4",
        expected: "in_progress",
        weight: 1.0,
        description: "Issue PROJ-4 status is in_progress",
      },
    ],
    maxSteps: 10,
    rewardProfile: R2,
    tags: ["form-fill"],
  },
  {
    id: "jira-iss-003",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Change issue priority",
    goal: "Change issue PROJ-9 priority to 'Highest'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_priority",
        id: "iss-9",
        expected: "highest",
        weight: 1.0,
        description: "Issue PROJ-9 priority is highest",
      },
    ],
    maxSteps: 10,
    rewardProfile: R2,
    tags: ["form-fill"],
  },
  {
    id: "jira-iss-004",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Assign issue to user",
    goal: "Assign issue PROJ-5 to Jordan Lee (usr-3).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_assignee",
        id: "iss-5",
        expected: "usr-3",
        weight: 1.0,
        description: "Issue PROJ-5 is assigned to usr-3",
      },
    ],
    maxSteps: 10,
    rewardProfile: R2,
    tags: ["form-fill"],
  },
  {
    id: "jira-iss-005",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Set story points",
    goal: "Set story points for issue PROJ-13 to 5.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_story_points",
        id: "iss-13",
        expected: 5,
        weight: 1.0,
        description: "Issue PROJ-13 has 5 story points",
      },
    ],
    maxSteps: 10,
    rewardProfile: R2,
    tags: ["form-fill"],
  },

  // ---------------------------------------------------------------------------
  // Stage 3 — create / delete (medium, maxSteps 15)
  // ---------------------------------------------------------------------------
  {
    id: "jira-iss-006",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Create a story",
    goal: "Create a new story in project PROJ titled 'Implement password strength meter' with priority 'High'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          summary: "Implement password strength meter",
          type: "story",
          priority: "high",
          projectId: "proj-1",
        },
        weight: 1.0,
        description: "Story 'Implement password strength meter' exists with correct fields",
      },
    ],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["create"],
  },
  {
    id: "jira-iss-007",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Create a bug",
    goal: "Create a new bug in project PROJ titled 'Login form crashes on empty submit' with priority 'Highest' and assign to Sam Williams (usr-2).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          summary: "Login form crashes on empty submit",
          type: "bug",
          priority: "highest",
          assigneeId: "usr-2",
          projectId: "proj-1",
        },
        weight: 1.0,
        description: "Bug exists with correct fields",
      },
    ],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["create"],
  },
  {
    id: "jira-iss-008",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Create task with sprint and epic",
    goal: "Create a new task in project PROJ titled 'Write integration tests for OAuth' in Sprint 13 (sprint-2) and epic 'User Authentication' (epic-1) with 3 story points.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          summary: "Write integration tests for OAuth",
          type: "task",
          sprintId: "sprint-2",
          epicId: "epic-1",
          storyPoints: 3,
          projectId: "proj-1",
        },
        weight: 1.0,
        description: "Task exists with sprint, epic, and story points",
      },
    ],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["create", "multi-field"],
  },
  {
    id: "jira-iss-009",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Delete an issue",
    goal: "Delete issue PROJ-16 ('Add loading skeletons').",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_count_equals",
        expected: 24,
        weight: 1.0,
        description: "Total issue count is 24 (one deleted)",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["delete"],
  },
  {
    id: "jira-iss-010",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Create issue in KANB project",
    goal: "Create a new task in the Marketing Kanban project (proj-2) titled 'Update brand guidelines' with priority 'Medium'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          summary: "Update brand guidelines",
          type: "task",
          priority: "medium",
          projectId: "proj-2",
        },
        weight: 1.0,
        description: "Task exists in KANB project",
      },
    ],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["create"],
  },

  // ---------------------------------------------------------------------------
  // Stage 5 — multi-field updates (medium, maxSteps 15)
  // ---------------------------------------------------------------------------
  {
    id: "jira-iss-011",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Multi-field update",
    goal: "Update issue PROJ-13: set summary to 'Standardize API error codes', priority to 'High', and story points to 5.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-13",
        expected: {
          summary: "Standardize API error codes",
          priority: "high",
          storyPoints: 5,
        },
        weight: 1.0,
        description: "PROJ-13 has updated summary, priority, and story points",
      },
    ],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["multi-field"],
  },
  {
    id: "jira-iss-012",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Change issue type",
    goal: "Change issue PROJ-14 from 'story' to 'task'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_type",
        id: "iss-14",
        expected: "task",
        weight: 1.0,
        description: "PROJ-14 type is task",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["form-fill"],
  },
  {
    id: "jira-iss-013",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Link issue to epic",
    goal: "Add issue PROJ-14 to the 'Dashboard Redesign' epic (epic-2).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_in_epic",
        id: "iss-14",
        expected: "epic-2",
        weight: 1.0,
        description: "PROJ-14 is in epic-2",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["form-fill"],
  },
  {
    id: "jira-iss-014",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Reassign and reprioritize",
    goal: "Reassign issue PROJ-9 from Sam Williams to Alex Johnson (usr-1) and change priority from 'Medium' to 'High'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_assignee",
        id: "iss-9",
        expected: "usr-1",
        weight: 0.5,
        description: "PROJ-9 is assigned to usr-1",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_priority",
        id: "iss-9",
        expected: "high",
        weight: 0.5,
        description: "PROJ-9 priority is high",
      },
    ],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["multi-field"],
  },
  {
    id: "jira-iss-015",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Update description and labels",
    goal: "Update issue PROJ-6: change description to 'Document all auth endpoints including OAuth, MFA, and session management' and add label 'api'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-6",
        expected: {
          description: "Document all auth endpoints including OAuth, MFA, and session management",
          labels: ["docs", "api"],
        },
        weight: 1.0,
        description: "PROJ-6 has updated description and labels",
      },
    ],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["multi-field"],
  },

  // ---------------------------------------------------------------------------
  // Stage 7 — bulk/complex operations (hard, maxSteps 25)
  // ---------------------------------------------------------------------------
  {
    id: "jira-iss-016",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Close all in-review issues",
    goal: "Transition all issues currently 'In Review' to 'Done'. There are currently 3 issues in review: PROJ-3 (iss-3), PROJ-12 (iss-12), and KANB-3 (iss-21).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-3",
        expected: "done",
        weight: 0.34,
        description: "PROJ-3 status is done",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-12",
        expected: "done",
        weight: 0.33,
        description: "PROJ-12 status is done",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-21",
        expected: "done",
        weight: 0.33,
        description: "KANB-3 status is done",
      },
    ],
    maxSteps: 25,
    rewardProfile: R10,
    tags: ["bulk", "transition"],
  },
  {
    id: "jira-iss-017",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Bulk priority for bugs",
    goal: "Set priority to 'Highest' for all bug-type issues. Bugs: PROJ-3 (iss-3), PROJ-9 (iss-9), PROJ-15 (iss-15), KANB-5 (iss-23).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_priority",
        id: "iss-3",
        expected: "highest",
        weight: 0.25,
        description: "PROJ-3 priority is highest",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_priority",
        id: "iss-9",
        expected: "highest",
        weight: 0.25,
        description: "PROJ-9 priority is highest",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_priority",
        id: "iss-15",
        expected: "highest",
        weight: 0.25,
        description: "PROJ-15 priority is highest",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_priority",
        id: "iss-23",
        expected: "highest",
        weight: 0.25,
        description: "KANB-5 priority is highest",
      },
    ],
    maxSteps: 25,
    rewardProfile: R10,
    tags: ["bulk", "priority"],
  },
  {
    id: "jira-iss-018",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Set points for unestimated issues",
    goal: "Set story points to 3 for all issues that currently have no story points (null). Unestimated: PROJ-13 (iss-13), PROJ-14 (iss-14), PROJ-18 (iss-18).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_story_points",
        id: "iss-13",
        expected: 3,
        weight: 0.34,
        description: "PROJ-13 has 3 story points",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_story_points",
        id: "iss-14",
        expected: 3,
        weight: 0.33,
        description: "PROJ-14 has 3 story points",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_story_points",
        id: "iss-18",
        expected: 3,
        weight: 0.33,
        description: "PROJ-18 has 3 story points",
      },
    ],
    maxSteps: 25,
    rewardProfile: R10,
    tags: ["bulk", "estimation"],
  },

  // ---------------------------------------------------------------------------
  // Stage 8 — complex multi-step (hard, maxSteps 30)
  // ---------------------------------------------------------------------------
  {
    id: "jira-iss-019",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "hard",
    curriculumStage: 8,
    title: "Create 3 issues in sprint",
    goal: "Create 3 new tasks in project PROJ, all in Sprint 13 (sprint-2): 'Write API contract tests' (3 pts), 'Set up monitoring alerts' (2 pts), 'Update deployment docs' (1 pt).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          summary: "Write API contract tests",
          sprintId: "sprint-2",
          storyPoints: 3,
          projectId: "proj-1",
        },
        weight: 0.34,
        description: "Task 'Write API contract tests' exists in sprint with 3 pts",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          summary: "Set up monitoring alerts",
          sprintId: "sprint-2",
          storyPoints: 2,
          projectId: "proj-1",
        },
        weight: 0.33,
        description: "Task 'Set up monitoring alerts' exists in sprint with 2 pts",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          summary: "Update deployment docs",
          sprintId: "sprint-2",
          storyPoints: 1,
          projectId: "proj-1",
        },
        weight: 0.33,
        description: "Task 'Update deployment docs' exists in sprint with 1 pt",
      },
    ],
    maxSteps: 30,
    rewardProfile: R15,
    tags: ["create", "bulk", "sprint"],
  },
  {
    id: "jira-iss-020",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "hard",
    curriculumStage: 8,
    title: "Triage backlog issues",
    goal: "Triage backlog issues: assign PROJ-13 to Jordan Lee (usr-3), assign PROJ-14 to Taylor Brown (usr-4), and set both to priority 'Medium' with 5 story points each.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-13",
        expected: {
          assigneeId: "usr-3",
          priority: "medium",
          storyPoints: 5,
        },
        weight: 0.5,
        description: "PROJ-13 is triaged correctly",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-14",
        expected: {
          assigneeId: "usr-4",
          priority: "medium",
          storyPoints: 5,
        },
        weight: 0.5,
        description: "PROJ-14 is triaged correctly",
      },
    ],
    maxSteps: 25,
    rewardProfile: R10,
    tags: ["multi-step", "triage"],
  },
  {
    id: "jira-iss-021",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "hard",
    curriculumStage: 8,
    title: "Complex issue workflow",
    goal: "Create a new bug 'API returns 500 on concurrent requests' in PROJ with priority 'Highest', assign to Alex Johnson (usr-1), add to Sprint 13 (sprint-2), link to epic 'User Authentication' (epic-1), set 8 story points, and add labels 'bug' and 'backend'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          summary: "API returns 500 on concurrent requests",
          type: "bug",
          priority: "highest",
          assigneeId: "usr-1",
          sprintId: "sprint-2",
          epicId: "epic-1",
          storyPoints: 8,
          labels: ["bug", "backend"],
          projectId: "proj-1",
        },
        weight: 1.0,
        description: "Complex bug issue created with all fields",
      },
    ],
    maxSteps: 20,
    rewardProfile: R10,
    tags: ["create", "multi-field", "complex"],
  },
  {
    id: "jira-iss-022",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "hard",
    curriculumStage: 8,
    title: "Transition chain",
    goal: "Move issue PROJ-4 (iss-4) through the full workflow: To Do -> In Progress -> In Review -> Done.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-4",
        expected: "done",
        weight: 1.0,
        description: "PROJ-4 is done after full transition chain",
      },
    ],
    maxSteps: 20,
    rewardProfile: R8,
    tags: ["transition", "multi-step"],
  },
  {
    id: "jira-iss-023",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "hard",
    curriculumStage: 8,
    title: "Prepare issues for sprint",
    goal: "Move issues PROJ-13 (iss-13) and PROJ-14 (iss-14) into Sprint 14 (sprint-3) and set their story points to 5 each.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-13",
        expected: {
          sprintId: "sprint-3",
          storyPoints: 5,
        },
        weight: 0.5,
        description: "PROJ-13 is in sprint-3 with 5 points",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-14",
        expected: {
          sprintId: "sprint-3",
          storyPoints: 5,
        },
        weight: 0.5,
        description: "PROJ-14 is in sprint-3 with 5 points",
      },
    ],
    maxSteps: 20,
    rewardProfile: R8,
    tags: ["sprint", "multi-step"],
  },
  {
    id: "jira-iss-024",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "hard",
    curriculumStage: 8,
    title: "Reorganize epic issues",
    goal: "Move all issues in epic 'User Authentication' (epic-1) that are 'to_do' to epic 'Dashboard Redesign' (epic-2). Issues: PROJ-4 (iss-4), PROJ-5 (iss-5), PROJ-6 (iss-6).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_in_epic",
        id: "iss-4",
        expected: "epic-2",
        weight: 0.34,
        description: "PROJ-4 is in epic-2",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_epic",
        id: "iss-5",
        expected: "epic-2",
        weight: 0.33,
        description: "PROJ-5 is in epic-2",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_epic",
        id: "iss-6",
        expected: "epic-2",
        weight: 0.33,
        description: "PROJ-6 is in epic-2",
      },
    ],
    maxSteps: 25,
    rewardProfile: R10,
    tags: ["bulk", "epic"],
  },
  {
    id: "jira-iss-025",
    site: "jira",
    domain: "issues",
    type: "action",
    difficulty: "hard",
    curriculumStage: 8,
    title: "Create subtask under story",
    goal: "Create a subtask titled 'Unit tests for OAuth callback handler' under the PROJ project, link it to epic 'User Authentication' (epic-1), assign to Jordan Lee (usr-3), set 2 story points, and add to Sprint 13 (sprint-2).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          summary: "Unit tests for OAuth callback handler",
          type: "subtask",
          epicId: "epic-1",
          assigneeId: "usr-3",
          storyPoints: 2,
          sprintId: "sprint-2",
          projectId: "proj-1",
        },
        weight: 1.0,
        description: "Subtask created with all correct fields",
      },
    ],
    maxSteps: 20,
    rewardProfile: R10,
    tags: ["create", "multi-field"],
  },
];
