import type { TaskDefinition } from "@simbench/core";

const R10 = {
  completion: 10.0,
  partialPerCheck: true,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.2,
};
const R15 = {
  completion: 15.0,
  partialPerCheck: true,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.2,
};

export const multiDomainTasks: TaskDefinition[] = [
  {
    id: "jira-multi-001",
    site: "jira",
    domain: "multi-domain",
    type: "action",
    difficulty: "hard",
    curriculumStage: 9,
    title: "Sprint planning workflow",
    goal: "Complete Sprint 13 (sprint-2). Then start Sprint 14 (sprint-3). Move incomplete issues from sprint-2 (PROJ-2 iss-2, PROJ-4 iss-4) to sprint-3.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "sprint_has_state",
        id: "sprint-2",
        expected: "closed",
        weight: 0.25,
        description: "Sprint 13 is closed",
      },
      {
        type: "state_predicate",
        predicate: "sprint_has_state",
        id: "sprint-3",
        expected: "active",
        weight: 0.25,
        description: "Sprint 14 is active",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_sprint",
        id: "iss-2",
        expected: "sprint-3",
        weight: 0.25,
        description: "PROJ-2 moved to sprint-3",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_sprint",
        id: "iss-4",
        expected: "sprint-3",
        weight: 0.25,
        description: "PROJ-4 moved to sprint-3",
      },
    ],
    maxSteps: 25,
    rewardProfile: R10,
    tags: ["sprint", "lifecycle", "multi-step"],
  },
  {
    id: "jira-multi-002",
    site: "jira",
    domain: "multi-domain",
    type: "action",
    difficulty: "hard",
    curriculumStage: 9,
    title: "Release management",
    goal: "Prepare for release: transition all 'in_review' issues to 'done' (PROJ-3 iss-3, PROJ-12 iss-12, KANB-3 iss-21), then complete Sprint 13 (sprint-2).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-3",
        expected: "done",
        weight: 0.2,
        description: "PROJ-3 is done",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-12",
        expected: "done",
        weight: 0.2,
        description: "PROJ-12 is done",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-21",
        expected: "done",
        weight: 0.2,
        description: "KANB-3 is done",
      },
      {
        type: "state_predicate",
        predicate: "sprint_has_state",
        id: "sprint-2",
        expected: "closed",
        weight: 0.4,
        description: "Sprint 13 is closed",
      },
    ],
    maxSteps: 25,
    rewardProfile: R10,
    tags: ["transition", "sprint", "release"],
  },
  {
    id: "jira-multi-003",
    site: "jira",
    domain: "multi-domain",
    type: "action",
    difficulty: "hard",
    curriculumStage: 9,
    title: "Bug triage and sprint",
    goal: "Triage bug KANB-5 (iss-23): assign to Sam Williams (usr-2), set priority to 'Highest', add 2 story points. Then create a new sprint 'Bug Fix Sprint' in PROJ with goal 'Critical bug fixes'. Move PROJ-3 (iss-3) and PROJ-9 (iss-9) into the new sprint.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-23",
        expected: {
          assigneeId: "usr-2",
          priority: "highest",
          storyPoints: 2,
        },
        weight: 0.3,
        description: "KANB-5 triaged correctly",
      },
      {
        type: "state_predicate",
        predicate: "sprint_has_state",
        id: "sprint-4",
        expected: "future",
        weight: 0.2,
        description: "Bug Fix Sprint created",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_sprint",
        id: "iss-3",
        expected: "sprint-4",
        weight: 0.25,
        description: "PROJ-3 in bug fix sprint",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_sprint",
        id: "iss-9",
        expected: "sprint-4",
        weight: 0.25,
        description: "PROJ-9 in bug fix sprint",
      },
    ],
    maxSteps: 30,
    rewardProfile: R15,
    tags: ["triage", "sprint", "create", "multi-step"],
  },
  {
    id: "jira-multi-004",
    site: "jira",
    domain: "multi-domain",
    type: "action",
    difficulty: "hard",
    curriculumStage: 9,
    title: "Full project setup",
    goal: "Create a new project 'Infrastructure' with key 'INFRA', type 'scrum', lead Alex Johnson (usr-1). Create an epic 'Cloud Migration' in the new project. Create a task 'Set up Kubernetes cluster' in INFRA with priority 'High', 8 story points, assigned to Jordan Lee (usr-3), linked to the new epic.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "project_has_fields",
        expected: {
          name: "Infrastructure",
          key: "INFRA",
          type: "scrum",
          lead: "usr-1",
        },
        weight: 0.3,
        description: "INFRA project created",
      },
      {
        type: "state_predicate",
        predicate: "epic_has_status",
        id: "epic-4",
        expected: "to_do",
        weight: 0.2,
        description: "Cloud Migration epic exists",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          summary: "Set up Kubernetes cluster",
          type: "task",
          priority: "high",
          storyPoints: 8,
          assigneeId: "usr-3",
          epicId: "epic-4",
          projectId: "proj-3",
        },
        weight: 0.5,
        description: "Task created with all fields in INFRA project",
      },
    ],
    maxSteps: 30,
    rewardProfile: R15,
    tags: ["project", "epic", "create", "multi-step"],
  },
  {
    id: "jira-multi-005",
    site: "jira",
    domain: "multi-domain",
    type: "action",
    difficulty: "hard",
    curriculumStage: 10,
    title: "End-to-end sprint cycle",
    goal: "Complete the full sprint cycle: (1) Complete Sprint 13 (sprint-2), (2) Start Sprint 14 (sprint-3), (3) Create 2 new tasks in PROJ in sprint-3: 'Optimize database queries' (5 pts) and 'Add caching layer' (8 pts), both assigned to Alex Johnson (usr-1).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "sprint_has_state",
        id: "sprint-2",
        expected: "closed",
        weight: 0.15,
        description: "Sprint 13 closed",
      },
      {
        type: "state_predicate",
        predicate: "sprint_has_state",
        id: "sprint-3",
        expected: "active",
        weight: 0.15,
        description: "Sprint 14 active",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          summary: "Optimize database queries",
          storyPoints: 5,
          assigneeId: "usr-1",
          sprintId: "sprint-3",
          projectId: "proj-1",
        },
        weight: 0.35,
        description: "Optimize DB task created in sprint",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          summary: "Add caching layer",
          storyPoints: 8,
          assigneeId: "usr-1",
          sprintId: "sprint-3",
          projectId: "proj-1",
        },
        weight: 0.35,
        description: "Add caching task created in sprint",
      },
    ],
    maxSteps: 30,
    rewardProfile: R15,
    tags: ["sprint", "create", "lifecycle", "end-to-end"],
  },
  {
    id: "jira-multi-006",
    site: "jira",
    domain: "multi-domain",
    type: "action",
    difficulty: "hard",
    curriculumStage: 10,
    title: "Epic completion workflow",
    goal: "Complete the User Authentication epic (epic-1): transition all non-done issues in epic-1 to 'done' (PROJ-2 iss-2, PROJ-3 iss-3, PROJ-4 iss-4, PROJ-5 iss-5, PROJ-6 iss-6, PROJ-11 iss-11, PROJ-12 iss-12, PROJ-15 iss-15), then update the epic status to 'done'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-2",
        expected: "done",
        weight: 0.08,
        description: "PROJ-2 done",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-3",
        expected: "done",
        weight: 0.08,
        description: "PROJ-3 done",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-4",
        expected: "done",
        weight: 0.08,
        description: "PROJ-4 done",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-5",
        expected: "done",
        weight: 0.08,
        description: "PROJ-5 done",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-6",
        expected: "done",
        weight: 0.08,
        description: "PROJ-6 done",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-11",
        expected: "done",
        weight: 0.08,
        description: "PROJ-11 done",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-12",
        expected: "done",
        weight: 0.08,
        description: "PROJ-12 done",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-15",
        expected: "done",
        weight: 0.08,
        description: "PROJ-15 done",
      },
      {
        type: "state_predicate",
        predicate: "epic_has_status",
        id: "epic-1",
        expected: "done",
        weight: 0.36,
        description: "Epic status is done",
      },
    ],
    maxSteps: 40,
    rewardProfile: R15,
    tags: ["epic", "transition", "bulk", "end-to-end"],
  },
  {
    id: "jira-multi-007",
    site: "jira",
    domain: "multi-domain",
    type: "action",
    difficulty: "hard",
    curriculumStage: 9,
    title: "Cross-project issue management",
    goal: "Create a bug 'Shared auth library crash' in PROJ with priority 'Highest', 3 story points, assigned to Jordan Lee (usr-3). Then create a related task 'Update marketing site auth flow' in KANB project with priority 'High', assigned to Taylor Brown (usr-4).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          summary: "Shared auth library crash",
          type: "bug",
          priority: "highest",
          storyPoints: 3,
          assigneeId: "usr-3",
          projectId: "proj-1",
        },
        weight: 0.5,
        description: "Bug created in PROJ",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          summary: "Update marketing site auth flow",
          type: "task",
          priority: "high",
          assigneeId: "usr-4",
          projectId: "proj-2",
        },
        weight: 0.5,
        description: "Task created in KANB",
      },
    ],
    maxSteps: 25,
    rewardProfile: R10,
    tags: ["create", "cross-project"],
  },
  {
    id: "jira-multi-008",
    site: "jira",
    domain: "multi-domain",
    type: "action",
    difficulty: "hard",
    curriculumStage: 10,
    title: "Backlog grooming session",
    goal: "Groom the PROJ backlog: (1) Set story points for PROJ-13 (iss-13) to 5 and PROJ-14 (iss-14) to 3, (2) Assign PROJ-13 to Jordan Lee (usr-3) and PROJ-14 to Taylor Brown (usr-4), (3) Link PROJ-14 to Dashboard Redesign epic (epic-2), (4) Create a new task 'API versioning strategy' with 5 story points in PROJ.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-13",
        expected: { storyPoints: 5, assigneeId: "usr-3" },
        weight: 0.25,
        description: "PROJ-13 groomed",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-14",
        expected: { storyPoints: 3, assigneeId: "usr-4", epicId: "epic-2" },
        weight: 0.25,
        description: "PROJ-14 groomed with epic",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          summary: "API versioning strategy",
          storyPoints: 5,
          projectId: "proj-1",
        },
        weight: 0.5,
        description: "New task created",
      },
    ],
    maxSteps: 30,
    rewardProfile: R15,
    tags: ["grooming", "multi-step", "estimation"],
  },
  {
    id: "jira-multi-009",
    site: "jira",
    domain: "multi-domain",
    type: "action",
    difficulty: "hard",
    curriculumStage: 10,
    title: "Team workload rebalancing",
    goal: "Rebalance workload: (1) Reassign PROJ-4 (iss-4) from Alex Johnson to Taylor Brown (usr-4), (2) Reassign PROJ-11 (iss-11) from Jordan Lee to Sam Williams (usr-2), (3) Reassign PROJ-8 (iss-8) from Jordan Lee to Alex Johnson (usr-1), (4) Create a saved filter 'Team Workload' with JQL 'assignee in (usr-1, usr-2, usr-3, usr-4) ORDER BY assignee'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_assignee",
        id: "iss-4",
        expected: "usr-4",
        weight: 0.34,
        description: "PROJ-4 assigned to Taylor",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_assignee",
        id: "iss-11",
        expected: "usr-2",
        weight: 0.33,
        description: "PROJ-11 assigned to Sam",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_assignee",
        id: "iss-8",
        expected: "usr-1",
        weight: 0.33,
        description: "PROJ-8 assigned to Alex",
      },
    ],
    maxSteps: 25,
    rewardProfile: R10,
    tags: ["reassign", "filter", "multi-step"],
  },
  {
    id: "jira-multi-010",
    site: "jira",
    domain: "multi-domain",
    type: "action",
    difficulty: "hard",
    curriculumStage: 10,
    title: "Emergency hotfix workflow",
    goal: "Handle an emergency: (1) Create a bug 'Production database connection pool exhausted' in PROJ with priority 'Highest', type 'bug', 1 story point, assigned to Alex Johnson (usr-1), (2) Add it to Sprint 13 (sprint-2), (3) Immediately transition it to 'in_progress'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          summary: "Production database connection pool exhausted",
          type: "bug",
          priority: "highest",
          storyPoints: 1,
          assigneeId: "usr-1",
          sprintId: "sprint-2",
          status: "in_progress",
          projectId: "proj-1",
        },
        weight: 1.0,
        description: "Emergency bug created, in sprint, and in progress",
      },
    ],
    maxSteps: 20,
    rewardProfile: R10,
    tags: ["create", "transition", "emergency"],
  },
];
