import type { TaskDefinition } from "@thetabench/core"

const R10 = {
  completion: 10.0,
  partialPerCheck: true,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.2,
}
const R15 = {
  completion: 15.0,
  partialPerCheck: true,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.2,
}

export const multiDomainTasks: TaskDefinition[] = [
  {
    id: "jira-multi-001",
    site: "jira",
    domain: "multi-domain",
    type: "action",
    difficulty: "hard",
    curriculumStage: 9,
    title: "Sprint planning workflow",
    goal: "Complete PLAT Sprint 13 (sprint-4). Then start PLAT Sprint 14 (sprint-5). Move incomplete issues from sprint-4 (PLAT-11 iss-2, PLAT-13 iss-4) to sprint-5.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "sprint_has_state",
        id: "sprint-4",
        expected: "closed",
        weight: 0.25,
        description: "PLAT Sprint 13 is closed",
      },
      {
        type: "state_predicate",
        predicate: "sprint_has_state",
        id: "sprint-5",
        expected: "active",
        weight: 0.25,
        description: "PLAT Sprint 14 is active",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_sprint",
        id: "iss-2",
        expected: "sprint-5",
        weight: 0.25,
        description: "PLAT-11 moved to sprint-5",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_sprint",
        id: "iss-4",
        expected: "sprint-5",
        weight: 0.25,
        description: "PLAT-13 moved to sprint-5",
      },
    ],
    maxSteps: 25,
    rewardProfile: R10,
    tags: ["sprint", "lifecycle", "multi-step"],
  },
  {
    id: "jira-multi-002",
    site: "jira",
    domain: "multi-domain",
    type: "action",
    difficulty: "hard",
    curriculumStage: 9,
    title: "Release management",
    goal: "Prepare v2.3.0 for release: transition all 'Code Review' and 'QA' issues to 'Done' (PLAT-12 iss-3, PLAT-13 iss-4, PLAT-21 iss-12, PLAT-52 iss-33), then complete PLAT Sprint 13 (sprint-4).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-3",
        expected: "Done",
        weight: 0.15,
        description: "PLAT-12 is Done",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-4",
        expected: "Done",
        weight: 0.15,
        description: "PLAT-13 is Done",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-12",
        expected: "Done",
        weight: 0.15,
        description: "PLAT-21 is Done",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-33",
        expected: "Done",
        weight: 0.15,
        description: "PLAT-52 is Done",
      },
      {
        type: "state_predicate",
        predicate: "sprint_has_state",
        id: "sprint-4",
        expected: "closed",
        weight: 0.4,
        description: "PLAT Sprint 13 is closed",
      },
    ],
    maxSteps: 25,
    rewardProfile: R10,
    tags: ["transition", "sprint", "release"],
  },
  {
    id: "jira-multi-003",
    site: "jira",
    domain: "multi-domain",
    type: "action",
    difficulty: "hard",
    curriculumStage: 9,
    title: "Bug triage and sprint",
    goal: "Triage bug PLAT-58 (iss-39, the MegaCorp payment overflow from ZD-1001): assign to Ravi Kumar (usr-3), confirm priority 'Highest', add 5 story points, set component 'Payment Service' (cmp-2). Then add to PLAT Sprint 13 (sprint-4). Also create a new sprint 'PLAT Hotfix Sprint' with goal 'Critical bug fixes' in PLAT project.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-39",
        expected: {
          assigneeId: "usr-3",
          priority: "highest",
          storyPoints: 5,
          sprintId: "sprint-4",
        },
        weight: 0.6,
        description: "PLAT-58 triaged and moved to sprint-4",
      },
      {
        type: "state_predicate",
        predicate: "sprint_has_state",
        id: "sprint-6",
        expected: "future",
        weight: 0.4,
        description: "PLAT Hotfix Sprint created",
      },
    ],
    maxSteps: 30,
    rewardProfile: R15,
    tags: ["triage", "sprint", "create", "cross-platform", "multi-step"],
  },
  {
    id: "jira-multi-004",
    site: "jira",
    domain: "multi-domain",
    type: "action",
    difficulty: "hard",
    curriculumStage: 9,
    title: "Full project setup",
    goal: "Create a new project 'Infrastructure' with key 'INFRA', type 'scrum', lead Priya Sharma (usr-1). Create an epic 'Cloud Migration' in the new project. Create a task 'Set up Kubernetes cluster' in INFRA with priority 'High', 8 story points, assigned to Ravi Kumar (usr-3), linked to the new epic.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "project_has_fields",
        expected: {
          name: "Infrastructure",
          key: "INFRA",
          type: "scrum",
          lead: "usr-1",
        },
        weight: 0.3,
        description: "INFRA project created",
      },
      {
        type: "state_predicate",
        predicate: "epic_has_status",
        id: "epic-7",
        expected: "Open",
        weight: 0.2,
        description: "Cloud Migration epic exists",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          summary: "Set up Kubernetes cluster",
          type: "task",
          priority: "high",
          storyPoints: 8,
          assigneeId: "usr-3",
          epicId: "epic-7",
          projectId: "proj-9",
        },
        weight: 0.5,
        description: "Task created with all fields in INFRA project",
      },
    ],
    maxSteps: 30,
    rewardProfile: R15,
    tags: ["project", "epic", "create", "multi-step"],
  },
  {
    id: "jira-multi-005",
    site: "jira",
    domain: "multi-domain",
    type: "action",
    difficulty: "hard",
    curriculumStage: 10,
    title: "End-to-end sprint cycle",
    goal: "Complete the full sprint cycle: (1) Complete PLAT Sprint 13 (sprint-4), (2) Start PLAT Sprint 14 (sprint-5), (3) Create 2 new tasks in PLAT in sprint-5: 'Optimize database queries' (5 pts) and 'Add caching layer' (8 pts), both assigned to Priya Sharma (usr-1).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "sprint_has_state",
        id: "sprint-4",
        expected: "closed",
        weight: 0.15,
        description: "Sprint 13 closed",
      },
      {
        type: "state_predicate",
        predicate: "sprint_has_state",
        id: "sprint-5",
        expected: "active",
        weight: 0.15,
        description: "Sprint 14 active",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          summary: "Optimize database queries",
          storyPoints: 5,
          assigneeId: "usr-1",
          sprintId: "sprint-5",
          projectId: "proj-4",
        },
        weight: 0.35,
        description: "Optimize DB task in sprint",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          summary: "Add caching layer",
          storyPoints: 8,
          assigneeId: "usr-1",
          sprintId: "sprint-5",
          projectId: "proj-4",
        },
        weight: 0.35,
        description: "Add caching task in sprint",
      },
    ],
    maxSteps: 30,
    rewardProfile: R15,
    tags: ["sprint", "create", "lifecycle", "end-to-end"],
  },
  {
    id: "jira-multi-006",
    site: "jira",
    domain: "multi-domain",
    type: "action",
    difficulty: "hard",
    curriculumStage: 10,
    title: "Epic completion workflow",
    goal: "Complete the Auth Service Overhaul epic (epic-1): transition all non-Done issues in epic-1 to 'Done' (PLAT-11 iss-2, PLAT-12 iss-3, PLAT-13 iss-4, PLAT-15 iss-6, PLAT-16 iss-7, PLAT-17 iss-8), then update the epic status to 'Done'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-2",
        expected: "Done",
        weight: 0.1,
        description: "PLAT-11 Done",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-3",
        expected: "Done",
        weight: 0.1,
        description: "PLAT-12 Done",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-4",
        expected: "Done",
        weight: 0.1,
        description: "PLAT-13 Done",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-6",
        expected: "Done",
        weight: 0.1,
        description: "PLAT-15 Done",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-7",
        expected: "Done",
        weight: 0.1,
        description: "PLAT-16 Done",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_status",
        id: "iss-8",
        expected: "Done",
        weight: 0.1,
        description: "PLAT-17 Done",
      },
      {
        type: "state_predicate",
        predicate: "epic_has_status",
        id: "epic-1",
        expected: "Done",
        weight: 0.4,
        description: "Epic status Done",
      },
    ],
    maxSteps: 40,
    rewardProfile: R15,
    tags: ["epic", "transition", "bulk", "end-to-end"],
  },
  {
    id: "jira-multi-007",
    site: "jira",
    domain: "multi-domain",
    type: "action",
    difficulty: "hard",
    curriculumStage: 9,
    title: "Cross-project issue management",
    goal: "Create a bug 'Shared auth library crash' in PLAT (proj-4) with priority 'Highest', 3 story points, assigned to Ravi Kumar (usr-3). Then create a related task 'Update checkout auth flow' in FAPP (proj-5) with priority 'High', assigned to Sneha Reddy (usr-4).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          summary: "Shared auth library crash",
          type: "bug",
          priority: "highest",
          storyPoints: 3,
          assigneeId: "usr-3",
          projectId: "proj-4",
        },
        weight: 0.5,
        description: "Bug created in PLAT",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          summary: "Update checkout auth flow",
          type: "task",
          priority: "high",
          assigneeId: "usr-4",
          projectId: "proj-5",
        },
        weight: 0.5,
        description: "Task created in FAPP",
      },
    ],
    maxSteps: 25,
    rewardProfile: R10,
    tags: ["create", "cross-project"],
  },
  {
    id: "jira-multi-008",
    site: "jira",
    domain: "multi-domain",
    type: "action",
    difficulty: "hard",
    curriculumStage: 10,
    title: "Backlog grooming session",
    goal: "Groom the PLAT backlog: (1) Set story points for PLAT-15 (iss-6) to 5 and PLAT-17 (iss-8) to 3, (2) Assign PLAT-15 to Ravi Kumar (usr-3) and PLAT-17 to Sneha Reddy (usr-4), (3) Link PLAT-17 to Payment API v2 epic (epic-2), (4) Create a new task 'API versioning strategy' with 5 story points in PLAT.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-6",
        expected: { storyPoints: 5, assigneeId: "usr-3" },
        weight: 0.25,
        description: "PLAT-15 groomed",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-8",
        expected: { storyPoints: 3, assigneeId: "usr-4", epicId: "epic-2" },
        weight: 0.25,
        description: "PLAT-17 groomed with epic",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          summary: "API versioning strategy",
          storyPoints: 5,
          projectId: "proj-4",
        },
        weight: 0.5,
        description: "New task created",
      },
    ],
    maxSteps: 30,
    rewardProfile: R15,
    tags: ["grooming", "multi-step", "estimation"],
  },
  {
    id: "jira-multi-009",
    site: "jira",
    domain: "multi-domain",
    type: "action",
    difficulty: "hard",
    curriculumStage: 10,
    title: "Team workload rebalancing",
    goal: "Rebalance workload across Platform backend engineers: (1) Reassign PLAT-13 (iss-4) to Sneha Reddy (usr-4), (2) Reassign PLAT-21 (iss-12) to Arjun Mehta (usr-2), (3) Reassign PLAT-17 (iss-8) to Priya Sharma (usr-1).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_assignee",
        id: "iss-4",
        expected: "usr-4",
        weight: 0.34,
        description: "PLAT-13 assigned to Sneha",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_assignee",
        id: "iss-12",
        expected: "usr-2",
        weight: 0.33,
        description: "PLAT-21 assigned to Arjun",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_assignee",
        id: "iss-8",
        expected: "usr-1",
        weight: 0.33,
        description: "PLAT-17 assigned to Priya",
      },
    ],
    maxSteps: 25,
    rewardProfile: R10,
    tags: ["reassign", "multi-step"],
  },
  {
    id: "jira-multi-010",
    site: "jira",
    domain: "multi-domain",
    type: "action",
    difficulty: "hard",
    curriculumStage: 10,
    title: "Emergency hotfix workflow",
    goal: "Handle an emergency: (1) Create a bug 'Production database connection pool exhausted' in PLAT with priority 'Highest', type 'bug', 1 story point, assigned to Priya Sharma (usr-1), (2) Add it to PLAT Sprint 13 (sprint-4), (3) Immediately transition it to 'In Development'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        expected: {
          summary: "Production database connection pool exhausted",
          type: "bug",
          priority: "highest",
          storyPoints: 1,
          assigneeId: "usr-1",
          sprintId: "sprint-4",
          status: "In Development",
          projectId: "proj-4",
        },
        weight: 1.0,
        description: "Emergency bug created, in sprint, and in development",
      },
    ],
    maxSteps: 20,
    rewardProfile: R10,
    tags: ["create", "transition", "emergency"],
  },
]
