import type { TaskDefinition } from "@thetabench/core"

const R = {
  completion: 2.0,
  partialPerCheck: false,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
}

export const navigationTasks: TaskDefinition[] = [
  {
    id: "jira-nav-001",
    site: "jira",
    domain: "navigation",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 1,
    title: "Navigate to dashboard",
    goal: "Navigate to the Jira dashboard and report what you see.",
    retrievalRubric: {
      question: "What content is on this page?",
      groundTruth:
        "Jira Dashboard with project stats, open issues, and active sprints",
      acceptableVariations: ["dashboard", "Dashboard", "jira dashboard"],
      rubric: "Agent must navigate to the main Jira dashboard page.",
    },
    evalChecks: [],
    maxSteps: 5,
    rewardProfile: R,
    tags: ["navigation"],
  },
  {
    id: "jira-nav-002",
    site: "jira",
    domain: "navigation",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 1,
    title: "Navigate to PLAT board",
    goal: "Navigate to the Platform Engineering (PLAT) board and report the columns you see.",
    retrievalRubric: {
      question: "What columns are on the PLAT board?",
      groundTruth: "Open, In Development, Code Review, QA, Staging, Done",
      acceptableVariations: [
        "6 columns",
        "Open, In Development, Code Review, QA, Staging, Done",
      ],
      rubric:
        "Agent must navigate to the PLAT scrum board and list its workflow columns.",
    },
    evalChecks: [],
    maxSteps: 5,
    rewardProfile: R,
    tags: ["navigation"],
  },
  {
    id: "jira-nav-003",
    site: "jira",
    domain: "navigation",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 1,
    title: "Navigate to PLAT backlog",
    goal: "Navigate to the Platform Engineering project backlog and report the total number of issues.",
    retrievalRubric: {
      question: "How many issues are in the PLAT project?",
      groundTruth: "55",
      acceptableVariations: ["55", "55 issues"],
      rubric:
        "Agent must navigate to PLAT backlog. Platform has 55 issues total (30 stories + 15 bugs + 10 tasks).",
    },
    evalChecks: [],
    maxSteps: 5,
    rewardProfile: R,
    tags: ["navigation"],
  },
  {
    id: "jira-nav-004",
    site: "jira",
    domain: "navigation",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 1,
    title: "Navigate to filters",
    goal: "Navigate to the Saved Filters page and report the filter names.",
    retrievalRubric: {
      question: "What saved filters exist?",
      groundTruth:
        "My Open Issues, PLAT — Release v2.3.0, All Critical Bugs, Sprint 13 — Active, Unassigned Backlog, This Week's Resolved",
      acceptableVariations: [
        "6 filters",
        "My Open Issues, PLAT — Release v2.3.0, All Critical Bugs, Sprint 13 — Active, Unassigned Backlog, This Week's Resolved",
      ],
      rubric: "Agent must navigate to the saved filters list (6 total).",
    },
    evalChecks: [],
    maxSteps: 5,
    rewardProfile: R,
    tags: ["navigation"],
  },
  {
    id: "jira-nav-005",
    site: "jira",
    domain: "navigation",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 1,
    title: "Navigate to project settings",
    goal: "Navigate to the Platform Engineering (PLAT) project settings and report the project type.",
    retrievalRubric: {
      question: "What type is the Platform Engineering project?",
      groundTruth: "scrum",
      acceptableVariations: ["scrum", "Scrum"],
      rubric:
        "Agent must navigate to the PLAT project settings. PLAT is a scrum project.",
    },
    evalChecks: [],
    maxSteps: 5,
    rewardProfile: R,
    tags: ["navigation"],
  },
  {
    id: "jira-nav-006",
    site: "jira",
    domain: "navigation",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 1,
    title: "Navigate to all projects",
    goal: "Navigate to the Projects page and report the project keys.",
    retrievalRubric: {
      question: "What project keys exist?",
      groundTruth: "SUS, SEU, SAP, PLAT, FAPP, MOB, DEVOPS, LCRM",
      acceptableVariations: [
        "8 projects",
        "SUS, SEU, SAP, PLAT, FAPP, MOB, DEVOPS, LCRM",
      ],
      rubric: "Agent must navigate to projects page. 8 projects exist.",
    },
    evalChecks: [],
    maxSteps: 5,
    rewardProfile: R,
    tags: ["navigation"],
  },
]
