import type { TaskDefinition } from "@simbench/core";

const R = {
  completion: 2.0,
  partialPerCheck: false,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
};

export const navigationTasks: TaskDefinition[] = [
  {
    id: "jira-nav-001",
    site: "jira",
    domain: "navigation",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 1,
    title: "Navigate to dashboard",
    goal: "Navigate to the Jira dashboard and report what you see.",
    retrievalRubric: {
      question: "What content is on this page?",
      groundTruth: "Jira Dashboard with project stats, open issues, and active sprints",
      acceptableVariations: ["dashboard", "Dashboard", "jira dashboard"],
      rubric: "Agent must navigate to the main Jira dashboard page.",
    },
    evalChecks: [],
    maxSteps: 5,
    rewardProfile: R,
    tags: ["navigation"],
  },
  {
    id: "jira-nav-002",
    site: "jira",
    domain: "navigation",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 1,
    title: "Navigate to project board",
    goal: "Navigate to the PROJ Board and report the columns you see.",
    retrievalRubric: {
      question: "What columns are on the board?",
      groundTruth: "Backlog, To Do, In Progress, In Review, Done",
      acceptableVariations: ["5 columns", "Backlog, To Do, In Progress, In Review, Done"],
      rubric: "Agent must navigate to the PROJ scrum board and list its columns.",
    },
    evalChecks: [],
    maxSteps: 5,
    rewardProfile: R,
    tags: ["navigation"],
  },
  {
    id: "jira-nav-003",
    site: "jira",
    domain: "navigation",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 1,
    title: "Navigate to backlog",
    goal: "Navigate to the Product Development project backlog and report the number of issues.",
    retrievalRubric: {
      question: "How many issues are in the backlog?",
      groundTruth: "18 issues in the PROJ project",
      acceptableVariations: ["18", "18 issues"],
      rubric: "Agent must navigate to the PROJ backlog view.",
    },
    evalChecks: [],
    maxSteps: 5,
    rewardProfile: R,
    tags: ["navigation"],
  },
  {
    id: "jira-nav-004",
    site: "jira",
    domain: "navigation",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 1,
    title: "Navigate to filters",
    goal: "Navigate to the Saved Filters page and report the filter names.",
    retrievalRubric: {
      question: "What saved filters exist?",
      groundTruth: "My Open Issues, Sprint Bugs, Unassigned Tasks",
      acceptableVariations: ["3 filters", "My Open Issues, Sprint Bugs, Unassigned Tasks"],
      rubric: "Agent must navigate to the saved filters list.",
    },
    evalChecks: [],
    maxSteps: 5,
    rewardProfile: R,
    tags: ["navigation"],
  },
  {
    id: "jira-nav-005",
    site: "jira",
    domain: "navigation",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 1,
    title: "Navigate to project settings",
    goal: "Navigate to the Product Development project settings and report the project type.",
    retrievalRubric: {
      question: "What type is the Product Development project?",
      groundTruth: "scrum",
      acceptableVariations: ["scrum", "Scrum"],
      rubric: "Agent must navigate to the PROJ project settings.",
    },
    evalChecks: [],
    maxSteps: 5,
    rewardProfile: R,
    tags: ["navigation"],
  },
];
