import type { TaskDefinition } from "@thetabench/core"

const R = {
  completion: 2.0,
  partialPerCheck: false,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
}
const R5 = {
  completion: 5.0,
  partialPerCheck: false,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
}

export const retrievalTasks: TaskDefinition[] = [
  {
    id: "jira-ret-001",
    site: "jira",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Issue assignee lookup",
    goal: "Who is assigned to issue PLAT-11?",
    retrievalRubric: {
      question: "Who is assigned to PLAT-11?",
      groundTruth: "Kiran Patel",
      acceptableVariations: ["Kiran Patel", "kiran patel", "usr-5"],
      rubric: "PLAT-11 (iss-2) is assigned to Kiran Patel (usr-5).",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "jira-ret-002",
    site: "jira",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Sprint goal lookup",
    goal: "What is the goal of PLAT Sprint 13 (the active Platform sprint)?",
    retrievalRubric: {
      question: "What is Sprint 13's goal?",
      groundTruth: "Pre-release hardening",
      acceptableVariations: [
        "Pre-release hardening",
        "pre-release hardening for v2.3.0",
      ],
      rubric: "PLAT Sprint 13 (sprint-4) has goal 'Pre-release hardening'.",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "jira-ret-003",
    site: "jira",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 3,
    title: "Epic status lookup",
    goal: "What is the status of the 'Payment API v2' epic?",
    retrievalRubric: {
      question: "What is the Payment API v2 epic status?",
      groundTruth: "In Development",
      acceptableVariations: [
        "In Development",
        "in development",
        "In development",
      ],
      rubric:
        "The Payment API v2 epic (epic-2, PLAT-2) has status 'In Development'.",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "jira-ret-004",
    site: "jira",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 3,
    title: "PLAT done story points total",
    goal: "What is the total story points for all 'Done' issues in the Platform Engineering project?",
    retrievalRubric: {
      question: "Total story points of done PLAT issues?",
      groundTruth: "58",
      acceptableVariations: ["58", "58 points", "fifty-eight"],
      rubric: "PLAT has 15 done issues with a total of 58 story points.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["retrieval", "calculation"],
  },
  {
    id: "jira-ret-005",
    site: "jira",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 4,
    title: "Sprint dates lookup",
    goal: "What are the start and end dates of PLAT Sprint 13 (the active Platform sprint)?",
    retrievalRubric: {
      question: "When does Sprint 13 start and end?",
      groundTruth: "Start: 2026-03-31, End: 2026-04-13",
      acceptableVariations: [
        "March 31 to April 13",
        "2026-03-31 to 2026-04-13",
        "Mar 31 - Apr 13",
      ],
      rubric: "PLAT Sprint 13 (sprint-4) runs from 2026-03-31 to 2026-04-13.",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "jira-ret-006",
    site: "jira",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 4,
    title: "Project lead lookup",
    goal: "Who is the lead of the Frontend App (FAPP) project?",
    retrievalRubric: {
      question: "Who leads the FAPP project?",
      groundTruth: "Sneha Reddy",
      acceptableVariations: ["Sneha Reddy", "sneha reddy", "usr-4"],
      rubric:
        "The Frontend App project (proj-5, FAPP) lead is Sneha Reddy (usr-4).",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "jira-ret-007",
    site: "jira",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Highest priority issue lookup",
    goal: "What is the priority of issue PLAT-58?",
    retrievalRubric: {
      question: "What priority is PLAT-58?",
      groundTruth: "highest",
      acceptableVariations: ["highest", "Highest"],
      rubric:
        "PLAT-58 (iss-39, payment overflow bug from MegaCorp) has priority 'highest'.",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "jira-ret-008",
    site: "jira",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Epic child issue list",
    goal: "List all child issues in the 'Auth Service Overhaul' epic (epic-1, PLAT-1).",
    retrievalRubric: {
      question: "What issues are in the Auth Service Overhaul epic?",
      groundTruth:
        "PLAT-10, PLAT-11, PLAT-12, PLAT-13, PLAT-14, PLAT-15, PLAT-16, PLAT-17",
      acceptableVariations: ["8 issues", "PLAT-10 through PLAT-17"],
      rubric:
        "Auth Service Overhaul epic contains 8 stories: PLAT-10..PLAT-17.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["retrieval", "epic"],
  },
  {
    id: "jira-ret-009",
    site: "jira",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Issue components lookup",
    goal: "What components does issue PLAT-58 belong to?",
    retrievalRubric: {
      question: "What components are on PLAT-58?",
      groundTruth: "Payment Service",
      acceptableVariations: ["Payment Service", "cmp-1"],
      rubric:
        "PLAT-58 (payment overflow bug) is in the 'Payment Service' component.",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "jira-ret-010",
    site: "jira",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Sprint 12 done count",
    goal: "How many issues in PLAT Sprint 12 (sprint-3) are done?",
    retrievalRubric: {
      question: "How many done issues are in PLAT Sprint 12?",
      groundTruth: "6",
      acceptableVariations: ["six", "6 issues"],
      rubric: "PLAT Sprint 12 has 6 done issues (closed sprint).",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["retrieval", "sprint"],
  },
  {
    id: "jira-ret-011",
    site: "jira",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "PLAT-58 cross-platform reference",
    goal: "PLAT-58 is linked to an external Zendesk ticket. Which Zendesk ticket ID does PLAT-58 reference in its description?",
    retrievalRubric: {
      question: "Which Zendesk ticket is referenced in PLAT-58?",
      groundTruth: "ZD-1001",
      acceptableVariations: ["ZD-1001", "MegaCorp ticket ZD-1001"],
      rubric:
        "PLAT-58's description mentions 'Zendesk ticket ZD-1001 from MegaCorp'.",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["retrieval", "cross-platform"],
  },
  {
    id: "jira-ret-012",
    site: "jira",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 3,
    title: "Fix version count",
    goal: "How many fix versions exist for the Platform Engineering project?",
    retrievalRubric: {
      question: "How many PLAT fix versions exist?",
      groundTruth: "5",
      acceptableVariations: ["5", "5 versions", "five"],
      rubric:
        "PLAT has 5 versions: v2.1.0, v2.2.0, v2.2.1 (released), v2.3.0, v2.3.1 (unreleased).",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R,
    tags: ["retrieval", "versions"],
  },
]
