import type { TaskDefinition } from "@simbench/core";

const R = {
  completion: 2.0,
  partialPerCheck: false,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
};
const R5 = {
  completion: 5.0,
  partialPerCheck: false,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
};

export const retrievalTasks: TaskDefinition[] = [
  {
    id: "jira-ret-001",
    site: "jira",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Issue assignee lookup",
    goal: "Who is assigned to issue PROJ-2?",
    retrievalRubric: {
      question: "Who is assigned to PROJ-2?",
      groundTruth: "Jordan Lee",
      acceptableVariations: ["Jordan Lee", "jordan lee", "usr-3"],
      rubric: "PROJ-2 (iss-2) is assigned to Jordan Lee (usr-3).",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "jira-ret-002",
    site: "jira",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Sprint goal lookup",
    goal: "What is the goal of Sprint 13?",
    retrievalRubric: {
      question: "What is Sprint 13's goal?",
      groundTruth: "Complete auth module",
      acceptableVariations: ["Complete auth module", "complete auth module"],
      rubric: "Sprint 13 (sprint-2) has goal 'Complete auth module'.",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "jira-ret-003",
    site: "jira",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 3,
    title: "Epic status lookup",
    goal: "What is the status of the 'Dashboard Redesign' epic?",
    retrievalRubric: {
      question: "What is the Dashboard Redesign epic status?",
      groundTruth: "to_do",
      acceptableVariations: ["to do", "To Do", "to_do"],
      rubric: "The Dashboard Redesign epic (epic-2) has status 'to_do'.",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "jira-ret-004",
    site: "jira",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 3,
    title: "Story points total for done issues",
    goal: "What is the total story points for all 'done' issues?",
    retrievalRubric: {
      question: "Total story points of done issues?",
      // done: iss-1(5)+iss-7(3)+iss-10(5)+iss-19(3) = 16
      groundTruth: "16",
      acceptableVariations: ["16", "16 points", "sixteen"],
      rubric: "Done issues: PROJ-1(5)+PROJ-7(3)+PROJ-10(5)+KANB-1(3) = 16.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["retrieval", "calculation"],
  },
  {
    id: "jira-ret-005",
    site: "jira",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 4,
    title: "Sprint dates lookup",
    goal: "What are the start and end dates of Sprint 13?",
    retrievalRubric: {
      question: "When does Sprint 13 start and end?",
      groundTruth: "Start: 2025-04-15, End: 2025-04-28",
      acceptableVariations: [
        "April 15 to April 28",
        "2025-04-15 to 2025-04-28",
        "Apr 15 - Apr 28",
      ],
      rubric: "Sprint 13 runs from 2025-04-15 to 2025-04-28.",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "jira-ret-006",
    site: "jira",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 4,
    title: "Project lead lookup",
    goal: "Who is the lead of the Marketing Kanban project?",
    retrievalRubric: {
      question: "Who leads the Marketing Kanban project?",
      groundTruth: "Sam Williams",
      acceptableVariations: ["Sam Williams", "sam williams", "usr-2"],
      rubric: "The Marketing Kanban project (proj-2) lead is Sam Williams (usr-2).",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "jira-ret-007",
    site: "jira",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Issue priority lookup",
    goal: "What is the priority of issue PROJ-3?",
    retrievalRubric: {
      question: "What priority is PROJ-3?",
      groundTruth: "highest",
      acceptableVariations: ["highest", "Highest"],
      rubric: "PROJ-3 (iss-3) has priority 'highest'.",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "jira-ret-008",
    site: "jira",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Epic issue list",
    goal: "List all issues in the 'Campaign Tracker' epic (epic-3).",
    retrievalRubric: {
      question: "What issues are in the Campaign Tracker epic?",
      // epic-3: iss-19(KANB-1), iss-20(KANB-2), iss-22(KANB-4), iss-23(KANB-5) = 4
      groundTruth: "KANB-1, KANB-2, KANB-4, KANB-5",
      acceptableVariations: ["4 issues", "KANB-1, KANB-2, KANB-4, KANB-5"],
      rubric: "Campaign Tracker epic contains KANB-1, KANB-2, KANB-4, KANB-5.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["retrieval", "epic"],
  },
  {
    id: "jira-ret-009",
    site: "jira",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Issue labels lookup",
    goal: "What labels does issue PROJ-2 have?",
    retrievalRubric: {
      question: "What labels are on PROJ-2?",
      groundTruth: "backend, auth",
      acceptableVariations: ["backend and auth", "auth, backend"],
      rubric: "PROJ-2 (iss-2) has labels: backend, auth.",
    },
    evalChecks: [],
    maxSteps: 10,
    rewardProfile: R,
    tags: ["retrieval"],
  },
  {
    id: "jira-ret-010",
    site: "jira",
    domain: "retrieval",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Sprint closed issues",
    goal: "How many issues in Sprint 12 (sprint-1) are done?",
    retrievalRubric: {
      question: "How many done issues are in Sprint 12?",
      // sprint-1 issues: iss-1(done), iss-7(done), iss-10(done) = 3 total in sprint, all done
      groundTruth: "3",
      acceptableVariations: ["three", "3 issues", "all 3"],
      rubric: "Sprint 12 has 3 issues (PROJ-1, PROJ-7, PROJ-10) and all are done.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["retrieval", "sprint"],
  },
];
