import type { TaskDefinition } from "@thetabench/core"

const R = {
  completion: 5.0,
  partialPerCheck: false,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
}
const RH = {
  completion: 8.0,
  partialPerCheck: false,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.1,
}

export const searchTasks: TaskDefinition[] = [
  {
    id: "jira-srch-001",
    site: "jira",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Find issues by assignee",
    goal: "How many issues are assigned to Ravi Kumar (usr-3)?",
    retrievalRubric: {
      question: "How many issues are assigned to Ravi Kumar?",
      groundTruth: "34",
      acceptableVariations: ["34", "34 issues", "thirty-four"],
      rubric:
        "Ravi Kumar (usr-3) is assigned to 34 issues across PLAT (10) and Support projects (24 as default assignee round-robin).",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["retrieval", "counting"],
  },
  {
    id: "jira-srch-002",
    site: "jira",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Find issues in active sprint",
    goal: "How many issues are in PLAT Sprint 13 (the active sprint)?",
    retrievalRubric: {
      question: "How many issues are in PLAT Sprint 13?",
      groundTruth: "19",
      acceptableVariations: ["19", "19 issues"],
      rubric:
        "PLAT Sprint 13 (sprint-4) contains 19 issues: 10 stories + 5 bugs + 4 tasks.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["retrieval", "sprint"],
  },
  {
    id: "jira-srch-003",
    site: "jira",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Find issues by epic",
    goal: "How many issues are in the 'Auth Service Overhaul' epic (epic-1)?",
    retrievalRubric: {
      question: "How many issues are in the Auth Service Overhaul epic?",
      groundTruth: "8",
      acceptableVariations: ["eight", "8 issues"],
      rubric:
        "Epic-1 (Auth Service Overhaul) has 8 issues: PLAT-10 through PLAT-17.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["retrieval", "epic"],
  },
  {
    id: "jira-srch-004",
    site: "jira",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Find issues by type — stories",
    goal: "How many story-type issues exist across all projects?",
    retrievalRubric: {
      question: "How many stories are there?",
      groundTruth: "117",
      acceptableVariations: ["117", "117 stories"],
      rubric: "117 stories across all projects (mostly in PLAT and LCRM).",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["retrieval", "counting"],
  },
  {
    id: "jira-srch-005",
    site: "jira",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Count bugs",
    goal: "How many bug-type issues exist across all projects?",
    retrievalRubric: {
      question: "How many bugs are there?",
      groundTruth: "88",
      acceptableVariations: ["88", "88 bugs"],
      rubric:
        "88 bugs across all projects — mostly LCRM (70) plus 15 in PLAT and some in FAPP.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["retrieval", "counting"],
  },
  {
    id: "jira-srch-006",
    site: "jira",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Find unestimated issues",
    goal: "How many issues have no story points set (null)?",
    retrievalRubric: {
      question: "How many issues are unestimated?",
      groundTruth: "193",
      acceptableVariations: ["193", "193 issues"],
      rubric:
        "193 issues have null story points — bugs, tasks, and most LCRM/Support issues.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["retrieval", "estimation"],
  },
  {
    id: "jira-srch-007",
    site: "jira",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Sprint velocity calculation",
    goal: "What is the total story points for all issues in PLAT Sprint 13 (sprint-4)?",
    retrievalRubric: {
      question: "What is the total story points in PLAT Sprint 13?",
      groundTruth: "59",
      acceptableVariations: ["59", "59 points", "fifty-nine"],
      rubric: "PLAT Sprint 13 contains 19 issues totaling 59 story points.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: RH,
    tags: ["retrieval", "calculation"],
  },
  {
    id: "jira-srch-008",
    site: "jira",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Find highest priority issues",
    goal: "Which issues have 'Highest' priority? List their keys.",
    retrievalRubric: {
      question: "Which issues have highest priority?",
      groundTruth: "PLAT-51, PLAT-56, PLAT-58, PLAT-64",
      acceptableVariations: ["4 issues", "PLAT-51, PLAT-56, PLAT-58, PLAT-64"],
      rubric:
        "4 highest-priority bugs: PLAT-51 (webhook timeout), PLAT-56 (DB connection leak), PLAT-58 (payment overflow), PLAT-64 (duplicate payment events).",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["retrieval", "priority"],
  },
  {
    id: "jira-srch-009",
    site: "jira",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Find unassigned issues",
    goal: "How many issues are unassigned (no assignee) across the workspace?",
    retrievalRubric: {
      question: "How many issues are unassigned?",
      groundTruth: "54",
      acceptableVariations: ["54", "54 issues"],
      rubric: "54 issues have null assignee.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["retrieval", "counting"],
  },
  {
    id: "jira-srch-010",
    site: "jira",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "LCRM project issue count",
    goal: "How many total issues are in the Legacy CRM (LCRM) project?",
    retrievalRubric: {
      question: "How many issues are in the LCRM project?",
      groundTruth: "214",
      acceptableVariations: ["214", "214 issues"],
      rubric:
        "The LCRM project has 214 issues (legacy inherited backlog for migration).",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["retrieval", "counting"],
  },
  {
    id: "jira-srch-011",
    site: "jira",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Support project total",
    goal: "How many issues are across all three Support projects (SUS + SEU + SAP)?",
    retrievalRubric: {
      question: "How many Support issues total?",
      groundTruth: "90",
      acceptableVariations: ["90", "90 issues"],
      rubric:
        "Each Support project has 30 issues: SUS=30, SEU=30, SAP=30 = 90 total.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["retrieval", "counting"],
  },
]
