import type { TaskDefinition } from "@simbench/core";

const R = {
  completion: 5.0,
  partialPerCheck: false,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
};
const RH = {
  completion: 8.0,
  partialPerCheck: false,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.1,
};

export const searchTasks: TaskDefinition[] = [
  {
    id: "jira-srch-001",
    site: "jira",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Find issues by assignee",
    goal: "How many issues are assigned to Sam Williams (usr-2)?",
    retrievalRubric: {
      question: "How many issues are assigned to Sam Williams?",
      // iss-3(PROJ-3), iss-9(PROJ-9), iss-19(KANB-1), iss-20(KANB-2), iss-24(KANB-6) = 5
      groundTruth: "5",
      acceptableVariations: ["five", "5 issues"],
      rubric: "Sam Williams (usr-2) is assigned to PROJ-3, PROJ-9, KANB-1, KANB-2, KANB-6 = 5 issues.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["retrieval", "counting"],
  },
  {
    id: "jira-srch-002",
    site: "jira",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Find issues in active sprint",
    goal: "List all issues in the active sprint (Sprint 13). What are their keys?",
    retrievalRubric: {
      question: "What issues are in Sprint 13?",
      // sprint-2 issues: iss-2(PROJ-2), iss-3(PROJ-3), iss-4(PROJ-4), iss-5(PROJ-5), iss-9(PROJ-9), iss-11(PROJ-11), iss-12(PROJ-12) = 7
      groundTruth: "PROJ-2, PROJ-3, PROJ-4, PROJ-5, PROJ-9, PROJ-11, PROJ-12",
      acceptableVariations: ["7 issues", "7"],
      rubric: "Sprint 13 (sprint-2) contains 7 issues: PROJ-2, PROJ-3, PROJ-4, PROJ-5, PROJ-9, PROJ-11, PROJ-12.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["retrieval", "sprint"],
  },
  {
    id: "jira-srch-003",
    site: "jira",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Find issues by epic",
    goal: "How many issues are in the 'User Authentication' epic (epic-1)?",
    retrievalRubric: {
      question: "How many issues are in the User Authentication epic?",
      // epic-1: iss-1, iss-2, iss-3, iss-4, iss-5, iss-6, iss-11, iss-12, iss-15 = 9
      groundTruth: "9",
      acceptableVariations: ["nine", "9 issues"],
      rubric: "Epic-1 has 9 issues: PROJ-1, PROJ-2, PROJ-3, PROJ-4, PROJ-5, PROJ-6, PROJ-11, PROJ-12, PROJ-15.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["retrieval", "epic"],
  },
  {
    id: "jira-srch-004",
    site: "jira",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Find issues by type",
    goal: "How many story-type issues exist across all projects?",
    retrievalRubric: {
      question: "How many stories are there?",
      // stories: iss-1, iss-2, iss-5, iss-8, iss-14, iss-18, iss-24 = 7
      groundTruth: "7",
      acceptableVariations: ["seven", "7 stories"],
      rubric: "There are 7 stories: PROJ-1, PROJ-2, PROJ-5, PROJ-8, PROJ-14, PROJ-18, KANB-6.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["retrieval", "counting"],
  },
  {
    id: "jira-srch-005",
    site: "jira",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Count bugs",
    goal: "How many bug-type issues exist across all projects?",
    retrievalRubric: {
      question: "How many bugs are there?",
      // bugs: iss-3(PROJ-3), iss-9(PROJ-9), iss-15(PROJ-15), iss-23(KANB-5) = 4
      groundTruth: "4",
      acceptableVariations: ["four", "4 bugs"],
      rubric: "There are 4 bugs: PROJ-3, PROJ-9, PROJ-15, KANB-5.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["retrieval", "counting"],
  },
  {
    id: "jira-srch-006",
    site: "jira",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Find unestimated issues",
    goal: "Which issues have no story points set (null)? List their keys.",
    retrievalRubric: {
      question: "Which issues are unestimated?",
      // null storyPoints: iss-13(PROJ-13), iss-14(PROJ-14), iss-18(PROJ-18) = 3
      groundTruth: "PROJ-13, PROJ-14, PROJ-18",
      acceptableVariations: ["3 issues", "3", "PROJ-13, PROJ-14, PROJ-18"],
      rubric: "Three issues have null story points: PROJ-13, PROJ-14, PROJ-18.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["retrieval", "estimation"],
  },
  {
    id: "jira-srch-007",
    site: "jira",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Sprint velocity calculation",
    goal: "What is the total story points for all issues in Sprint 13 (sprint-2)?",
    retrievalRubric: {
      question: "What is the total story points in Sprint 13?",
      // sprint-2: iss-2(8)+iss-3(3)+iss-4(5)+iss-5(8)+iss-9(2)+iss-11(5)+iss-12(3) = 34
      groundTruth: "34",
      acceptableVariations: ["34 points", "34 story points", "thirty-four"],
      rubric: "Sprint 13 total: 8+3+5+8+2+5+3 = 34 story points.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: RH,
    tags: ["retrieval", "calculation"],
  },
  {
    id: "jira-srch-008",
    site: "jira",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Find highest priority issues",
    goal: "Which issues have 'Highest' priority? List their keys.",
    retrievalRubric: {
      question: "Which issues have highest priority?",
      // highest: iss-3(PROJ-3), iss-23(KANB-5) = 2
      groundTruth: "PROJ-3, KANB-5",
      acceptableVariations: ["2 issues", "PROJ-3 and KANB-5"],
      rubric: "Two issues have highest priority: PROJ-3 and KANB-5.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["retrieval", "priority"],
  },
  {
    id: "jira-srch-009",
    site: "jira",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Find unassigned issues",
    goal: "How many issues are unassigned (no assignee)?",
    retrievalRubric: {
      question: "How many issues are unassigned?",
      // null assigneeId: iss-5, iss-13, iss-14, iss-18, iss-23 = 5
      groundTruth: "5",
      acceptableVariations: ["five", "5 issues"],
      rubric: "Five issues are unassigned: PROJ-5, PROJ-13, PROJ-14, PROJ-18, KANB-5.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["retrieval", "counting"],
  },
  {
    id: "jira-srch-010",
    site: "jira",
    domain: "search",
    type: "retrieval",
    difficulty: "medium",
    curriculumStage: 6,
    title: "KANB project issue count",
    goal: "How many total issues are in the Marketing Kanban project (KANB)?",
    retrievalRubric: {
      question: "How many issues are in the KANB project?",
      groundTruth: "7",
      acceptableVariations: ["seven", "7 issues"],
      rubric: "The KANB project has 7 issues: KANB-1 through KANB-7.",
    },
    evalChecks: [],
    maxSteps: 15,
    rewardProfile: R,
    tags: ["retrieval", "counting"],
  },
];
