import type { TaskDefinition } from "@simbench/core";

const R5 = {
  completion: 5.0,
  partialPerCheck: true,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
};
const R8 = {
  completion: 8.0,
  partialPerCheck: true,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.2,
};
const R10 = {
  completion: 10.0,
  partialPerCheck: true,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.2,
};

export const sprintTasks: TaskDefinition[] = [
  // ---------------------------------------------------------------------------
  // Stage 3 — basic sprint operations
  // ---------------------------------------------------------------------------
  {
    id: "jira-spr-001",
    site: "jira",
    domain: "sprints",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Create a sprint",
    goal: "Create a new sprint named 'Sprint 15' in project PROJ with goal 'Performance optimization'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "sprint_has_state",
        id: "sprint-4",
        expected: "future",
        weight: 1.0,
        description: "Sprint 15 exists in future state",
      },
    ],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["create", "sprint"],
  },
  {
    id: "jira-spr-002",
    site: "jira",
    domain: "sprints",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Move issue to sprint",
    goal: "Move issue PROJ-13 (iss-13) into Sprint 13 (sprint-2).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_in_sprint",
        id: "iss-13",
        expected: "sprint-2",
        weight: 1.0,
        description: "PROJ-13 is in sprint-2",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["sprint", "move"],
  },

  // ---------------------------------------------------------------------------
  // Stage 5 — sprint lifecycle
  // ---------------------------------------------------------------------------
  {
    id: "jira-spr-003",
    site: "jira",
    domain: "sprints",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Complete active sprint",
    goal: "Complete Sprint 13 (sprint-2), the currently active sprint.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "sprint_has_state",
        id: "sprint-2",
        expected: "closed",
        weight: 1.0,
        description: "Sprint 13 is closed",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["sprint", "complete"],
  },
  {
    id: "jira-spr-004",
    site: "jira",
    domain: "sprints",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Move multiple issues to sprint",
    goal: "Move issues PROJ-13 (iss-13) and PROJ-14 (iss-14) into Sprint 14 (sprint-3).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_in_sprint",
        id: "iss-13",
        expected: "sprint-3",
        weight: 0.5,
        description: "PROJ-13 is in sprint-3",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_sprint",
        id: "iss-14",
        expected: "sprint-3",
        weight: 0.5,
        description: "PROJ-14 is in sprint-3",
      },
    ],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["sprint", "bulk"],
  },
  {
    id: "jira-spr-005",
    site: "jira",
    domain: "sprints",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Remove issue from sprint",
    goal: "Remove issue PROJ-5 (iss-5) from Sprint 13 (sprint-2) back to the backlog (no sprint).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_in_sprint",
        id: "iss-5",
        expected: null,
        weight: 1.0,
        description: "PROJ-5 has no sprint (backlog)",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["sprint", "move"],
  },

  // ---------------------------------------------------------------------------
  // Stage 7 — complex sprint workflows
  // ---------------------------------------------------------------------------
  {
    id: "jira-spr-006",
    site: "jira",
    domain: "sprints",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Start future sprint",
    goal: "First complete Sprint 13 (sprint-2), then start Sprint 14 (sprint-3).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "sprint_has_state",
        id: "sprint-2",
        expected: "closed",
        weight: 0.5,
        description: "Sprint 13 is closed",
      },
      {
        type: "state_predicate",
        predicate: "sprint_has_state",
        id: "sprint-3",
        expected: "active",
        weight: 0.5,
        description: "Sprint 14 is active",
      },
    ],
    maxSteps: 15,
    rewardProfile: R8,
    tags: ["sprint", "lifecycle", "multi-step"],
  },
  {
    id: "jira-spr-007",
    site: "jira",
    domain: "sprints",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Plan sprint with issues",
    goal: "Create a new sprint 'Sprint 15' in PROJ with goal 'Bug fixes'. Then move issues PROJ-15 (iss-15) and PROJ-13 (iss-13) into it.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "sprint_has_state",
        id: "sprint-4",
        expected: "future",
        weight: 0.34,
        description: "Sprint 15 exists",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_sprint",
        id: "iss-15",
        expected: "sprint-4",
        weight: 0.33,
        description: "PROJ-15 is in sprint-4",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_sprint",
        id: "iss-13",
        expected: "sprint-4",
        weight: 0.33,
        description: "PROJ-13 is in sprint-4",
      },
    ],
    maxSteps: 20,
    rewardProfile: R10,
    tags: ["sprint", "create", "multi-step"],
  },
  {
    id: "jira-spr-008",
    site: "jira",
    domain: "sprints",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Close sprint and move incomplete",
    goal: "Complete Sprint 13 (sprint-2), then move all incomplete issues (not 'done') from sprint-2 to Sprint 14 (sprint-3). Incomplete sprint-2 issues: PROJ-2 (iss-2), PROJ-3 (iss-3), PROJ-4 (iss-4), PROJ-5 (iss-5), PROJ-9 (iss-9), PROJ-11 (iss-11), PROJ-12 (iss-12).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "sprint_has_state",
        id: "sprint-2",
        expected: "closed",
        weight: 0.2,
        description: "Sprint 13 is closed",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_sprint",
        id: "iss-2",
        expected: "sprint-3",
        weight: 0.12,
        description: "PROJ-2 moved to sprint-3",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_sprint",
        id: "iss-3",
        expected: "sprint-3",
        weight: 0.11,
        description: "PROJ-3 moved to sprint-3",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_sprint",
        id: "iss-4",
        expected: "sprint-3",
        weight: 0.11,
        description: "PROJ-4 moved to sprint-3",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_sprint",
        id: "iss-5",
        expected: "sprint-3",
        weight: 0.12,
        description: "PROJ-5 moved to sprint-3",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_sprint",
        id: "iss-9",
        expected: "sprint-3",
        weight: 0.11,
        description: "PROJ-9 moved to sprint-3",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_sprint",
        id: "iss-11",
        expected: "sprint-3",
        weight: 0.12,
        description: "PROJ-11 moved to sprint-3",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_sprint",
        id: "iss-12",
        expected: "sprint-3",
        weight: 0.11,
        description: "PROJ-12 moved to sprint-3",
      },
    ],
    maxSteps: 30,
    rewardProfile: R10,
    tags: ["sprint", "bulk", "lifecycle"],
  },
  {
    id: "jira-spr-009",
    site: "jira",
    domain: "sprints",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Sprint scope adjustment",
    goal: "Remove PROJ-5 (iss-5, 8 pts) from Sprint 13 (sprint-2) and replace it with PROJ-15 (iss-15, 1 pt) to reduce sprint scope.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_in_sprint",
        id: "iss-5",
        expected: null,
        weight: 0.5,
        description: "PROJ-5 removed from sprint",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_sprint",
        id: "iss-15",
        expected: "sprint-2",
        weight: 0.5,
        description: "PROJ-15 added to sprint-2",
      },
    ],
    maxSteps: 15,
    rewardProfile: R8,
    tags: ["sprint", "move", "planning"],
  },
  {
    id: "jira-spr-010",
    site: "jira",
    domain: "sprints",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Create and populate sprint",
    goal: "Create sprint 'Sprint 15' in PROJ with goal 'Tech debt cleanup'. Add PROJ-13 (iss-13), PROJ-14 (iss-14), and PROJ-18 (iss-18) to it. Set story points: PROJ-13 = 5, PROJ-14 = 3, PROJ-18 = 8.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "sprint_has_state",
        id: "sprint-4",
        expected: "future",
        weight: 0.15,
        description: "Sprint 15 exists",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-13",
        expected: { sprintId: "sprint-4", storyPoints: 5 },
        weight: 0.28,
        description: "PROJ-13 in sprint with 5 pts",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-14",
        expected: { sprintId: "sprint-4", storyPoints: 3 },
        weight: 0.28,
        description: "PROJ-14 in sprint with 3 pts",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-18",
        expected: { sprintId: "sprint-4", storyPoints: 8 },
        weight: 0.29,
        description: "PROJ-18 in sprint with 8 pts",
      },
    ],
    maxSteps: 25,
    rewardProfile: R10,
    tags: ["sprint", "create", "bulk", "estimation"],
  },
];
