import type { TaskDefinition } from "@thetabench/core"

const R5 = {
  completion: 5.0,
  partialPerCheck: true,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
}
const R8 = {
  completion: 8.0,
  partialPerCheck: true,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.2,
}
const R10 = {
  completion: 10.0,
  partialPerCheck: true,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.2,
}

// Sprint reference (new CESS data):
//   sprint-1 PLAT Sprint 10  closed
//   sprint-2 PLAT Sprint 11  closed
//   sprint-3 PLAT Sprint 12  closed
//   sprint-4 PLAT Sprint 13  active    (benchmark day 2026-04-13)
//   sprint-5 PLAT Sprint 14  future

export const sprintTasks: TaskDefinition[] = [
  // ---------------------------------------------------------------------------
  // Stage 3 — basic sprint operations
  // ---------------------------------------------------------------------------
  {
    id: "jira-spr-001",
    site: "jira",
    domain: "sprints",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Create a sprint",
    goal: "Create a new sprint named 'PLAT Sprint 15' in project PLAT with goal 'Performance optimization'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "sprint_has_state",
        id: "sprint-6",
        expected: "future",
        weight: 1.0,
        description: "PLAT Sprint 15 exists in future state",
      },
    ],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["create", "sprint"],
  },
  {
    id: "jira-spr-002",
    site: "jira",
    domain: "sprints",
    type: "action",
    difficulty: "medium",
    curriculumStage: 3,
    title: "Move issue to sprint",
    goal: "Move issue PLAT-17 (iss-8, currently with no sprint) into PLAT Sprint 13 (sprint-4).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_in_sprint",
        id: "iss-8",
        expected: "sprint-4",
        weight: 1.0,
        description: "PLAT-17 is in sprint-4",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["sprint", "move"],
  },

  // ---------------------------------------------------------------------------
  // Stage 5 — sprint lifecycle
  // ---------------------------------------------------------------------------
  {
    id: "jira-spr-003",
    site: "jira",
    domain: "sprints",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Complete active sprint",
    goal: "Complete PLAT Sprint 13 (sprint-4), the currently active sprint.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "sprint_has_state",
        id: "sprint-4",
        expected: "closed",
        weight: 1.0,
        description: "PLAT Sprint 13 is closed",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["sprint", "complete"],
  },
  {
    id: "jira-spr-004",
    site: "jira",
    domain: "sprints",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Move multiple issues to sprint",
    goal: "Move issues PLAT-15 (iss-6) and PLAT-17 (iss-8) into PLAT Sprint 14 (sprint-5).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_in_sprint",
        id: "iss-6",
        expected: "sprint-5",
        weight: 0.5,
        description: "PLAT-15 is in sprint-5",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_sprint",
        id: "iss-8",
        expected: "sprint-5",
        weight: 0.5,
        description: "PLAT-17 is in sprint-5",
      },
    ],
    maxSteps: 15,
    rewardProfile: R5,
    tags: ["sprint", "bulk"],
  },
  {
    id: "jira-spr-005",
    site: "jira",
    domain: "sprints",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Remove issue from sprint",
    goal: "Remove issue PLAT-14 (iss-5) from PLAT Sprint 12 (sprint-3) back to the backlog.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_in_sprint",
        id: "iss-5",
        expected: null,
        weight: 1.0,
        description: "PLAT-14 has no sprint (backlog)",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["sprint", "move"],
  },

  // ---------------------------------------------------------------------------
  // Stage 7 — complex sprint workflows
  // ---------------------------------------------------------------------------
  {
    id: "jira-spr-006",
    site: "jira",
    domain: "sprints",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Close Sprint 13 and start Sprint 14",
    goal: "First complete PLAT Sprint 13 (sprint-4), then start PLAT Sprint 14 (sprint-5).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "sprint_has_state",
        id: "sprint-4",
        expected: "closed",
        weight: 0.5,
        description: "PLAT Sprint 13 is closed",
      },
      {
        type: "state_predicate",
        predicate: "sprint_has_state",
        id: "sprint-5",
        expected: "active",
        weight: 0.5,
        description: "PLAT Sprint 14 is active",
      },
    ],
    maxSteps: 15,
    rewardProfile: R8,
    tags: ["sprint", "lifecycle", "multi-step"],
  },
  {
    id: "jira-spr-007",
    site: "jira",
    domain: "sprints",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Plan sprint with issues",
    goal: "Create a new sprint 'PLAT Sprint 15' in PLAT with goal 'Bug fixes'. Then move issues PLAT-15 (iss-6) and PLAT-17 (iss-8) into it.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "sprint_has_state",
        id: "sprint-6",
        expected: "future",
        weight: 0.34,
        description: "PLAT Sprint 15 exists",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_sprint",
        id: "iss-6",
        expected: "sprint-6",
        weight: 0.33,
        description: "PLAT-15 is in sprint-6",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_sprint",
        id: "iss-8",
        expected: "sprint-6",
        weight: 0.33,
        description: "PLAT-17 is in sprint-6",
      },
    ],
    maxSteps: 20,
    rewardProfile: R10,
    tags: ["sprint", "create", "multi-step"],
  },
  {
    id: "jira-spr-008",
    site: "jira",
    domain: "sprints",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Close sprint and move incomplete",
    goal: "Complete PLAT Sprint 13 (sprint-4), then move all incomplete issues (status not 'Done') from sprint-4 to PLAT Sprint 14 (sprint-5). Incomplete in sprint-4: PLAT-11 (iss-2), PLAT-12 (iss-3), PLAT-16 (iss-7), PLAT-19 (iss-10), PLAT-21 (iss-12), PLAT-28 (iss-19).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "sprint_has_state",
        id: "sprint-4",
        expected: "closed",
        weight: 0.3,
        description: "Sprint 13 closed",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_sprint",
        id: "iss-2",
        expected: "sprint-5",
        weight: 0.12,
        description: "PLAT-11 moved",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_sprint",
        id: "iss-3",
        expected: "sprint-5",
        weight: 0.12,
        description: "PLAT-12 moved",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_sprint",
        id: "iss-7",
        expected: "sprint-5",
        weight: 0.12,
        description: "PLAT-16 moved",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_sprint",
        id: "iss-10",
        expected: "sprint-5",
        weight: 0.12,
        description: "PLAT-19 moved",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_sprint",
        id: "iss-12",
        expected: "sprint-5",
        weight: 0.11,
        description: "PLAT-21 moved",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_sprint",
        id: "iss-19",
        expected: "sprint-5",
        weight: 0.11,
        description: "PLAT-28 moved",
      },
    ],
    maxSteps: 30,
    rewardProfile: R10,
    tags: ["sprint", "bulk", "lifecycle"],
  },
  {
    id: "jira-spr-009",
    site: "jira",
    domain: "sprints",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Sprint scope adjustment",
    goal: "Remove PLAT-16 (iss-7, 8 pts) from PLAT Sprint 13 (sprint-4) and add PLAT-17 (iss-8, 5 pts) in its place to reduce sprint scope.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "issue_in_sprint",
        id: "iss-7",
        expected: null,
        weight: 0.5,
        description: "PLAT-16 removed from sprint",
      },
      {
        type: "state_predicate",
        predicate: "issue_in_sprint",
        id: "iss-8",
        expected: "sprint-4",
        weight: 0.5,
        description: "PLAT-17 added to sprint-4",
      },
    ],
    maxSteps: 15,
    rewardProfile: R8,
    tags: ["sprint", "move", "planning"],
  },
  {
    id: "jira-spr-010",
    site: "jira",
    domain: "sprints",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Create and populate sprint",
    goal: "Create sprint 'PLAT Sprint 15' in PLAT with goal 'Tech debt cleanup'. Add PLAT-15 (iss-6), PLAT-17 (iss-8), and PLAT-29 (iss-20) to it. Set story points: PLAT-15 = 5, PLAT-17 = 3, PLAT-29 = 8.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "sprint_has_state",
        id: "sprint-6",
        expected: "future",
        weight: 0.15,
        description: "PLAT Sprint 15 exists",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-6",
        expected: { sprintId: "sprint-6", storyPoints: 5 },
        weight: 0.28,
        description: "PLAT-15 in sprint with 5 pts",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-8",
        expected: { sprintId: "sprint-6", storyPoints: 3 },
        weight: 0.28,
        description: "PLAT-17 in sprint with 3 pts",
      },
      {
        type: "state_predicate",
        predicate: "issue_has_fields",
        id: "iss-20",
        expected: { sprintId: "sprint-6", storyPoints: 8 },
        weight: 0.29,
        description: "PLAT-29 in sprint with 8 pts",
      },
    ],
    maxSteps: 25,
    rewardProfile: R10,
    tags: ["sprint", "create", "bulk", "estimation"],
  },
]
