import type { TaskDefinition } from "@thetabench/core"

const R5 = {
  completion: 5.0,
  partialPerCheck: true,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
}

// Domain note: ThetaCore's TaskDomain union does not include "agents" —
// these are agent / group routing tasks, mapped to the closest available
// domain "teams".
export const agentTasks: TaskDefinition[] = [
  {
    id: "zen-agt-001",
    site: "zendesk",
    domain: "teams",
    type: "action",
    difficulty: "easy",
    curriculumStage: 3,
    title: "Reassign ticket to billing agent",
    goal: "Reassign ticket tic-19 (phone callback) from usr-4 to billing agent usr-3, and route it to the Billing group (grp-2).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "ticket_has_assignee",
        id: "tic-19",
        expected: "usr-3",
        weight: 0.5,
        description: "assignee changed",
      },
      {
        type: "state_diff",
        entity: "tickets",
        id: "tic-19",
        field: "groupId",
        expected: "grp-2",
        weight: 0.5,
        description: "group changed",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["assign", "routing"],
  },
  {
    id: "zen-agt-002",
    site: "zendesk",
    domain: "teams",
    type: "action",
    difficulty: "medium",
    curriculumStage: 4,
    title: "Add a new support group",
    goal: "Create a new group named 'Enterprise Support' with description 'Dedicated enterprise queue.'",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "group_exists_with_name",
        expected: "Enterprise Support",
        weight: 1.0,
        description: "group created",
      },
    ],
    maxSteps: 8,
    rewardProfile: R5,
    tags: ["create", "groups"],
  },
  {
    id: "zen-agt-003",
    site: "zendesk",
    domain: "teams",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Unassign and re-route a stale ticket",
    goal: "On ticket tic-23 (bulk import fails): unassign the current agent (set assigneeId to null) and route the ticket to the Triage group (grp-3).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "ticket_has_assignee",
        id: "tic-23",
        expected: null,
        weight: 0.5,
        description: "ticket is unassigned",
      },
      {
        type: "state_diff",
        entity: "tickets",
        id: "tic-23",
        field: "groupId",
        expected: "grp-3",
        weight: 0.5,
        description: "ticket routed to triage",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["unassign", "routing"],
  },
  {
    id: "zen-agt-004",
    site: "zendesk",
    domain: "teams",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Take ownership of an unassigned ticket",
    goal: "Assign yourself (admin usr-1) to ticket tic-18 (search returns no results).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "ticket_has_assignee",
        id: "tic-18",
        expected: "usr-1",
        weight: 1.0,
        description: "ticket owned by usr-1",
      },
    ],
    maxSteps: 8,
    rewardProfile: R5,
    tags: ["assign"],
  },
  {
    id: "zen-agt-005",
    site: "zendesk",
    domain: "teams",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Onboard a new customer contact",
    goal: "Create a new end-user contact named 'Avery Kim' with email 'avery.kim@example.com' for the organization 'Acme Corp.'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "user_exists_with_email",
        expected: "avery.kim@example.com",
        weight: 1.0,
        description: "contact created",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["create", "contacts"],
  },
]
