import type { TaskDefinition } from "@thetabench/core"

const R5 = {
  completion: 5.0,
  partialPerCheck: true,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
}

// Domain note: ThetaCore's TaskDomain union does not include "macros" —
// these saved-reply tasks map to the closest domain "lists".
export const macroTasks: TaskDefinition[] = [
  {
    id: "zen-mac-001",
    site: "zendesk",
    domain: "lists",
    type: "action",
    difficulty: "easy",
    curriculumStage: 3,
    title: "Create a follow-up macro",
    goal: "Create a new macro titled 'Awaiting customer info' with body 'We've followed up but haven't heard back — let us know if you'd still like help.' (active = true).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "macro_exists_with_title",
        expected: "Awaiting customer info",
        weight: 1.0,
        description: "macro created",
      },
    ],
    maxSteps: 8,
    rewardProfile: R5,
    tags: ["create", "macros"],
  },
  {
    id: "zen-mac-002",
    site: "zendesk",
    domain: "lists",
    type: "action",
    difficulty: "easy",
    curriculumStage: 3,
    title: "Activate a deactivated macro",
    goal: "Set the macro mac-5 ('Unable to reproduce') back to active (true).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "macro_active",
        id: "mac-5",
        expected: true,
        weight: 1.0,
        description: "mac-5 is active",
      },
    ],
    maxSteps: 6,
    rewardProfile: R5,
    tags: ["update", "macros"],
  },
  {
    id: "zen-mac-003",
    site: "zendesk",
    domain: "lists",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Apply a macro and resolve",
    goal: "On ticket tic-16 (CSV export how-to): add a public comment from usr-2 with the body of macro mac-4 ('Glad we could help. Closing this ticket — feel free to reopen if anything else comes up.') and transition the ticket to 'closed'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "ticket_has_public_comment_from",
        id: "tic-16",
        expected: "usr-2",
        weight: 0.5,
        description: "comment from usr-2",
      },
      {
        type: "state_predicate",
        predicate: "ticket_has_status",
        id: "tic-16",
        expected: "closed",
        weight: 0.5,
        description: "ticket closed",
      },
    ],
    maxSteps: 12,
    rewardProfile: R5,
    tags: ["macros", "multi-step"],
  },
  {
    id: "zen-mac-004",
    site: "zendesk",
    domain: "lists",
    type: "action",
    difficulty: "medium",
    curriculumStage: 4,
    title: "Rename a macro",
    goal: "Rename macro mac-1 from 'Acknowledge receipt' to 'Acknowledge new ticket'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "macro_has_title",
        id: "mac-1",
        expected: "Acknowledge new ticket",
        weight: 1.0,
        description: "macro title updated",
      },
    ],
    maxSteps: 6,
    rewardProfile: R5,
    tags: ["update", "macros"],
  },
  {
    id: "zen-mac-005",
    site: "zendesk",
    domain: "lists",
    type: "action",
    difficulty: "medium",
    curriculumStage: 4,
    title: "Deactivate a stale macro",
    goal: "Mark macro mac-3 ('Bug confirmed — escalating') as inactive (active = false).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "macro_active",
        id: "mac-3",
        expected: false,
        weight: 1.0,
        description: "mac-3 is inactive",
      },
    ],
    maxSteps: 6,
    rewardProfile: R5,
    tags: ["update", "macros"],
  },
]
