import type { TaskDefinition } from "@thetabench/core"

const R = {
  completion: 2.0,
  partialPerCheck: false,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
}

export const navigationTasks: TaskDefinition[] = [
  {
    id: "zen-nav-001",
    site: "zendesk",
    domain: "navigation",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 1,
    title: "Navigate to home",
    goal: "Navigate to the Zendesk Support agent home and report the title of the active view in the left sidebar.",
    retrievalRubric: {
      question: "Which view in the left sidebar is currently selected?",
      groundTruth: "Tickets",
      acceptableVariations: ["Tickets", "tickets", "Your work / Tickets"],
      rubric:
        "Agent must navigate to the Support home and identify the 'Tickets' item under 'Your work' as the active view.",
    },
    evalChecks: [],
    maxSteps: 5,
    rewardProfile: R,
    tags: ["navigation"],
  },
  {
    id: "zen-nav-002",
    site: "zendesk",
    domain: "navigation",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 1,
    title: "Open the sample ticket",
    goal: "Open ticket #2 (the SAMPLE: How does Zendesk work ticket) and report its current status.",
    retrievalRubric: {
      question: "What is the status of ticket #2?",
      groundTruth: "open",
      acceptableVariations: ["open", "Open"],
      rubric:
        "Agent must navigate to ticket #2 (tic-2) and report status 'open'.",
    },
    evalChecks: [],
    maxSteps: 5,
    rewardProfile: R,
    tags: ["navigation"],
  },
  {
    id: "zen-nav-003",
    site: "zendesk",
    domain: "navigation",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 1,
    title: "Navigate to CC'd view",
    goal: "Navigate to the 'CC'd' view under 'Shared work' and report the section heading.",
    retrievalRubric: {
      question: "Which sidebar section contains the CC'd view?",
      groundTruth: "Shared work",
      acceptableVariations: ["Shared work", "shared work"],
      rubric: "Agent must click 'CC'd' inside the 'Shared work' group.",
    },
    evalChecks: [],
    maxSteps: 5,
    rewardProfile: R,
    tags: ["navigation"],
  },
  {
    id: "zen-nav-004",
    site: "zendesk",
    domain: "navigation",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 1,
    title: "Open the Last 30 days view",
    goal: "Open the 'Last 30 days' view under 'Completed work' and report what kinds of tickets it contains.",
    retrievalRubric: {
      question: "What ticket statuses appear in 'Last 30 days'?",
      groundTruth: "solved and closed",
      acceptableVariations: [
        "solved and closed",
        "solved, closed",
        "completed",
      ],
      rubric:
        "Agent must navigate to the 'Last 30 days' view; it filters to solved/closed tickets.",
    },
    evalChecks: [],
    maxSteps: 5,
    rewardProfile: R,
    tags: ["navigation"],
  },
  {
    id: "zen-nav-005",
    site: "zendesk",
    domain: "navigation",
    type: "retrieval",
    difficulty: "easy",
    curriculumStage: 1,
    title: "Find the setup guide",
    goal: "Locate the AI agents setup guide on the home page and report the first step listed.",
    retrievalRubric: {
      question: "What is the first step in the AI agents setup guide?",
      groundTruth: "Invite team",
      acceptableVariations: ["Invite team", "invite team", "Invite your team"],
      rubric:
        "Agent must locate the right-hand 'Setup guide / AI agents' card and identify 'Invite team' as the first checklist item.",
    },
    evalChecks: [],
    maxSteps: 5,
    rewardProfile: R,
    tags: ["navigation"],
  },
]
