import type { TaskDefinition } from "@thetabench/core"

const R2 = {
  completion: 2.0,
  partialPerCheck: false,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
}
const R5 = {
  completion: 5.0,
  partialPerCheck: true,
  stepPenalty: -0.01,
  invalidActionPenalty: -0.1,
}
const R8 = {
  completion: 8.0,
  partialPerCheck: true,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.2,
}
const R10 = {
  completion: 10.0,
  partialPerCheck: true,
  stepPenalty: -0.02,
  invalidActionPenalty: -0.2,
}

// Domain note: ThetaCore's TaskDomain union does not include "tickets",
// so Zendesk ticket tasks use the closest available domain — "issues".
// This keeps `domain` filtering consistent across sites that share the
// generic engine while still being human-meaningful.
export const ticketTasks: TaskDefinition[] = [
  // -------------------------------------------------------------------------
  // Stage 2 — easy single-field updates
  // -------------------------------------------------------------------------
  {
    id: "zen-tic-001",
    site: "zendesk",
    domain: "issues",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Update ticket subject",
    goal: "Change the subject of ticket tic-3 to 'Login fails after password reset (high priority)'.",
    evalChecks: [
      {
        type: "state_diff",
        entity: "tickets",
        id: "tic-3",
        field: "subject",
        expected: "Login fails after password reset (high priority)",
        weight: 1.0,
        description: "tic-3 subject updated",
      },
    ],
    maxSteps: 8,
    rewardProfile: R2,
    tags: ["form-fill"],
  },
  {
    id: "zen-tic-002",
    site: "zendesk",
    domain: "issues",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Mark ticket as pending",
    goal: "Transition ticket tic-5 (Mobile app crashes) from 'open' to 'pending'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "ticket_has_status",
        id: "tic-5",
        expected: "pending",
        weight: 1.0,
        description: "tic-5 is pending",
      },
    ],
    maxSteps: 8,
    rewardProfile: R2,
    tags: ["status"],
  },
  {
    id: "zen-tic-003",
    site: "zendesk",
    domain: "issues",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Lower ticket priority",
    goal: "Change the priority of ticket tic-14 (duplicate notifications) from 'low' to 'normal'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "ticket_has_priority",
        id: "tic-14",
        expected: "normal",
        weight: 1.0,
        description: "tic-14 priority is normal",
      },
    ],
    maxSteps: 8,
    rewardProfile: R2,
    tags: ["priority"],
  },
  {
    id: "zen-tic-004",
    site: "zendesk",
    domain: "issues",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Tag ticket as escalated",
    goal: "Add the tag 'escalated' to ticket tic-17 (SSL renewal failed).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "ticket_has_tag",
        id: "tic-17",
        expected: "escalated",
        weight: 1.0,
        description: "tic-17 has tag 'escalated'",
      },
    ],
    maxSteps: 8,
    rewardProfile: R2,
    tags: ["tags"],
  },
  {
    id: "zen-tic-005",
    site: "zendesk",
    domain: "issues",
    type: "action",
    difficulty: "easy",
    curriculumStage: 2,
    title: "Remove a tag from a ticket",
    goal: "Remove the tag 'crash' from ticket tic-5 (Mobile app crashes).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "ticket_lacks_tag",
        id: "tic-5",
        expected: "crash",
        weight: 1.0,
        description: "tic-5 no longer has tag 'crash'",
      },
    ],
    maxSteps: 8,
    rewardProfile: R2,
    tags: ["tags"],
  },

  // -------------------------------------------------------------------------
  // Stage 3 — single-action create / assign
  // -------------------------------------------------------------------------
  {
    id: "zen-tic-006",
    site: "zendesk",
    domain: "issues",
    type: "action",
    difficulty: "easy",
    curriculumStage: 3,
    title: "Create a follow-up ticket",
    goal: "Create a new ticket with subject 'Follow up on login bug', priority 'high', and channel 'email' (defaults are fine for the rest).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "ticket_exists_with_subject",
        expected: "Follow up on login bug",
        weight: 1.0,
        description: "ticket created",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["create"],
  },
  {
    id: "zen-tic-007",
    site: "zendesk",
    domain: "issues",
    type: "action",
    difficulty: "easy",
    curriculumStage: 3,
    title: "Assign an unassigned ticket",
    goal: "Assign ticket tic-6 (dark mode preference) to agent usr-2 (Marcus Allen).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "ticket_has_assignee",
        id: "tic-6",
        expected: "usr-2",
        weight: 1.0,
        description: "tic-6 assigned to usr-2",
      },
    ],
    maxSteps: 8,
    rewardProfile: R2,
    tags: ["assign"],
  },
  {
    id: "zen-tic-008",
    site: "zendesk",
    domain: "issues",
    type: "action",
    difficulty: "easy",
    curriculumStage: 3,
    title: "Close a solved ticket",
    goal: "Close ticket tic-8 (subscription cancellation) — transition its status from 'solved' to 'closed'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "ticket_has_status",
        id: "tic-8",
        expected: "closed",
        weight: 1.0,
        description: "tic-8 is closed",
      },
    ],
    maxSteps: 8,
    rewardProfile: R2,
    tags: ["status"],
  },

  // -------------------------------------------------------------------------
  // Stage 4 — comments and routing
  // -------------------------------------------------------------------------
  {
    id: "zen-tic-009",
    site: "zendesk",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 4,
    title: "Reply to the sample ticket",
    goal: "Add a public comment from agent usr-1 to ticket tic-2 (SAMPLE) saying 'Welcome — happy to help.'",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "ticket_has_public_comment_from",
        id: "tic-2",
        expected: "usr-1",
        weight: 1.0,
        description: "public comment from usr-1 on tic-2",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["comments"],
  },
  {
    id: "zen-tic-010",
    site: "zendesk",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 4,
    title: "Internal note on a billing ticket",
    goal: "Add an internal (private) comment from agent usr-3 to ticket tic-21 (card declined) saying 'Customer's card on file declined twice this month — escalating to billing ops.'",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "ticket_has_internal_comment_from",
        id: "tic-21",
        expected: "usr-3",
        weight: 1.0,
        description: "internal note added by usr-3 on tic-21",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["comments", "internal"],
  },
  {
    id: "zen-tic-011",
    site: "zendesk",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 4,
    title: "Route ticket to billing group",
    goal: "Move ticket tic-11 (invoice PDF) into the Billing group (grp-2).",
    evalChecks: [
      {
        type: "state_diff",
        entity: "tickets",
        id: "tic-11",
        field: "groupId",
        expected: "grp-2",
        weight: 1.0,
        description: "tic-11 routed to billing group",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["routing"],
  },
  {
    id: "zen-tic-012",
    site: "zendesk",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 4,
    title: "Escalate to urgent + assign to admin",
    goal: "Escalate ticket tic-22 (Slack integration disconnects) to priority 'urgent' and assign it to admin usr-1.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "ticket_has_priority",
        id: "tic-22",
        expected: "urgent",
        weight: 0.5,
        description: "tic-22 priority is urgent",
      },
      {
        type: "state_predicate",
        predicate: "ticket_has_assignee",
        id: "tic-22",
        expected: "usr-1",
        weight: 0.5,
        description: "tic-22 assigned to usr-1",
      },
    ],
    maxSteps: 10,
    rewardProfile: R5,
    tags: ["priority", "assign"],
  },

  // -------------------------------------------------------------------------
  // Stage 5 — multi-step workflows
  // -------------------------------------------------------------------------
  {
    id: "zen-tic-013",
    site: "zendesk",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Investigate, comment, mark pending",
    goal: "On ticket tic-15 (Chat widget on Safari): add a public comment from usr-2 saying 'Reproduced — pushing fix shortly.' and transition status to 'pending'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "ticket_has_public_comment_from",
        id: "tic-15",
        expected: "usr-2",
        weight: 0.5,
        description: "public comment by usr-2",
      },
      {
        type: "state_predicate",
        predicate: "ticket_has_status",
        id: "tic-15",
        expected: "pending",
        weight: 0.5,
        description: "tic-15 is pending",
      },
    ],
    maxSteps: 12,
    rewardProfile: R5,
    tags: ["multi-step"],
  },
  {
    id: "zen-tic-014",
    site: "zendesk",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 5,
    title: "Solve the SSO request",
    goal: "On ticket tic-13 (SAML SSO request): change priority to 'high', add a public comment from usr-1 saying 'Confirmed — will be available in our enterprise plan next quarter.', then mark the ticket 'solved'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "ticket_has_priority",
        id: "tic-13",
        expected: "high",
        weight: 0.34,
        description: "priority high",
      },
      {
        type: "state_predicate",
        predicate: "ticket_has_public_comment_from",
        id: "tic-13",
        expected: "usr-1",
        weight: 0.33,
        description: "public comment from usr-1",
      },
      {
        type: "state_predicate",
        predicate: "ticket_has_status",
        id: "tic-13",
        expected: "solved",
        weight: 0.33,
        description: "ticket solved",
      },
    ],
    maxSteps: 14,
    rewardProfile: R8,
    tags: ["multi-step", "workflow"],
  },

  // -------------------------------------------------------------------------
  // Stage 6 — bulk-ish actions
  // -------------------------------------------------------------------------
  {
    id: "zen-tic-015",
    site: "zendesk",
    domain: "issues",
    type: "action",
    difficulty: "medium",
    curriculumStage: 6,
    title: "Tag all webhook tickets",
    goal: "Add the tag 'webhooks-incident' to every ticket whose existing tags include 'webhooks' (tic-10, tic-29).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "ticket_has_tag",
        id: "tic-10",
        expected: "webhooks-incident",
        weight: 0.5,
        description: "tic-10 tagged",
      },
      {
        type: "state_predicate",
        predicate: "ticket_has_tag",
        id: "tic-29",
        expected: "webhooks-incident",
        weight: 0.5,
        description: "tic-29 tagged",
      },
    ],
    maxSteps: 14,
    rewardProfile: R8,
    tags: ["bulk", "tags"],
  },
  {
    id: "zen-tic-016",
    site: "zendesk",
    domain: "issues",
    type: "action",
    difficulty: "hard",
    curriculumStage: 6,
    title: "Reassign all unassigned triage tickets to usr-2",
    goal: "Find every ticket currently in the Triage group (grp-3) with no assignee, and assign each one to agent usr-2 (Marcus Allen).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "ticket_has_assignee",
        id: "tic-6",
        expected: "usr-2",
        weight: 0.25,
        description: "tic-6 assigned",
      },
      {
        type: "state_predicate",
        predicate: "ticket_has_assignee",
        id: "tic-14",
        expected: "usr-2",
        weight: 0.25,
        description: "tic-14 assigned",
      },
      {
        type: "state_predicate",
        predicate: "ticket_has_assignee",
        id: "tic-18",
        expected: "usr-2",
        weight: 0.25,
        description: "tic-18 assigned",
      },
      {
        type: "state_predicate",
        predicate: "ticket_has_assignee",
        id: "tic-24",
        expected: "usr-2",
        weight: 0.25,
        description: "tic-24 assigned",
      },
    ],
    maxSteps: 16,
    rewardProfile: R8,
    tags: ["bulk", "assign"],
  },

  // -------------------------------------------------------------------------
  // Stage 7 — merging + complex
  // -------------------------------------------------------------------------
  {
    id: "zen-tic-017",
    site: "zendesk",
    domain: "issues",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Merge duplicate webhook tickets",
    goal: "Tickets tic-10 and tic-29 describe the same webhook regression. Merge tic-29 into tic-10 (so tic-10 is the surviving target).",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "ticket_has_status",
        id: "tic-29",
        expected: "closed",
        weight: 0.5,
        description: "source ticket closed",
      },
      {
        type: "state_predicate",
        predicate: "ticket_has_tag",
        id: "tic-10",
        expected: "signature",
        weight: 0.5,
        description: "target inherits tags from merged source",
      },
    ],
    maxSteps: 14,
    rewardProfile: R8,
    tags: ["merge"],
  },
  {
    id: "zen-tic-018",
    site: "zendesk",
    domain: "issues",
    type: "action",
    difficulty: "hard",
    curriculumStage: 7,
    title: "Refund workflow",
    goal: "On tic-4 (refund request): add a public comment from usr-3 saying 'Refund issued via Stripe.', tag the ticket 'refunded', then mark it 'solved'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "ticket_has_tag",
        id: "tic-4",
        expected: "refunded",
        weight: 0.34,
        description: "tagged refunded",
      },
      {
        type: "state_predicate",
        predicate: "ticket_has_public_comment_from",
        id: "tic-4",
        expected: "usr-3",
        weight: 0.33,
        description: "comment from usr-3",
      },
      {
        type: "state_predicate",
        predicate: "ticket_has_status",
        id: "tic-4",
        expected: "solved",
        weight: 0.33,
        description: "solved",
      },
    ],
    maxSteps: 14,
    rewardProfile: R8,
    tags: ["multi-step", "billing"],
  },

  // -------------------------------------------------------------------------
  // Stage 9–10 — expert / orchestration
  // -------------------------------------------------------------------------
  {
    id: "zen-tic-019",
    site: "zendesk",
    domain: "issues",
    type: "action",
    difficulty: "expert",
    curriculumStage: 9,
    title: "Outage triage",
    goal: "We're paging the SSL outage. On ticket tic-17: priority 'urgent' (already), assign to usr-1, add a public comment from usr-1 saying 'Cert renewed; service restored.', tag with 'incident-resolved', then transition status to 'solved'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "ticket_has_assignee",
        id: "tic-17",
        expected: "usr-1",
        weight: 0.2,
        description: "assigned to usr-1",
      },
      {
        type: "state_predicate",
        predicate: "ticket_has_priority",
        id: "tic-17",
        expected: "urgent",
        weight: 0.2,
        description: "priority urgent",
      },
      {
        type: "state_predicate",
        predicate: "ticket_has_public_comment_from",
        id: "tic-17",
        expected: "usr-1",
        weight: 0.2,
        description: "public comment from usr-1",
      },
      {
        type: "state_predicate",
        predicate: "ticket_has_tag",
        id: "tic-17",
        expected: "incident-resolved",
        weight: 0.2,
        description: "tagged incident-resolved",
      },
      {
        type: "state_predicate",
        predicate: "ticket_has_status",
        id: "tic-17",
        expected: "solved",
        weight: 0.2,
        description: "solved",
      },
    ],
    maxSteps: 18,
    rewardProfile: R10,
    tags: ["multi-step", "incident"],
  },
  {
    id: "zen-tic-020",
    site: "zendesk",
    domain: "issues",
    type: "action",
    difficulty: "expert",
    curriculumStage: 10,
    title: "End-to-end SSO onboarding",
    goal: "On tic-20 (SSO onboarding): assign to usr-1, route to the Support group (grp-1), add a public comment from usr-1 saying 'Booking SSO setup call — calendly link sent.', transition to 'pending', then add the tag 'onboarding-call-sent'.",
    evalChecks: [
      {
        type: "state_predicate",
        predicate: "ticket_has_assignee",
        id: "tic-20",
        expected: "usr-1",
        weight: 0.2,
        description: "assigned",
      },
      {
        type: "state_diff",
        entity: "tickets",
        id: "tic-20",
        field: "groupId",
        expected: "grp-1",
        weight: 0.2,
        description: "routed to grp-1",
      },
      {
        type: "state_predicate",
        predicate: "ticket_has_public_comment_from",
        id: "tic-20",
        expected: "usr-1",
        weight: 0.2,
        description: "comment from usr-1",
      },
      {
        type: "state_predicate",
        predicate: "ticket_has_status",
        id: "tic-20",
        expected: "pending",
        weight: 0.2,
        description: "pending",
      },
      {
        type: "state_predicate",
        predicate: "ticket_has_tag",
        id: "tic-20",
        expected: "onboarding-call-sent",
        weight: 0.2,
        description: "tagged",
      },
    ],
    maxSteps: 20,
    rewardProfile: R10,
    tags: ["multi-step", "onboarding"],
  },
]
